### ISSUE TITLE
It asks me for authentication when registering

### ISSUE THREAD

**Issue by Davison2000** [onsip/SIP.js#1000]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).

when I register, the server sends me a 401 Unauthorized, any way for the client to send the authenticated user again?

SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 208.89.107.91:10060;rport=10060;branch=z9hG4bK434844
From: <sip:davison_test@208.89.104.141>;tag=31e9fhuq6q
To: <sip:davison_test@208.89.104.141>;tag=06e0bb78
Call-ID: 929r6convhdn24qobvui
CSeq: 2 REGISTER
Content-Length: 0
Via: SIP/2.0/TCP 208.89.107.183:34119;branch=z9hG4bK434844;ws-hacked=WSS
WWW-Authenticate: Digest realm="208.89.104.141",nonce="1659021505:2897917711aeacdbe7804410e08ef540a012b7ed",stale=FALSE,algorithm=MD5

**Comment by john-e-riordan** [comment]
This is not the forum for support. Please try the [google group](https://groups.google.com/forum/#!forum/sip_js). Thanks.
