### ISSUE TITLE
On Net Inbound Exception

### ISSUE THREAD

**Issue by mgarf** [onsip/SIP.js#1004]
**Describe the bug**
On Net - Call between two numbers registered to the sip server & switch
Off Net - Call between two numbers registered to different servers & switchs

When I receive an inbound call from a off net phone and answer the sip client handles it perfectly.
When I make outbound calls either off net or on net the sip client handles it perfectly

When I recieve an inbound call from a on net phone and answer i receive the following exception:

```
SessionDescriptionHandler.setDescription failed - OperationError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=rtpmap:2 G726-32/8000 Duplicate statically assigned payload type with conflicting codec name or clock rate.
```

**Logs**
Sun Aug 28 2022 20:34:51 GMT-0500 (Central Daylight Time) | sip.Transport | Received WebSocket text message:

INVITE sip:b9hmjp23@127.0.0.1:42074;transport=ws SIP/2.0
Record-Route: <sip:127.0.0.1:1080;transport=ws;r2=on;lr>
Record-Route: <sip:208.89.107.176;r2=on;lr>
Via: SIP/2.0/WS 127.0.0.1:1080;branch=z9hG4bK6da4.b28af315.0
Via: SIP/2.0/UDP 208.89.106.229:5060;received=208.89.106.229;branch=z9hG4bK-524287-1-MmI0OGY1NWMxNTZkM2YyYmZiY2ZhNDM4ZWNjZGVjMWQ.--fc91f46335176cbf1c34fd5fadf618d5;rport=5060
Via: SIP/2.0/UDP 208.89.106.230:5071;branch=z9hG4bK-w4adjbftfiavxcd4;rport=5071
Max-Forwards: 69
Record-Route: <sip:208.89.106.229:5060;transport=udp;lr>
Contact: sip:208.89.106.229:5060
To: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>
From: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>;tag=3g76a2uvr2a3rwam.o
Call-ID: 1fd1227d-a2eb995e@192.168.135.178
CSeq: 403 INVITE
Expires: 300
Allow: INVITE, ACK, BYE, CANCEL, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS, UPDATE
Content-Disposition: session
Content-Type: application/sdp
User-Agent: Sippy
P-Asserted-Identity: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>
Remote-Party-ID: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>;party=calling
h323-conf-id: 844673537-3300259278-4257825630-4257825630
cisco-GUID: 844673537-3300259278-4257825630-4257825630
Content-Length: 797

v=0
o=Sippy 3478873077314704919 1 IN IP4 208.89.106.230
s=-
t=0 0
m=audio 36114 UDP/TLS/RTP/SAVPF 0 2 8 9 18 96 97 98 101
c=IN IP4 208.89.107.176
a=rtpmap:0 PCMU/8000
a=rtpmap:2 G726-32/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729a/8000
a=rtpmap:96 G726-40/8000
a=rtpmap:97 G726-24/8000
a=rtpmap:98 G726-16/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:36115
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-256 28:A3:BA:B6:F0:2F:B7:32:84:B8:EB:5E:C4:50:33:E0:24:01:B2:C4:65:C2:D5:6E:B6:F3:F8:32:59:4E:F8:8C
a=ptime:20
a=ice-ufrag:B3Tb8rjw
a=ice-pwd:6CYdkNZZolBQrw5jq6cZjq5rHv
a=candidate:2lNGn32LK1y6uqo4 1 UDP 2130706431 208.89.107.176 36114 typ host
a=candidate:2lNGn32LK1y6uqo4 2 UDP 2130706430 208.89.107.176 36115 typ host

Sun Aug 28 2022 20:34:51 GMT-0500 (Central Daylight Time) | sip.Transport | Sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WS 127.0.0.1:1080;branch=z9hG4bK6da4.b28af315.0
Via: SIP/2.0/UDP 208.89.106.229:5060;received=208.89.106.229;branch=z9hG4bK-524287-1-MmI0OGY1NWMxNTZkM2YyYmZiY2ZhNDM4ZWNjZGVjMWQ.--fc91f46335176cbf1c34fd5fadf618d5;rport=5060
Via: SIP/2.0/UDP 208.89.106.230:5071;branch=z9hG4bK-w4adjbftfiavxcd4;rport=5071
From: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>;tag=3g76a2uvr2a3rwam.o
To: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>
CSeq: 403 INVITE
Call-ID: 1fd1227d-a2eb995e@192.168.135.178
Supported: outbound
User-Agent: SIP.js/0.20.0
Content-Length: 0

Sun Aug 28 2022 20:34:51 GMT-0500 (Central Daylight Time) | sip.Invitation | Invitation.progress

Sun Aug 28 2022 20:34:51 GMT-0500 (Central Daylight Time) | sip.invite-dialog | INVITE dialog 1fd1227d-a2eb995e@192.168.135.1781ghj39nhqi3g76a2uvr2a3rwam.o constructed

Sun Aug 28 2022 20:34:51 GMT-0500 (Central Daylight Time) | sip.Transport | Sending WebSocket message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WS 127.0.0.1:1080;branch=z9hG4bK6da4.b28af315.0
Via: SIP/2.0/UDP 208.89.106.229:5060;received=208.89.106.229;branch=z9hG4bK-524287-1-MmI0OGY1NWMxNTZkM2YyYmZiY2ZhNDM4ZWNjZGVjMWQ.--fc91f46335176cbf1c34fd5fadf618d5;rport=5060
Via: SIP/2.0/UDP 208.89.106.230:5071;branch=z9hG4bK-w4adjbftfiavxcd4;rport=5071
From: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>;tag=3g76a2uvr2a3rwam.o
To: <sip:{REMOVED_FOR_BUG_REPORT}@208.89.106.229>;tag=1ghj39nhqi
CSeq: 403 INVITE
Call-ID: 1fd1227d-a2eb995e@192.168.135.178
Supported: outbound
User-Agent: SIP.js/0.20.0
Record-Route: <sip:127.0.0.1:1080;transport=ws;r2=on;lr>
Record-Route: <sip:208.89.107.176;r2=on;lr>
Record-Route: <sip:208.89.106.229:5060;transport=udp;lr>
Contact: <sip:b9hmjp23@3u1lvnrks8c3.invalid;transport=ws>
Content-Length: 0

Sun Aug 28 2022 20:34:51 GMT-0500 (Central Daylight Time) | Line | [172059773478d6c7df7-1213-4362-82ca-758b2a5c7f69] Received INVITE

Sun Aug 28 2022 20:34:52 GMT-0500 (Central Daylight Time) | Line | [LINE_ONE-1fd1227d-a2eb995e@192.168.135.1783g76a2uvr2a3rwam.o] Accepting Invitation...

Sun Aug 28 2022 20:34:52 GMT-0500 (Central Daylight Time) | sip.Invitation | Invitation.accept

Sun Aug 28 2022 20:34:52 GMT-0500 (Central Daylight Time) | sip.Invitation | Session 1fd1227d-a2eb995e@192.168.135.1783g76a2uvr2a3rwam.o transitioned to state Establishing

Sun Aug 28 2022 20:34:52 GMT-0500 (Central Daylight Time) | Line | [1fd1227d-a2eb995e@192.168.135.1783g76a2uvr2a3rwam.o] session state changed to Establishing

Sun Aug 28 2022 20:34:53 GMT-0500 (Central Daylight Time) | sip.SessionDescriptionHandler | SessionDescriptionHandler.setDescription failed - OperationError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=rtpmap:2 G726-32/8000 Duplicate statically assigned payload type with conflicting codec name or clock rate.

Sun Aug 28 2022 20:34:53 GMT-0500 (Central Daylight Time) | sip.Invitation | Session.setOfferAndGetAnswer: SDH setDescription or getDescription rejected...

**Expected behavior**
Answered call

**Observed behavior**
Exception causing a 480 - Temporarily Unavailable

**Environment Information**
 - Chrome | Electron 20 | SipJS 0.20

**Comment by zusrut** [comment]
Its not a bug the issue reason is perfectly described in the error message.

**Comment by jayeshhhh** [comment]
Hello @zusrut @mgarf 

I am also facing this type of issue.

Call automatically rejected once the call is incoming from another extension.

**Error**:
1) DOMException: Failed to parse SessionDescription. a=rtpmap:2 G726-32/8000 Duplicate statically assigned payload type with conflicting codec name or clock rate.
2) DOMException: PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer.

Thing is that it was working fine very well before 2 days ago, Now it's giving error. Even though i've checked [sipml5](https://www.doubango.org/sipml5/call.htm?svn=252) as well. It have same error there.

**Comment by mgarf** [comment]
@jayeshhhh after digging deep into peerconnection research this is due to an unsupported audio codec. The best thing to do is in the sdp filter out the audio codecs that are not supported (which to me is strange the library doesnt do this automatically). I created a function that invoked `RTCRtpReceiver.getCapabilities('audio')?.codecs` and filtered out any audio formats that werent on the list and then injected it as a modifier so it could run before accepting the call

**Comment by jengkhaw95** [comment]
Hi @mgarf 
I ran into this issue and I think the way you described is very likely to solve the issue. Could you please provide an example on this?

**Comment by mgarf** [comment]
I overrode the list of media in allow to dedup and remove audio types I didn't want

**Comment by jengkhaw95** [comment]
@mgarf Thanks for the advice. This is what I did to make answering call works.

```
const customModifier: (
  description: RTCSessionDescriptionInit
) => Promise<RTCSessionDescriptionInit> = async (desc) => {
  const { type, sdp } = desc;

  const cleanedSdp = cleanSdp(sdp);

  const newDescription = new RTCSessionDescription({
    type,
    sdp: cleanedSdp,
  });

  return newDescription;
};```

Then passing the modifier when answer:
`sipClient.answer({
                      sessionDescriptionHandlerModifiers: [customModifier],
                    })`
