### ISSUE TITLE
cannot invite with #

### ISSUE THREAD

**Issue by vieridipaola** [onsip/SIP.js#1006]
**Describe the bug**
Cannot send invite that starts with # -- such as #4@sip.mydomain.org.

**Logs**
Uncaught TypeError: Invalid to URI: undefined
(in class Inviter)

**To Reproduce (if possible)**
dial sip:#@server or even sip:*#@server

**Expected behavior**
Should accept the URI containing #..

**Observed behavior**
Client fails - no message sent to server.

**Environment Information**
 - latest SIPjs
 - latest Firefox

**Comment by vieridipaola** [comment]
It seems that 

```
    static makeURI(uri) {
        return _core__WEBPACK_IMPORTED_MODULE_6__.Grammar.URIParse(uri);
    }
```

is returning _undefined_ when using **#** in _uri_ param.

**Comment by vieridipaola** [comment]
...and if I try to force acceptance of the URI sip:#4@server by by-passing makeURI then I get this other error:

`TypeError: ruri.clone is not a function`

**Comment by john-e-riordan** [comment]
Not a bug.

- `makeURI()` returns undefined if the syntax of the URI is invalid.
- The syntax must conform to a SIP URI as defined in the RFC (https://tools.ietf.org/html/rfc3261#section-25).
- `#` is not a valid character in that part of a SIP URI.

```
const uriInvalid = UserAgent.makeURI("sip:#4@sip.mydomain.org");
console.warn(uriInvalid?.aor); // undefined

const uriValid = UserAgent.makeURI("sip:%234@sip.mydomain.org");
console.warn(uriValid?.aor); // #4@sip.mydomain.org
```

I've add a remark to the documentation for `makeURI()` to clarify the behavior of the method here d8b4b3c469739a980d687551432e70ddc3ab3c59 which will go out with next release.

**Comment by vieridipaola** [comment]
Thanks!
