### ISSUE TITLE
Video-Media (Camera) can not be embed afterwards

### ISSUE THREAD

**Issue by BRFCommend** [onsip/SIP.js#1015]
There is a strange behaviour when a call has been accepted and a Session Progress (183, Early-Media) was sent before.
A camera source can then not be activated anymore, it is switched on for a glimpse of a second and then off again.

**Comment by john-e-riordan** [comment]
If you believe this is a bug, please resubmit the issue using the bug template and provide the associated information: https://github.com/onsip/SIP.js/issues/new/choose

Otherwise please use our our google group (https://groups.google.com/forum/#!forum/sip_js) for help.
