### ISSUE TITLE
 sip.Transport | WebSocket error occurred

### ISSUE THREAD

**Issue by m-amine-aouini** [onsip/SIP.js#1016]
**Describe the bug**
When i invoke start in user agent i get ( WebSocket closed unexpectedly )

**Logs**
Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | Configuration:
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · allowLegacyNotifications: false
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · authorizationHa1: ""
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · authorizationPassword: NOT SHOWN
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · authorizationUsername: ""
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · delegate: {}
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · contactName: ""
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · contactParams: {"transport":"ws"}
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · displayName: ""
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · forceRport: false
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · gracefulShutdown: true
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · hackAllowUnregisteredOptionTags: false
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · hackIpInContact: false
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · hackViaTcp: false
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · instanceId: ""
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · instanceIdAlwaysAdded: false
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · logBuiltinEnabled: true
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · logConfiguration: true
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · logConnector: undefined
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · logLevel: "log"
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · noAnswerTimeout: 60
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · preloadedRouteSet: []
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · reconnectionAttempts: 0
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · reconnectionDelay: 4
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · sendInitialProvisionalResponse: true
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · sessionDescriptionHandlerFactory: (session, options) => {
    // provide a default media stream factory if need be
    if (mediaStreamFactory === undefined) {
      mediaStreamFactory = (0,_media_stream_factory_default_js__WEBPACK_IMPORTED_MODULE_0__.defaultMediaStreamFactory)();
    }
    // make sure we allow `0` to be passed in so timeout can be disabled
    const iceGatheringTimeout = (options === null || options === void 0 ? void 0 : options.iceGatheringTimeout) !== undefined ? options === null || options === void 0 ? void 0 : options.iceGatheringTimeout : 5000;
    // merge passed factory options into default session description configuration
    const sessionDescriptionHandlerConfiguration = {
      iceGatheringTimeout,
      peerConnectionConfiguration: Object.assign(Object.assign({}, (0,_peer_connection_configuration_default_js__WEBPACK_IMPORTED_MODULE_1__.defaultPeerConnectionConfiguration)()), options === null || options === void 0 ? void 0 : options.peerConnectionConfiguration)
    };
    const logger = session.userAgent.getLogger("sip.SessionDescriptionHandler");
    return new _session_description_handler_js__WEBPACK_IMPORTED_MODULE_2__.SessionDescriptionHandler(logger, mediaStreamFactory, sessionDescriptionHandlerConfiguration);
  }
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · sessionDescriptionHandlerFactoryOptions: {}
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · sipExtension100rel: "Unsupported"
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · sipExtensionReplaces: "Unsupported"
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · sipExtensionExtraSupported: []
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · sipjsId: "5te4t"
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · transportConstructor: Transport
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · transportOptions: {"server":"wss://localhost:8080"}
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · uri: sip:anonymous.78lu1l@anonymous.invalid
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · userAgentString: "SIP.js/0.21.1"
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | · viaHost: "tgd8jei51o64.invalid"
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | Starting sip:anonymous.78lu1l@anonymous.invalid
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.UserAgent | Transitioned from Stopped to Started
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.Transport | Connecting wss://localhost:8080
logger-factory.js:93 Mon Nov 21 2022 13:41:44 GMT+0100 (Central European Standard Time) | sip.Transport | Transitioned from Disconnected to Connecting
transport.js:197 WebSocket connection to 'wss://localhost:8080/' failed: 
_connect @ transport.js:197
connect @ transport.js:100
start @ user-agent.js:337
main @ SIPsetup.js:38
./src/index.js @ index.js:14
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
logger-factory.js:85 Mon Nov 21 2022 13:41:47 GMT+0100 (Central European Standard Time) | sip.Transport | WebSocket error occurred.
print @ logger-factory.js:85
genericLog @ logger-factory.js:65
genericLog @ logger.js:25
error @ logger.js:13
onWebSocketError @ transport.js:355
(anonymous) @ transport.js:200
error (async)
_connect @ transport.js:200
connect @ transport.js:100
start @ user-agent.js:337
main @ SIPsetup.js:38
./src/index.js @ index.js:14
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
logger-factory.js:89 Mon Nov 21 2022 13:41:47 GMT+0100 (Central European Standard Time) | sip.Transport | WebSocket closed unexpectedly
print @ logger-factory.js:89
genericLog @ logger-factory.js:65
genericLog @ logger.js:25
warn @ logger.js:16
onWebSocketClose @ transport.js:339
(anonymous) @ transport.js:199
logger-factory.js:93 Mon Nov 21 2022 13:41:47 GMT+0100 (Central European Standard Time) | sip.Transport | WebSocket closed wss://localhost:8080 (code: 1006)
logger-factory.js:93 Mon Nov 21 2022 13:41:47 GMT+0100 (Central European Standard Time) | sip.Transport | Transitioned from Connecting to Disconnected
SIPsetup.js:38 Error: WebSocket closed wss://localhost:8080 (code: 1006)
    at Transport.onWebSocketClose (transport.js:337:1)
    at WebSocket.<anonymous> (transport.js:199:1)

**To Reproduce (if possible)**
1. I Add userAgent.start()
4. I See error

**Observed behavior**
I tried on SignalWire I had same error too

**Environment Information**
 - FS 1.6.14 ( I tried 1.10.2 and I had same error)
 - SIP.JS 0.21.2

**Comment by john-e-riordan** [comment]
Not a bug - for setup/support help please try the [google group](https://groups.google.com/forum/#!forum/sip_js).

**Comment by Irfanwani** [comment]
Anyone solved this issue? I am uisng it is react native. Getting the same error in android. Websocket never connects. Works fine on iOS.

**Comment by Irfanwani** [comment]
> @Irfanwani did you solve this if yes can you tell me how you did

I don't remember, it has been a year now. can you please post some relevant code?
