### ISSUE TITLE
Hold/Resume issue

### ISSUE THREAD

**Issue by dgooden** [onsip/SIP.js#12]
Using the current master branch of SIP.js on both sides of the call.

If the caller puts the call on hold, hold/resume works great. However if the recipient of the call puts the call on hold, it turns into an INVITE/ACK loop. It looks like the caller side isn't noticing the ACK, so the recipient side keeps sending the INVITE. And so on. This goes on until the ACK timeout kicks in and ends the call.

Let me know if you need anymore information, better logs, etc.

I've added an example of the INVITE/ACK loop below.  (These packets are from the caller side) :

sip-0.5.0.js:168
Mon May 05 2014 17:25:04 GMT-0400 (EDT) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WS  38.101.17.161;branch=z9hG4bKe0a3.7851f9e1.0
Via: SIP/2.0/WS gtf423cseabl.invalid;rport=50173;received=72.64.129.133;branch=z9hG4bK280403
To: sip:ws0@38.101.17.161;tag=fm4eu7i2rj
From: "ws2" sip:ws2@38.101.17.161;tag=ekrulilh4a
Call-ID: c3bvq677970qgkqmcc5n
CSeq: 8608 INVITE
Contact: sip:ws0@38.101.17.161;gr=urn:uuid:2895ed1f-21e1-48fa-a495-fa285a157f72
Supported: gruu,outbound
Content-Type: application/sdp
Content-Length: 2194

v=0
o=- 8774960189842969587 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL
m=audio 63998 RTP/SAVPF 111 103 104 0 8 106 105 13 126
c=IN IP4 72.64.129.133
a=rtcp:63998 IN IP4 72.64.129.133
a=candidate:3934755452 1 udp 2113937151 10.3.1.34 63998 typ host generation 0
a=candidate:3934755452 2 udp 2113937151 10.3.1.34 63998 typ host generation 0
a=candidate:2819253492 1 udp 1845501695 72.64.129.133 63998 typ srflx raddr 10.3.1.34 rport 63998 generation 0
a=candidate:2819253492 2 udp 1845501695 72.64.129.133 63998 typ srflx raddr 10.3.1.34 rport 63998 generation 0
a=candidate:2751751820 1 tcp 1509957375 10.3.1.34 0 typ host generation 0
a=candidate:2751751820 2 tcp 1509957375 10.3.1.34 0 typ host generation 0
a=ice-ufrag:pLndoGbuL4gLARri
a=ice-pwd:fUevfgt5H7ZIvfyu9h0LHrmP
a=fingerprint:sha-256 B0:D9:D0:A8:E9:09:5A:09:83:D2:51:B9:77:DD:D6:87:F3:4F:98:A0:FE:92:B1:87:24:AC:87:A4:C6:30:C3:23
a=setup:passive
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:4182389599 cname:YpP0KdY624KG+5d4
a=ssrc:4182389599 msid:CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL 5798c099-111b-4d82-8093-9cb37e5961d8
a=ssrc:4182389599 mslabel:CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL
a=ssrc:4182389599 label:5798c099-111b-4d82-8093-9cb37e5961d8
m=video 1 RTP/SAVPF 100 116 117
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:pLndoGbuL4gLARri
a=ice-pwd:fUevfgt5H7ZIvfyu9h0LHrmP
a=fingerprint:sha-256 B0:D9:D0:A8:E9:09:5A:09:83:D2:51:B9:77:DD:D6:87:F3:4F:98:A0:FE:92:B1:87:24:AC:87:A4:C6:30:C3:23
a=setup:passive
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000

 sip-0.5.0.js:168
Mon May 05 2014 17:25:04 GMT-0400 (EDT) | sip.transport | received WebSocket text message:

ACK sip:ws0@38.101.17.161;gr=urn:uuid:2895ed1f-21e1-48fa-a495-fa285a157f72 SIP/2.0
Via: SIP/2.0/WS  38.101.17.161;branch=z9hG4bKcydzigwkX
Via: SIP/2.0/WS gtf423cseabl.invalid;rport=50173;received=72.64.129.133;branch=z9hG4bK9518782
Max-Forwards: 16
To: sip:ws0@38.101.17.161;tag=fm4eu7i2rj
From: "ws2" sip:ws2@38.101.17.161;tag=ekrulilh4a
Call-ID: c3bvq677970qgkqmcc5n
CSeq: 8608 ACK
Supported: outbound
User-Agent: SIP.js/0.5.0-devel
Content-Length: 0

 sip-0.5.0.js:168
Mon May 05 2014 17:25:05 GMT-0400 (EDT) | sip.transaction.ict | z9hG4bK4873201 | Timer M expired for INVITE client transaction z9hG4bK4873201 sip-0.5.0.js:168
Mon May 05 2014 17:25:05 GMT-0400 (EDT) | sip.transaction.ict | z9hG4bK4873201 | emitting event stateChanged sip-0.5.0.js:168
Mon May 05 2014 17:25:05 GMT-0400 (EDT) | sip.ua | emitting event transactionDestroyed sip-0.5.0.js:168
Mon May 05 2014 17:25:08 GMT-0400 (EDT) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WS  38.101.17.161;branch=z9hG4bKe0a3.7851f9e1.0
Via: SIP/2.0/WS gtf423cseabl.invalid;rport=50173;received=72.64.129.133;branch=z9hG4bK280403
To: sip:ws0@38.101.17.161;tag=fm4eu7i2rj
From: "ws2" sip:ws2@38.101.17.161;tag=ekrulilh4a
Call-ID: c3bvq677970qgkqmcc5n
CSeq: 8608 INVITE
Contact: sip:ws0@38.101.17.161;gr=urn:uuid:2895ed1f-21e1-48fa-a495-fa285a157f72
Supported: gruu,outbound
Content-Type: application/sdp
Content-Length: 2194

v=0
o=- 8774960189842969587 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL
m=audio 63998 RTP/SAVPF 111 103 104 0 8 106 105 13 126
c=IN IP4 72.64.129.133
a=rtcp:63998 IN IP4 72.64.129.133
a=candidate:3934755452 1 udp 2113937151 10.3.1.34 63998 typ host generation 0
a=candidate:3934755452 2 udp 2113937151 10.3.1.34 63998 typ host generation 0
a=candidate:2819253492 1 udp 1845501695 72.64.129.133 63998 typ srflx raddr 10.3.1.34 rport 63998 generation 0
a=candidate:2819253492 2 udp 1845501695 72.64.129.133 63998 typ srflx raddr 10.3.1.34 rport 63998 generation 0
a=candidate:2751751820 1 tcp 1509957375 10.3.1.34 0 typ host generation 0
a=candidate:2751751820 2 tcp 1509957375 10.3.1.34 0 typ host generation 0
a=ice-ufrag:pLndoGbuL4gLARri
a=ice-pwd:fUevfgt5H7ZIvfyu9h0LHrmP
a=fingerprint:sha-256 B0:D9:D0:A8:E9:09:5A:09:83:D2:51:B9:77:DD:D6:87:F3:4F:98:A0:FE:92:B1:87:24:AC:87:A4:C6:30:C3:23
a=setup:passive
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:4182389599 cname:YpP0KdY624KG+5d4
a=ssrc:4182389599 msid:CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL 5798c099-111b-4d82-8093-9cb37e5961d8
a=ssrc:4182389599 mslabel:CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL
a=ssrc:4182389599 label:5798c099-111b-4d82-8093-9cb37e5961d8
m=video 1 RTP/SAVPF 100 116 117
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:pLndoGbuL4gLARri
a=ice-pwd:fUevfgt5H7ZIvfyu9h0LHrmP
a=fingerprint:sha-256 B0:D9:D0:A8:E9:09:5A:09:83:D2:51:B9:77:DD:D6:87:F3:4F:98:A0:FE:92:B1:87:24:AC:87:A4:C6:30:C3:23
a=setup:passive
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000

 sip-0.5.0.js:168
Mon May 05 2014 17:25:08 GMT-0400 (EDT) | sip.transport | received WebSocket text message:

ACK sip:ws0@38.101.17.161;gr=urn:uuid:2895ed1f-21e1-48fa-a495-fa285a157f72 SIP/2.0
Via: SIP/2.0/WS  38.101.17.161;branch=z9hG4bKcydzigwkX
Via: SIP/2.0/WS gtf423cseabl.invalid;rport=50173;received=72.64.129.133;branch=z9hG4bK6223582
Max-Forwards: 16
To: sip:ws0@38.101.17.161;tag=fm4eu7i2rj
From: "ws2" sip:ws2@38.101.17.161;tag=ekrulilh4a
Call-ID: c3bvq677970qgkqmcc5n
CSeq: 8608 ACK
Supported: outbound
User-Agent: SIP.js/0.5.0-devel
Content-Length: 0

 sip-0.5.0.js:168
Mon May 05 2014 17:25:12 GMT-0400 (EDT) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WS  38.101.17.161;branch=z9hG4bKe0a3.7851f9e1.0
Via: SIP/2.0/WS gtf423cseabl.invalid;rport=50173;received=72.64.129.133;branch=z9hG4bK280403
To: sip:ws0@38.101.17.161;tag=fm4eu7i2rj
From: "ws2" sip:ws2@38.101.17.161;tag=ekrulilh4a
Call-ID: c3bvq677970qgkqmcc5n
CSeq: 8608 INVITE
Contact: sip:ws0@38.101.17.161;gr=urn:uuid:2895ed1f-21e1-48fa-a495-fa285a157f72
Supported: gruu,outbound
Content-Type: application/sdp
Content-Length: 2194

v=0
o=- 8774960189842969587 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL
m=audio 63998 RTP/SAVPF 111 103 104 0 8 106 105 13 126
c=IN IP4 72.64.129.133
a=rtcp:63998 IN IP4 72.64.129.133
a=candidate:3934755452 1 udp 2113937151 10.3.1.34 63998 typ host generation 0
a=candidate:3934755452 2 udp 2113937151 10.3.1.34 63998 typ host generation 0
a=candidate:2819253492 1 udp 1845501695 72.64.129.133 63998 typ srflx raddr 10.3.1.34 rport 63998 generation 0
a=candidate:2819253492 2 udp 1845501695 72.64.129.133 63998 typ srflx raddr 10.3.1.34 rport 63998 generation 0
a=candidate:2751751820 1 tcp 1509957375 10.3.1.34 0 typ host generation 0
a=candidate:2751751820 2 tcp 1509957375 10.3.1.34 0 typ host generation 0
a=ice-ufrag:pLndoGbuL4gLARri
a=ice-pwd:fUevfgt5H7ZIvfyu9h0LHrmP
a=fingerprint:sha-256 B0:D9:D0:A8:E9:09:5A:09:83:D2:51:B9:77:DD:D6:87:F3:4F:98:A0:FE:92:B1:87:24:AC:87:A4:C6:30:C3:23
a=setup:passive
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:4182389599 cname:YpP0KdY624KG+5d4
a=ssrc:4182389599 msid:CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL 5798c099-111b-4d82-8093-9cb37e5961d8
a=ssrc:4182389599 mslabel:CByLqPrgLDG430X9kJcVdPAh7l80FAgkxcFL
a=ssrc:4182389599 label:5798c099-111b-4d82-8093-9cb37e5961d8
m=video 1 RTP/SAVPF 100 116 117
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:pLndoGbuL4gLARri
a=ice-pwd:fUevfgt5H7ZIvfyu9h0LHrmP
a=fingerprint:sha-256 B0:D9:D0:A8:E9:09:5A:09:83:D2:51:B9:77:DD:D6:87:F3:4F:98:A0:FE:92:B1:87:24:AC:87:A4:C6:30:C3:23
a=setup:passive
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000

 sip-0.5.0.js:168
Mon May 05 2014 17:25:12 GMT-0400 (EDT) | sip.transport | received WebSocket text message:

ACK sip:ws0@38.101.17.161;gr=urn:uuid:2895ed1f-21e1-48fa-a495-fa285a157f72 SIP/2.0
Via: SIP/2.0/WS  38.101.17.161;branch=z9hG4bKcydzigwkX
Via: SIP/2.0/WS gtf423cseabl.invalid;rport=50173;received=72.64.129.133;branch=z9hG4bK3750483
Max-Forwards: 16
To: sip:ws0@38.101.17.161;tag=fm4eu7i2rj
From: "ws2" sip:ws2@38.101.17.161;tag=ekrulilh4a
Call-ID: c3bvq677970qgkqmcc5n
CSeq: 8608 ACK
Supported: outbound
User-Agent: SIP.js/0.5.0-devel
Content-Length: 0

**Comment by ManikantaJNSVV** [comment]
on network change how to send invite from client side in angular 5
