### ISSUE TITLE
ast_srtp_unprotect: SRTP unprotect failed with: authentication failure 110

### ISSUE THREAD

**Issue by murugan-pandian** [onsip/SIP.js#128]
<b>Call drop:</b> chrome to Zoiper SIP phone i am getting following error 

sip.inviteclientcontext | Failed to set remote answer sdp:<b> Called with SDP without ice-ufrag and ice-pwd.</b>

chrome->Aseterisk 13->SIP Phone

**Comment by ahmed-rayan** [comment]
i have this error : ast_srtp_unprotect srtp unprotect failed with authentication failure 110
if any one help me
