### ISSUE TITLE
Unable to register when extension uses PJSIP with Asterisk

### ISSUE THREAD

**Issue by jwoertink** [onsip/SIP.js#135]
I'm using Asterisk 12.7.1 and SIP.js 0.6.4.

When I register an extension like 1060 through the sip.conf, I can go to the asterisk CLI and run `sip show peers` and see the extension. If I register an extension like 1061 through the pjsip.conf then run `pjsip show endpoints` it doesn't show my extension as being registered. Yet, if I use a client like X-Lite, I can log in with 1061 and it will show it registered. Is there an additional setting in the config that SIP.js would need?

**Comment by wakamoleguy** [comment]
Any news on this?  Interop issues tend to be time-sensitive with browser updates.

**Comment by jwoertink** [comment]
I haven't noticed. I'm not working with this stuff anymore, but I'm sure with the latest versions of stuff this might be fixed.
