### ISSUE TITLE
extraHeaders in UA configuration

### ISSUE THREAD

**Issue by beradrian** [onsip/SIP.js#137]
It will be very useful to include extraHeaders in the UA configuration. This will be combined with the extraHeaders in the parameters passed in the instance methods.

Currently there's no way to specify extra headers for REGISTER, when this is done automatically when creating the UA.

**Comment by james-onsip** [comment]
I'm going to close this, as it would add complexity without value (necessarily). It wouldn't be intuitive that extraHeaders for the UA creation are specifically for the register request, and wakamoleguy touched on how this could be done in the code as it exists today.

That said, we would welcome a a pull request detailing the value of said change.

Thanks,
James
