### ISSUE TITLE
Offer ha1 config options instead of plaintext password

### ISSUE THREAD

**Issue by Mantriur** [onsip/SIP.js#139]
I don't like the idea of exposing the plaintext password in the javascript, so I'm creating the ha1 inside PHP. Would it be possible to offer a config option for the ha1 string instead of a password?

**Comment by wakamoleguy** [comment]
I've been thinking more about this, and I'm realizing that a naive implementation may not get us what we want.  Holding plaintext passwords in JavaScript memory isn't great, but using the HA1 as I understand it doesn't help out much either.  If somebody steals the HA1, they can use it to authenticate just as well as if they had the password.  It would, however, gain us the following (arguably not valuable) security:

* If SIP.js doesn't know the authentication user nor password, somebody stealing the HA1 may not know who they can authenticate as.  They know the realm, though, so they could probably figure it out, especially with access to a SIP trace.
* If the authentication password is shared between your SIP provider and other services, the HA1 would not work on those other services.  For example, if you use your Facebook password for your SIP service, the HA1 can't steal your Facebook account.  That said, *don't share your passwords between services.*
* Somebody walking by your computer while your console log is open and you are debugging the configuration object with the password showing, that person won't be able to remember a HA1 at a glance.  That seems somewhat unlikely and could just as easily be protected against with a hard-to-read-at-a-glance password.

Are there other benefits, or am I misunderstanding the digest mechanism?

**Comment by wakamoleguy** [comment]
For what it's worth, we've had a second request for this.

**Comment by james-criscuolo** [comment]
This is now out in 0.17.0, closing.
