### ISSUE TITLE
Overriding WebSocket Implementation

### ISSUE THREAD

**Issue by thomasquintana** [onsip/SIP.js#141]
Hi Gals/Guys,

My company is using sip.js in a cordova softphone project. We have had a lot of success with our custom [MediaHandler](https://github.com/BetterVoice/PhoneRTCMediaHandler) which uses a modified version of [phonertc](https://github.com/BetterVoice/phonertc) that includes a native websocket implementation.

Moving on, the reason for the native websocket implementation is because in order to receive calls on iOS while the app is in background mode we needed to set the socket interface for VoIP usage.

The problem we are having is that we would like to test our websocket implementation against sip.js to make sure everything is working but we can't seem to find a straightforward way to override the default websocket implementation without forking the project.

I would like to know if this is possible? If not would the sip.js team provide a patch we can use? Do I just bite the bullet and fork the project?

Best,
Thomas Quintana

P.S. Thank very much for all the hard work!

**Comment by wakamoleguy** [comment]
Hi Thomas,

In 0.6.4, you should be able to simply override `window.WebSocket` before creating the SIP.js UA.  Since 0.6.4, there have been some improvements that allow you to manually specify dependencies such as WebSockets and Promises.  Most of those changes were done with Node.js in mind, but I would guess they would apply to mobile and cordova as well.  @joseph-onsip, do you know if it is possible to override the default WebSocket implementation using `environment`?

**Comment by thomasquintana** [comment]
Woah! Awesome response time! I apologize we are using 0.6.3.

**Comment by lylepratt** [comment]
Hi guys, I guess we should have specified that we are currently on 0.6.3 because our MediaHandler for phonertc doesn't use your Promises stuff yet. Any way to do this with 0.6.3?

**Comment by wakamoleguy** [comment]
You can probably still override `window.WebSocket` at any time before creating the UA.  We aren't caching that internally or anything, so when the UA is created and attempts to connect, it will use whatever implementation it sees globally.

This is all based on how it works in a browser.  It's possible that cordova and iOS causes that behavior to change.  Let me know if that doesn't work, and we can try to investigate further.

**Comment by joseph-onsip** [comment]
(note that the commits mentioned below aren't yet in a tagged release)

> we are currently on 0.6.3 because our MediaHandler for phonertc doesn't use your Promises stuff yet

Once I realized that the Promise stuff could break custom `mediaHandlerFactory` implementations, I fixed it in https://github.com/onsip/SIP.js/commit/f3e5cfa40bb99df33bfc830987263b36794db9d8

> @joseph-onsip, do you know if it is possible to override the default WebSocket implementation using `environment`?

 It sure is (as of https://github.com/onsip/SIP.js/commit/63d205ceea4976f8af91a6f50608a3e71339ea00)! See https://github.com/onsip/SIP.js/pull/108 for information on how to provide a custom `environment`.

**Comment by thomasquintana** [comment]
Thank you guys very much for the prompt responses. I am currently trying the recommendations and I will update once tested.

**Comment by thomasquintana** [comment]
Hey Guys,

@wakamoleguy overriding window.WebSocket did the trick in Cordova.

Cheers,
Tom

**Comment by lylepratt** [comment]
Awesome! Background calls on iOS here we come!

**Comment by lylepratt** [comment]
Hi Guys,

We've finally updated our plugin to use promises, but it looks like we need to be overriding the global WebSocket differently now. How should we override the Websocket in 0.7.1?

**Comment by lylepratt** [comment]
I guess I should really be asking, how do we override WebSocket after SIP.js has already been instantiated? Overriding window.WebSocket in our dialer was working in SIP.js 0.6.4, however on 0.7.1, that no longer works.

**Comment by thomasquintana** [comment]
+1

**Comment by lylepratt** [comment]
OK Guys. Well...I believe overriding the websocket was working this whole time and I'm just an idiot. Was a different problem. Sincere apologies for the bother!

**Comment by lylepratt** [comment]
OK. I was wrong yet again. Its definitely not override the websocket like before. I'm going to open a new issue to track this.
