### ISSUE TITLE
SDP included in PRACK to 183 answer retransmission

### ISSUE THREAD

**Issue by joseph-onsip** [onsip/SIP.js#144]
(reported by Łukasz Starowicz on the [mailing list](https://groups.google.com/d/msg/sip_js/C6r8CzjG29w/vtWJNJ4HFCAJ))

Here are the notable portions of the [console log](https://gist.githubusercontent.com/joseph-onsip/1d0a485580d7b23f3da6/raw/f9ce6ef17e2f6923d34c9fea4fe077e498fbe694/Receiving%20183%20answer%20retransmission%20results%20in%20PRACK%20with%20SDP):

* [outgoing INVITE with SDP](https://gist.github.com/joseph-onsip/1d0a485580d7b23f3da6#file-receiving-183-answer-retransmission-results-in-prack-with-sdp-L291-L328)
* [incoming 183 with SDP](https://gist.github.com/joseph-onsip/1d0a485580d7b23f3da6#file-receiving-183-answer-retransmission-results-in-prack-with-sdp-L350-L391)
* [outgoing PRACK *without* SDP](https://gist.github.com/joseph-onsip/1d0a485580d7b23f3da6#file-receiving-183-answer-retransmission-results-in-prack-with-sdp-L415-L429)
* [incoming 183 with SDP (retransmission)](https://gist.github.com/joseph-onsip/1d0a485580d7b23f3da6#file-receiving-183-answer-retransmission-results-in-prack-with-sdp-L440-L481)
* [outgoing PRACK *with* SDP](https://gist.github.com/joseph-onsip/1d0a485580d7b23f3da6#file-receiving-183-answer-retransmission-results-in-prack-with-sdp-L495-L515)

I'm not yet familiar enough with the relevant specs to be certain of the correct solution, but I feel like the retransmission's SDP should be disregarded, and the resulting PRACK should again have no SDP.

**Comment by egreenmachine** [comment]
You are correct. From [RFC 3262](https://www.ietf.org/rfc/rfc3262.txt) page 9 
>Once a reliable provisional response is received, retransmissions of
   that response MUST be discarded.

**Comment by joseph-onsip** [comment]
Oh, I see, there's no PRACK associated with the 183 retransmission, but the original PRACK should itself be retransmitted until [its 200 OK](https://gist.github.com/joseph-onsip/1d0a485580d7b23f3da6#file-receiving-183-answer-retransmission-results-in-prack-with-sdp-L523-L535) is received

**Comment by SirLouen** [comment]
Any ideas about this. There is no compatibility to earlymedia for SIP.js?

**Comment by wakamoleguy** [comment]
Under most circumstances, 100rel will work to set up early media (although branching scenarios should investigate the InviteWithoutSdp).  This issue in particular covers a case where a retransmission of the 183 will not be handled properly.  Under normal network scenarios, this should come up only rarely.

**Comment by james-onsip** [comment]
Well, didn't know committing with the number would close it.

Anyways, the commit reference above does fix this, I'll be sure to reply to the thread on the mailing list.

**Comment by joseph-onsip** [comment]
It was the "fix #144" at the end that did it :D https://help.github.com/articles/closing-issues-via-commit-messages/
