### ISSUE TITLE
A call suddenly stops after about 27 seconds

### ISSUE THREAD

**Issue by victorgb6** [onsip/SIP.js#146]
Hi,

I'm having some troubles making an audio call, everythings works fine when I make the call, I can listen both ends, but then suddenly It stops the connenction. I'm using Freeswitch version 1.4.6.

I thinks these timeouts should be the reason, but I don't know how to fix it.

    Thu Feb 05 2015 11:26:38 GMT+0100 (Hora estándar romance) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK1796330
    sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:38 GMT+0100 (Hora estándar romance) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK1796330

I leave here the complete log:

Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.transport | sending WebSocket message:

INVITE sip:06078@voip.virtualcenter360.es SIP/2.0
Via: SIP/2.0/WSS ergcqjvgv68d.invalid;branch=z9hG4bK1796330
Max-Forwards: 70
To: <sip:06078@voip.virtualcenter360.es>
From: "usuario_WebRTC" <sip:demoWRTC.telecoming.com@voip.virtualcenter360.es>;tag=5thpckmd2a
Call-ID: sou7iias5fd6q4jirv33
CSeq: 5835 INVITE
X-INR-VAR1:MIVAR=PROBANDO
X-INR-VAR2:IVRGENERICA=LO QUE SEA
X-INR-NUMVARS:2
Contact: <sip:j2qheshr@ergcqjvgv68d.invalid;transport=ws;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY,INVITE,MESSAGE
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.6.4
Content-Length: 1793

v=0
o=- 3713690536037307056 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS GICqdHX1nKW49LknoMVxdwLgHTJv2kgnnXhs
m=audio 64292 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 130.117.88.33
a=rtcp:64292 IN IP4 130.117.88.33
a=candidate:586919451 1 udp 2122260223 192.168.11.69 54182 typ host generation 0
a=candidate:586919451 2 udp 2122260223 192.168.11.69 54182 typ host generation 0
a=candidate:2746460335 1 udp 1686052607 130.117.88.33 64292 typ srflx raddr 192.168.11.69 rport 54182 generation 0
a=candidate:2746460335 2 udp 1686052607 130.117.88.33 64292 typ srflx raddr 192.168.11.69 rport 54182 generation 0
a=candidate:1819824875 1 tcp 1518280447 192.168.11.69 0 typ host tcptype active generation 0
a=candidate:1819824875 2 tcp 1518280447 192.168.11.69 0 typ host tcptype active generation 0
a=ice-ufrag:KSNEE5TAxK4UUHFX
a=ice-pwd:H4GsXTqXTD2zYLhQ3hqThJoe
a=ice-options:google-ice
a=fingerprint:sha-256 D0:49:8E:C9:2B:D0:D9:91:3A:09:ED:83:1B:FC:49:74:D8:57:2A:67:33:48:EC:4A:E2:26:3D:70:30:DC:98:4D
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:3926917584 cname:V2g0xR5IZw7rAwe3
a=ssrc:3926917584 msid:GICqdHX1nKW49LknoMVxdwLgHTJv2kgnnXhs f8973347-35bb-49d1-b2d2-21e608e70c59
a=ssrc:3926917584 mslabel:GICqdHX1nKW49LknoMVxdwLgHTJv2kgnnXhs
a=ssrc:3926917584 label:f8973347-35bb-49d1-b2d2-21e608e70c59

sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.transport | received WebSocket text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS ergcqjvgv68d.invalid;branch=z9hG4bK1796330;received=130.117.88.33;rport=33822
From: "usuario_WebRTC" <sip:demoWRTC.telecoming.com@voip.virtualcenter360.es>;tag=5thpckmd2a
To: <sip:06078@voip.virtualcenter360.es>
Call-ID: sou7iias5fd6q4jirv33
CSeq: 5835 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.4.6~64bit
Content-Length: 0

sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.transaction.ict | emitting event stateChanged
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS ergcqjvgv68d.invalid;branch=z9hG4bK1796330;received=130.117.88.33;rport=33822
From: "usuario_WebRTC" <sip:demoWRTC.telecoming.com@voip.virtualcenter360.es>;tag=5thpckmd2a
To: <sip:06078@voip.virtualcenter360.es>;tag=2j27XaQ29BDmS
Call-ID: sou7iias5fd6q4jirv33
CSeq: 5835 INVITE
Contact: <sip:06078@212.230.135.233:50601;transport=udp>
User-Agent: FreeSWITCH-mod_sofia/1.4.6~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Session-Expires: 120;refresher=uas
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 868
Remote-Party-ID: "Outbound Call" <sip:webrtc06078@voip.virtualcenter360.es>;party=calling;privacy=off;screen=no

v=0
o=FreeSWITCH 1423106285 1423106286 IN IP4 212.230.135.233
s=FreeSWITCH
c=IN IP4 212.230.135.233
t=0 0
a=msid-semantic: WMS odCN4iUxfIXcODlMoaUcE5q3FGKrgB1v
m=audio 27832 UDP/TLS/RTP/SAVPF 111 126 106
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:126 telephone-event/8000
a=rtpmap:106 CN/8000
a=ptime:20
a=fingerprint:sha-256 E8:63:5D:E6:36:7D:42:23:B3:9F:E7:14:57:ED:69:09:27:2C:2F:8B:41:24:8C:66:D3:F6:CF:43:94:92:EA:76
a=rtcp-mux
a=rtcp:27832 IN IP4 212.230.135.233
a=ssrc:2295891493 cname:Et8zBTXHrKJ5dVIr
a=ssrc:2295891493 msid:odCN4iUxfIXcODlMoaUcE5q3FGKrgB1v a0
a=ssrc:2295891493 mslabel:odCN4iUxfIXcODlMoaUcE5q3FGKrgB1v
a=ssrc:2295891493 label:odCN4iUxfIXcODlMoaUcE5q3FGKrgB1va0
a=ice-ufrag:VsupnLiTiSaok2JP
a=ice-pwd:lHfNq2kICUDGGcYrujHIUQr2
a=candidate:9521069524 1 udp 659136 212.230.135.233 27832 typ host generation 0

sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.transaction.ict | emitting event stateChanged
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.dialog | new UAC dialog created with status CONFIRMED
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.invitecontext.mediahandler | emitting event setDescription
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.transport | sending WebSocket message:

ACK sip:06078@212.230.135.233:50601;transport=udp SIP/2.0
Via: SIP/2.0/WSS ergcqjvgv68d.invalid;branch=z9hG4bK7873163
Max-Forwards: 70
To: <sip:06078@voip.virtualcenter360.es>;tag=2j27XaQ29BDmS
From: "usuario_WebRTC" <sip:demoWRTC.telecoming.com@voip.virtualcenter360.es>;tag=5thpckmd2a
Call-ID: sou7iias5fd6q4jirv33
CSeq: 5835 ACK
Supported: outbound
User-Agent: SIP.js/0.6.4
Content-Length: 0

sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.inviteclientcontext | emitting event accepted
webRTC-Client.js?cCache=54d3447253ced:508 WebRTC_Client_TBS | Call Accepted: f {RTCConstraints: Object, inviteWithoutSdp: false, anonymous: false, renderbody: null, rendertype: "text/plain"…}
webRTC-Client.js?cCache=54d3447253ced:514 WebRTC_Client_TBS | Emitting event (onWebRTC_CallStarted)
demoWebRTC.php?phonenumber=06078:201 demo onWebRTC_CallStarted!!!
webRTC-Client.js?cCache=54d3447253ced:517 WebRTC_Client_TBS | Call Started
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.invitecontext.mediahandler | stream added: odCN4iUxfIXcODlMoaUcE5q3FGKrgB1v
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.invitecontext.mediahandler | emitting event addStream
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:06 GMT+0100 (Hora estándar romance) | sip.invitecontext.mediahandler | ICE connection state changed to "checking"
2sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:07 GMT+0100 (Hora estándar romance) | sip.invitecontext.mediahandler | ICE connection state changed to "completed"
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:38 GMT+0100 (Hora estándar romance) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK1796330
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:38 GMT+0100 (Hora estándar romance) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK1796330
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:38 GMT+0100 (Hora estándar romance) | sip.transaction.ict | emitting event stateChanged
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:38 GMT+0100 (Hora estándar romance) | sip.ua | emitting event transactionDestroyed
sip-0.6.4.min.js:36 Thu Feb 05 2015 11:26:38 GMT+0100 (Hora estándar romance) | sip.transport | received WebSocket text message:

BYE sip:j2qheshr@ergcqjvgv68d.invalid;transport=ws;ob SIP/2.0
Via: SIP/2.0/WSS 212.230.135.233:50601;rport;branch=z9hG4bKBXc8Qpe5aZvpK
Max-Forwards: 70
From: <sip:06078@voip.virtualcenter360.es>;tag=2j27XaQ29BDmS
To: "usuario_WebRTC" <sip:demoWRTC.telecoming.com@voip.virtualcenter360.es>;tag=5thpckmd2a
Call-ID: sou7iias5fd6q4jirv33
CSeq: 71231010 BYE
Contact: <sip:06078@212.230.135.233:50601;transport=udp>
User-Agent: FreeSWITCH-mod_sofia/1.4.6~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Reason: Q.850;cause=16;text="NORMAL_CLEARING"
Content-Length: 0
X-Asterisk-HangupCause: Normal Clearing
X-Asterisk-HangupCauseCode: 16

**Comment by victorgb6** [comment]
Hi, i 've checked my back-end configuration and I found a problem there. You can close or delete the issue.

**Comment by anhpt253** [comment]
hi victorgb6,

I'm having the same your troubles. Can you show your resolve for this trouble? Thank you
