### ISSUE TITLE
WebRTC with SIP.js and Asterisk server on net

### ISSUE THREAD

**Issue by alauts** [onsip/SIP.js#147]
I'm trying to get the SIP.js to work correctly but can not get the audio to work in either direction.

RTP debug shows 

Got  RTP packet from    192.168.123.8:8000 (type 00, seq 039456, ts 2944010142, len 000160)
Sent RTP packet to      192.168.123.41:50174 (via ICE) (type 00, seq 015709, ts 2944010136, len 000160)
Got  RTP packet from    192.168.123.8:8000 (type 00, seq 039457, ts 2944010302, len 000160)
Sent RTP packet to      192.168.123.41:50174 (via ICE) (type 00, seq 015710, ts 2944010296, len 000160)

...all in the same direction from the softphone (192.168.123.8) to the browser running the test (192.168.123.41)

Asterisk version 11.11
Linux version Ubuntu 14.04
SIP.js version 0.6.4
Web Browser version 40.0.2214.109

test script:

script src="sip-0.6.4.js"
script type="text/javascript"
var config = {
  // Replace this IP address with your Asterisk IP address
  uri: '1060@192.168.123.7',

  // Replace this IP address with your Asterisk IP address,
  // and replace the port with your Asterisk port from the http.conf file
  ws_servers: 'ws://192.168.123.7:8088/ws',

  // Replace this with the username from your sip.conf file
  authorizationUser: '1060',

  // Replace this with the password from your sip.conf file
  password: 'password',
  
  // HackIpInContact for Asterisk
  hackIpInContact: true,
  
};

var ua = new SIP.UA(config);

var options = {
        media: {
                constraints: {
                        audio: true,
                        video: false
                }
        }
};
// Invite with audio only
ua.invite('1061', options);
script

Does the Asterisk server setup described on the sipjs.org site need to be altered to handle the rtp stream differently for a server that is on the same LAN?

**Comment by alauts** [comment]
This issue still exhibits the same characteristics when using Asterisk 13.1

**Comment by egreenmachine** [comment]
I have answered [this thread](https://groups.google.com/forum/#!topic/sip_js/Gctj-VeOxL4) on our google group.

**Comment by james-onsip** [comment]
I'm going to close this issue, but please continue the conversations and ask any further questions in the previously mentioned thread.
