### ISSUE TITLE
Looking for updated api info for api.onsip.com/api

### ISSUE THREAD

**Issue by rastographics** [onsip/SIP.js#150]
Long-standing satisfied onsip customer here. I'm looking to implement a basic js/cordova app that simple shows a users voicemails, allows them to listen to them and delete.

My.onsip portal does not work consistently for playing the voicemails, and i want to make this in a very easy mobile friendly app anyways. 

The api docs at https://github.com/onsip/developer.onsip.com/tree/master/content/admin-api are enough to help me get the users account pulled up. There is no documentation for voicemails that I can find though.

I found the UserAddressVoicemailboxRead action by studying the my.onsip portal, which gives me a voicemailboxId but I still need to locate:

"Get all voicemails for a voicemailboxId"

It looks like my.onsip uses some sort of non-standard api way of getting this info and I can't figure it out.

Once I have the voicemail ID it looks like I can call the XmppVoicemailCacheRead action to get the actual voicemail recording as an mp3. (Although this call works without authentication so maybe not secure to use?)

Sorry if this is the wrong place to ask, but when I left a message on onsip developer site, Tim Cleves said this is the best place to start for finding this info.

I do not need an programming help, just need to know what api to call to get the voicemails for a given voicemailboxid.

Thanks

**Comment by rastographics** [comment]
Obviously I'm happy to share my final source code with the community to help out onsip and others who want an app for managing voicemail.

**Comment by wakamoleguy** [comment]
Hi Joel,

As you have devised, My.OnSIP uses the XmppVoicemailCacheRead call to fetch the voicemail recordings from our Admin API.  The tricky part is how they actually get cached in the first place.  That is currently only available through our [XMPP-based realtime API](http://wiki.onsip.com/docs/XMPP_API).  We do not usually recommend that people develop directly against this API, as it is not very user friendly and has a very long learning curve.  In fact, the particular API command to cache the voicemails is not actually documented in those docs at all.  I can't say that it is private, as My.OnSIP does use it and any User could make the API call, but we really didn't set it up with the intention of using it outside of My.OnSIP.

Browser network tools may be the easiest way to get the API call you are looking for, along with the basic XMPP instructions I linked above.  If that doesn't work out, I can try to cobble together some documentation on the specific XMPP API command.

Alternatively, another option could be to send the voicemails out via email, where they could be stored and managed externally.  We've had several people pipe voicemails via email to transcription services and the like.

Thanks,

-Will

**Comment by rastographics** [comment]
Thanks Will. I will look into the docs on the XMPP api. A precursory view of everything suggests that in its simplest form, it is a matter of sending an xml-formatted request to the server to create a subscription which then causes the server to return an xml response to the client whenever items change related to that subscription?

I found the api call for caching via the pubsub. I will attempt to go this route. The reason is I also need my app to allow people to delete messages directly, so getting the voicemail via email would not allow for that. Also, wav files do not play on most phones easily like mp3 do.

I just need to wrap my head around the xml pub-sub conventions. Too bad it can't be redone using websockets :) 

Thanks again

**Comment by rastographics** [comment]
Should I be using https://github.com/onsip/OXJS in this endeavor?

**Comment by rastographics** [comment]
@wakamoleguy if you get a chance to make an example on the proper way to use OX.js but for getting voicemail subscription ([this demo](https://github.com/onsip/OXJS/blob/master/examples/demo-strophe/glue.js) only shows how to subscribe to Active Calls) I would really appreciate it.

**Comment by onsip** [comment]
Hi Joel,

I am out of the office today, and I will take a look at this on Monday.
OX.js does a lot of work to help navigate Strophe and the Bosh connection.
It will likely be handy in simplifying this.

Thanks,

-Will

**Comment by rastographics** [comment]
Trying to implement this has been a real challenge. I've been considering your idea to parse emails with attached wavs using a service like mandrill along with a backend webserver that can parse the text to get caller name, number, date, and message length.

I was wondering, since other clients are also automating some processes around this voicemail notification email, is it possible onsip could add some invisible tags to the email so it would be very easy to find and parse the important parameters?

Something like:
```
<user id="3456" name="Joel Szwarga" /> 
<caller number="8488494834" name="Fred Smith" /> 
<voicemail id="349348" length="48" date="2015-02-25T09:08:33" />
```

Including the user id would allow the backend parser to associate the voicemail with specific user, and including the voicemail Id could potentially allow a simple call to the onsip server to delete the message (if implemented in the clients backend).

Any thoughts on this?

**Comment by wakamoleguy** [comment]
Hi again,

I've pushed a new branch to the OX.js repo where I updated the example to subscribe to Voicemail publishes.  When a publish is received, you can click a button generate the cached message.  Lastly, it returns the API call to read that cached message (as an mp3).

I'm not sure why JQuery is having trouble displaying the link, so I am aggressively logging and alerting the resulting URL.  JQuery seems to get its act together if you click the cache button twice.

In any case, that should hopefully get you going in the right direction with OX.js.  Note that using the demo, you'll have to log in, then authenticate, then subscribe to the voicemails.  There is also a cap on the number of subscriptions allowed (I believe it is 10).  If you are doing extensive testing, I recommend using either multiple users or shorter expiration times (right now, it defaults to an hour).

As for your suggested features for the email option, that is not currently on our road map.  It is an interesting idea, though, and something we should consider if/when our road map does lead there.

Cheers,

Will

**Comment by wakamoleguy** [comment]
Closing this, as any future conversation on it is better taken elsewhere (support.onsip.com, for example).
