### ISSUE TITLE
Change log messages when Timers 'expire'

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#152]
When timers 'expire' or 'go off' in SIP.js, a message gets logged that reads something like this:

> sip-0.6.4.min.js:36 Tue Feb 24 2015 16:47:03 GMT+0200 (Финляндия (зима)) | sip.transaction.nist | Timer J expired for non-INVITE server transaction z9hG4bK7f5249a4 

While technically accurate, it causes a lot of confusion for non-experts examining the logs, which leads to many red herring support issues.  We should change the message to better indicate that these are normal occurrences and not something to worry about.

**Comment by joseph-onsip** [comment]
An alternative is to eliminate the messages, and manually re-enable them when debugging an issue (the same philosophy we'll be applying to event emissions when #66 is merged).

**Comment by wakamoleguy** [comment]
Philosophy applied.

**Comment by wakamoleguy** [comment]
Actually...nevermind.  I misunderstood what that was saying.

**Comment by jlaine** [comment]
It would be great to address this, I find these log messages thoroughly confusing.
