### ISSUE TITLE
Thank you contributors!

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#154]
@sanyatuning
@liveninja
@wpp
@Rob--W
@Bat-o-matic 
@sicdigital 
@seanbright 
@caruizdiaz 
@Destreyf 

Hi contributors!
I've recently added you to our Thanks.md file.  Currently, I only added information available directly from this repository and GitHub.  If you would like to add one or two additional bits of information, please feel free to submit a pull request or comment here.  Preferably, additional information should be short links to various other social media sites, web pages, etc:
- [Will Mitchell](https://github.com/wakamoleguy) - [Twitter](https://twitter.com/wakamoleguy), [CodePen](http://codepen.io/wakamoleguy), [Website](http://www.wakamoleguy.com)

We appreciate your contributions, and thank you for helping to build the SIP.js community ever greater!

Cheers,

-Will

PS - I may close this Issue at some point, but that doesn't mean the information is locked in.  If you'd ever like to change your information after that, please let me know.

**Comment by wpp** [comment]
Lovely gesture! Thanks to all the contributors and the onsip team for managing this splendidly.

**Comment by egreenmachine** [comment]
@mrothstein
@zxcpoiu
@growtofill
@Mirocow
@ringcentral

Thanks for helping keep this project going! You have all been added to the `THANKS.md` file.

**Comment by egreenmachine** [comment]
I do not think we need an open issue for this. Feel free to comment here if you think we missed someone that should be added to the `THANKS.md` file.
