### ISSUE TITLE
Important Session.js event "terminated" not documented 

### ISSUE THREAD

**Issue by klarrimore** [onsip/SIP.js#161]
It took us a while to realize that we needed a "termnated" event on Session for various different reasons (transport errors, media issues, getting "endTime" on session, etc).  We had implemented listeners for all the events listed at http://sipjs.com/api/0.6.0/session/ but "endTime" wasn't always available on the "bye" event and other various issues.  We looked through the source and discovered the very helpful but hard to find "terminated" event.  I think it's a critical bug that this event doesn't get more sunlight.

**Comment by egreenmachine** [comment]
Hi @klarrimore 
Please see #67 and our [mailing list](https://groups.google.com/forum/#!msg/sip_js/A8kO6wa__yM/Tsxxlzn178MJ) regarding this. I am going to close this as a duplicate and you can continue the discussion there.

**Comment by klarrimore** [comment]
My bad, I didn't think to look for a docuentation issue.  I even thought submitting it to github issues might be out of place.

**Comment by wakamoleguy** [comment]
I've added documentation for the event, as it exists in 0.6.x versions.  The termination events in general are cleaned up better on the master branch, so I expect the documentation to be improved with the next release.

http://sipjs.com/api/0.6.0/session/#terminated
