### ISSUE TITLE
Bogus behavior when making a call between two UAs with different audio/video capabilities

### ISSUE THREAD

**Issue by abdelghafour** [onsip/SIP.js#171]
Hello, 

We are using sip,js to implement an angularJS audio/video chat client with KAMAILIO as backend.

Platform: 
	PC1 (no camera support) —— KAMAILIO —— PC2 (with camera support)

Steps to reproduce:
1. Make a call from PC1 to PC2

Expected behavior:
1. PC2 gets audio/no video stream from PC1
2. PC1 gets audio/video stream from PC2

Seen behavior:
Audio/no video stream on both PCs

Our investigation of the sip.js code shows that, upon reaceipt of the invite from PC1, PC2’s UA only recycles the SDP and does not create a new one based on its capabilities (audio and video). And hence the received SDP does not contains any video codecs, tags …, PC2’s UA sends a videoless SDP.

One of our options to fix that is to make PC2’s UA send a re-invite with correct capabilities, but this keeps on getting answered by a 488 not acceptable here.

I need to mention that, if PC2 calls PC1, the call is established correctly.

Regards,

**Comment by wakamoleguy** [comment]
You need to set 'OfferToReceiveVideo: true' in PC1's RTCConstraints.  This will cause an `m=video` line to be available in both session descriptions.  Browsers will not negotiate one-way media streams unless you tell them to.

**Comment by devLaaziz** [comment]
Hello, 
I' experiencing the same issue, I tried to add OfferToReceiveVideo:true in my media constraints but no succes in sending SDP with video tag.

I tried:

options = {
            media: {
              constraints: {
                audio: audio,
                video: video,
                mandatory: {
                  OfferToReceiveVideo: true
                }
              }
            }
          };

and, 

options = {
            media: {
              constraints: {
                audio: audio,
                video: video,
               OfferToReceiveVideo: true
              }
            }
          };


Regards,

**Comment by wakamoleguy** [comment]
Here is a sample that we use in our own code at OnSIP:

~~~ javascript
ua.invite(target, {
          media: {
            stream: stream,
            constraints: constraints
          },
          RTCConstraints: {
            optional: [{
              DtlsSrtpKeyAgreement: true
            }],
            mandatory: {
              OfferToReceiveVideo: constraints.video
            }
          },
          inviteWithoutSdp: true
        });
~~~

**Comment by abdelghafour** [comment]
Hello Wakamoleguy, 
Thank you for your response, that made it!

I still need to mention that with 0.7.0, I had troubles establishing video session, but with 0.6.4 it worked correctly.
Should I open an issue for that, or is it a known issue ? 

Thank you,

**Comment by wakamoleguy** [comment]
Hi,

Can you copy your JavaScript logs to a gist and post them on our [Mailing List](https://groups.google.com/forum/#!forum/sip_js)?  That is the preferred area for those issues, until we can narrow them down enough to become a GitHub Issue.

**Comment by kylemeier** [comment]
abdelghafour I think you're running into the same issue I was: https://github.com/onsip/SIP.js/issues/172

**Comment by abdelghafour** [comment]
Thank you kylemeier.
The #172 update should do it.
