### ISSUE TITLE
Change in options.media.render in 0.7.0

### ISSUE THREAD

**Issue by kylemeier** [onsip/SIP.js#172]
I'm trying out the new version and am unable to get any video to render or sound to play. When I switch back to the older version, everything works fine.

The same issue occurs if I update the demo to 0.7.0: http://jsfiddle.net/crzx22b4/1/
(no other changes made to the demo other than changing the version)

I'm assuming there's something I need to change in my app for the new version to work, but can't figure out what it is. To help me out, can you show me how that demo needs to be changed in order for video to render?

**Comment by wakamoleguy** [comment]
Hi Kyle,

This is a small API change from the previous version.  We'll be sure to go through and change all of the demos.

Note that the `media.render` option format has changed:

~~~ javascript
// New
render: {
    remote: remoteRender,
    local: localRender
}

// Old

**Comment by kylemeier** [comment]
Ahhh, I knew it was something simple. Thank you!

**Comment by wakamoleguy** [comment]
You're welcome!  I'm just going to leave this open so we don't forget about documenting it.  I'll add something right now to draw attention to it in the API docs.

**Comment by james-onsip** [comment]
I'm going to close this, as a note was left on [this guide](http://sipjs.com/guides/make-call/) and also covered in [the documentation](http://sipjs.com/api/0.7.0/mediaHandler/#renderrenderhint).
