### ISSUE TITLE
Allow +sip.ice (and other media features) to be included in Contacts

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#174]
Currently, there is no way to easily add media features to the Contact address of a UA, specifically when registering.  This would allow us to declare that we support ICE while registering, for example, according to [RFC 5768](https://tools.ietf.org/html/rfc5768).

We cannot simply append +sip.ice to all Contact addresses, since ICE is a feature mandated by WebRTC only.  If you supply a custom MediaHandler or run SIP.js in other contexts than the browser, we very well may _not_ support ICE.  Thus, an option or way to specify options is necessary.

**Comment by egreenmachine** [comment]
This is possible in `0.15.X` and forward using the [extraContactHeaderParams](https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.registereroptions.extracontactheaderparams.md) option.
