### ISSUE TITLE
Chrome cannot hold() audio/video/SDP call offered by Firefox

### ISSUE THREAD

**Issue by josephfrazier** [onsip/SIP.js#182]
(found while testing for #170)

To reproduce:
- Open http://jsfiddle.net/uc6pg02f/ in Chrome, create a UA as "chrome"
- Open http://jsfiddle.net/uc6pg02f/ in Firefox, create a UA as "firefox"
- in the Firefox fiddle, enter "chrome" in the target field and make a call
- once the call is setup, click "hold" in Chrome

Expected:
- Chrome sends an INVITE

Actual:
- This appears in the console:

> Mon Jun 01 2015 15:22:41 GMT-0400 (EDT) | sip.invitecontext.mediahandler | Failed to set local offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set video receive codecs..module.exports.LoggerFactory.print @ sip-0.7.0.js:2817module.exports.Object.keys.forEach.LoggerFactory.(anonymous function) @ sip-0.7.0.js:2834module.exports.Object.keys.forEach.Logger.(anonymous function) @ sip-0.7.0.js:2828methodFailed @ sip-0.7.0.js:11119

**Comment by Demitrius** [comment]
Yes, confirm it

**Comment by egreenmachine** [comment]
We believe that this issue may be resolved in the latest tagged version [0.8.0](https://github.com/onsip/SIP.js/releases/tag/0.8.0). Can you please retest with that version and let us know if this is still an issue. We will close this issue on 11/1/17 if we do not hear back. Thanks.
