### ISSUE TITLE
Presence Events not Received from FreeSWITCH

### ISSUE THREAD

**Issue by lylepratt** [onsip/SIP.js#184]
Hi guys,

We had this working nicely, but suddenly it has stopped working, I believe since we updated to the latest SIP.js release. We're subscribing to presence events via SIP.js. I can see the subscriptions being received by FreeSWITCH with a `202 Accepted`, but I never receive any events via the `notify` event. 

Just wondering if others have had this issue, or if there is something known that is preventing this from working now.

**Comment by lylepratt** [comment]
Extra bit of info: This could also be because we are now using TLS (wss://).

**Comment by lylepratt** [comment]
We've confirmed that FreeSWITCH is sending out the NOTIFY events, but they are timing out and are never received by SIP.js.

**Comment by lylepratt** [comment]
OK. We've narrowed this down to a TLS issue. Basically when using `wss://` with SIP.js + FS, FS is unable to reach SIP.js with the Notify events. Instead they just timeout.

**Comment by lylepratt** [comment]
This seemed related:
http://lists.sip-router.org/pipermail/sr-users/2014-July/084157.html

So, we tried to enable `NDLB-force-rport` on the FS profile, but it did not help. 

Surely you guys have encountered this before? Any tips?

**Comment by thomasquintana** [comment]
+1

**Comment by wakamoleguy** [comment]
Hi Lyle,

Sorry for the delay in response.  It seemed like you were making some progress in tracking it down, and we unfortunately don't have experience with this setup.  Internally, we only use FreeSWITCH for media functionality, and keep presence events in our SIP proxy layer.

I have seen FreeSWITCH do some weird things with TLS before, though, and so I'm not terribly surprised.  Can you tell if it is a network issue, or if FreeSWITCH is refusing to put data onto the WebSocket?  It definitely seems weird.

-Will

**Comment by lylepratt** [comment]
Does not appear to be a network issue. Works fine when not using `wss://` protocol. `NOTIFY` events from FS just eventually time out.

According to the link I posted above, Kamailio has the same problem with sending `NOTIFY` events to SIP.js. On Kamailio, this is required: `fix_nated_contact() must be run for both REGISTER and SUBSCRIBE`.

However, I'm not really sure WHY that is required at all, and why is it only required when using SIP.js?

**Comment by lylepratt** [comment]
Hi guys. We still have not resolved this issue, so we opened a ticket with FreeSWITCH. You can find it here: https://freeswitch.org/jira/browse/FS-7680

We've also included detailed logs of requests via `ws` and `wss` in the ticket.

**Comment by lylepratt** [comment]
I would appreciate it if anyone would upvote the issue we've filed on Jira. Basically presence is completely broken with SIP.js and FreeSWICH over WSS. Its a very important issue we need to get resolved, and some support via Jira would help!

**Comment by Destreyf** [comment]
lylepratt can you confirm something for me, are you using NDLB-connectile-dysfunction ANYWHERE, in your extensions/users, your sofia profiles, trunks, gateways anything... this has been a pain for me, but presence works fine over ws, but with wss its broken if using NDLB-connectile-dysfunction in any part of the system. #90

**Comment by lylepratt** [comment]
Howdy. We do use NDLB-connectile-dysfunction in other profiles, but not the registration profiles we are using for WebRTC connections. Does that still make a difference in your tests?

**Comment by wakamoleguy** [comment]
Hey Lyle.  I noticed that the FreeSwitch ticket didn't get much traction.  Any chance you worked this one out?

**Comment by lylepratt** [comment]
No we ended up writing our own method to catch evens via the event socket. :(

**Comment by wakamoleguy** [comment]
That's a shame, although I'm glad you have a workaround.  I'll keep this open, but label accordingly (from our perspective).

**Comment by egreenmachine** [comment]
Since this was tracked down to be a FreeSWITCH issue I am going to close the ticket. Feel free to continue the thread if there are any more questions.

**Comment by zek** [comment]
5 years passed and still same problem :(

I can send presence events via WSS and Twinkle can catch it but WSS not receiving any events.

**Comment by zek** [comment]
So do we have any solutions either on FS or SIP.js?

**Comment by md-riaz** [comment]
https://github.com/signalwire/freeswitch/issues/398
