### ISSUE TITLE
No Audio if oudbound call picked up after 8 seconds in Asterisk

### ISSUE THREAD

**Issue by sarumjanuch** [onsip/SIP.js#185]
Hi Guys, I am almost sure that it is not issue in yours library, but just in case, many people expirience same issue, maybe we will find some info here. When you place outgoing call from WebRTC extensions to anywhere else, if callee picks up call in 7 seconds everything is fine, if in 8, then call will have no audio. During debugging i find out, that in normal call asterisk sends dtls client_hello after 200 OK, and receiving server_hello back from browser. Meanwhile in the bad call i can see that after some period of time asterisk start sending client_hello, and browser don't respond to them, which causes that there is no dtls handshake happened, it don't know what ciphers etc. My question is next, when sip.js should become ready to receive client_hello messasges? And when it should ignore them? I would be really appreciate for any help, any ideas or points to RFC quotes, that can explain something.

**Comment by james-onsip** [comment]
Hi sarumjanuch,
  We've dealt with these types of problems pretty extensively here at OnSIP with Freeswitch. Most of the process you refer to occurs at the browser level, as SIP.js does not send or receive client_hello's. Our problems mainly were with the fact that we were using 3PCC (or, invite w/o SDP), so if you are trying that, switch it off and try again. Invite w/o SDP is an uncommon use case, so it wouldn't be terribly surprising if projects did not handle them appropriately in all situations.

Outside of this, most of debugging this will be between Asterisk debug logs and running your browser from command line to get better logs there as well (or wireshark).

Thanks,
James

**Comment by sarumjanuch** [comment]
I will reference this issue on asterisk issue tracker in case some of sip.js users will face same problem:
https://issues.asterisk.org/jira/browse/ASTERISK-24146

**Comment by sarumjanuch** [comment]
Following up to this issue, i did fixed it in asterisk. It was because asterisk was trying to check ICE as soon as it receives any SDP with candidates, but in this case browser is not yet in checking mode, because didn't receive remote description yet. If someone will face it again please go to that ticket for patch, i hope they will include it to next release. You can close it, or add somewhere to asterisk documentation as known issue. Thanks for your attention.
