### ISSUE TITLE
Web Audio Api in options.media.render.remote

### ISSUE THREAD

**Issue by pstanisl** [onsip/SIP.js#186]
Hi contributors!

Is there a way to directly use Web Audio Api in `options.media.render.remote`?

Thanks and best regards,
Petr

**Comment by joseph-onsip** [comment]
Potentially, if you provide your UA with a [mediaHandlerFactory](http://sipjs.com/api/0.7.0/ua_configuration_parameters/#mediahandlerfactory) that returns MediaHandlers whose [`render` method](https://github.com/onsip/SIP.js/blob/0.7.0/src/WebRTC/MediaHandler.js#L432-L446) uses [AudioContext.createMediaStreamSource](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource) (see the example code) to connect the remote stream's audio to the Web Audio graph ([this probably won't work in Chrome](https://code.google.com/p/chromium/issues/detail?id=241543)).
