### ISSUE TITLE
can not answer on incomming call

### ISSUE THREAD

**Issue by stshishkin** [onsip/SIP.js#187]
SIPjs does not send 200 OK message when I push the answer button.

log from Javascrip console below:
1.1.1.1 our PBX's external IP 
1234567890 callerID of incoming call

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.transport | received WebSocket text message:

INVITE sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WS 1.1.1.1:5060;branch=z9hG4bK596e6178;rport
Max-Forwards: 70
From: "1234567890" <sip:1234567890@1.1.1.1>;tag=as70c987a3
To: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>
Contact: <sip:1234567890@1.1.1.1:5060;transport=WS>
Call-ID: 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060
CSeq: 102 INVITE
User-Agent: Clientbase PBX
Date: Thu, 11 Jun 2015 17:06:25 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Type: application/sdp
Content-Length: 1012

v=0
o=root 1713972435 1713972435 IN IP4 1.1.1.1
s=Asterisk PBX 11.17.1
c=IN IP4 1.1.1.1
t=0 0
m=audio 11402 RTP/SAVP 8 3 0 101
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=ice-ufrag:13459e2257e15d9b089f29095c36def6
a=ice-pwd:09dd7b4c11e67a18102b5cf535cf13a2
a=candidate:H5fd5aaaa 1 UDP 2130706431 1.1.1.1 11402 typ host
a=candidate:Ha740145 1 UDP 2130706431 10.116.1.69 11402 typ host
a=candidate:S5fd5aaaa 1 UDP 1694498815 1.1.1.1 11402 typ srflx raddr 1.1.1.1 rport 11402
a=candidate:H5fd5aaaa 2 UDP 2130706430 1.1.1.1 11403 typ host
a=candidate:Ha740145 2 UDP 2130706430 10.116.1.69 11403 typ host
a=candidate:S5fd5aaaa 2 UDP 1694498814 1.1.1.1 11403 typ srflx raddr 1.1.1.1 rport 11403
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 56:67:9A:B8:32:67:BC:F9:AF:33:3B:25:45:35:38:72:BC:50:35:A5:AB:D2:64:26:87:2B:F5:44:2C:B1:CB:11
a=sendrecv

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.sipmessage | header "Content-Disposition" not present
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.ua | emitting event newTransaction
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.transport | sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WS 1.1.1.1:5060;branch=z9hG4bK596e6178;rport
To: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>
From: "1234567890" <sip:1234567890@1.1.1.1>;tag=as70c987a3
Call-ID: 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060
CSeq: 102 INVITE
Supported: outbound
Content-Length: 0

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.transaction.ist | adding event stateChanged
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event progress
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event accepted
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event rejected
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event failed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event connecting
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event terminated
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event dtmf
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event invite
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event cancel
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event refer
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event bye
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event hold
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event unhold
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event muted
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.servercontext | adding event unmuted
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.dialog | new UAS dialog created with status EARLY
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event userMediaRequest
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event userMedia
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event userMediaFailed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event userMediaRequest
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event userMedia
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event userMediaFailed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event iceGathering
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event iceCandidate
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event iceComplete
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event iceFailed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event getDescription
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event setDescription
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event dataChannel
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | adding event addStream
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | new listener added to event userMediaRequest
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | new listener added to event userMedia
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | new listener added to event userMediaFailed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | emitting event setDescription
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.inviteservercontext | new listener added to event invite
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.transport | sending WebSocket message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WS 1.1.1.1:5060;branch=z9hG4bK596e6178;rport
To: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>;tag=3cf033g13c
From: "1234567890" <sip:1234567890@1.1.1.1>;tag=as70c987a3
Call-ID: 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060
CSeq: 102 INVITE
Contact: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>
Supported: outbound
Content-Length: 0

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.inviteservercontext | emitting event progress
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.inviteservercontext | emitting event invite
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.ua | emitting event invite
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.inviteservercontext | new listener added to event accepted
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | new listener added to event addStream
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.inviteservercontext | new listener added to event bye
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.inviteservercontext | new listener added to event failed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.inviteservercontext | new listener added to event refer
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.ua | new listener added to event message
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | stream added: default
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:25 GMT+0300 (MSK) | sip.invitecontext.mediahandler | emitting event addStream
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:29 GMT+0300 (MSK) | sip.dialog | dialog 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:50603cf033g13cas70c987a3  changed to CONFIRMED state
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:29 GMT+0300 (MSK) | sip.invitecontext.mediahandler | acquiring local media
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:29 GMT+0300 (MSK) | sip.invitecontext.mediahandler | emitting event userMediaRequest
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:29 GMT+0300 (MSK) | sip.invitecontext.mediahandler | emitting event userMediaRequest
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:31 GMT+0300 (MSK) | sip.invitecontext.mediahandler | emitting event userMedia
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:31 GMT+0300 (MSK) | sip.invitecontext.mediahandler | emitting event userMedia
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:31 GMT+0300 (MSK) | sip.invitecontext.mediahandler | acquired local media stream
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:31 GMT+0300 (MSK) | sip.inviteservercontext | emitting event connecting
2sip-0.6.4.js:5879 Uncaught INVALID_STATE_ERROR: Invalid status: 5InviteServerContext.accept @ sip-0.6.4.js:5879(anonymous function) @ ua.js:176
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.transport | received WebSocket text message:

CANCEL sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WS 1.1.1.1:5060;branch=z9hG4bK596e6178;rport
Max-Forwards: 70
From: "1234567890" <sip:1234567890@1.1.1.1>;tag=as70c987a3
To: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>
Call-ID: 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060
CSeq: 102 CANCEL
User-Agent: Clientbase PBX
Content-Length: 0

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WS 1.1.1.1:5060;branch=z9hG4bK596e6178;rport
To: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>;tag=bgtg5m7r3g
From: "1234567890" <sip:1234567890@1.1.1.1>;tag=as70c987a3
Call-ID: 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060
CSeq: 102 CANCEL
Content-Length: 0

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.ua | emitting event newTransaction
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.transaction.nist | adding event stateChanged
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.servercontext | adding event progress
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.servercontext | adding event accepted
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.servercontext | adding event rejected
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.servercontext | adding event failed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.transport | sending WebSocket message:

SIP/2.0 487 Request Terminated
Via: SIP/2.0/WS 1.1.1.1:5060;branch=z9hG4bK596e6178;rport
To: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>;tag=3cf033g13c
From: "1234567890" <sip:1234567890@1.1.1.1>;tag=as70c987a3
Call-ID: 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060
CSeq: 102 INVITE
Supported: outbound
Content-Length: 0

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.transaction.ist | emitting event stateChanged
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.inviteservercontext | closing INVITE session 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060as70c987a3
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.invitecontext.mediahandler | closing PeerConnection
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.dialog | dialog 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:50603cf033g13cas70c987a3 deleted
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.inviteservercontext | emitting event cancel
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.inviteservercontext | emitting event rejected
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.inviteservercontext | emitting event failed
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.invitecontext.mediahandler | ICE connection state changed to "closed"
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.transport | received WebSocket text message:

ACK sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WS 1.1.1.1:5060;branch=z9hG4bK596e6178;rport
Max-Forwards: 70
From: "1234567890" <sip:1234567890@1.1.1.1>;tag=as70c987a3
To: <sip:3t1kns80@f4oikl5abo9n.invalid;transport=ws>;tag=3cf033g13c
Contact: <sip:1234567890@1.1.1.1:5060;transport=WS>
Call-ID: 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:5060
CSeq: 102 ACK
User-Agent: Clientbase PBX
Content-Length: 0

sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.transaction.ist | emitting event stateChanged
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:48 GMT+0300 (MSK) | sip.ua | emitting event transactionDestroyed

**Comment by james-onsip** [comment]
Hi stshishkin,
  Have you tried this with the [demo-phone](http://sipjs.com/demo-phone/)? I'm leaning towards an application-level error here, please check to make sure your listeners are set up correctly.

Thanks,
James

**Comment by stshishkin** [comment]
Hi James,

Yep I have try with online demo. And I can successfully call to outogoing direction, and as you can see I can receive messages from my Asterisk. But SIP message 200 OK was not send by SIPjs.

Sorry for my english.
I can show log from javascript console if it will helps.

Thank you for your answer.

**Comment by james-onsip** [comment]
A log from this call in the demo-phone would be great. Please post it in a [gist](https://gist.github.com/), so as to avoid clutter in this issue.

**Comment by stshishkin** [comment]
Thanks for prompt about gist.

Here it is.

1.1.1.1 our PBX's external IP 
2.2.2.2 my external IP
1234567890 callerID of incoming call

https://gist.github.com/stshishkin/6b11ae2b1745ed8e6863

**Comment by james-onsip** [comment]
The signaling from the SIP.js perspective looks correct. It looks like your Asterisk box is accepting and immediately terminating. Maybe you are missing something from our [guide](http://sipjs.com/guides/server-configuration/asterisk/)?

**Comment by stshishkin** [comment]
sorry if I did not provide correct log, but behavior of sip.js did not correct. as i said before sip.js did not send 200 OK message, when i try to answer. 

this string in first log 
sip-0.6.4.js:2680 Thu Jun 11 2015 20:06:29 GMT+0300 (MSK) | sip.dialog | dialog 79051c4363473dae0bb6ab8e68cd07e7@1.1.1.1:50603cf033g13cas70c987a3 changed to CONFIRMED state

appear after i push button "answer" but expected massage was not send.

this message is required to establish connection on our PBX (https://tools.ietf.org/html/rfc3665#section-3.1)

**Comment by james-onsip** [comment]
Could you please post the correct logs?

I am still inclined to think this is an issue on your end somewhere, as this is what amounts to a base case that you are testing.

**Comment by james-onsip** [comment]
Did you end up getting this to work? I'm going to close the issue in a week if there's no new developments.

**Comment by james-onsip** [comment]
As promised, closing.

**Comment by dehghanimeh** [comment]
# hey guys
# i have same problem on incoming calls 
## i have two sipjs user like this using this tutorial

https://sipjs.com/guides/server-configuration/asterisk/
-------------------------------------------------------------------------
[1060] ; This will be WebRTC client
type=friend
username=1060 ; The Auth user for SIP.js
host=dynamic ; Allows any host to register
secret=password ; The SIP Password for SIP.js
encryption=yes ; Tell Asterisk to use encryption for this peer
avpf=yes ; Tell Asterisk to use AVPF for this peer
icesupport=yes ; Tell Asterisk to use ICE for this peer
context=default ; Tell Asterisk which context to use when this peer is dialing
directmedia=no ; Asterisk will relay media for this peer
transport=udp,ws,wss ; Asterisk will allow this peer to register on UDP or WebSockets
force_avp=yes ; Force Asterisk to use avp. Introduced in Asterisk 11.11
dtlsenable=yes ; Tell Asterisk to enable DTLS for this peer
dtlsverify=no ; Tell Asterisk to not verify your DTLS certs
dtlscertfile=/etc/asterisk/conf/asterisk.pem ; Tell Asterisk where your DTLS cert file is
dtlsprivatekey=/etc/asterisk/conf/asterisk.pem ; Tell Asterisk where your DTLS private key is
dtlssetup=actpass ; Tell Asterisk to use actpass SDP parameter when setting up DTLS
---------------------------------------------------------------------------------------------------------
[1010] ; This will be WebRTC client
type=friend
username=1010 ; The Auth user for SIP.js
host=dynamic ; Allows any host to register
secret=password ; The SIP Password for SIP.js
encryption=yes ; Tell Asterisk to use encryption for this peer
avpf=yes ; Tell Asterisk to use AVPF for this peer
icesupport=yes ; Tell Asterisk to use ICE for this peer
context=default ; Tell Asterisk which context to use when this peer is dialing
directmedia=no ; Asterisk will relay media for this peer
transport=udp,ws,wss ; Asterisk will allow this peer to register on UDP or WebSockets
force_avp=yes ; Force Asterisk to use avp. Introduced in Asterisk 11.11
dtlsenable=yes ; Tell Asterisk to enable DTLS for this peer
dtlsverify=no ; Tell Asterisk to not verify your DTLS certs
dtlscertfile=/etc/asterisk/conf/asterisk.pem ; Tell Asterisk where your DTLS cert file is
dtlsprivatekey=/etc/asterisk/conf/asterisk.pem ; Tell Asterisk where your DTLS private key is
dtlssetup=actpass ; Tell Asterisk to use actpass SDP parameter when setting up DTLS
---------------------------------------------------------------------------------------------------------------
## and i have regular sip user like this
-----------------------------------------
[1001]
username=1001
nat=yes      
type=friend
host=dynamic
secret=password
context=default
----------------------------------------
## when user 1010 and 1060 from web want to call user 1001 , all things work fine.
## but when web user 1060 what to call web user 1010 
## the invite sipjs event not fired
`userAgent.on('invite',` function (session) {....
## and in asterisk cli appear this error
`chan_sip.c:4268`` __sip_reliable_xmit: Serious Network Trouble; __sip_xmit returns error for pkt data
## detail of asterisk cli error
------------------------------------------------------------------------------------------------
-- Executing [1010@default:4] Dial("SIP/1060-0000001b", "SIP/1010") in new stack
  == DTLS ECDH initialized (automatic), faster PFS enabled
  == Using SIP RTP CoS mark 5
Audio is at 11158
Adding codec ulaw to SDP
Adding codec alaw to SDP
Adding codec gsm to SDP
Adding non-codec 0x1 (telephone-event) to SDP
Reliably Transmitting (NAT) to 151.233.58.206:55423:
INVITE sip:q26suj9d@192.0.2.251;transport=ws SIP/2.0
Via: SIP/2.0/WS 185.8.173.206:5060;branch=z9hG4bK4c6736ac;rport
Max-Forwards: 70
From: "web" <sip:1060@185.8.173.206>;tag=as0110259a
To: <sip:q26suj9d@192.0.2.251;transport=ws>
Contact: <sip:1060@185.8.173.206:5060;transport=WS>
Call-ID: 3e5c57fe49a611db0470fd915fdc7c85@185.8.173.206:5060
CSeq: 102 INVITE
User-Agent: Asterisk PBX 14.1.1
Date: Mon, 18 Sep 2017 16:52:32 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Type: application/sdp
Content-Length: 804

v=0
o=root 30578188 30578188 IN IP4 185.8.173.206
s=Asterisk PBX 14.1.1
c=IN IP4 185.8.173.206
t=0 0
m=audio 11158 RTP/SAVPF 0 8 3 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=maxptime:150
a=ice-ufrag:2996824b4ff09e3e1544138235b5ebaf
a=ice-pwd:50372bfe57a9d2202c6377b90e84d932
a=candidate:Hb908adce 1 UDP 2130706431 185.8.173.206 11158 typ host
a=candidate:H2e1429de 1 UDP 2130706431 46.20.41.222 11158 typ host
a=candidate:Hb908adce 2 UDP 2130706430 185.8.173.206 11159 typ host
a=candidate:H2e1429de 2 UDP 2130706430 46.20.41.222 11159 typ host
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 49:5E:3B:D1:D4:2A:7E:93:D5:1C:E1:90:EC:AA:74:CC:3A:93:ED:78:F7:F3:0D:59:7F:54:CF:66:E2:90:77:32
a=sendrecv
---
[Sep 18 12:52:32] ERROR[15861][C-000003de]: chan_sip.c:4268 __sip_reliable_xmit: Serious Network Trouble; __sip_xmit returns error for pkt data
    -- Called SIP/1010
