### ISSUE TITLE
Can't hand media stream to incoming invites with 100rel

### ISSUE THREAD

**Issue by hatlessman** [onsip/SIP.js#192]
100rel helps hide the ICE setup time, but that isn't possible if the user doesn't accept the GUM request. (or for some reason Chrome denies the GUM for some reason), I suggest a UA configuration option for a media stream that gets passed to getDescription (?, fireNewSession?) on an incoming invite. 

Sorry I'm not including a pull request, but I don't know what I'm doing. Will try and come up with the changes if no one else does.

**Comment by hatlessman** [comment]
I handled it temporarily with an ugly global SUPERMEDIAHINT and replacing 
mediaHint = mediaHint || {};
with
mediaHint = mediaHint || SUPERMEDIAHINT;
in getDescription.

**Comment by etamme** [comment]
I am not certain I understand your problem fully, but SIP.js does support 100 rel, and setting up media in a 183/prack offer answer, but you need to enable it.

Search for 100rel on this page http://sipjs.com/api/0.7.0/session/

**Comment by joseph-onsip** [comment]
> I suggest a UA configuration option for a media stream that gets passed to getDescription (?, fireNewSession?) on an incoming invite.

You can pass a MediaStream when your 'invite' handler calls `accept`, as shown in lines 11-20 of http://jsfiddle.net/8osfkwwg/

See the docs for more info: http://sipjs.com/api/0.7.0/session/#acceptoptions

**Comment by hatlessman** [comment]
etamme: 100rel works great. The problem is on incoming calls when you want to reuse a media stream. How do you hand tghe incoming invite the reusable media stream so sipjs can do ICE before the call is answered?

joseph-onsip: Yes, but that would defeat the whole reason I want to use 100rel which is to do the ICE checking before the call is answered so I don't have two people who can't hear each other for the first 3-7 seconds of the call.

**Comment by wakamoleguy** [comment]
I think Joseph meant to say `progress` rather than `accept`.  Both should take the MediaStream option, when 100rel is active.

**Comment by hatlessman** [comment]
I understand, but I don't understand when I call the progress method on the session. This looks like its done automatically sometime after the 'connecting' event happens.

**Comment by hatlessman** [comment]
This doesn't seem to be an issue. More of a documentation clarification(?), GitHub is probably not the place for this.
