### ISSUE TITLE
Early media 

### ISSUE THREAD

**Issue by sarumjanuch** [onsip/SIP.js#193]
Hi Guys, i noticed that sip.js is not setting remote description when receives 183 Session Progress with SDP, instead i see: "new UAC dialog created with status EARLY". Is it by design, or i miss some option, or this is a bug?

**Comment by wakamoleguy** [comment]
Hi,

We purposefully do not set the remote description on non-reliable provisional responses.  Calls may fork to multiple destinations, causing the eventual 200 OK to have different SDP, and Peer Connections do not handle this well.

If you'd like to get early media running, you'll need to do so with [100rel](https://tools.ietf.org/html/rfc3262).  We use the 'rel100' parameter on the UA and Session to enable support for this.

Thanks,

-Will

**Comment by sarumjanuch** [comment]
Well i understand you, but isn't this should be optional? The issue is, that you are throwing out all Asterisk users. Asterisk do not support 100rel, and it starts ice negotiation, as soon as it sends response with ice candidates to originator, and that make some sense. In current situation, the ice negotiation will fail, because when Asterisk will send 183 with SDP, it will expect for ice negotiation phase, and browser would be not ready for that, because it don't set remote description yet.

**Comment by wakamoleguy** [comment]
This really is the "optional" way of doing it. Trust me when I say we spent days, if not weeks, mulling over the best way to support early media within the technical constraints of WebRTC. As a SIP UA, we cannot know what type of proxy or endpoint we are connecting to, and whether or not any request will fork. Additionally, we can only accept one branch. That isn't our choice but a constraint put forth by the peer connection API. When faced with breaking core RFC 3261 call scenarios or requiring UASs to implement further standards to gain further functionality, we choose the latter.

In this case, there is an RFC to get this behavior, it is quite mature (just one number after the core), and there are many servers that do support it. That's really the best we can do.

**Comment by joseph-onsip** [comment]
For more detail, see https://github.com/onsip/SIP.js/issues/211#issuecomment-133011647
