### ISSUE TITLE
Issue with “Using Cordova with iOS and WebRTC”

### ISSUE THREAD

**Issue by excendia** [onsip/SIP.js#197]
I followed the instructions of “Using Cordova with iOS and WebRTC” and deploy the application on iPhone/iPad and it doesn’t work.
I try to debug the javascript by adding alert messages before and after each line of javascript code. 
The message displayed after the following code was not display:
var SIP = cordova.require("com.onsip.cordova.Sipjs"); 
It seems like there is an issue with that line of code.

Here the code used (https://github.com/onsip/onsip-cordova):

    <video id="localVideo"></video>
    <video id="remoteVideo"></video>
    <input id="target" type="text">
    <button id="makeCall">Make Call</button>

    document.addEventListener("deviceready", function() {
      var SIP = cordova.require("com.onsip.cordova.Sipjs");
      var PhoneRTCMediaHandler = cordova.require("com.onsip.cordova.SipjsMediaHandler")(SIP);
      var mediaOptions = {
        media : {
          constraints: {
            audio: true,
            video: false
          },
          render: {
            local: {
              video: document.getElementById('localVideo')
            },
            remote: {
              video: document.getElementById('remoteVideo')
            }
          }
        }
      };

      window.ua = new SIP.UA({
       uri: 'xxxxxx',
	wsServers: 'ws://xxxxx:8088/ws',
	authorizationUser: 'xxxxxx',
	password: 'xxxxxx',
        mediaHandlerFactory: PhoneRTCMediaHandler,
        traceSip: true
      });

      document.getElementById("makeCall").addEventListener("touchstart", function() {
        if (window.session) {
          alert("Only one call at a time.");
          return;
        }
        window.session = window.ua.invite(document.getElementById('target').value, mediaOptions);
        window.session.on('terminated', function () {window.session = null;});
      });
      window.ua.on('invite', function(_session) {
        if (window.session) {
          alert("Only one call at a time.");
          _session.reject();
          return;
        }
        window.session = _session;
        window.session.accept(mediaOptions);
        window.session.on('terminated', function () {window.session = null;});

      });
    });
    app.initialize();

**Comment by egreenmachine** [comment]
Chances are the onsip-cordova project needs an updated WebRTC library. Interest in that project has been pretty minimal and the amount of work needed to get those libraries updated is not trivial. I haven't had the time to put into it recently, and not many other people here know how to recompile it. There are some other WebRTC wrappers out there that might work for you like [PhoneRTC](https://github.com/alongubkin/phonertc).

**Comment by lylepratt** [comment]
Hi @excendia We use this project in production for iOS:
https://github.com/BetterVoice/iOS-SIP.js

It is basically the same concept as the PhoneRTC project, except rewritten in a way that uses a native socket for signaling communication so that iOS VoIP backgrounding can happen properly. We also have Hold, Transfer, Mute, Hold Music, etc all working properly. Oh, also it works with 64bit builds as well.

**Comment by excendia** [comment]
Hi @lylepratt , thank you for your reply. 
Would you happen to have an example of iOS-SIP.js on how to register (with username, password, domain, websocket), call, and receive calls, along with all the other functionalities? Basically, I'd like to know how to use your plugin. Thank you.

**Comment by lylepratt** [comment]
@excendia it is used almost exactly like the PhoneRTC based plugin you've previously tried. It uses SIP.js as well. The only difference is you need to add this to your UA setup:

```
        mediaHandlerFactory: function defaultFactory (session, options) {        
            if (window.cordova && device.platform === 'iOS') {
              var PhoneRTCMediaHandler = cordova.require('com.sipjs.phonertc.mediahandler')(SIP);
              return new PhoneRTCMediaHandler(session, options);
            }
            else {
              return new SIP.WebRTC.MediaHandler.defaultFactory(session, options);
            }        
          },
```

Follow the install instructions once you've added the plugin to your cordova project. We will try to get some documentation in the repo written soon.

**Comment by lylepratt** [comment]
I added some instructions to the repo.

**Comment by excendia** [comment]
@lylepratt I followed the instructions, but I get linker errors when attempting to build a test application. Here are the steps I've taken: created project, added iOS platform, added SIP.js plugin, added iOS-Sip.js plugin, performed all the operations on step 4 for HelloCordova.xcodeproj, For CordovaLib.xcodeproj, I did the same, but I couldn't find Objective-C Bridging Header and Swift Optimization level. Anyways, I pressed the build button and it fails. Oh yeah, I added webrtc-ios-unified.a to my cordova iOS project folder and added it to linked frameworks and librairies.

**Comment by james-onsip** [comment]
I'm going to close this issue for now, but any further issues can be linked directly at [our cordova project](https://github.com/onsip/onsip-cordova), or, more likely, over at [lylepratt's project](https://github.com/BetterVoice/iOS-SIP.js).
