### ISSUE TITLE
Notify Event not available

### ISSUE THREAD

**Issue by Djcd** [onsip/SIP.js#2]
When i try to use your example from http://sipjs.com/api/0.5.0/subscription/#events

i get 

```
sip.ua | unable to add a listener to a nonexistent event notify sip-0.5.0.js:168
TypeError: Invalid or uninitialized event: notify
    at Object.EventEmitter.on (http://localhost:8080/js/sip-0.5.0.js:321:13)
    at new homeController (http://localhost:8080/app/controllers/homeController.js:6:19)
```

Greetings 
Djcd

**Comment by umasgn** [comment]
What if i want to subscribe for multiple uri 
![code](https://cloud.githubusercontent.com/assets/12139440/21021490/b8f083ca-bd9e-11e6-9260-b3018548724e.png)
?
