### ISSUE TITLE
UA#unregister with all:true no-ops when unregistered

### ISSUE THREAD

**Issue by joseph-onsip** [onsip/SIP.js#204]
demo: http://jsfiddle.net/ykguutf5/

expected: second `UA` sends `REGISTER` with `Contact: *` and `Expires: 0`, [first `UA` is unregistered](https://tools.ietf.org/html/rfc3261#section-10.2.2)

actual: [`this.logger.warn('already unregistered');`](https://github.com/onsip/SIP.js/blob/6d5932c0428942180789d371bdcc87c8e660172a/src/RegisterContext.js#L211)

**Comment by wakamoleguy** [comment]
For those following along, this has nothing to do with the nature of the first UA.  Simply attempting to call `ua.unregister()` on an unregistered UA will result in the same warning.

joseph-onsip, are you suggesting that we should special case that if the `all` flag is set?

**Comment by joseph-onsip** [comment]
> this has nothing to do with the nature of the first UA

Yeah, I just put it there to make the demo a little more realistic, demonstrating that there is indeed another UA that should be affected by the `unregister`.

> are you suggesting that we should special case that if the `all` flag is set?

Yes, I'll probably put together a PR for it, once I sort out any testing issues that may arise.

**Comment by wakamoleguy** [comment]
Sounds good.
