### ISSUE TITLE
dtmf not working

### ISSUE THREAD

**Issue by celevra** [onsip/SIP.js#210]
Hi,

i'm on freeswitch (one with 1.5 and one with 1.6 and i'm not sure if it is only an issue with freeswitch)
if i use session.dtmf('0') nothing happens as of the pbx doesn't hear it.
here is the log:

```
session.dtmf('0');
sip-0.7.0.min.js:36 Sat Aug 15 2015 16:05:14 GMT+0200 (CEST) | sip.transport | sending WebSocket message:

INFO sip:conf-1000_5521@46.38.231.117:5080;transport=udp SIP/2.0
Via: SIP/2.0/WSS hhug8d8lmtg9.invalid;branch=z9hG4bK9736550
Max-Forwards: 70
To: <sip:conf-1000_5521@lionkeen.net>;tag=SX3FZUtUFQH0c
From: <sip:meet-1@lionkeen.net>;tag=b97d9soi2v
Call-ID: ov2mkorur5hc01p22hf9
CSeq: 5417 INFO
Content-Type: application/dtmf-relay
Supported: outbound
User-Agent: SIP.js/0.7.0
Content-Length: 24

Signal= 0
Duration= 100

b.e…s.f {RTCConstraints: Object, inviteWithoutSdp: false, anonymous: false, renderbody: null, rendertype: "text/plain"…}
sip-0.7.0.min.js:36 Sat Aug 15 2015 16:05:14 GMT+0200 (CEST) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS hhug8d8lmtg9.invalid;branch=z9hG4bK9736550;received=188.174.151.201;rport=59074
From: <sip:meet-1@lionkeen.net>;tag=b97d9soi2v
To: <sip:conf-1000_5521@lionkeen.net>;tag=SX3FZUtUFQH0c
Call-ID: ov2mkorur5hc01p22hf9
CSeq: 5417 INFO
User-Agent: FreeSWITCH-mod_sofia/1.7.0+git~20150813T123518Z~dff03e35cf~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Content-Length: 0
```

is there anything else i can provide?

regards

celevra

**Comment by james-onsip** [comment]
Hi celevra,
What you've provided tells us that SIP.js is sending the DTMF correctly, and Freeswitch is even accepting that it was received, so this is most likely an issue with Freeswitch.

That said, [Freeswitch has a lot of DTMF options](https://wiki.freeswitch.org/wiki/DTMF), so you may want to mess around with a few of those before opening up an issue with them. I believe in our own implementation we use the 'liberal dtmf' option.

Good luck,
James

**Comment by victor-torres** [comment]
You can set `liberal-dtmf = true` in your profile configuration as FreeSWITCH documentation suggests [here](https://freeswitch.org/confluence/display/FREESWITCH/Sofia+Configuration+Files):

> liberal-dtmf
> Default: false
> 
> For DTMF negotiation, use this parameter to just always offer 2833 and accept both 2833 and INFO. Use of this parameter is not recommended since its purpose is to try to cope with buggy SIP implementations.
> 
>  `<param name="liberal-dtmf" value="true"/>`
