### ISSUE TITLE
UA.register() with callback/hook for error handling

### ISSUE THREAD

**Issue by jmcoimbra** [onsip/SIP.js#214]
Hello,

I would to share a thought: giving a callback or a hook to handle errors upon SIP REGISTER for SIP.js API.

For instance, we may have the other end down or something like that, so we can take an action programmatically.

Thanks

**Comment by joseph-onsip** [comment]
Hi @jmcoimbra, have you tried listening for the ['registrationFailed' event](http://sipjs.com/api/0.7.0/ua/#registrationfailed)? You may also be interested in the ['disconnected' event](http://sipjs.com/api/0.7.0/ua/#disconnected).

**Comment by wakamoleguy** [comment]
Hi,

There are three events on the UA dealing with registration.  You can listen for `registered` for when a registration is successful, `registrationFailed` for when a registration attempt fails, and `unregistered` for when you either manually unregister or a periodic re-registration attempt fails.

-Will
