### ISSUE TITLE
Firefox not emitting some ICE Connection State Changes

### ISSUE THREAD

**Issue by sarumjanuch** [onsip/SIP.js#215]
Hi everyone, is there any reason, and\or workaround for an issue, that in Firefox event handler for:
- session.mediaHandler.on('iceConnectionCompleted',
are not triggered?

Firefox: 40.0.2
sip.js: SIP.js/0.7.1

**Comment by sarumjanuch** [comment]
In consloe i see: RTCIceServer.url is deprecated! Use urls instead.

**Comment by james-onsip** [comment]
Hi sarumjanuch,
The closest workaround we have forces 'iceGatheringCompleted' to be emitted after a set timeout. This configuration parameter is called '[iceCheckingTimeout]'.(http://sipjs.com/api/0.7.0/ua_configuration_parameters/#icecheckingtimeout)

In terms of 'iceConnectionCompleted,' we don't have anything specifically for that, but nothing in SIP.js specifically hinges on that event occurring either.

**Comment by wakamoleguy** [comment]
Is this still happening?  I know that ICE states in browsers tend to be one of the most finicky areas, and change a lot from version to version.  At the moment, SIP.js just passes up any response from `peerConnection.oniceconnectionstatechange` to an event.  If the event is not emitting, the browser isn't reaching that state.

**Comment by james-onsip** [comment]
I'm going to close this, since there was no response, but please feel free to re-open if the case still happens.
