### ISSUE TITLE
`Session.hold()` and `Session.unhold` not documented

### ISSUE THREAD

**Issue by yahu577** [onsip/SIP.js#220]
Hi, I cannot find `Session.hold()` and `Session.unhold()` in the API documentation, is there a reason why? becoz' it's unstable? 

Ref: http://sipjs.com/api/0.7.0/session/

**Comment by wakamoleguy** [comment]
Pretty much, yes.  When we originally implemented it, hold and unhold were implemented by simply enabling and disabling relevant streams, with not consideration for actually signaling hold.  In latest versions of SIP.js, we now use re-INVITEs as is standard behavior.  We haven't circled back to document it yet.  Thank you for bringing it to our attention.

I've made an issue on our website repo:  https://github.com/onsip/sipjs.com/issues/17.
