### ISSUE TITLE
invite event with invalid null session

### ISSUE THREAD

**Issue by lucasRovaris** [onsip/SIP.js#221]
I was using the library when that happend, i got a sip invite event triggered and the session that came within the event was null.

I was not able to reproduce though, The question is, thats more likely to be some weird state of my application or could it be a sip.js related issue, or even known  issue?

The version im using is a specific commit as follows: #635c0ac27c763800a7eb48023bce0a62b93a0739

Thanks in advance.

**Comment by joseph-onsip** [comment]
Hi @lucasRovaris, unfortunately, without knowing any details about your configuration or what happened, we can't really help here. If you are able to reproduce the problem, please make a topic in the [Google Group](https://groups.google.com/forum/#!forum/sip_js), providing logs (with [`traceSip`](http://sipjs.com/api/0.7.0/ua_configuration_parameters/#tracesip) enabled) and as much information as you can about your client/server/network configurations. If it does turn out to be a bug, we can make another issue to address it.
