### ISSUE TITLE
Use the "Default Communication Device" for Audio

### ISSUE THREAD

**Issue by lylepratt** [onsip/SIP.js#226]
It appears that it is possible to get (at least Chrome) to use the "Default Communication Device" for audio. This should be the default SIP.js behavior, but SIP.js does not do this. Here is a related Chromium issue that has been solved, that also contains an example on how to achieve this behavior: 
https://code.google.com/p/chromium/issues/detail?id=340377

**Comment by james-onsip** [comment]
Hi lylepratt,
  Sorry for the long silence, here, but I gave this a look today. Passing `{optional:[{chromeRenderToAssociatedSink: true}]}` as the audio constraint should be enough to make this work from your app.

I'd like to eventually include this in SIP.js, but that parameter does not seem like the type of thing that will hang around. Firefox doesn't seem to have any particular way of making this happen yet, and worst case you can change which audio device is being used in the address bar, where I believe that setting will persist. Making this `optional` piece seems to work in Firefox (as in, it's still accepted as `true`), but I don't see any kind of documentation on it (or any in Chrome outside of that bug, for that matter).

Maybe another developer feels differently, but until this gets more ironed out (or at least documented), I'd rather keep this out of SIP.js

Thanks,
James

**Comment by james-onsip** [comment]
I'm going to close this since nobody chimed in, but please re-open if you still feel it's worth discussing.

Thanks,
James
