### ISSUE TITLE
Allow using a custom console

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#229]
Some JS frameworks offer their own wrapper around `window.console` (i.e. Angular's $log).
It would be very convenient to be able to tell SIP.js which `console` object to use when trying to print messages.

**Comment by lylepratt** [comment]
This is already possible: http://sipjs.com/api/0.5.0/ua_configuration_parameters/#log

**Comment by matthieusieben** [comment]
Oops, I missed this one. Thanks!
