### ISSUE TITLE
Allow editing EventEmitter.defaultMaxListeners

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#230]
In browsers, there is a wrapper around Node's implementation of EventEmitter. While this is very nice, the `EventEmitter.defaultMaxListeners` property is not exposed. I believe this is due to the fact that you still want to support the (deprecated) `off` method.

The following code would expose the same EventEmitter's API in browser as for Node.

``` js
Object.defineProperty(EventEmitter, 'defaultMaxListeners', {
  get: function () {
    return NodeEventEmitter.defaultMaxListeners;
  },
  set: function (value) {
    NodeEventEmitter.defaultMaxListeners = value;
  }
});
```

**Comment by wakamoleguy** [comment]
> I believe this is due to the fact that you still want to support the (deprecated) off method.

Yeah.

Unless there's a strong reason, I'd rather not muck around with that code right now.  I'm hoping to finalize the deprecation (AKA, remove the wrapper) in the next major version, which shouldn't be too far off.

Is not having defaultMaxListeners affecting you adversely?

**Comment by matthieusieben** [comment]
Not really, it just requires me to use `emitter.setMaxListeners(n)` instead of beeing able to use a global default.

**Comment by james-criscuolo** [comment]
Closing as we no longer have an event emitter wrapper (with the upcoming version at least).
