### ISSUE TITLE
expire not taken into account in 200 of SUBSCRIBE

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#232]
[RFC6665](http://tools.ietf.org/html/rfc6665#section-3.1.1) describes that 200 responses to SUBSCRIBE must contain a `Expires` header.

It looks like SIP.js ignores this value and only checks for an expire timeout in the NOTIFY's `Subscription-State` header. If the notify does not contain an expire, then the subscription is never refreshed.

`setExpiresTimeout` (in [Subscription.js](https://github.com/onsip/SIP.js/blob/master/src/Subscription.js#L200)) should use the `Expires` header from the SUBCRIBE's 200 if no expire is present in the NOTIFY's `Subscription-State` header.

**Comment by matthieusieben** [comment]
The section about the [Notifier NOTIFY Behavior](https://tools.ietf.org/html/rfc3265#section-3.2.2) only states that NOTIFYs **SHOULD** (and not **MUST**) contain an "expires" parameter. So using the value from the SUBSCRIBE's 200-class response seems more reliable.

**Comment by matthieusieben** [comment]
Actually, it looks like the `Expires` header is taken into account to set a refresh timeout ([here](https://github.com/onsip/SIP.js/blob/master/src/Subscription.js#L99)). But as soon as a NOTIFY is received, the timeout is [cleared](https://github.com/onsip/SIP.js/blob/master/src/Subscription.js#L219) and not re-created if the NOTIFY did not contain a `expire` param in the `Subscription-State`.

**Comment by wakamoleguy** [comment]
Another good catch!  The PR request (#236) looks good.  I'll accept that shortly.
