### ISSUE TITLE
Same dialog is reused when receiving Subscription-State is terminated;reason=timeout

### ISSUE THREAD

**Issue by adaxi** [onsip/SIP.js#234]
Here is the NOTIFY informing that our subscription is terminated:

```
NOTIFY sip:cbsr5umj@ss5fdi3s9p32.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WS 172.16.10.33:5060;branch=z9hG4bK2b37d1c6
Max-Forwards: 70
From: <sip:ID00000002@uep>;tag=as114a0625
To: <sip:6d2b467e-3234-4a6f-81a1-af0edab67638@escaux.com>;tag=6vd6h5hbf8
Contact: <sip:ID00000002@172.16.10.33:5060;transport=WS>
Call-ID: 9qaqhhdfavpjlj0np4fj
CSeq: 112 NOTIFY
User-Agent: ESCAUX-SIP
Subscription-State: terminated;reason=timeout
Event: presence
Content-Type: application/epresence+json
Content-Length: 0
```

Here is the SUBSCRIBE  sent back by SIP.js:

```
SUBSCRIBE sip:ID00000002@uep SIP/2.0
Via: SIP/2.0/WSS ss5fdi3s9p32.invalid;branch=z9hG4bK586217
Max-Forwards: 70
To: <sip:ID00000002@uep>
From: <sip:6d2b467e-3234-4a6f-81a1-af0edab67638@escaux.com>;tag=6vd6h5hbf8
Call-ID: 9qaqhhdfavpjlj0np4fj
CSeq: 2530 SUBSCRIBE
Authorization: Digest algorithm=MD5, username="6d2b467e-3234-4a6f-81a1-af0edab67638", realm="asterisk", nonce="33c25cbe", uri="sip:ID00000002@uep", response="36f2a49c2e05a24c048723e7fdc75033"
Accept: application/epresence+json
Event: presence
Expires: 60
Contact: <sip:cbsr5umj@ss5fdi3s9p32.invalid;transport=ws>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY,INVITE,MESSAGE
Supported: outbound
User-Agent: Escaux Connect - Development
Content-Length: 0
```

As you can see the Call-ID and from tag are identical. 
The expected outcome would be the creation of a new dialog.

**Comment by wakamoleguy** [comment]
Good catch on this one.  For those looking on, here are some relevant [RFC 6665](https://tools.ietf.org/html/rfc6665) snippets:

[Section 4.4.1](https://tools.ietf.org/html/rfc6665#section-4.4.1) explicitly states that we should be destroying the dialog in this case.
>  A subscription is destroyed after a notifier sends a NOTIFY request
>   with a "Subscription-State" of "terminated", or in certain error
>   situations described elsewhere in this document.  The subscriber will
>   generally answer such final requests with a 200 (OK) response (unless
>   a condition warranting an alternate response has arisen).  Except
>   when the mechanism described in Section 4.5.2 is used, the
>   destruction of a subscription results in the termination of its
>   associated dialog.

[Section 4.1.3](https://tools.ietf.org/html/rfc6665#section-4.1.3) explains the reasoning behind our immediate resubscription:
> timeout:  The subscription has been terminated because it was not
>      refreshed before it expired.  Clients MAY re-subscribe
>      immediately.  The "retry-after" parameter has no semantics for
>      "timeout".  This reason code is also associated with polling of
>      resource state, as detailed in Section 4.4.3.

So, we are definitely out of compliance with how we are handling this at the moment.  It's a tough one to fix reliably, though, and I want to go about it carefully.  @adaxi, your Pull Request makes an attempt at fixing it, although I am concerned that we are not refreshing all of our state properly when we resubscribe in that case.  It changes one parameter and resubscribes, depending on a lot of code to work that wasn't intended to deal with that sort of situation (a changing `this.request`).

Reading up on the RFC, the proper thing to do here, to me, seems to be using a completely new Subscription object, building everything from scratch.  The old subscription is terminated, so let's start new.  That has its own issues, though, as it doesn't leave us a lot of places to fix it.  We could either:

* Terminate the subscription without reviving it, allowing the application to resubscribe.  This would be an API breaking change, and have to be planned, merged carefully, documented, and communicated accordingly.
* Or, we could complicate `UA.subscribe` with code to deal with timeouts.  This may be okay, but it is certainly unique behavior in that area of the code base.

@adaxi - Is there a specific scenario or presence server that you ran into issues with, or is this just an effort to clean up some non-compliant behavior that could become an issue later?  I'd like to sit on this for a while and gather any feedback I can, both from the other devs and any users who make use of Subscriptions.

**Comment by matthieusieben** [comment]
I would be in favor of solution that exposes a higher level API. Having timeout errors handled properly by the framework would make SIP.js more reliable and easier to use.

Note that we have intensely been using & testing the PR(s) from @adaxi for the last 2 weeks without noticing anymore problems on an Asterisk 11 communication server.

**Comment by adaxi** [comment]
@wakamoleguy - It is related to #236, before my pull request the timers were always cleared when receiving a ```NOTIFY```, and were added if the ```NOTIFY``` contained the Expires time. Since Asterisk does not send the Expires time in the ```NOTIFY``` the subscriptions were not refreshed. This caused frequent timeouts, which led me to this issue.

Regarding my pull request, I assumed that it was OK to replace the ```this.request```, since it is  already done in the unsubscribe. As @matthieusieben stated, we have been using this code for the last 2 weeks without issues.

**Comment by james-onsip** [comment]
Hi @adaxi,
  I recently made some changes to unsubscribe that should make it work properly (as in, actually terminate a subscription). I don't think that had anything to do with this ticket, but is there anything still outstanding here?

Thanks,
James

**Comment by adaxi** [comment]
@james-onsip - I will test this as soon as possible, to check if your changes resolved this issue. As long as a new dialog is created when the subscribe method is called after a timeout it should be fine.

**Comment by adaxi** [comment]
We have tested SIP.js in production with your fixes and everything seems fine.
This issue can be closed.
