### ISSUE TITLE
Calling UA.start after autostart breaks when using WSS

### ISSUE THREAD

**Issue by tycode** [onsip/SIP.js#241]
I had some code like this:

var ua = new SIP.UA( ... );
ua.start();

When on insecure WebSockets, this worked and has been in use for over a year so we never found that it was a problem. However, when we switched to secure WebSockets, it stopped working (as in no further communication happens, no "registered" event is triggered, etc.).

It took a while to figure out what it was, but it appears the default configuration is for the SIP.UA constructor to call start() by itself. As soon as I removed the ua.start() in my code, it worked again. I am guessing that for insecure WebSockets, sip.js realises the connection is already started, and ignores the subsequent call. It should do this for secure WebSockets as well (or at least have consistent behavior, e.g. log a warning in both cases).

**Comment by james-onsip** [comment]
Hi tycode,
Sorry for the long silence here. I can't seem to reproduce this, testing in latest Firefox and Chrome. I know there has been some changes in browsers lately that don't allow insecure Websockets so maybe something has changed?

If you could retest, that'd be great. If the problem still persists, please dump any logs (with traceSip set to true) into a [gist](https://gist.github.com/), and post it here, then I'll inspect.

The [start function](https://github.com/onsip/SIP.js/blob/master/src/UA.js#L355) is fairly simple, so hopefully any bugs should not be too hard to track down, and at worst we need to make a state change slightly earlier than we normally do.

Thanks,
James

**Comment by james-onsip** [comment]
I'm going to close this, but if you can still reproduce we'd like to figure out what's wrong and fix it, so please re-open or open a new issue if that is the case.

Thanks,
James
