### ISSUE TITLE
Close media streams in case of failure

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#243]
When a `failed` event occurs on a session (such as in #242), the media streams are not closed.

Weather this is due to a wrong usage on SIP.js or not, I believe it would be safer to make sure that the media streams are always closed when a session fails or is terminated.

**Comment by markandrus** [comment]
I'm not sure this is desirable, at least as the default. For example, what if you want to call `getUserMedia` _once_ and use the resulting stream in multiple SIP.js Sessions? I don't think you'd want to call `getUserMedia` again due to one of them failing, would you?

**Comment by matthieusieben** [comment]
You probably wouldn't indeed.
