### ISSUE TITLE
Do not immediate terminate REFER subscription

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#25]
This was [requested in the mailing list](https://groups.google.com/forum/#!topic/sip_js/j2Y2oIjZ94s).

When receiving a REFER, the SIP.js user agent replies with a NOTIFY request immediately terminating the subscription.  This is valid as per [RFC 3515 Section 2.4.4](http://tools.ietf.org/html/rfc3515#section-2.4.4), but more complete information (see section 2.4.5 of the RFC) would be nice.

**Comment by klarrimore** [comment]
There's a similar but much more significant issue on the REFER request side in Session.refer.  On a 2XX response to a REFER with replaces, the Session immediately terminates.  The Session needs the ability to continue to stay up to respond and act on the actual NOTIFY.  The original 202 response simply means it's subscribed.  Should I break this out into another issue?

**Comment by wakamoleguy** [comment]
This has also been requested on the [mailing list](https://groups.google.com/d/msgid/sip_js/83c53f56-ea8b-4537-82b3-52761f970595%40googlegroups.com)

**Comment by klarrimore** [comment]
I opened an Issue about it a few days ago with some code I'm using as a workaround here: https://github.com/onsip/SIP.js/issues/254

**Comment by egreenmachine** [comment]
Can you try out #459? I think that I have addressed this issue there. 

* Due to the age of this issue, if we do not hear any feedback on this we will close it once we merge the pull request.
