### ISSUE TITLE
TURN server configuration with ephemeral password

### ISSUE THREAD

**Issue by wackazong** [onsip/SIP.js#250]
I am having problems with the TURN server configuration. I am using one-time passwords which expire after 10mins. The problem is that the TURN configuration needs to be done at UA instantiation. Is it not possible to set TURN credentials directly before making a call?

**Comment by josephfrazier** [comment]
Hi @wackazong. It's currently undocumented, but you can set `turnServers` in the `invite` method options. Here's an example: http://jsfiddle.net/sntjpva3/ You can confirm the TURN server usage at chrome://webrtc-internals or about:webrtc

**Comment by wackazong** [comment]
That's great, but what is even better, it also works on ```accept```. Thanks!
