### ISSUE TITLE
Does sip.js support multiple media devices?

### ISSUE THREAD

**Issue by vadirn** [onsip/SIP.js#251]
I've found the same question here: https://groups.google.com/forum/#!msg/sip_js/s0lJP9kvMe0/e_ZBp-kr2DEJ (here is the fork: https://github.com/onsip/SIP.js/compare/release...josephfrazier:multiple-streams)

What is the current state of things? How can I toggle between front/back cameras?

**Comment by josephfrazier** [comment]
The changes on that branch were incorporated into master as follows:

* https://github.com/josephfrazier/SIP.js/commit/9338fd8b1372d071a777780e8be7b5e7692be8c3 -> d70d06730a1057757e0c937fd5f2af048e7131bb
* https://github.com/josephfrazier/SIP.js/commit/042efea3a5feecaa41dbebaddd14a873cc265e40 -> 502184cc4221c1953a4610ae87e1c9f187f82465

so you should be able to receive/render multiple streams as described in the commit message of https://github.com/onsip/SIP.js/commit/d70d06730a1057757e0c937fd5f2af048e7131bb. Sending multiple streams can be done by passing an array as [`options.media.stream`](http://sipjs.com/api/0.7.0/ua/#invitetarget-elementoptions) to `UA#invite`. Here's an example: http://jsfiddle.net/d9uqokg1/

As far as toggling between front/back cameras, I haven't looked into it further after my comment in the linked discussion: https://groups.google.com/d/msg/sip_js/s0lJP9kvMe0/T0nnqFr7W-4J
