### ISSUE TITLE
NAPTR/SRV support for TURN

### ISSUE THREAD

**Issue by wackazong** [onsip/SIP.js#252]
I am trying to implement a NAPTR/SRV scheme for a collection of TURN servers. I then simply pass "turn:example.com" as turn server. This does not seem to be supported, can you confirm this? I presume this needs to be implemented in the browser's webRTC implementation?

**Comment by josephfrazier** [comment]
Yes, I believe this would need to be implemented by the browser. It looks like the relevant Chrome and Firefox bugs were created a few hours ago, actually:

* https://code.google.com/p/chromium/issues/detail?id=559115
* https://bugzilla.mozilla.org/show_bug.cgi?id=1226550

**Comment by wackazong** [comment]
Morphic resonance I guess. Thanks.
