### ISSUE TITLE
Event Accepted before event progress with "Ringing"

### ISSUE THREAD

**Issue by fwi-odoo** [onsip/SIP.js#253]
Hello,

I was using sip.js 0.6.3 with Asterisk 13.5 and had no issues. Since the Asterisk 13.6 version, the progress event with the reason_phrase "Ringing" is not triggered anymore. And I receive an accepted event before the call is answered. I tried the sip.js 0.7.2 but didn't fix my issue.
Did I miss something in the release notes or this is an actual issue?

Regards.

**Comment by wakamoleguy** [comment]
Hi,

A progress event will be sent any time a 1xx level response is received (except for a 100 Trying).  Can you confirm that your Asterisk server is still sending a 180 Ringing before it sends a 200 OK?

**Comment by fwi-odoo** [comment]
Yes my Asterisk server send the 180 Ringing when I enable the sip debug.

**Comment by wakamoleguy** [comment]
Can you ensure that you have `traceSip: true` set on your SIP.js UA, and post your JavaScript logs here in a gist?

**Comment by fwi-odoo** [comment]
You can find the log there: https://gist.github.com/fwi-odoo/3cd4ccc58c36d46e182d

**Comment by egreenmachine** [comment]
I do not see a 180 Ringing sent from Asterisk in your sip trace. This is what you should see if Asterisk is sending a 180.

```
Mon Nov 23 2015 09:17:34 GMT-0500 (EST) | sip.transport | received WebSocket text message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS u85335spskmp.invalid;branch=z9hG4bK3602066
Record-Route: <sip:some_ip_addresss;lr;ftag=pbsdv6q493;did=df8.e38056e4>
Record-Route: <sip:some_ip_addresss;lr;ftag=pbsdv6q493;did=df8.c7da2d07>
Record-Route: <sip:some_ip_addresss5060;transport=udp;lr;ovid=28ea64c3>
Record-Route: <sip:e1618945b4@some_ip_addresss:443;transport=wss;lr;ovid=28ea64c3>
From: "test" <sip:test@test.onsip.com>;tag=pbsdv6q493
To: <sip:test1@test.onsip.com>;tag=3aKy3F49SaKKr
Call-ID: mlpuefju1stfjhhgs5l5
CSeq: 4434 INVITE
Contact: <sip:contact@some_ip_addresss;gr>
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY
Supported: precondition, 100rel, timer, path, replaces
Content-Length: 0
```

**Comment by fwi-odoo** [comment]
In my Asterisk, I can see:

<--- SIP read from UDP:195.144.71.98:37665 --->
SIP/2.0 180 Ringing
Via: SIP/2.0/UDP 51.254.212.99:5060;rport=5060;received=51.254.212.99;branch=z9hG4bK5eb7e504
Call-ID: 4c4a5cd7651c190e51fd2a2449208b0b@51.254.212.99:5060
From: <sip:1060@51.254.212.99>;tag=as4ba4329b
To: <sip:1061@195.144.71.98>;tag=1de5f415-7489-48bc-af71-9814f28a61b9
CSeq: 102 INVITE
Allow: PRACK, SUBSCRIBE, NOTIFY, REFER, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, OPTIONS, MESSAGE, PUBLISH
Contact: <sip:1061@10.10.0.8:5062>
Content-Length: 0

**Comment by egreenmachine** [comment]
It looks like that 180 is coming from the callee (1061 - VoIP Phone). Asterisk is receiving it, but it is not sending a 180 to caller (1060 - SIP.js).
