### ISSUE TITLE
Allow wsServerMaxReconnection=0

### ISSUE THREAD

**Issue by MayamaTakeshi** [onsip/SIP.js#255]
Hello,
currently, wsServerMaxReconnection cannot be zero. I need sipjs to notify event 'disconnected' immediately instead of trying to reconnect as I pass a short-lived authentication token in the wss URI that will not be valid when reconnection is attempted (a new token must be fetched).
I don't want to fork sip.js just for this. May I suggest this to be allowed?

**Comment by wakamoleguy** [comment]
That seems like reasonable behavior that could be added to the library.  It looks like a WebSocket disconnection does fire an `unregistered` event before (synchronously) attempting to reconnect.  You may be able to disconnect the transport in a listener to that event, or adjust your authentication token for the new attempt.

**Comment by MayamaTakeshi** [comment]
Ah yes. I missed that. I can just use 'unregistered' to have the effect I need (I just tested it). Thanks for the tip. So for me this is not an issue anymore.
