### ISSUE TITLE
No media in Firefox 42 + Asterisk 11.19

### ISSUE THREAD

**Issue by soulhunter1987** [onsip/SIP.js#256]
Connecting to Asterisk 11.19 via WebRTC, asterisk setup according to http://sipjs.com/guides/server-configuration/asterisk/ SIP.js UA config:
```javascript
SIP.UA({
        uri:                user + '@' + host,
        wsServers:          [protocol + '//' + host + ':' + port + '/ws'],
        password:           password,
        hackIpInContact:    true,
        traceSip:           true,
        hackWssInTransport: true,
        stunServers:        [
            "stun:stun.l.google.com:19302",
            "stun:stun.sipgate.net",
            "stun:217.10.68.152",
            "stun:stun.sipgate.net:10000",
            "stun:217.10.68.152:10000"
        ]
    });
```
Using wss connection, call with audio only.
Chrome 47 works perfect when calling to another peer (webrtc or sip softphone, doesn't matter)
In Firefox 42 signaling works, but no sound in the call. Log from Firefox console:
<pre>
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | acquiring local media
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | acquired local media streams
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:0 1 UDP 2130379007 192.168.0.101 62932 typ host
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:6 1 UDP 2122252543 10.211.55.2 58112 typ host
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:12 1 UDP 2122187007 10.37.129.2 54950 typ host
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:0 2 UDP 2130379006 192.168.0.101 57483 typ host
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:6 2 UDP 2122252542 10.211.55.2 56119 typ host
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:12 2 UDP 2122187006 10.37.129.2 50620 typ host
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:3 1 UDP 1694179327 109.237.12.9 62932 typ srflx raddr 192.168.0.101 rport 62932
sip.js (строка 2892)
Fri Dec 04 2015 06:32:25 GMT+0200 (EET) | sip.invitecontext.mediahandler | ICE candidate received: candidate:3 2 UDP 1694179326 109.237.12.9 57483 typ srflx raddr 192.168.0.101 rport 57483
sip.js (строка 2892)
Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.invitecontext.mediahandler | RTCIceChecking Timeout Triggered after 5000 milliseconds
sip.js (строка 2892)

Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.transport | sending WebSocket message:

INVITE sip:2001:sip.7-travel.ru@sip.7-travel.ru SIP/2.0
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK3235882
Max-Forwards: 70
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 1622 INVITE
Contact: <sip:ok9q7c0q@192.0.2.155;transport=wss;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY,INVITE
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.2
Content-Length: 1301

v=0
o=mozilla...THIS_IS_SDPARTA-42.0 5797156348674783538 0 IN IP4 192.0.2.191
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 88:F0:3D:84:B4:E0:05:7A:BC:78:8F:B1:8E:A6:FF:E2:16:64:FA:DC:DD:3A:BA:44:C9:82:E7:77:01:0B:6C:79
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8
c=IN IP4 192.0.2.191
a=candidate:0 1 UDP 2130379007 192.168.0.101 62932 typ host
a=candidate:6 1 UDP 2122252543 10.211.55.2 58112 typ host
a=candidate:12 1 UDP 2122187007 10.37.129.2 54950 typ host
a=candidate:0 2 UDP 2130379006 192.168.0.101 57483 typ host
a=candidate:6 2 UDP 2122252542 10.211.55.2 56119 typ host
a=candidate:12 2 UDP 2122187006 10.37.129.2 50620 typ host
a=candidate:3 1 UDP 1694179327 109.237.12.9 62932 typ srflx raddr 192.168.0.101 rport 62932
a=candidate:3 2 UDP 1694179326 109.237.12.9 57483 typ srflx raddr 192.168.0.101 rport 57483
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=ice-pwd:02f20909c3c91ea8001d3f64c36d8c02
a=ice-ufrag:4c9d01bc
a=mid:sdparta_0
a=msid:{5f49c4a7-423f-c448-b0b8-3e1fb6a57c04} {b55793da-d771-134d-9102-b6a413531176}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:2542239510 cname:{f0e501e9-bd84-ab4a-a77d-4f5256fcdc19}

sip.js (строка 2892)

Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK3235882;received=109.237.12.9;rport=52740
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>;tag=as590ed82b
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 1622 INVITE
Server: Asterisk PBX 11.19.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="21b591e0"
Content-Length: 0

sip.js (строка 2892)

Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.transport | sending WebSocket message:

ACK sip:2001:sip.7-travel.ru@sip.7-travel.ru SIP/2.0
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK3235882
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>;tag=as590ed82b
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
Call-ID: 83j4btn7ss1gd1iu61nv
Content-Length: 0
CSeq: 1622 ACK

sip.js (строка 2892)

Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.transport | sending WebSocket message:

INVITE sip:2001:sip.7-travel.ru@sip.7-travel.ru SIP/2.0
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK2514840
Max-Forwards: 70
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 1623 INVITE
Authorization: Digest algorithm=MD5, username="9090", realm="asterisk", nonce="21b591e0", uri="sip:2001:sip.7-travel.ru@sip.7-travel.ru", response="b838ea271076d184c67b9f6577248400"
Contact: <sip:ok9q7c0q@192.0.2.155;transport=wss;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY,INVITE
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.2
Content-Length: 1301

v=0
o=mozilla...THIS_IS_SDPARTA-42.0 5797156348674783538 0 IN IP4 192.0.2.191
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 88:F0:3D:84:B4:E0:05:7A:BC:78:8F:B1:8E:A6:FF:E2:16:64:FA:DC:DD:3A:BA:44:C9:82:E7:77:01:0B:6C:79
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8
c=IN IP4 192.0.2.191
a=candidate:0 1 UDP 2130379007 192.168.0.101 62932 typ host
a=candidate:6 1 UDP 2122252543 10.211.55.2 58112 typ host
a=candidate:12 1 UDP 2122187007 10.37.129.2 54950 typ host
a=candidate:0 2 UDP 2130379006 192.168.0.101 57483 typ host
a=candidate:6 2 UDP 2122252542 10.211.55.2 56119 typ host
a=candidate:12 2 UDP 2122187006 10.37.129.2 50620 typ host
a=candidate:3 1 UDP 1694179327 109.237.12.9 62932 typ srflx raddr 192.168.0.101 rport 62932
a=candidate:3 2 UDP 1694179326 109.237.12.9 57483 typ srflx raddr 192.168.0.101 rport 57483
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=ice-pwd:02f20909c3c91ea8001d3f64c36d8c02
a=ice-ufrag:4c9d01bc
a=mid:sdparta_0
a=msid:{5f49c4a7-423f-c448-b0b8-3e1fb6a57c04} {b55793da-d771-134d-9102-b6a413531176}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:2542239510 cname:{f0e501e9-bd84-ab4a-a77d-4f5256fcdc19}

sip.js (строка 2892)
Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.transaction.ict | Timer D expired for INVITE client transaction z9hG4bK3235882
sip.js (строка 2892)

Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.transport | received WebSocket text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK2514840;received=109.237.12.9;rport=52740
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 1623 INVITE
Server: Asterisk PBX 11.19.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:2001@77.221.131.250:5060;transport=WS>
Content-Length: 0

sip.js (строка 2892)

Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.transport | received WebSocket text message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK2514840;received=109.237.12.9;rport=52740
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>;tag=as2ee2a13f
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 1623 INVITE
Server: Asterisk PBX 11.19.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:2001@77.221.131.250:5060;transport=WS>
Content-Length: 0

sip.js (строка 2892)
Fri Dec 04 2015 06:32:30 GMT+0200 (EET) | sip.dialog | new UAC dialog created with status EARLY
sip.js (строка 2892)

Fri Dec 04 2015 06:32:32 GMT+0200 (EET) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK2514840;received=109.237.12.9;rport=52740
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>;tag=as2ee2a13f
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 1623 INVITE
Server: Asterisk PBX 11.19.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:2001@77.221.131.250:5060;transport=WS>
Content-Type: application/sdp
Content-Length: 1447

v=0
o=root 281801830 281801830 IN IP4 77.221.131.250
s=Asterisk PBX 11.19.0
c=IN IP4 77.221.131.250
t=0 0
m=audio 14054 RTP/SAVPF 8 0 9
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:9 G722/8000
a=ptime:20
a=ice-ufrag:49f75bf767102bdd6b561b1222e2f2e5
a=ice-pwd:2fa4558c25d86ba513705e7137ebf56c
a=candidate:H4ddd83fa 1 UDP 2130706431 77.221.131.250 14054 typ host
a=candidate:H4ddd83fb 1 UDP 2130706431 77.221.131.251 14054 typ host
a=candidate:H4ddd83fc 1 UDP 2130706431 77.221.131.252 14054 typ host
a=candidate:H4ddd83fd 1 UDP 2130706431 77.221.131.253 14054 typ host
a=candidate:H4ddd83fe 1 UDP 2130706431 77.221.131.254 14054 typ host
a=candidate:Hac112a01 1 UDP 2130706431 172.17.42.1 14054 typ host
a=candidate:Hc0a87a01 1 UDP 2130706431 192.168.122.1 14054 typ host
a=candidate:H4ddd83fa 2 UDP 2130706430 77.221.131.250 14055 typ host
a=candidate:H4ddd83fb 2 UDP 2130706430 77.221.131.251 14055 typ host
a=candidate:H4ddd83fc 2 UDP 2130706430 77.221.131.252 14055 typ host
a=candidate:H4ddd83fd 2 UDP 2130706430 77.221.131.253 14055 typ host
a=candidate:H4ddd83fe 2 UDP 2130706430 77.221.131.254 14055 typ host
a=candidate:Hac112a01 2 UDP 2130706430 172.17.42.1 14055 typ host
a=candidate:Hc0a87a01 2 UDP 2130706430 192.168.122.1 14055 typ host
a=connection:new
a=setup:active
a=fingerprint:SHA-256 17:6F:92:6E:F6:DB:42:2B:F6:05:AF:D7:FB:87:5D:3A:72:7A:A6:2C:D3:D6:E9:BA:BA:39:92:E0:A4:78:9A:14
a=sendrecv

sip.js (строка 2892)

Fri Dec 04 2015 06:32:32 GMT+0200 (EET) | sip.dialog | dialog 83j4btn7ss1gd1iu61nv2vqbedg59qas2ee2a13f  changed to CONFIRMED state

sip.js (строка 2892)

Fri Dec 04 2015 06:32:32 GMT+0200 (EET) | sip.transport | sending WebSocket message:

ACK sip:2001@77.221.131.250:5060;transport=ws SIP/2.0
Via: SIP/2.0/WSS 192.0.2.155;branch=z9hG4bK965839
Max-Forwards: 70
To: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>;tag=as2ee2a13f
From: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 1623 ACK
Supported: outbound
User-Agent: SIP.js/0.7.2
Content-Length: 0

sip.js (строка 2892)
Fri Dec 04 2015 06:32:32 GMT+0200 (EET) | sip.invitecontext.mediahandler | stream added: {b2f90a74-2b3c-0745-805d-61fe0a6cdb90}
sip.js (строка 2892)

Fri Dec 04 2015 06:32:34 GMT+0200 (EET) | sip.transport | received WebSocket text message:

BYE sip:ok9q7c0q@192.0.2.155;transport=wss;ob SIP/2.0
Via: SIP/2.0/WS 77.221.131.250:5060;branch=z9hG4bK07b6e1ad;rport
Max-Forwards: 70
From: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>;tag=as2ee2a13f
To: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 102 BYE
User-Agent: Asterisk PBX 11.19.0
Proxy-Authorization: Digest username="9090", realm="asterisk", algorithm=MD5, uri="sip:sip.7-travel.ru", nonce="21b591e0", response="3e3aab3cb8ad814df62cf595fb3fb1f4"
X-Asterisk-HangupCause: Normal Clearing
X-Asterisk-HangupCauseCode: 16
Content-Length: 0

sip.js (строка 2892)

Fri Dec 04 2015 06:32:34 GMT+0200 (EET) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WS 77.221.131.250:5060;branch=z9hG4bK07b6e1ad;rport
To: <sip:9090@sip.7-travel.ru>;tag=2vqbedg59q
From: <sip:2001:sip.7-travel.ru@sip.7-travel.ru>;tag=as2ee2a13f
Call-ID: 83j4btn7ss1gd1iu61nv
CSeq: 102 BYE
Supported: outbound
User-Agent: SIP.js/0.7.2
Content-Length: 0

sip.js (строка 2892)
Fri Dec 04 2015 06:32:34 GMT+0200 (EET) | sip.inviteclientcontext | closing INVITE session 83j4btn7ss1gd1iu61nvujfff56fgr
sip.js (строка 2892)
Fri Dec 04 2015 06:32:34 GMT+0200 (EET) | sip.invitecontext.mediahandler | closing PeerConnection
sip.js (строка 2892)
Fri Dec 04 2015 06:32:34 GMT+0200 (EET) | sip.dialog | dialog 83j4btn7ss1gd1iu61nv2vqbedg59qas2ee2a13f deleted
</pre>

**Comment by soulhunter1987** [comment]
I think it is an Asterisk issue (or may be asterisk-related configuration). I currently moved to Freeswitch and everything works out of the box there. I think this issue may be closed.

**Comment by roginvs** [comment]
As far as I know, this is because Firefox forces stronger DTLS security, which is not supported with default version of openssl. Try to rebuild asterisk with latest openssl library.

**Comment by soulhunter1987** [comment]
May be you are right, but i already moved to FS and do not want to deal with asterisk any more. I is a nigthmare ) FS works out of the box, while Asterisk needs a lot of configuration for WebRTC usage and in fact doesn't work as expected in many scenarios.
