### ISSUE TITLE
PermissionDeniedError when permission should be granted

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#26]
I've heard of this happening a couple times, both in Chrome, across platform (once on Mac OS X and once on Windows 8.1).

~~~
sip.invitecontext.mediahandler | unable to acquire stream sip-0.5.0.js?v=1400985007312:168 NavigatorUserMediaError {constraintName: "", message: "", name: "PermissionDeniedError"} sip-0.5.0.js?v=1400985007312:170
~~~

It has been reported to happen more often when the JS Console is open, which suggests something weird may be going on.

**Comment by wpp** [comment]
I noticed this a couple of times. But like @wakamoleguy suggested it only happens when the "JS Console is open". I think it happens more often when I set breakpoints in Chrome (perhaps be a timing issue). But thats as far as "reproducing" it goes.

**Comment by james-onsip** [comment]
We haven't seen this in a while, but if anybody sees it again, feel free to re-open or open a new issue.

Thanks,
James

**Comment by yeligoth** [comment]
[Quantifiers_activity.pptx](https://github.com/onsip/SIP.js/files/664054/Quantifiers_activity.pptx)
