### ISSUE TITLE
Demo phone not working in Chrome

### ISSUE THREAD

**Issue by girishdharmaraj** [onsip/SIP.js#263]
Hello,

I was trying to use the http://sipjs.com/demo-phone/ via Chrome browser (latest version) connected to my freeswitch server, the client is getting registered but unable to place the INVITE.

If I use Mozilla Firefox everything is ok and able to hear the voice. any idea what I need to change to get it working on google Chrome.

**Comment by egreenmachine** [comment]
We are aware of this issue starting in Chrome 47 and are looking for a solution. I am going to close this ticket in favor of [sipjs.com #21](https://github.com/onsip/sipjs.com/issues/21).
