### ISSUE TITLE
No Audio call on Peer to Peer connection

### ISSUE THREAD

**Issue by NishatSharma** [onsip/SIP.js#264]
Hi, I am using Asterisk 11.11 and centOs 6.5 with the reference from below link:
**** sip.js 0.7.1 *****
http://sipjs.com/guides/server-configuration/asterisk/

I have followed the same steps as mentioned in above link

****************** ****************** ****************** ****************** ****************** ****************** 
When i try to call using 3cx phone from 1061 (Legacy Client) to 1062 (Legacy Client), Call get connected and i clearly heard voice from the other end.
****************** ****************** ****************** ****************** ****************** ******************  

*********  *********  *********  *********  *********  *********  *********  *********  *********  *********  *********  
                                                              Problem:

When i i try to call from 1060 (WebRTC Client) to 1061 (Legacy Client) using sip.js

CALL GET CONNECTED BUT CAN'T HEAR VOICE FROM OTHER END.
*********  *********  *********  *********  *********  *********  *********  *********  *********  *********  *********  

Client apps: Firefox 39.0

Below are the Asterisk config files:

********** http.conf *************
[general]
enabled=yes
bindaddr=192.168.55.55 ; Replace this with your IP address
bindport=8088 ; Replace this with the port you want to listen 

************* sip.conf *************
[general]
realm=192.168.55.55 ; Replace this with your IP address
udpbindaddr=192.168.55.55 ; Replace this with your IP address
transport=udp

[1060] ; This will be WebRTC client
type=friend
username=1060 ; The Auth user for SIP.js
host=dynamic ; Allows any host to register
secret=Aa1060 ; The SIP Password for SIP.js
encryption=yes ; Tell Asterisk to use encryption for this peer
avpf=yes ; Tell Asterisk to use AVPF for this peer
icesupport=yes ; Tell Asterisk to use ICE for this peer
context=default ; Tell Asterisk which context to use when this peer is dialing
directmedia=no ; Asterisk will relay media for this peer
transport=udp,ws ; Asterisk will allow this peer to register on UDP or WebSockets
force_avp=yes ; Force Asterisk to use avp. Introduced in Asterisk 11.11
dtlsenable=yes ; Tell Asterisk to enable DTLS for this peer
dtlsverify=no ; Tell Asterisk to not verify your DTLS certs
dtlscertfile=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS cert file is
dtlsprivatekey=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS private key is
dtlssetup=actpass ; Tell Asterisk to use actpass SDP parameter when setting up DTLS

[1061] ; This will be the legacy SIP client
type=friend
username=1061
host=dynamic
secret=Aa1061
context=default

[1062] ; This will be the legacy SIP client
type=friend
username=1062
host=dynamic
secret=Aa1062
context=default

************* extensions.conf *************
[default]
exten => 1060,1,Dial(SIP/1060) ; Dialing 1060 will call the SIP client registered to 1060
exten => 1061,1,Dial(SIP/1061) ; Dialing 1061 will call the SIP client registered to 1061
exten => 1062,1,Dial(SIP/1062) ; Dialing 1062 will call the SIP client registered to 1062
  

*******************************************************************************************************************************
                                                           Browser logs
*******************************************************************************************************************************

Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | configuration parameters after validation:
sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · viaHost: "192.0.2.77"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · uri: sip:1060@192.168.55.55
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · wsServers: [{"ws_uri":"ws://192.168.55.55:8088/ws","sip_uri":"<sip:192.168.55.55:8088;transport=ws;lr>","weight":0,"status":0,"scheme":"WS"}]
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · password: NOT SHOWN
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · registerExpires: 600
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · register: true
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · registrarServer: sip:192.168.55.55
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · wsServerMaxReconnection: 3
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · wsServerReconnectionTimeout: 10
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · connectionRecoveryMinInterval: 2
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · connectionRecoveryMaxInterval: 30
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · keepAliveInterval: 0
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · usePreloadedRoute: false
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · userAgentString: "SIP.js/0.7.1"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · iceCheckingTimeout: 5000
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · noAnswerTimeout: 60000
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · stunServers: ["stun:stun.l.google.com:19302"]
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · turnServers: []
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · traceSip: true
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · hackViaTcp: false
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · hackIpInContact: true
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · hackWssInTransport: false
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · contactTransport: "ws"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · forceRport: false
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · autostart: true
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · rel100: "none"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · replaces: "none"
sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · mediaHandlerFactory: function defaultFactory(session, options) {
"use strict";

  return new MediaHandler(session, options);
}

sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · authenticationFactory: undefined
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · authorizationUser: "1060"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · instanceId: "3fd288e7-dbba-4f7f-af15-dac6c500fd7d"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · sipjsId: "ppm4j"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · hostportParams: "192.168.55.55"
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | · media: undefined
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.ua | user requested startup...
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:21 GMT+0530 (India Standard Time) | sip.transport | connecting to WebSocket ws://192.168.55.55:8088/ws
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:22 GMT+0530 (India Standard Time) | sip.transport | WebSocket ws://192.168.55.55:8088/ws connected
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:22 GMT+0530 (India Standard Time) | sip.ua | connection state set to 0
sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:22 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

REGISTER sip:192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK8417301
Max-Forwards: 70
To: <sip:1060@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=b4gfu699q5
Call-ID: a4nf3heukv1lu917fnafh9
CSeq: 81 REGISTER
Contact: <sip:45l4e1p5@192.0.2.77;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:3fd288e7-dbba-4f7f-af15-dac6c500fd7d>";expires=600
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:23 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK8417301;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=b4gfu699q5
To: <sip:1060@192.168.55.55>;tag=as424c86bc
Call-ID: a4nf3heukv1lu917fnafh9
CSeq: 81 REGISTER
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="192.168.55.55", nonce="4a9de4e5"
Content-Length: 0

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:23 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

REGISTER sip:192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK618983
Max-Forwards: 70
To: <sip:1060@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=b4gfu699q5
Call-ID: a4nf3heukv1lu917fnafh9
CSeq: 82 REGISTER
Authorization: Digest algorithm=MD5, username="1060", realm="192.168.55.55", nonce="4a9de4e5", uri="sip:192.168.55.55", response="867dff9ed67661d4961758538159bbde"
Contact: <sip:45l4e1p5@192.0.2.77;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:3fd288e7-dbba-4f7f-af15-dac6c500fd7d>";expires=600
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:23 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK618983;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=b4gfu699q5
To: <sip:1060@192.168.55.55>;tag=as424c86bc
Call-ID: a4nf3heukv1lu917fnafh9
CSeq: 82 REGISTER
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Expires: 600
Contact: <sip:45l4e1p5@192.0.2.77;transport=ws>;expires=600
Date: Wed, 23 Dec 2015 04:45:13 GMT
Content-Length: 0

sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:23 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | acquiring local media
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:25 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | acquired local media streams
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:25 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ICE candidate received: candidate:0 1 UDP 2128609535 192.168.5.66 50437 typ host
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:25 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ICE candidate received: candidate:0 2 UDP 2128609534 192.168.5.66 50438 typ host
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:25 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ICE candidate received: candidate:1 1 UDP 1692467199 202.131.123.146 18881 typ srflx raddr 192.168.5.66 rport 50437
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:25 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ICE candidate received: candidate:1 2 UDP 1692467198 202.131.123.146 65424 typ srflx raddr 192.168.5.66 rport 50438
sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:25 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

INVITE sip:1061@192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK2052471
Max-Forwards: 70
To: <sip:1061@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1391 INVITE
Contact: <sip:45l4e1p5@192.0.2.77;transport=ws;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.1
Content-Length: 1110

v=0
o=mozilla...THIS_IS_SDPARTA-39.0 4294967295 0 IN IP4 192.0.2.212
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 FF:A2:8A:DC:0E:07:23:8F:44:92:BD:24:DA:AA:B3:5D:95:E3:53:EC:56:62:75:1F:BB:6F:0D:FC:7C:DB:D2:54
a=group:BUNDLE sdparta_0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 18881 UDP/TLS/RTP/SAVPF 109 9 0 8
c=IN IP4 202.131.123.146
a=candidate:0 1 UDP 2128609535 192.168.5.66 50437 typ host
a=candidate:0 2 UDP 2128609534 192.168.5.66 50438 typ host
a=candidate:1 1 UDP 1692467199 202.131.123.146 18881 typ srflx raddr 192.168.5.66 rport 50437
a=candidate:1 2 UDP 1692467198 202.131.123.146 65424 typ srflx raddr 192.168.5.66 rport 50438
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=ice-pwd:1aa4c4c6e82d4bd9b61bfc8955079111
a=ice-ufrag:5cf0fc5f
a=mid:sdparta_0
a=msid:{4ffac880-bd3c-4e0f-9980-94db3a80ac83} {6e95f371-a363-4d4c-b5cc-5deb8bab00c2}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:556552029 cname:{7d6564f4-c1b8-4f3b-b634-fdd758171eb0}

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:26 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK2052471;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
To: <sip:1061@192.168.55.55>;tag=as7db80572
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1391 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="192.168.55.55", nonce="5367a6b5"
Content-Length: 0

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:26 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

ACK sip:1061@192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK2052471
To: <sip:1061@192.168.55.55>;tag=as7db80572
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1391 ACK

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:26 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

INVITE sip:1061@192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK844225
Max-Forwards: 70
To: <sip:1061@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1392 INVITE
Authorization: Digest algorithm=MD5, username="1060", realm="192.168.55.55", nonce="5367a6b5", uri="sip:1061@192.168.55.55", response="4381429e850997e71d2ced35c7b4c952"
Contact: <sip:45l4e1p5@192.0.2.77;transport=ws;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.1
Content-Length: 1110

v=0
o=mozilla...THIS_IS_SDPARTA-39.0 4294967295 0 IN IP4 192.0.2.212
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 FF:A2:8A:DC:0E:07:23:8F:44:92:BD:24:DA:AA:B3:5D:95:E3:53:EC:56:62:75:1F:BB:6F:0D:FC:7C:DB:D2:54
a=group:BUNDLE sdparta_0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 18881 UDP/TLS/RTP/SAVPF 109 9 0 8
c=IN IP4 202.131.123.146
a=candidate:0 1 UDP 2128609535 192.168.5.66 50437 typ host
a=candidate:0 2 UDP 2128609534 192.168.5.66 50438 typ host
a=candidate:1 1 UDP 1692467199 202.131.123.146 18881 typ srflx raddr 192.168.5.66 rport 50437
a=candidate:1 2 UDP 1692467198 202.131.123.146 65424 typ srflx raddr 192.168.5.66 rport 50438
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=ice-pwd:1aa4c4c6e82d4bd9b61bfc8955079111
a=ice-ufrag:5cf0fc5f
a=mid:sdparta_0
a=msid:{4ffac880-bd3c-4e0f-9980-94db3a80ac83} {6e95f371-a363-4d4c-b5cc-5deb8bab00c2}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:556552029 cname:{7d6564f4-c1b8-4f3b-b634-fdd758171eb0}

sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:26 GMT+0530 (India Standard Time) | sip.transaction.ict | Timer D expired for INVITE client transaction z9hG4bK2052471
sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:26 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK844225;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
To: <sip:1061@192.168.55.55>
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1392 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:1061@192.168.55.55:5060;transport=WS>
Content-Length: 0

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:15:26 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK844225;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
To: <sip:1061@192.168.55.55>;tag=as64ad6ade
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1392 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:1061@192.168.55.55:5060;transport=WS>
Content-Length: 0

sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:26 GMT+0530 (India Standard Time) | sip.dialog | new UAC dialog created with status EARLY
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:15:58 GMT+0530 (India Standard Time) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK844225
sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:16:26 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK844225;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
To: <sip:1061@192.168.55.55>;tag=as64ad6ade
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1392 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:1061@192.168.55.55:5060;transport=WS>
Content-Length: 0

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:17:06 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK844225;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
To: <sip:1061@192.168.55.55>;tag=as64ad6ade
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1392 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:1061@192.168.55.55:5060;transport=WS>
Content-Type: application/sdp
Content-Length: 589

v=0
o=root 1876956366 1876956366 IN IP4 192.168.55.55
s=Asterisk PBX 11.11.0
c=IN IP4 192.168.55.55
t=0 0
m=audio 18762 RTP/SAVPF 0 8
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=ptime:20
a=ice-ufrag:7ebf6a451ef956bb0796a6f4317f0f3c
a=ice-pwd:2f04e27b6f850b1d69e09c874575487a
a=candidate:Hc0a83737 1 UDP 2130706431 192.168.55.55 18762 typ host
a=candidate:Hc0a83737 2 UDP 2130706430 192.168.55.55 18763 typ host
a=connection:new
a=setup:active
a=fingerprint:SHA-256 26:93:4F:49:44:CA:08:56:52:79:E6:2D:D3:2A:86:7A:A7:75:CD:EE:CD:13:B6:71:74:02:23:31:73:BA:35:D8
a=sendrecv

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:17:06 GMT+0530 (India Standard Time) | sip.dialog | dialog ppm4jpj78hkmqk3571tpbdei776rn9as64ad6ade  changed to CONFIRMED state

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:17:06 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

ACK sip:1061@192.168.55.55:5060;transport=ws SIP/2.0
Via: SIP/2.0/WS 192.0.2.77;branch=z9hG4bK8183418
Max-Forwards: 70
To: <sip:1061@192.168.55.55>;tag=as64ad6ade
From: <sip:1060@192.168.55.55>;tag=bdei776rn9
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 1392 ACK
Supported: outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0

sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:06 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | stream added: {fa80a672-af98-4ab6-8a44-4900c6e3bc26}
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:11 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | RTCIceChecking Timeout Triggered after 5000 milliseconds
sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:17:19 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

BYE sip:45l4e1p5@192.0.2.77;transport=ws;ob SIP/2.0
Via: SIP/2.0/WS 192.168.55.55:5060;branch=z9hG4bK0dde47e4
Max-Forwards: 70
From: <sip:1061@192.168.55.55>;tag=as64ad6ade
To: <sip:1060@192.168.55.55>;tag=bdei776rn9
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 102 BYE
User-Agent: Asterisk PBX 11.11.0
Proxy-Authorization: Digest username="1060", realm="192.168.55.55", algorithm=MD5, uri="sip:192.168.55.55", nonce="5367a6b5", response="c727f52ceaf50974abd1821ba4f4db17"
X-Asterisk-HangupCause: Normal Clearing
X-Asterisk-HangupCauseCode: 16
Content-Length: 0

sip-0.7.1.js (line 2810)

Wed Dec 23 2015 18:17:19 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WS 192.168.55.55:5060;branch=z9hG4bK0dde47e4
To: <sip:1060@192.168.55.55>;tag=bdei776rn9
From: <sip:1061@192.168.55.55>;tag=as64ad6ade
Call-ID: ppm4jpj78hkmqk3571tp
CSeq: 102 BYE
Supported: outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0

sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:19 GMT+0530 (India Standard Time) | sip.inviteclientcontext | closing INVITE session ppm4jpj78hkmqk3571tp98ju01709m
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:19 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | closing PeerConnection
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:19 GMT+0530 (India Standard Time) | sip.dialog | dialog ppm4jpj78hkmqk3571tpbdei776rn9as64ad6ade deleted
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:19 GMT+0530 (India Standard Time) | sip.transaction.nist | Timer J expired for non-INVITE server transaction z9hG4bK0dde47e4
sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:25 GMT+0530 (India Standard Time) | sip.inviteclientcontext | Error: Attempted to send BYE in a terminated session.
	

target.call(console, content);

sip-0.7.1.js (line 2810)
Wed Dec 23 2015 18:17:38 GMT+0530 (India Standard Time) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK844225
sip-0.7.1.js (line 2810)

Any help is highly appreciated.

**Comment by egreenmachine** [comment]
It appears that Asterisk is sending a BYE, and the call is terminating. Since this appears to be an Asterisk issue, I am going to close this issue. For help with Asterisk, could you please follow up on our [mailing list](https://groups.google.com/forum/#!forum/sip_js) and include logs from Asterisk? Thanks
