### ISSUE TITLE
No Audio call on Peer to Peer connection

### ISSUE THREAD

**Issue by mitesh1980** [onsip/SIP.js#265]
Hi @egreenmachine,

I am trying to call using Asterisk 11.11 only, not using FreeSwitch now.

********************** ********************** ********************** ********************** ********************** 
I am successfull to get audio call using 3cx softphone on calling 1061 (Legacy Client) to 1062 (Legacy Client)

Problem: When i try t call using sip.js and WebRTC client (1060) to 1061 (Legacy Client). call get connected but no audio.
********************** ********************** ********************** ********************** ********************** 

*******************************************************************************************************************************
Asterisk log:

Http conf:

[general]
enabled=yes
bindaddr=192.168.55.55 ; Replace this with your IP address
bindport=8088 ; Replace this with the port you want to listen

sip.conf:

[general]
realm=192.168.55.55 ; Replace this with your IP address
udpbindaddr=192.168.55.55 ; Replace this with your IP address
transport=udp
icesupport=yes ;

[1060] ; This will be WebRTC client
type=friend
username=1060 ; The Auth user for SIP.js
host=dynamic ; Allows any host to register
secret=Aa1060 ; The SIP Password for SIP.js
encryption=yes ; Tell Asterisk to use encryption for this peer
avpf=yes ; Tell Asterisk to use AVPF for this peer
icesupport=yes ; Tell Asterisk to use ICE for this peer
context=default ; Tell Asterisk which context to use when this peer is dialing
directmedia=no ; Asterisk will relay media for this peer
transport=udp,ws ; Asterisk will allow this peer to register on UDP or WebSockets
force_avp=yes ; Force Asterisk to use avp. Introduced in Asterisk 11.11
dtlsenable=yes ; Tell Asterisk to enable DTLS for this peer
dtlsverify=no ; Tell Asterisk to not verify your DTLS certs
dtlscertfile=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS cert file is
dtlsprivatekey=/etc/asterisk/keys/asterisk.pem ; Tell Asterisk where your DTLS private key is
dtlssetup=actpass ; Tell Asterisk to use actpass SDP parameter when setting up DTLS

[1061] ; This will be the legacy SIP client
type=friend
username=1061
host=dynamic
secret=Aa1061
context=default

[1062] ; This will be the legacy SIP client
type=friend
username=1062
host=dynamic
secret=Aa1062
context=default

extensions.conf:

[general]
[default]
exten => 1060,1,Dial(SIP/1060) ; Dialing 1060 will call the SIP client registered to 1060
exten => 1061,1,Dial(SIP/1061) ; Dialing 1061 will call the SIP client registered to 1061
exten => 1062,1,Dial(SIP/1062) ; Dialing 1062 will call the SIP client registered to 1062

*******************************************************************************************************************************
Browser log :: 

Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | configuration parameters after validation:
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · viaHost: "192.0.2.39"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · uri: sip:1060@192.168.55.55
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · wsServers: [{"ws_uri":"ws://192.168.55.55:8088/ws","sip_uri":"<sip:192.168.55.55:8088;transport=ws;lr>","weight":0,"status":0,"scheme":"WS"}]
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · password: NOT SHOWN
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · registerExpires: 600
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · register: true
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · registrarServer: sip:192.168.55.55
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · wsServerMaxReconnection: 3
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · wsServerReconnectionTimeout: 10
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · connectionRecoveryMinInterval: 2
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · connectionRecoveryMaxInterval: 30
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · keepAliveInterval: 0
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · usePreloadedRoute: false
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · userAgentString: "SIP.js/0.7.1"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · iceCheckingTimeout: 5000
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · noAnswerTimeout: 60000
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · stunServers: ["stun:null"]
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · turnServers: []
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · traceSip: true
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · hackViaTcp: false
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · hackIpInContact: true
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · hackWssInTransport: false
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · contactTransport: "ws"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · forceRport: false
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · autostart: true
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · rel100: "none"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · replaces: "none"
sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · mediaHandlerFactory: function defaultFactory(session, options) {
"use strict";

  return new MediaHandler(session, options);
}

sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · authenticationFactory: undefined
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · authorizationUser: "1060"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · instanceId: "1cf105ad-f426-4279-ac8e-d0d9710fafe6"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · sipjsId: "lmfem"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · hostportParams: "192.168.55.55"
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | · media: undefined
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.ua | user requested startup...
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:47 GMT+0530 (India Standard Time) | sip.transport | connecting to WebSocket ws://192.168.55.55:8088/ws
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:48 GMT+0530 (India Standard Time) | sip.transport | WebSocket ws://192.168.55.55:8088/ws connected
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:48 GMT+0530 (India Standard Time) | sip.ua | connection state set to 0
sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:48 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

REGISTER sip:192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK1439709
Max-Forwards: 70
To: <sip:1060@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=c3fc38pv8r
Call-ID: o85ri2j93p9m5gjupdedhq
CSeq: 81 REGISTER
Contact: <sip:pmh91k37@192.0.2.39;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:1cf105ad-f426-4279-ac8e-d0d9710fafe6>";expires=600
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:49 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK1439709;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=c3fc38pv8r
To: <sip:1060@192.168.55.55>;tag=as0cb422fb
Call-ID: o85ri2j93p9m5gjupdedhq
CSeq: 81 REGISTER
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="192.168.55.55", nonce="3d0bad12"
Content-Length: 0

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:49 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

REGISTER sip:192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK5260782
Max-Forwards: 70
To: <sip:1060@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=c3fc38pv8r
Call-ID: o85ri2j93p9m5gjupdedhq
CSeq: 82 REGISTER
Authorization: Digest algorithm=MD5, username="1060", realm="192.168.55.55", nonce="3d0bad12", uri="sip:192.168.55.55", response="9cf40844dd09cb8541d89344620c4481"
Contact: <sip:pmh91k37@192.0.2.39;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:1cf105ad-f426-4279-ac8e-d0d9710fafe6>";expires=600
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:49 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK5260782;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=c3fc38pv8r
To: <sip:1060@192.168.55.55>;tag=as0cb422fb
Call-ID: o85ri2j93p9m5gjupdedhq
CSeq: 82 REGISTER
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Expires: 600
Contact: <sip:pmh91k37@192.0.2.39;transport=ws>;expires=600
Date: Thu, 24 Dec 2015 03:11:38 GMT
Content-Length: 0

sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:50 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | acquiring local media
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:51 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | acquired local media streams
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:51 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ICE candidate received: candidate:0 1 UDP 2128609535 192.168.5.66 50458 typ host
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:51 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ICE candidate received: candidate:0 2 UDP 2128609534 192.168.5.66 50459 typ host
sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:53 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

INVITE sip:1061@192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK9277042
Max-Forwards: 70
To: <sip:1061@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
Call-ID: lmfemhosah81njiijop6
CSeq: 7555 INVITE
Contact: <sip:pmh91k37@192.0.2.39;transport=ws;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.1
Content-Length: 916

v=0
o=mozilla...THIS_IS_SDPARTA-39.0 4294967295 0 IN IP4 192.0.2.67
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 E9:19:C3:31:90:BB:11:56:15:E1:CE:8B:92:03:EB:73:2F:C9:47:E0:52:95:2B:BF:2B:B4:A6:C7:10:23:B5:C1
a=group:BUNDLE sdparta_0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 50458 UDP/TLS/RTP/SAVPF 109 9 0 8
c=IN IP4 192.168.5.66
a=candidate:0 1 UDP 2128609535 192.168.5.66 50458 typ host
a=candidate:0 2 UDP 2128609534 192.168.5.66 50459 typ host
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=ice-pwd:0e1097b0ff55158a8feeed2696e32d0e
a=ice-ufrag:8c3ffa52
a=mid:sdparta_0
a=msid:{7d1f65c7-21f4-4528-95e0-21e9262c7fde} {844c2c22-3ead-407d-9b51-37aa45d4c836}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:522719446 cname:{0afcc099-72d5-4ae2-a837-ca09e9079b0e}

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:53 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK9277042;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
To: <sip:1061@192.168.55.55>;tag=as15dbc943
Call-ID: lmfemhosah81njiijop6
CSeq: 7555 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="192.168.55.55", nonce="57c93e71"
Content-Length: 0

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:53 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

ACK sip:1061@192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK9277042
To: <sip:1061@192.168.55.55>;tag=as15dbc943
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
Call-ID: lmfemhosah81njiijop6
CSeq: 7555 ACK

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:53 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

INVITE sip:1061@192.168.55.55 SIP/2.0
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK2032100
Max-Forwards: 70
To: <sip:1061@192.168.55.55>
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
Call-ID: lmfemhosah81njiijop6
CSeq: 7556 INVITE
Authorization: Digest algorithm=MD5, username="1060", realm="192.168.55.55", nonce="57c93e71", uri="sip:1061@192.168.55.55", response="556800dab595839a7ad76e86f7c4d65c"
Contact: <sip:pmh91k37@192.0.2.39;transport=ws;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.1
Content-Length: 916

v=0
o=mozilla...THIS_IS_SDPARTA-39.0 4294967295 0 IN IP4 192.0.2.67
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 E9:19:C3:31:90:BB:11:56:15:E1:CE:8B:92:03:EB:73:2F:C9:47:E0:52:95:2B:BF:2B:B4:A6:C7:10:23:B5:C1
a=group:BUNDLE sdparta_0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 50458 UDP/TLS/RTP/SAVPF 109 9 0 8
c=IN IP4 192.168.5.66
a=candidate:0 1 UDP 2128609535 192.168.5.66 50458 typ host
a=candidate:0 2 UDP 2128609534 192.168.5.66 50459 typ host
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=ice-pwd:0e1097b0ff55158a8feeed2696e32d0e
a=ice-ufrag:8c3ffa52
a=mid:sdparta_0
a=msid:{7d1f65c7-21f4-4528-95e0-21e9262c7fde} {844c2c22-3ead-407d-9b51-37aa45d4c836}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:522719446 cname:{0afcc099-72d5-4ae2-a837-ca09e9079b0e}

sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:53 GMT+0530 (India Standard Time) | sip.transaction.ict | Timer D expired for INVITE client transaction z9hG4bK9277042
sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:53 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK2032100;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
To: <sip:1061@192.168.55.55>
Call-ID: lmfemhosah81njiijop6
CSeq: 7556 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:1061@192.168.55.55:5060;transport=WS>
Content-Length: 0

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:54 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK2032100;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
To: <sip:1061@192.168.55.55>;tag=as0184df39
Call-ID: lmfemhosah81njiijop6
CSeq: 7556 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:1061@192.168.55.55:5060;transport=WS>
Content-Length: 0

sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:54 GMT+0530 (India Standard Time) | sip.dialog | new UAC dialog created with status EARLY
sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:56 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK2032100;received=192.168.5.66
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
To: <sip:1061@192.168.55.55>;tag=as0184df39
Call-ID: lmfemhosah81njiijop6
CSeq: 7556 INVITE
Server: Asterisk PBX 11.11.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:1061@192.168.55.55:5060;transport=WS>
Content-Type: application/sdp
Content-Length: 589

v=0
o=root 2140861074 2140861074 IN IP4 192.168.55.55
s=Asterisk PBX 11.11.0
c=IN IP4 192.168.55.55
t=0 0
m=audio 16732 RTP/SAVPF 0 8
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=ptime:20
a=ice-ufrag:47746d173c7099c4484c547e25a58535
a=ice-pwd:4ffd9a360a9d1df53da80951359675c9
a=candidate:Hc0a83737 1 UDP 2130706431 192.168.55.55 16732 typ host
a=candidate:Hc0a83737 2 UDP 2130706430 192.168.55.55 16733 typ host
a=connection:new
a=setup:active
a=fingerprint:SHA-256 26:93:4F:49:44:CA:08:56:52:79:E6:2D:D3:2A:86:7A:A7:75:CD:EE:CD:13:B6:71:74:02:23:31:73:BA:35:D8
a=sendrecv

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:56 GMT+0530 (India Standard Time) | sip.dialog | dialog lmfemhosah81njiijop6e0nc9etqaoas0184df39  changed to CONFIRMED state

sip-0.7.1.js (line 2810)

Thu Dec 24 2015 16:41:56 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

ACK sip:1061@192.168.55.55:5060;transport=ws SIP/2.0
Via: SIP/2.0/WS 192.0.2.39;branch=z9hG4bK4269294
Max-Forwards: 70
To: <sip:1061@192.168.55.55>;tag=as0184df39
From: <sip:1060@192.168.55.55>;tag=e0nc9etqao
Call-ID: lmfemhosah81njiijop6
CSeq: 7556 ACK
Supported: outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0

sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:41:56 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | stream added: {06f8cc61-c5bb-480e-9b70-66ab4749be6e}
sip-0.7.1.js (line 2810)
Thu Dec 24 2015 16:42:01 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | RTCIceChecking Timeout Triggered after 5000 milliseconds

Any help is highly appreciated

**Comment by egreenmachine** [comment]
Hi @mitesh1980,

This is not a SIP.js issue, but an Asterisk configuration issue. As I have stated in #264, for help with configuring Asterisk, FreeSWITCH, or any other PBX please start a discussion on our [mailing list](https://groups.google.com/forum/#!forum/sip_js). We would like to keep Github issues for actual bugs within SIP.js.

Thanks
