### ISSUE TITLE
Cannot read property 'connected' of undefined Use --force to continue.

### ISSUE THREAD

**Issue by Hostile** [onsip/SIP.js#267]
Any idea?

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Jan  8 21:04:04 2016 from node-6wq.pool-125-27.dynamic.totbb.net
root@ns1:~# screen -r
[screen is terminating]
root@ns1:~# cd node_modules/sip.js/
root@ns1:~/node_modules/sip.js# grunt test
Running "jasmine:components" (jasmine) task
Testing jasmine specs via PhantomJS

Warning: Cannot read property 'connected' of undefined Use --force to continue.

Aborted due to warnings.
root@ns1:~/node_modules/sip.js# npm cache clear
root@ns1:~/node_modules/sip.js# grub -v
-bash: grub: command not found
root@ns1:~/node_modules/sip.js# geunt -v
-bash: geunt: command not found
root@ns1:~/node_modules/sip.js# grunt -v
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-browserify" local Npm module tasks.
Reading /root/node_modules/sip.js/node_modules/grunt-browserify/package.json...OK
Parsing /root/node_modules/sip.js/node_modules/grunt-browserify/package.json...OK
Loading "browserify.js" tasks...OK
+ browserify

Registering "grunt-contrib-copy" local Npm module tasks.
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-copy/package.json...OK
Parsing /root/node_modules/sip.js/node_modules/grunt-contrib-copy/package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-uglify/package.json...OK
Parsing /root/node_modules/sip.js/node_modules/grunt-contrib-uglify/package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jshint/package.json...OK
Parsing /root/node_modules/sip.js/node_modules/grunt-contrib-jshint/package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-jasmine" local Npm module tasks.
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/package.json...OK
Parsing /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/package.json...OK
Loading "jasmine.js" tasks...OK
+ jasmine

Registering "grunt-peg" local Npm module tasks.
Reading /root/node_modules/sip.js/node_modules/grunt-peg/package.json...OK
Parsing /root/node_modules/sip.js/node_modules/grunt-peg/package.json...OK
Loading "peg.js" tasks...OK
+ peg

Registering "grunt-trimtrailingspaces" local Npm module tasks.
Reading /root/node_modules/sip.js/node_modules/grunt-trimtrailingspaces/package.json...OK
Parsing /root/node_modules/sip.js/node_modules/grunt-trimtrailingspaces/package.json...OK
Loading "trimtrailingspaces.js" tasks...OK
+ trimtrailingspaces
Loading "Gruntfile.js" tasks...OK
+ build, default, devel, grammar, quick, test, travis

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "build" task

Running "trimtrailingspaces:main" (trimtrailingspaces) task
Verifying property trimtrailingspaces.main exists in config...OK
Files: src/ClientContext.js, src/Constants.js, src/Dialog/RequestSender.js, src/Dialogs.js, src/DigestAuthentication.js, src/EventEmitter.js, src/Exceptions.js, src/Grammar.js, src/Grammar/dist/Grammar.js, src/Hacks.js, src/LoggerFactory.js, src/MediaHandler.js, src/NameAddrHeader.js, src/Parser.js, src/RegisterContext.js, src/RequestSender.js, src/SIP.js, src/SIPMessage.js, src/SanityCheck.js, src/ServerContext.js, src/Session.js, src/Session/DTMF.js, src/Subscription.js, src/Timers.js, src/Transactions.js, src/Transport.js, src/UA.js, src/URI.js, src/Utils.js, src/WebRTC.js, src/WebRTC/MediaHandler.js, src/WebRTC/MediaStreamManager.js, src/environment.js, src/environment_browser.js, src/index.js
Options: encoding="utf8", failIfTrimmed, filter="isFile"
Processing file: src/ClientContext.js
Reading src/ClientContext.js...OK
Writing src/ClientContext.js...OK
Processing file: src/Constants.js
Reading src/Constants.js...OK
Writing src/Constants.js...OK
Processing file: src/Dialog/RequestSender.js
Reading src/Dialog/RequestSender.js...OK
Writing src/Dialog/RequestSender.js...OK
Processing file: src/Dialogs.js
Reading src/Dialogs.js...OK
Writing src/Dialogs.js...OK
Processing file: src/DigestAuthentication.js
Reading src/DigestAuthentication.js...OK
Writing src/DigestAuthentication.js...OK
Processing file: src/EventEmitter.js
Reading src/EventEmitter.js...OK
Writing src/EventEmitter.js...OK
Processing file: src/Exceptions.js
Reading src/Exceptions.js...OK
Writing src/Exceptions.js...OK
Processing file: src/Grammar.js
Reading src/Grammar.js...OK
Writing src/Grammar.js...OK
Processing file: src/Grammar/dist/Grammar.js
Reading src/Grammar/dist/Grammar.js...OK
Writing src/Grammar/dist/Grammar.js...OK
Processing file: src/Hacks.js
Reading src/Hacks.js...OK
Writing src/Hacks.js...OK
Processing file: src/LoggerFactory.js
Reading src/LoggerFactory.js...OK
Writing src/LoggerFactory.js...OK
Processing file: src/MediaHandler.js
Reading src/MediaHandler.js...OK
Writing src/MediaHandler.js...OK
Processing file: src/NameAddrHeader.js
Reading src/NameAddrHeader.js...OK
Writing src/NameAddrHeader.js...OK
Processing file: src/Parser.js
Reading src/Parser.js...OK
Writing src/Parser.js...OK
Processing file: src/RegisterContext.js
Reading src/RegisterContext.js...OK
Writing src/RegisterContext.js...OK
Processing file: src/RequestSender.js
Reading src/RequestSender.js...OK
Writing src/RequestSender.js...OK
Processing file: src/SIP.js
Reading src/SIP.js...OK
Writing src/SIP.js...OK
Processing file: src/SIPMessage.js
Reading src/SIPMessage.js...OK
Writing src/SIPMessage.js...OK
Processing file: src/SanityCheck.js
Reading src/SanityCheck.js...OK
Writing src/SanityCheck.js...OK
Processing file: src/ServerContext.js
Reading src/ServerContext.js...OK
Writing src/ServerContext.js...OK
Processing file: src/Session.js
Reading src/Session.js...OK
Writing src/Session.js...OK
Processing file: src/Session/DTMF.js
Reading src/Session/DTMF.js...OK
Writing src/Session/DTMF.js...OK
Processing file: src/Subscription.js
Reading src/Subscription.js...OK
Writing src/Subscription.js...OK
Processing file: src/Timers.js
Reading src/Timers.js...OK
Writing src/Timers.js...OK
Processing file: src/Transactions.js
Reading src/Transactions.js...OK
Writing src/Transactions.js...OK
Processing file: src/Transport.js
Reading src/Transport.js...OK
Writing src/Transport.js...OK
Processing file: src/UA.js
Reading src/UA.js...OK
Writing src/UA.js...OK
Processing file: src/URI.js
Reading src/URI.js...OK
Writing src/URI.js...OK
Processing file: src/Utils.js
Reading src/Utils.js...OK
Writing src/Utils.js...OK
Processing file: src/WebRTC.js
Reading src/WebRTC.js...OK
Writing src/WebRTC.js...OK
Processing file: src/WebRTC/MediaHandler.js
Reading src/WebRTC/MediaHandler.js...OK
Writing src/WebRTC/MediaHandler.js...OK
Processing file: src/WebRTC/MediaStreamManager.js
Reading src/WebRTC/MediaStreamManager.js...OK
Writing src/WebRTC/MediaStreamManager.js...OK
Processing file: src/environment.js
Reading src/environment.js...OK
Writing src/environment.js...OK
Processing file: src/environment_browser.js
Reading src/environment_browser.js...OK
Writing src/environment_browser.js...OK
Processing file: src/index.js
Reading src/index.js...OK
Writing src/index.js...OK

Running "devel" task

Running "jshint" task

Running "jshint:src" (jshint) task
Verifying property jshint.src exists in config...OK
Files: src/ClientContext.js, src/Constants.js, src/Dialog/RequestSender.js, src/Dialogs.js, src/DigestAuthentication.js, src/EventEmitter.js, src/Exceptions.js, src/Grammar.js, src/Hacks.js, src/LoggerFactory.js, src/MediaHandler.js, src/NameAddrHeader.js, src/Parser.js, src/RegisterContext.js, src/RequestSender.js, src/SIP.js, src/SIPMessage.js, src/SanityCheck.js, src/ServerContext.js, src/Session.js, src/Session/DTMF.js, src/Subscription.js, src/Timers.js, src/Transactions.js, src/Transport.js, src/UA.js, src/URI.js, src/Utils.js, src/WebRTC.js, src/WebRTC/MediaHandler.js, src/WebRTC/MediaStreamManager.js, src/environment.js, src/environment_browser.js, src/index.js -> src
Options: force=false, reporter=null, jshintrc
OK
>> 34 files lint free.

Running "quick" task

Running "grammar" task

Running "peg" task

Running "peg:grammar" (peg) task
Verifying property peg.grammar exists in config...OK
Files: src/Grammar/src/Grammar.pegjs -> src/Grammar/dist/Grammar.js
Options: exportVar="module.exports", output="source", plugins=[], optimize="size", allowedStartRules=["Contact","Name_Addr_Header","Record_Route","Request_Response","SIP_URI","Subscription_State","Supported","Require","Via","absoluteURI","Call_ID","Content_Disposition","Content_Length","Content_Type","CSeq","displayName","Event","From","host","Max_Forwards","Min_SE","Proxy_Authenticate","quoted_string","Refer_To","Replaces","Session_Expires","stun_URI","To","turn_URI","uuid","WWW_Authenticate","challenge"]
Generating parser from "src/Grammar/src/Grammar.pegjs"...
Reading src/Grammar/src/Grammar.pegjs...OK
Writing src/Grammar/dist/Grammar.js...OK
Parser "src/Grammar/dist/Grammar.js" generated in 459ms.

Running "browserify" task

Running "browserify:devel" (browserify) task
Verifying property browserify.devel exists in config...OK
Files: src/index.js -> dist/sip-0.7.2.js
Options: bundleOptions={"standalone":"SIP"}, postBundleCB=undefined
Writing dist/sip-0.7.2.js...OK

Running "uglify" task

Running "uglify:devel" (uglify) task
Verifying property uglify.devel exists in config...OK
Files: dist/sip-0.7.2.js -> dist/sip-0.7.2.min.js
Options: banner="/*\n * SIP version 0.7.2\n * Copyright (c) 2014-2016 Junction Networks, Inc <http://www.onsip.com>\n * Homepage: http://sipjs.com\n * License: http://sipjs.com/license/\n *\n *\n * ~~~SIP.js contains substantial portions of JsSIP under the following license~~~\n * Homepage: http://jssip.net\n * Copyright (c) 2012-2013 José Luis Millán - Versatica <http://www.versatica.com> \n *\n * Permission is hereby granted, free of charge, to any person obtaining\n * a copy of this software and associated documentation files (the\n * \"Software\"), to deal in the Software without restriction, including\n * without limitation the rights to use, copy, modify, merge, publish,\n * distribute, sublicense, and/or sell copies of the Software, and to\n * permit persons to whom the Software is furnished to do so, subject to\n * the following conditions:\n *\n * The above copyright notice and this permission notice shall be\n * included in all copies or substantial portions of the Software.\n *\n * THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\n * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\n * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\n * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION\n * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n *\n * ~~~ end JsSIP license ~~~\n */\n\n\n", footer="", compress={"warnings":false}, mangle={}, beautify={"ascii_only":true}, report=false
Minifying with UglifyJS...Reading dist/sip-0.7.2.js...OK
OK
Writing dist/sip-0.7.2.min.js...OK
File "dist/sip-0.7.2.min.js" created.

Running "copy" task

Running "copy:min" (copy) task
Verifying property copy.min exists in config...OK
Files: dist/sip-0.7.2.min.js -> dist/sip.min.js
Options: encoding="utf8", processContent=false, processContentExclude=[], mode=false
Copying dist/sip-0.7.2.min.js -> dist/sip.min.js
Reading dist/sip-0.7.2.min.js...OK
Writing dist/sip.min.js...OK
Copied 1 files

Running "copy:dist" (copy) task
Verifying property copy.dist exists in config...OK
Files: dist/sip-0.7.2.js -> dist/sip.js
Options: encoding="utf8", processContent=false, processContentExclude=[], mode=false
Copying dist/sip-0.7.2.js -> dist/sip.js
Reading dist/sip-0.7.2.js...OK
Writing dist/sip.js...OK
Copied 1 files

Running "test" task

Running "jasmine" task

Running "jasmine:components" (jasmine) task
Verifying property jasmine.components exists in config...OK
Files: dist/sip-0.7.2.js
Options: version="2.0.1", timeout=10000, styles=[], specs="test/spec/*.js", helpers="test/helpers/*.js", vendor="test/polyfills/*.js", polyfills=[], outfile="_SpecRunner.html", host="", template="/root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/tasks/jasmine/templates/DefaultRunner.tmpl", templateOptions={}, junit={}, ignoreEmpty=false, display="full", summary=false, keepRunner
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/tasks/lib/../jasmine/reporters/PhantomReporter.js...OK
Writing .grunt/grunt-contrib-jasmine/reporter.js...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.css...OK
Writing .grunt/grunt-contrib-jasmine/jasmine.css...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js...OK
Writing .grunt/grunt-contrib-jasmine/jasmine.js...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js...OK
Writing .grunt/grunt-contrib-jasmine/jasmine-html.js...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/node_modules/jasmine-core/lib/jasmine-core/json2.js...OK
Writing .grunt/grunt-contrib-jasmine/json2.js...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/node_modules/jasmine-core/lib/jasmine-core/boot.js...OK
Writing .grunt/grunt-contrib-jasmine/boot.js...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/node_modules/jasmine-core/images/jasmine_favicon.png...OK
Writing .grunt/grunt-contrib-jasmine/jasmine_favicon.png...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/tasks/lib/../../node_modules/es5-shim/es5-shim.js...OK
Writing .grunt/grunt-contrib-jasmine/es5-shim.js...OK
Reading /root/node_modules/sip.js/node_modules/grunt-contrib-jasmine/tasks/jasmine/templates/DefaultRunner.tmpl...OK
Processing source...OK
Writing _SpecRunner.html...OK

Testing jasmine specs via phantom

Warning: Cannot read property 'connected' of undefined Use --force to continue.

Aborted due to warnings.
root@ns1:~/node_modules/sip.js#

**Comment by josephfrazier** [comment]
There's a (more active) thread on the mailing list about this issue: https://groups.google.com/d/msg/sip_js/Dk8Q4Vgqn0E/uGlCpvFwBQAJ
