### ISSUE TITLE
REGISTER request should also contain the display name in To field

### ISSUE THREAD

**Issue by growtofill** [onsip/SIP.js#268]
Currently, SIP.js REGISTER request looks like this:

```
REGISTER sip:domain.com SIP/2.0
Via: SIP/2.0/WS 192.168.253.177;branch=z9hG4bK5696513
Max-Forwards: 70
To: <sip:username@domain.com>
From: "user name" <sip:username@domain.com>;tag=t9a358bps2
Call-ID: 2ehc6n13ee2vs34phrlm4a
CSeq: 84 REGISTER
Contact: <sip:dlnqqpfq@192.168.253.177;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:ac545210-918c-4971-b316-a85910f7b65b>";expires=600
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY,INVITE
Supported: path,gruu,outbound
User-Agent: SIP.js/0.7.1
Content-Length: 0
```

While according to [RFC 3261](https://tools.ietf.org/html/rfc3261#page-64):

> \5. The registrar extracts the address-of-record from the To header
         field of the request.

So it's not always possible to register with a display name, even if a server implementation adheres to RFC.

**Comment by wakamoleguy** [comment]
I'm not sure that 'address of record' typically includes the display name.  Again from the RFC ([Definitions](https://tools.ietf.org/html/rfc3261#section-6)):

> Address-of-Record: An address-of-record (AOR) is a SIP or SIPS URI
>         that points to a domain with a location service that can map
>         the URI to another URI where the user might be available.
>         Typically, the location service is populated through
>         registrations.  An AOR is frequently thought of as the "public
>         address" of the user.

In other places, it references examples such as `alice@atlanta.com`.

**Comment by josephfrazier** [comment]
On the other hand, it looks like the To/From headers of a REGISTER are generally supposed to be "the same", depending on how [Section 10.2](https://tools.ietf.org/html/rfc3261#page-58) is interpreted:

>       From: The From header field contains the address-of-record of the
           person responsible for the registration.  The value is the
           same as the To header field unless the request is a third-
           party registration.

[One example of registration](https://tools.ietf.org/html/rfc3261#section-24.1) shows a display name in the To header, so it seems reasonable for sip.js to do this as well.

**Comment by growtofill** [comment]
@wakamoleguy my point is that by RFC the registrar is not obligated to even look into From field.

**Comment by akozlovcodeminders** [comment]
Hi everybody,

SIP server usually works with To header of REGISTER request accordingly to RFC. Display name and Address-of-Record should be in To header. From header can be different to To header in case when somebody else try to register your AOR.

**Comment by josephfrazier** [comment]
I looked into this a bit more and I think I've found the relevant section of the code: https://github.com/onsip/SIP.js/blob/8d6ac90169307768e24a99f7de01db264150e5ed/src/SIPMessage.js#L100-L120

Notice how `ua.configuration.displayName` is the fallback value for the From display name ([lines 112-114](https://github.com/onsip/SIP.js/blob/8d6ac90169307768e24a99f7de01db264150e5ed/src/SIPMessage.js#L112-L114)), but is not considered when constructing the To display name ([line 102](https://github.com/onsip/SIP.js/blob/8d6ac90169307768e24a99f7de01db264150e5ed/src/SIPMessage.js#L102)). It wouldn't make sense to have the same fallback behavior here, as that would also affect non-REGISTER requests, but I think that having `RegisterContext` set `params.to_displayName` [here](https://github.com/onsip/SIP.js/blob/8d6ac90169307768e24a99f7de01db264150e5ed/src/RegisterContext.js#L28) would achieve the desired effect.

Pull Request coming shortly :)
