### ISSUE TITLE
Anonymous INVITE request should include INVITE as understood method in Allow header

### ISSUE THREAD

**Issue by growtofill** [onsip/SIP.js#270]
Currently, an INVITE request from unregistered UA is missing INVITE in Allow header:

```
INVITE sip:address@example.com SIP/2.0
Via: SIP/2.0/WSS ws.example.com;branch=z9hG4bK479671
Max-Forwards: 70
To: <sip:address@example.com>
From: <sip:anonymous.37vsaq@anonymous.invalid>;tag=6te1dpsfrv
Call-ID: etjihiqif75ge6u6hk05
CSeq: 1100 INVITE
Contact: <sip:301c77um@ws.example.com;transport=ws;ob>
Allow: ACK,CANCEL,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.2
Content-Length: 2702
```

While [according to RFC](https://tools.ietf.org/html/rfc3261#section-20.5):

> All methods, including ACK and CANCEL, understood by the UA MUST be
   included in the list of methods in the Allow header field, when
   present.

And the UA _does understand_ INVITE method (e.g. when put on hold by another SIP.js client) and responds to it accordingly:

```
Thu Jan 14 2016 12:09:46 GMT+0200 (EET) | sip.transport | received WebSocket text message:
INVITE sip:301c77um@*.*.*.*:*;transport=ws;ob SIP/2.0
[...]
Thu Jan 14 2016 12:09:46 GMT+0200 (EET) | sip.transport | sending WebSocket message:
SIP/2.0 100 Trying
[...]
Thu Jan 14 2016 12:09:46 GMT+0200 (EET) | sip.inviteclientcontext | re-INVITE received 
Thu Jan 14 2016 12:09:46 GMT+0200 (EET) | sip.invitecontext.mediahandler | already have local media 
Thu Jan 14 2016 12:09:46 GMT+0200 (EET) | sip.transport | sending WebSocket message:
SIP/2.0 200 OK
[...]
```

This prevents some third party clients from being able to put SIP.js client on hold.

**Comment by james-onsip** [comment]
Good catch. It turns out the generation of the Allow header was adding 'INVITE' and 'MESSAGE' only if the user had created listeners for those on the UA in question. Seeing as we can still properly handle those without user interaction, removing this conditional seemed to make sense.

Thanks,
James

**Comment by josephfrazier** [comment]
@james-onsip, shouldn't the MESSAGE reception logic also be changed then, to avoid replying 405 when there's no `.on('message')` listener, even though `Allow: MESSAGE` was sent previously? Here's the relevant code: https://github.com/onsip/SIP.js/blob/92923c5d52ea43ee5285213af27b6c93e9a89d44/src/UA.js#L619-L632

**Comment by james-onsip** [comment]
Good catch (again), also now fixed.
