### ISSUE TITLE
Wrong bindTarget on sip.js 0.7.2

### ISSUE THREAD

**Issue by GuillaumeCousin** [onsip/SIP.js#274]
Hello, I was workink with sip.js 0.6.4 without problem and i juste decide to change to the 0.7.2 version.
Now my application doesnt work.

My code : I work in a class in the constructor i have
this.SipPhoneUA = new SIP.UA(configUA);
this.SipPhoneUA.on('connected', this.onConnected, this);
this.SipPhoneUA.on('disconnected', this.onDisconnected, this);
this.SipPhoneUA.on('registered', this.onRegistered, this);
this.SipPhoneUA.on('unregistered', this.onUnregistered, this);
this.SipPhoneUA.on('registrationFailed', this.onRegistrationFailed, this);
this.SipPhoneUA.on('message', this.onRcvMessage, this);
this.SipPhoneUA.on('invite', this.onRcvInvite, this);
		
this.SipPhoneUA.start();

When the connected event occur i go in the onConnected method but i'm not whith the good bindTarget (the wrong scope)
The bindTraget is the UA and not my class instance.
With sip.js 0.6.4 it works good.
I dont see any changes on the Event construction on the last new api guides ?

Thanks for answer.

**Comment by josephfrazier** [comment]
This changed in [0.7.0](https://github.com/onsip/SIP.js/releases/tag/0.7.0) (albeit with a misleading release note). From the commit message of https://github.com/onsip/SIP.js/commit/b07a368727c19676cb143479eb204ea2852f4992:

> * #on, #once and #off do NOT take third arguments (bindTarget)

>  listeners should be explicitly bound to their objects before passing to
  EventEmitter methods

You should be able to migrate your code as follows:

```
this.SipPhoneUA.on('connected', this.onConnected.bind(this));

**Comment by roman-yerin** [comment]
Perhaps, somebody should update docs

**Comment by wakamoleguy** [comment]
Docs updated.
