### ISSUE TITLE
Register once without retrying when it expires

### ISSUE THREAD

**Issue by andrewvmail** [onsip/SIP.js#277]
Just wondering if there is anyway on how to register once without the retry after the register has expires.

Thanks

**Comment by james-onsip** [comment]
Hi @andrewvmail,
  As far as i can tell, there doesn't seem to be a way to do this. SIP.js silently begins re-registering 3 seconds before registration expires, then resets the expiration upon successful registration, all without emitting events. I believe we've discussed a `reregistered` event in the past, but it was never implemented, and even so it would occur after the time that you are looking for anyway.

  Out of curiosity, what is the use case for this? A UA that silently unregisters by allowing their registration to expire may not be the type of thing we necessarily want to make possible (although the RFC doesn't seem to forbid it at a glance), so maybe there is another way around your problem.

Thanks,
James

**Comment by andrewvmail** [comment]
@james-onsip,

I'm making a mobile voice app. Using vendor push mechanism as a means to trigger a register and then an invite. It's based on this slides if your interested http://www.kamailio.org/events/2015-KamailioWorld/Day2/20-Federico.Cabiddu-Kamailio-In-A-Mobile-World.pdf

I have the timeout really short but it keeps re-registering it self. Might not be a big deal though.

Cheers
Andrew

**Comment by etamme** [comment]
If you are purely using push notifications for initial user location, you could simply register on receipt of a push notification, then set a callback on session termination to unregister the UA.

**Comment by andrewvmail** [comment]
@etamme, 

Is there a particular session method i should be using for unregister? is it session.unregister?

Thanks,
Andrew

**Comment by andrewvmail** [comment]
Nevermind saw it. session.unregister().

Clossing comment.
Thanks guys.

**Comment by wakamoleguy** [comment]
Ah, I think you're looking for `session.ua.unregister()`
