### ISSUE TITLE
Constraints from userMediaRequest event don't match the ones being set in UA#invite

### ISSUE THREAD

**Issue by growtofill** [onsip/SIP.js#284]
I'm trying to set constraints in `UA#invite` like this:

```
userAgent.invite(address, { media:
    constraints: {
        audio: true,
        video: { mandatory: { minWidth: 1280, minHeight: 720 } }
    }
});
```
However, the call is still established with default 640x480 resolution. When I add a listener on `userMediaRequest` callback, `constraints` there doesn't match the ones from `mediaHint`:

![screen shot 2016-01-27 at 19 28 28](https://cloud.githubusercontent.com/assets/2944963/12622220/f17d1f48-c52c-11e5-90a6-327146aefeba.png)

I know that there is an alternative (newer?) syntax with `ideal` instead of `mandatory`, but it doesn't work also.

I'm using Chrome 48 and SIP.js 0.7.2.

Is this a bug?

**Comment by james-onsip** [comment]
Hi @growtofill,
  It looks like you're missing a set of curly-braces, between the word `media` and the word `constraints`. Try:

```
userAgent.invite(address, { media: {
    constraints: {
        audio: true,
        video: { mandatory: { minWidth: 1280, minHeight: 720 } }
    }}
});
```
Outside of this, I was not able to reproduce your problem. I could understand why the code would fall back to the `true, true` object that is being emitted, I'm just not entirely sure why your snapshot correctly parses mediaHint.

Good luck,
James

**Comment by growtofill** [comment]
Yes, I've messed up with object structure. So sorry, issue closed.
