### ISSUE TITLE
Incoming call has video?

### ISSUE THREAD

**Issue by ny4rlathotep** [onsip/SIP.js#289]
Hello All!
I'm attempting to develop a strategy to recognize whether an incoming call has video enabled so that I can then manipulate html/css elements appropriately.  My approach thus far has been to examine the incoming session acquired from: ua.on('invite', function(new_session){incoming_call(new_session)} (which as I can tell is an InviteServerContext object).  I'm attempting to access the value at: new_session.mediaHandler.mediaHint.constraints.video.
This fails at constraints, where it is undefined.
Am I on the right track here, and if not can you steer me in the right direction as to how I can check this?

**Comment by gled-rs** [comment]
check the sdp received if it has video.

Maybe more reliable ?

**Comment by wakamoleguy** [comment]
Hi.  This has been asked several times on the [mailing list](https://groups.google.com/forum/#!forum/sip_js).  [This thread](https://groups.google.com/forum/#!searchin/sip_js/detect$20video/sip_js/8kWIRsoTlm4/1YG2U5WJiSoJ) in particular may be helpful.  gled-rs is on the right track that checking the SDP is the more reliable way to go.

I'm going to close this ticket, as it is not a bug or feature request of the library itself.  Please follow up on the mailing list if you have more questions.

Thank you!

**Comment by ny4rlathotep** [comment]
Thank you! Sorry I didn't know where else to post; I was unaware of the mailing list. Cheers!

**Comment by ny4rlathotep** [comment]
O. click on support. I feel stupid. Please excuse my ignorance. X P

**Comment by wakamoleguy** [comment]
Completely excused.  It's not the most obvious thing, and you're far from the first to end up here. :-)

**Comment by ny4rlathotep** [comment]
Well that makes me feel slightly better. : ) Thx Again!
