### ISSUE TITLE
Losing about 3-5 seconds at the beginning of a SIP session

### ISSUE THREAD

**Issue by shadmehr** [onsip/SIP.js#302]
We are losing about 3-5 seconds of media at the beginning of a SIP session especially with Bluetooth. We tested by calling a VoiceXML application through the Asterisk where our WebRTC sip client is registered. When our sip client sends an invite to our server, it gets a Provisional 100 Trying and then a 200 OK immediately after. We don’t have this problem when calling another sip client.
 
Logs:
 
INVITE sip:*99@sip.excendia.com SIP/2.0
Via: SIP/2.0/TCP 192.0.2.234;branch=z9hG4bK9674431
Max-Forwards: 70
To: <sip:*99@sip.excendia.com>
From: <sip:EXCE02_10713_27@sip.excendia.com>;tag=mr50j6u877
Call-ID: p58vc1m9h1b9hte8m3me
CSeq: 7538 INVITE
Contact: <sip:16g8qdv2@192.0.2.234;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.3
Content-Length: 1752
 
v=0
o=- 38334533357133261 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS HImU6C8WQCkLiCpSGt2Z8Uqpsb8Phuchsjkz
m=audio 51984 UDP/TLS/RTP/SAVPF 111 103 9 0 8 106 105 13 126
c=IN IP4 192.222.241.4
a=rtcp:42234 IN IP4 192.222.241.4
a=candidate:1838712287 1 udp 2122260223 192.168.0.167 51984 typ host generation 0
a=candidate:1838712287 2 udp 2122260222 192.168.0.167 42234 typ host generation 0
a=candidate:589003055 1 tcp 1518280447 192.168.0.167 9 typ host tcptype active generation 0
a=candidate:589003055 2 tcp 1518280446 192.168.0.167 9 typ host tcptype active generation 0
a=candidate:3973088107 1 udp 1686052607 192.222.241.4 51984 typ srflx raddr 192.168.0.167 rport 51984 generation 0
a=candidate:3973088107 2 udp 1686052606 192.222.241.4 42234 typ srflx raddr 192.168.0.167 rport 42234 generation 0
a=ice-ufrag:UiObD9TKsAInkUWb
a=ice-pwd:8zoeCtmWDp/oa+EZO8qhmL+J
a=fingerprint:sha-256 26:EB:6C:54:13:FA:BA:04:83:1E:08:48:BF:B0:36:79:D3:90:B0:5D:9F:86:62:68:13:9C:65:F4:4D:6C:37:EB
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:3727269668 cname:+K6WIrVc385Rfzyz
a=ssrc:3727269668 msid:HImU6C8WQCkLiCpSGt2Z8Uqpsb8Phuchsjkz d008e709-c3d7-46f6-bb9e-b896d091325b
a=ssrc:3727269668 mslabel:HImU6C8WQCkLiCpSGt2Z8Uqpsb8Phuchsjkz
a=ssrc:3727269668 label:d008e709-c3d7-46f6-bb9e-b896d091325b
 
 
Line: 15, Column 18
Wed Mar 23 2016 12:44:28 GMT-0400 (EDT) | sip.transport | received WebSocket text message:
 
SIP/2.0 401 Unauthorized
Via: SIP/2.0/TCP 192.0.2.234;branch=z9hG4bK9674431;received=192.222.241.4;rport=45406
From: <sip:EXCE02_10713_27@sip.excendia.com>;tag=mr50j6u877
To: <sip:*99@sip.excendia.com>;tag=as34d11ce6
Call-ID: p58vc1m9h1b9hte8m3me
CSeq: 7538 INVITE
Server: Excendia
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
WWW-Authenticate: Digest algorithm=MD5, realm="ets1.excendia.com", nonce="506ef980"
Content-Length: 0
 
 
 
Line: 15, Column 18
Wed Mar 23 2016 12:44:28 GMT-0400 (EDT) | sip.transport | sending WebSocket message:
 
ACK sip:*99@sip.excendia.com SIP/2.0
Via: SIP/2.0/TCP 192.0.2.234;branch=z9hG4bK9674431
To: <sip:*99@sip.excendia.com>;tag=as34d11ce6
From: <sip:EXCE02_10713_27@sip.excendia.com>;tag=mr50j6u877
Call-ID: p58vc1m9h1b9hte8m3me
Content-Length: 0
CSeq: 7538 ACK
 
 
 
Line: 15, Column 18
Wed Mar 23 2016 12:44:28 GMT-0400 (EDT) | sip.transport | sending WebSocket message:
 
INVITE sip:*99@sip.excendia.com SIP/2.0
Via: SIP/2.0/TCP 192.0.2.234;branch=z9hG4bK6956281
Max-Forwards: 70
To: <sip:*99@sip.excendia.com>
From: <sip:EXCE02_10713_27@sip.excendia.com>;tag=mr50j6u877
Call-ID: p58vc1m9h1b9hte8m3me
CSeq: 7539 INVITE
Authorization: Digest algorithm=MD5, username="EXCE02_10713_27", realm="ets1.excendia.com", nonce="506ef980", uri="sip:*99@sip.excendia.com", response="364f64c9f22606400c093065d88ac823"
Contact: <sip:16g8qdv2@192.0.2.234;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.3
Content-Length: 1752
 
v=0
o=- 38334533357133261 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS HImU6C8WQCkLiCpSGt2Z8Uqpsb8Phuchsjkz
m=audio 51984 UDP/TLS/RTP/SAVPF 111 103 9 0 8 106 105 13 126
c=IN IP4 192.222.241.4
a=rtcp:42234 IN IP4 192.222.241.4
a=candidate:1838712287 1 udp 2122260223 192.168.0.167 51984 typ host generation 0
a=candidate:1838712287 2 udp 2122260222 192.168.0.167 42234 typ host generation 0
a=candidate:589003055 1 tcp 1518280447 192.168.0.167 9 typ host tcptype active generation 0
a=candidate:589003055 2 tcp 1518280446 192.168.0.167 9 typ host tcptype active generation 0
a=candidate:3973088107 1 udp 1686052607 192.222.241.4 51984 typ srflx raddr 192.168.0.167 rport 51984 generation 0
a=candidate:3973088107 2 udp 1686052606 192.222.241.4 42234 typ srflx raddr 192.168.0.167 rport 42234 generation 0
a=ice-ufrag:UiObD9TKsAInkUWb
a=ice-pwd:8zoeCtmWDp/oa+EZO8qhmL+J
a=fingerprint:sha-256 26:EB:6C:54:13:FA:BA:04:83:1E:08:48:BF:B0:36:79:D3:90:B0:5D:9F:86:62:68:13:9C:65:F4:4D:6C:37:EB
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:3727269668 cname:+K6WIrVc385Rfzyz
a=ssrc:3727269668 msid:HImU6C8WQCkLiCpSGt2Z8Uqpsb8Phuchsjkz d008e709-c3d7-46f6-bb9e-b896d091325b
a=ssrc:3727269668 mslabel:HImU6C8WQCkLiCpSGt2Z8Uqpsb8Phuchsjkz
a=ssrc:3727269668 label:d008e709-c3d7-46f6-bb9e-b896d091325b
 
 
Line: 15, Column 18
Wed Mar 23 2016 12:44:28 GMT-0400 (EDT) | sip.transaction.ict | Timer D expired for INVITE client transaction z9hG4bK9674431
Line: 15, Column 18
Wed Mar 23 2016 12:44:28 GMT-0400 (EDT) | sip.transport | received WebSocket text message:
 
SIP/2.0 100 Trying
Via: SIP/2.0/TCP 192.0.2.234;branch=z9hG4bK6956281;received=192.222.241.4;rport=45406
From: <sip:EXCE02_10713_27@sip.excendia.com>;tag=mr50j6u877
To: <sip:*99@sip.excendia.com>
Call-ID: p58vc1m9h1b9hte8m3me
CSeq: 7539 INVITE
Server: Excendia
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:*99@216.46.7.115:5060;transport=WS>
Content-Length: 0
 
 
Wed Mar 23 2016 12:44:28 GMT-0400 (EDT) | sip.transport | received WebSocket text message:
 
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.0.2.234;branch=z9hG4bK6956281;received=192.222.241.4;rport=45406
From: <sip:EXCE02_10713_27@sip.excendia.com>;tag=mr50j6u877
To: <sip:*99@sip.excendia.com>;tag=as17ed189d
Call-ID: p58vc1m9h1b9hte8m3me
CSeq: 7539 INVITE
Server: Excendia
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:*99@216.46.7.115:5060;transport=WS>
Content-Type: application/sdp
Content-Length: 877
 
v=0
o=root 244376040 244376040 IN IP4 216.46.7.115
s=Asterisk PBX 13.6.0
c=IN IP4 216.46.7.115
t=0 0
m=audio 13888 RTP/SAVPF 0 8 3 126
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:3 GSM/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=ptime:20
a=maxptime:150
a=ice-ufrag:72df23715cbe4f6005b84db50eec4dc4
a=ice-pwd:3a007a736bfe26301bac54246a4192d8
a=candidate:Hd82e0773 1 UDP 2130706431 216.46.7.115 13888 typ host
a=candidate:Sd82e0773 1 UDP 1694498815 216.46.7.115 13888 typ srflx raddr 216.46.7.115 rport 13888
a=candidate:Hd82e0773 2 UDP 2130706430 216.46.7.115 13889 typ host
a=candidate:Sd82e0773 2 UDP 1694498814 216.46.7.115 13889 typ srflx raddr 216.46.7.115 rport 13889
a=connection:new
a=setup:active
a=fingerprint:SHA-256 83:FE:07:D8:D3:B0:CD:94:64:72:38:81:21:BB:55:CF:64:1E:41:07:B3:84:F8:AC:2C:A7:84:D0:43:E2:C4:B1
a=sendrecv
 
 
 
Wed Mar 23 2016 12:44:28 GMT-0400 (EDT) | sip.dialog | new UAC dialog created with status CONFIRMED
Line: 15, Column 18
Wed Mar 23 2016 12:44:29 GMT-0400 (EDT) | sip.transport | sending WebSocket message:
 
ACK sip:*99@216.46.7.115:5060;transport=ws SIP/2.0
Via: SIP/2.0/TCP 192.0.2.234;branch=z9hG4bK1418231
Max-Forwards: 70
To: <sip:*99@sip.excendia.com>;tag=as17ed189d
From: <sip:EXCE02_10713_27@sip.excendia.com>;tag=mr50j6u877
Call-ID: p58vc1m9h1b9hte8m3me
CSeq: 7539 ACK
Supported: outbound
User-Agent: SIP.js/0.7.3
Content-Length: 0

**Comment by james-criscuolo** [comment]
Hi @shadmehr, 

Have you tried using Invite without SDP? We were running into the same issue, it is because ICE takes some time to set up completely once the answer is received. Our solution was invite w/o SDP, and it has worked (also it was a big reason this project began).

I'm going to close this issue as there is not a problem with the library, but please feel free to continue this topic over [on our mailing list](https://groups.google.com/forum/#!forum/sip_js).

Thanks,
James
