### ISSUE TITLE
Dosnt fired event "bye/terminated"

### ISSUE THREAD

**Issue by finethanks** [onsip/SIP.js#303]
Person A maked a call to Person B and created active session. If Persone A terminate call session, everything works correctly. 
But if Person B terminate call session, dosnt fired event "bye/terminated" on side of Person A.

Used for testing sip2sip.info accounts

PS. Same problem with other libraries, for exapmle, sipml5

**Comment by james-criscuolo** [comment]
Hi @finethanks,
  Have you checked your logs? If the endpoint never receives a BYE, it would not surprise me that a "bye/terminated" is not emitted.

The fact that this also occurs with other libraries leads me to believe this is a problem with your web socket server, or whatever else you have between the endpoints. If this were a problem (for us or anyone) we would surely have gotten more reports about it, or seen it ourselves.

I'm going to close the issue, but I suggest following up on the mailing list of one/all of your backend servers. I'm assuming sip2sip.info is doing something slightly out of standard that causes nothing else to work with it.

Thanks,
James

**Comment by finethanks** [comment]
Thanks! My eyes glazed over
