### ISSUE TITLE
INVITE request should include REFER as understood method in Allow header

### ISSUE THREAD

**Issue by growtofill** [onsip/SIP.js#304]
Similarly to [the issue 270](https://github.com/onsip/SIP.js/issues/270), an INVITE request from unregistered UA is missing REFER in Allow header:

```
INVITE sip:username@example.com SIP/2.0
Via: SIP/2.0/WSS ws.example.com;branch=z9hG4bK3459694
Max-Forwards: 70
To: <sip:username@example.com>
From: "username" <sip:anonymous.9fipph@anonymous.invalid>;tag=jqcpja132o
Call-ID: 2gqlte3lmhrjb9t5lvbv
CSeq: 6621 INVITE
Contact: <sip:r794rcbd@ws.example.com;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY
Content-Type: application/sdp
Supported: outbound
User-Agent: SIP.js/0.7.3
Content-Length: 5277
```

Again, [according to RFC](https://tools.ietf.org/html/rfc3261#section-20.5):

> All methods, including ACK and CANCEL, understood by the UA MUST be
   included in the list of methods in the Allow header field, when
   present.

**Comment by etamme** [comment]
Do you have a message handler for .on( 'refer')? I am not certain, but it may be that the Allow header dynamically adds request types as the handlers are added.

**Comment by growtofill** [comment]
> Do you have a message handler for .on( 'refer')?

I do, but it doesn't matter. The client [does understand](https://github.com/onsip/SIP.js/blob/master/src/Session.js#L699-L731) this method, therefore in must be included in Allow header.

> the Allow header dynamically adds request types as the handlers are added.

This used to be the case for INVITE and MESSAGE methods, but it led to an incorrect behavior and was changed (see [issue 270](https://github.com/onsip/SIP.js/issues/270)).
