### ISSUE TITLE
receiving DTMF

### ISSUE THREAD

**Issue by Jay383** [onsip/SIP.js#306]
Hello,

I have trouble receiving DTMF events through a freeswitch-server with SIPjs.
I can send DTMF fine.
When trying to receive, I can see in the freeswitch-logs that the DTMF is received.

Is there some special configuration options required ?
I have tried most options like liberal-dtmf, pass-rfc2833 and dtmf-type info/rfc2833

**Comment by james-criscuolo** [comment]
Hi @Jay383,
  The only option we set on our freeswitch boxes is liberal-dtmf (true). This does successfully achieve dtmf in SIP.js for us.

Unfortunately I'm not really sure what else we can do regarding this issue, so I'm going to close. I recommend asking the Freeswitch mailing list if there is a way to confirm DTMF is not only received, but sent as well, in which case we could narrow down the problem.

Thanks,
James

**Comment by Jay383** [comment]
Hello,

Thanks for your prompt reply. I'll do some more digging elsewhere :)
