### ISSUE TITLE
telephone-event not negotiated

### ISSUE THREAD

**Issue by jorg80** [onsip/SIP.js#307]
In order to receive DTMF events I assume SIPjs needs to accept 101 telephone-event ?

It doesn't seem to be accepted when using Firefox 45.0.1/SIPjs 0.7.3 in the sdp
Is this a Firefox or SIPjs issue ?

Local SDP
v=0
o=mozilla...THIS_IS_SDPARTA-45.0.1 4605489585144588997 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 A6:E4:C0:5D:53:0A:AD:6C:2D:4A:05:1D:44:04:51:1D:34:98:4B:23:81:3F:A4:0D:6C:3C:24:EB:A6:0F:CA:88
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 58030 RTP/SAVPF 8
c=IN IP4 213.a.b.c.d
a=candidate:0 1 UDP 2122252543 192.168.1.3 63782 typ host
a=candidate:4 1 UDP 2122121471 213.a.b.c.d 56604 typ host
a=candidate:8 1 UDP 2122187007 2001:x:xx::xa 56605 typ host
a=sendrecv
a=end-of-candidates
a=ice-pwd:3603a709e7d780d935156c7b414dd4ee
a=ice-ufrag:d8b4d0b3
a=msid:{38e528d0-d246-2941-ab0d-9d1f60faea7f} {dce8b3ee-4a81-e142-95c3-4f0ffd3dd59a}
a=rtcp-mux
**a=rtpmap:8 PCMA/8000
**a=setup:active
a=ssrc:3918238202 cname:{398d7dd1-c863-eb47-a3a3-e1855ea5c370}

Remote SDP
v=0
o=FreeSWITCH 1459564579 1459564580 IN IP6 2001:xx:xx::x
s=-
t=0 0
a=sendrecv
a=msid-semantic:WMS CxeLJvgxDkxDei3gmOxDtwhV23why6j0
m=audio 31372 RTP/SAVPF 8 101
c=IN IP6 2001:xx:xx::x
a=candidate:9475937373 1 udp 659136 2001:xx:xx::yy 31372 typ host generation 0
a=candidate:9475937373 2 udp 659136 2001:xx:xx::yy 31372 typ host generation 0
a=sendrecv
a=fingerprint:sha-256 98:AD:63:9D:25:B0:F3:74:43:56:65:2A:1E:90:52:5D:67:DF:40:BC:7E:45:39:01:BA:A4:5B:77:61:5E:EE:48
a=ice-pwd:clQMV7PFLmuyMpxRI0fnBpV5
a=ice-ufrag:etCyPKkHEGP2DYTX
a=ptime:20
a=rtcp:31372 IN IP6 2001:xx:xx::yy
a=rtcp-mux
**a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000/1
**

**Comment by wakamoleguy** [comment]
The WebRTC spec does not currently expose any API for handling telephone event as a media type.

To send and receive DTMF using SIP.js, we use SIP INFO packets. If you receive one, you should see a `dtmf` event fire on the session.
