### ISSUE TITLE
session.accept() Uncaught (inPromise) DOMException 

### ISSUE THREAD

**Issue by fredguth** [onsip/SIP.js#315]
Hi, 
I am wondering if I made any mistake or if you guys have seen something like this:
sip.js:11568 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
[https://www.evernote.com/l/AZTXeIafroJF2qp4VWuNVfvzaRasNWwTSikB/image.png](https://www.evernote.com/l/AZTXeIafroJF2qp4VWuNVfvzaRasNWwTSikB/image.png)

It seems related to issue #175, but as I am not using mediaHandler directly, just accepting a call, I don't know what should have I done differently.

Thanks
p.s. using sip.js 0.7.2

**Comment by james-criscuolo** [comment]
Hi @fredguth,

If you are calling `play` on the stream at the earliest possible moment, it may be causing this. Based on [this thread](http://stackoverflow.com/questions/36803176/how-to-prevent-the-play-request-was-interrupted-by-a-call-to-pause-error), chaining a promise after your `play` call may fix it.

James

**Comment by svarunan** [comment]
@fredguth , This issue will be seen in current version of chrome > 50. I'd suggest to create a new Audio element each time dynamically for ring tone playback or for playing remote stream.
Have a common js function which will make sure it stops the play request of existing audio element and removes it. then have a new audio element created and attach the src with stream or URL

**Comment by fredguth** [comment]
Thanks @james-criscuolo and @svarunan.

**Comment by Payetus** [comment]
@james-criscuolo how would you chain promises can you put a snippet
