### ISSUE TITLE
which function can I verify the user's audio is able to use ?

### ISSUE THREAD

**Issue by tuluxmu** [onsip/SIP.js#317]
Hi, 
Recently, I meet with a problem.
some user's microphone is not used.
And when I make a inbound call , the console will display "unable to acquire stream".
I am wondering if there is a function I can use to verify if the user has audio?

Thanks.
p.s. using 0.6.4

**Comment by james-criscuolo** [comment]
Hi @tuluxmu,
  You can call `getUserMedia` independently, then pass that stream into SIP.js, instead of relying on SIP.js making that call. This should be the direct call that is error'ing out.

 James

**Comment by egreenmachine** [comment]
This question appears to be answered. Please direct any follow up to our [mailing list](https://groups.google.com/forum/#!forum/sip_js).
