### ISSUE TITLE
Notification about INFO message was recently removed

### ISSUE THREAD

**Issue by alexandrkozlov** [onsip/SIP.js#323]
Hi,

You recently removed notification about INFO message called from _Session.js_:
>      case SIP.C.INFO:
>        if(this.status === C.STATUS_CONFIRMED || this.status === C.STATUS_WAITING_FOR_ACK) {
>               ..........
>                this.emit('info', request)
>               ..........
>                request.reply(200);

We really need it in our application, please replace:
>      case SIP.C.INFO:
>               ..........
>                request.reply(415, null, ["Accept: application/dtmf-relay"]);

with the following 
>      case SIP.C.INFO:
>               ..........
>              if (!this.emit('info', request))
>                request.reply(415, null, ["Accept: application/dtmf-relay"]);
>              else
>                request.reply(200);

**Comment by josephfrazier** [comment]
Hi @alexandrkozlov, can you link to the commit in question? I'm having trouble finding where `emit('info', request)` was _ever_ called anywhere.

**Comment by alexandrkozlov** [comment]
Sorry, right I'm also not sure that it was really called before (maybe it was our temporary local changes)

So, please replace line 694 of https://github.com/onsip/SIP.js/blob/master/src/Session.js with 
>if (!this.emit('info', request))
>           request.reply(415, null, ["Accept: application/dtmf-relay"]);
>         else
>           request.reply(200);

Probably the best way is to send 200 OK only if listener really process INFO, but anyway it's better than right now

**Comment by alexandrkozlov** [comment]
Let's continue in #324
