### ISSUE TITLE
interoperability support

### ISSUE THREAD

**Issue by cloud2pilot** [onsip/SIP.js#325]
i have been exaustively testing many different releases of Asterisk with chan_sip, pjsip, many different settings in extensions.conf and still i have not been able to achieve a working demo of sipjs app. would anybody have an asterisk docker setup capable of doing so ?

**Comment by egreenmachine** [comment]
Have you tried following our official guide? http://sipjs.com/guides/server-configuration/asterisk/

Following the guide exactly and using Asterisk 11.11.0 definitely works. There are some troubleshooting links at the bottom of the guide as well.

**Comment by james-criscuolo** [comment]
I'm going to close this, but our google group or the Asterisks forums will likely provide a better answer here.
