### ISSUE TITLE
Chrome: Failed to construct 'RTCPeerConnection': Malformed constraints object. 

### ISSUE THREAD

**Issue by alexandrkozlov** [onsip/SIP.js#328]
Hi,

I need to pass "offerToReceiveVideo: false" parameter to _createOffer()_. Right now the only way to do this is set _RTCConstraints_, but it is also passed to 

    this.peerConnection = new SIP.WebRTC.RTCPeerConnection({'iceServers': servers}, RTCConstraints);

In Google Chrome I got error Failed to construct 'RTCPeerConnection': Malformed constraints object. 

Please create separate constraints for _RTCPeerConnection_ and _createOffer_

**Comment by james-criscuolo** [comment]
Hi @alexandrkozlov,
  This is a valid bug. There's a bit to think about seeing as it changes what is likely a commonly used piece of code, but we will get to it in due time. In the meantime, PRs are always welcome.

Thanks for reporting,
James

**Comment by james-criscuolo** [comment]
Looking through our code, we pass in:

```
RTCConstraints: {
  optional: [{
    DtlsSrtpKeyAgreement: true
  }],
  mandatory: {
    OfferToReceiveVideo: constraints.video
  }
}
```

Does this not work for you? I wasn't aware at the moment I posted that we did the same thing, so maybe this is not a valid bug after all.

**Comment by alexandrkozlov** [comment]
In your case:
Chrome says: Failed to execute 'createOffer' on 'RTCPeerConnection': Unsatisfiable constraint offerToReceiveVideo(…)
FireFox says: Mandatory/optional in createOffer options no longer works! Use {} instead (note the case difference)!

**Comment by alexandrkozlov** [comment]
So, please add separate fields to solve my problem.

**Comment by james-criscuolo** [comment]
Can you paste what your RTCConstraints object looks like? Or just your whole accept/invite call? The code I pasted works for us, and has worked for a long time.

**Comment by alexandrkozlov** [comment]
I'm trying to make presentation using _sendonly_ video stream:
```javascript
    let sharingOptions = {
        media: {
            constraints: {
                audio: false,
                video: {
                    mandatory: {
                        chromeMediaSource: 'desktop',
                        maxWidth: window.screen.width,
                        maxHeight: window.screen.height,
                        maxFrameRate: 5
                    },
                    optional: [
                        {googLeakyBucket: true},
                        {googTemporalLayeredScreencast: true}
                    ]
                }
            }
        },
        RTCConstraints: {
            offerToReceiveVideo: false
        }
    };
```

userAgent.invite(address, sharingOptions);

if I remove _RTCConstraints_ parameter from _SIP.WebRTC.RTCPeerConnection_ all works fine.

If I change _RTCConstraints_ as you proposed:
```javascript
RTCConstraints: {
  optional: [{
    DtlsSrtpKeyAgreement: true
  }],
  mandatory: {
    OfferToReceiveVideo: false
  }
}
```
then both browser do not want to process it in _createOffer()_

**Comment by james-criscuolo** [comment]
I can't seem to reproduce, but this seems like something that should be easily reproducible via [jsfiddle](https://jsfiddle.net/). Would you mind making an example there with the failure?

I'm curious if it has to do with some of your optional arguments, but that wouldn't really make sense either.

**Comment by alexandrkozlov** [comment]
I tried to edit some of examples from http://sipjs.com/guides/full-demo-app/, but when I click Run og jsfiddle I got several errors and nothing work:

/OnSIP/xv00uLur/?utm_source=website&utm_medium=embed&utm_campaign=xv00uLur#run:1 Font from origin 'https://jsfiddle.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://jsfiddle.net' is therefore not allowed access.
https://sipjs.com/download/sip-0.7.0.min.js Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
(index):571 Uncaught ReferenceError: SIP is not defined

Can you tell me how to run example on jsfiddle properly?

**Comment by james-criscuolo** [comment]
This is now fixed. It seems fiddle has updated their policies regarding https, but this demo is now updated to work with them.

**Comment by alexandrkozlov** [comment]
To reproduce my problem please replace function in example
https://jsfiddle.net/OnSIP/xv00uLur/?utm_source=website&utm_medium=embed&utm_campaign=xv00uLur (link from http://sipjs.com/guides/full-demo-app/)
```javascript
function mediaOptions(audio, video, remoteRender, localRender) {
    return {
      RTCConstraints: {
        offerToReceiveVideo: false
      },
        media: {
            constraints: {
                audio: false,
                video: true
            },
            render: {
                remote: remoteRender,
                local: localRender
            }
        }
    };
}
```
**Result (Chrome):** VM70 sip-0.7.5.js:11333 Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed constraints object.
**Result (FF):** All works fine

**Now solution proposed by you:**
```javascript
function mediaOptions(audio, video, remoteRender, localRender) {
    return {
      RTCConstraints: {
  optional: [{
    DtlsSrtpKeyAgreement: true
  }],
  mandatory: {
    OfferToReceiveVideo: false
  }
},
        media: {
            constraints: {
                audio: false,
                video: true
            },
            render: {
                remote: remoteRender,
                local: localRender
            }
        }
    };
}
```
**Result (Chrome):** All works fine
**Result (FF):** Mandatory/optional in createOffer options no longer works! Use {"offerToReceiveVideo":false} instead (note the case difference)!
_The last means that you propose wrong way for FireFox._

**Comment by james-criscuolo** [comment]
I was able to reproduce the results you saw above. Upon doing some digging, it seems the second argument to the RTCPeerConnection constructor is no longer [part of the spec](https://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface), so the fact that browsers do anything with it currently is probably being deprecated.

I _think_ dropping that argument from [the RTCPeerConnection creation](https://github.com/onsip/SIP.js/blob/master/src/WebRTC/MediaHandler.js#L378) should fix this without causing any ill effects for others, but I am not sure. The constraints object that is passed there is always passed to createOffer/Answer, so I believe that should just be duplicate information that can be removed. In terms of what should be passed once this is removed, the RTCConstraints object should be:

`{ offerToReceiveAudio: false }`

and I believe that would work for both (although I haven't tested yet). I can probably test and get a Pull Request together before the end of the week, but please feel free to do so if you have time in the meantime. The line to change is linked above, it's more the testing and evidence/confidence that nothing will break that is the time consuming aspect.

**Comment by wpp** [comment]
Hi! I've done some testing today and opened https://github.com/onsip/SIP.js/pull/331. Would be great if @alexandrkozlov could confirm.

Cheers.

**Comment by alexandrkozlov** [comment]
Thanks. All works fine with proposed PR
