### ISSUE TITLE
Subscription should emit `rejected` for every unsuccessful final (300-699) response received

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#332]
There is a mismatch between the doc and the implementation of [SIP.Subscription](http://sipjs.com/api/0.7.0/subscription/) (Which inherits from [SIP.ClientContext](http://sipjs.com/api/0.7.0/context/client/)), especially regarding the `rejected` event (documented at  [SIP.ClientContext#rejected](http://sipjs.com/api/0.7.0/context/client/#rejected)):

> ## rejected
> 
> Fired each time an unsuccessful final (300-699) response is received. Note: This will also emit a failed event.

The prototype of `Subscription` overrides `receiveResponse`, which is the method that would emit `rejected` messages, but this method only emits `failed`events, on a restricted set of `errorCodes` and no `rejected` event, especially not on any "unsuccessful final (300-699) response received".

Note that I did get an undesired behavior from this as I was not able to detect 403 rejections messages that occurred when a real time peer was removed (Asterisk). The workaround being to "monkey patch" the list of error codes:

``` js
mySub.errorCodes.push(403)
```

**Comment by james-criscuolo** [comment]
Hi @matthieusieben,
  Sorry this managed to sit as long as it did, but I believed I've got it fixed on my fork: https://github.com/james-criscuolo/SIP.js/commit/0c257b17ef0e9800096dd87ad72525434efd6261

The error codes listed are defined by the RFC to cause the subscription to be seen as terminated, but indeed all error codes should get the emissions (both 'failed' and 'rejected', now). Once the emissions take place, determining if the subscription is still active can be done by checking the state property. Once the other issue is checked out (#366, which was the larger rework of that commit), I'll get this merged, but in the meantime if you could test to make sure your use case is still functional with the new code, that would be great.

Thanks,
James

**Comment by james-criscuolo** [comment]
The other ticket was successfully tested and closed, so I merged the commit onto master. I'm going to close this ticket as well, please let me know if you run into any further issues though.

Thanks,
James
