### ISSUE TITLE
How to use sip outbound proxy?

### ISSUE THREAD

**Issue by Mancy** [onsip/SIP.js#334]
Hello,
    I want to know if there is anyway to set sip outbound proxy in SIP.js
I already found 'Route' and 'Record-Route' headers that could be used for this, correct me!
but how to set these headers to something like
`<sip:{0}:{1};lr;sipjs-outbound;transport={2}>`

**Comment by james-criscuolo** [comment]
Hi @Mancy,
  You are looking for the [`wsServers` UA configuration parameter](http://sipjs.com/api/0.7.0/ua_configuration_parameters/#wsservers). Route and Record-Route headers have other purposes, all described in full detail in [the SIP RFC](https://tools.ietf.org/html/rfc3261).

In the future, please keep questions like this to [the google group](https://groups.google.com/forum/#!forum/sip_js), as we prefer this space to be used for problems with the library.

Thanks,
James

**Comment by egreenmachine** [comment]
The websocket is essentially the outbound proxy as all traffic will go through it regardless of the end sip address.
