### ISSUE TITLE
SIP.js demo on can't be run on webpage because it is not secure

### ISSUE THREAD

**Issue by coolmig** [onsip/SIP.js#340]
Hello guys,

I've just tried to run the SIP.js demo on the webpage but it doesn't work, because browsers no longer accept media from insecure webpages. On Chrome this is the console error when Alice tries to call Bob:

getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

So this is a kind request to enable HTTPS on sipjs.com for people to be able to run the demo. Right now I can't connect to https://sipjs.com

Best regards,
Miguel Molina

**Comment by james-criscuolo** [comment]
Hi Miguel,
  We are aware of this problem, and it is actually an issue with github pages involving custom domains. The demos will work in Firefox, but it would take... a bit too much time at the moment to move off of github pages, so we are leaving the site as is for the time being. We also [already have an issue in the website's repo](https://github.com/onsip/sipjs.com/issues/21) regarding this, so I'm going to close this one.

Thanks,
James
