### ISSUE TITLE
Outdated docs for registrationFailed

### ISSUE THREAD

**Issue by virusman** [onsip/SIP.js#341]
registrationFailed callback has one argument (cause) according to the docs: http://sipjs.com/api/0.7.0/ua/#registrationfailed
In reality, however, it gets two arguments: response and cause.
https://github.com/onsip/SIP.js/blob/master/src/RegisterContext.js#L174

**Comment by james-criscuolo** [comment]
Just fixed this. Also, there is a [separate repo for the docs](https://github.com/onsip/sipjs.com), so feel free to do PRs there in the future for similar problems.
