### ISSUE TITLE
InviteServerContext event on dialog confirmed

### ISSUE THREAD

**Issue by colinmorelli** [onsip/SIP.js#343]
It appears that there's no event that fires when a dialog enters a confirmed state on an inbound call. Once SIP.js sends the 200 OK, it goes into status 7 (`WAITING_FOR_ACK`). When it receives the ACK, it sets the status to `CONFIRMED` but there's no additional event to be notified of this that I can see. 

For applications that use the status message to inform the user about what's happening with the call, this is somewhat problematic. I could simply show "connected" at status 7 but there's no guarantee that the dialog is active yet.

The confirmSession method that gets called when the ACK is received is here:

```
    function confirmSession() {
      /* jshint validthis:true */
      var contentType;

      SIP.Timers.clearTimeout(this.timers.ackTimer);
      SIP.Timers.clearTimeout(this.timers.invite2xxTimer);
      this.status = C.STATUS_CONFIRMED;
      this.unmute();

      // TODO - this logic assumes Content-Disposition defaults
      contentType = request.getHeader('Content-Type');
      if (contentType !== 'application/sdp') {
        this.renderbody = request.body;
        this.rendertype = contentType;
      }
    }
```

For client calls, this can be done with the `accepted` event. This is triggered after the 200 OK is received but before the ACK is sent. Most of the time this is actually fine to consider the call `confirmed` (as SIP.js does) since, unless you're placing the SDP in the ACK, both parties should have an SDP and be able to negotiate media at this point.

For incoming server calls, however, that's not the case. Given that SIP.js places the SDP in the 200 OK it can't assume the dialog has started until it receives the ACK.

Does it make sense to have a `confirmed` event that would fire whenever entering status 12? Or a more general `status` event that fires for all dialog state changes?

**Comment by markandrus** [comment]
Hey @colinmorelli, please take a look at #321. It added the "confirmed" event you mention.

**Comment by colinmorelli** [comment]
You're absolutely right. Didn't see it because that isn't in the latest release. Apologies for the bogus ticket. I'll run off of master until a new release is cut with that.

**Comment by colinmorelli** [comment]
Actually would it be possible to get a more recent release of SIP.js? It has been a while since 0.7.5 was shipped, and with the grammar files and lack of pre-built dist files in the repo it's not quite as straightforward to use SIP.js from a non release tag. I certainly can do this for the time being but it would be great if a new release could be shipped.
