### ISSUE TITLE
DTLS failure due to reason 'sslv3 alert handshake failure'

### ISSUE THREAD

**Issue by stshishkin** [onsip/SIP.js#345]
We've faced with aborting call after RBT connection with message in asterisk console:
[2016-08-11 15:55:25] ERROR[30166][C-000001d7]: res_rtp_asterisk.c:2106 __rtp_recvfrom: DTLS failure occurred on RTP instance '0x7f8e98036948' due to reason 'sslv3 alert handshake failure', terminating

(client - Chrome 52.0.2743.116 (64bit), OS X 10.11.5 )
(server - asterisk 11.20.0 )
call log : [call.txt](https://github.com/onsip/SIP.js/files/413312/call.txt)

**Comment by egreenmachine** [comment]
What version of openssl are you running and did you compile Asterisk against? You probably need to update it to support Chrome's new cipher and then this should work. I am going to close this as it is not a SIP.js issue. Please see #344 for more information on openssl versions.

**Comment by stshishkin** [comment]
Thank you for your hint! It's worked for me
