### ISSUE TITLE
Testing SIP events

### ISSUE THREAD

**Issue by manuelspagnolo** [onsip/SIP.js#347]
Hi everyone,
I'm trying to figure out how to write tests for my application using SIP.js.
Basically, in my app I have a User Agent and, depending on the events, this app is supposed to do something.

For example, what I want to test is:

> ```
> ...code code code...
> var phone = new SIP.UA()
> 
> phone.on('invite', function(){
>      console.log('INVITED');
>  });
> ```

My attempt, by using Jasmine was something like this (copy-pasted from the repo):

> ```
>   ...code code code...
>   beforeEach(function(){
>      ua = mockphone;
>      ua.transport = jasmine.createSpyObj('transport', ['send', 'connect', 'disconnect', 'reConnect']);
> 
>     request = SIP.Parser.parseMessage([
>         'REFER sip:gled5gsn@hk95bautgaa7.invalid;transport=ws;aor=name40domain.com SIP/2.0',
>         'Max-Forwards: 65',
>         'To: <sip:name@domain.com>',
>         'From: "test1" <sip:test1@onsnip.onsip.com>;tag=rto5ib4052',
>         'Call-ID: grj0liun879lfj35evfq',
>         'CSeq: 1798 INVITE',
>         'Contact: <sip:e55r35u3@kgu78r4e1e6j.invalid;transport=ws;ob>',
>         'Allow: ACK,CANCEL,BYE,OPTIONS,INVITE,MESSAGE',
>         'Content-Type: application/sdp',
>         'Supported: outbound',
>         'User-Agent: SIP.js 0.5.0-devel',
>         'Content-Length: 10',
>         '',
>         'a=sendrecv',
>         ''].join('\r\n'), ua);
> 
>     spyOn(SIP.Transactions, 'InviteServerTransaction');
>     spyOn(SIP.Transactions, 'NonInviteServerTransaction');
> 
>     ServerContext = new SIP.ServerContext(ua,request);
> });
> ```

But I'm not able to generate an invite event to test out my UA. 
I run in the same issue when I'm trying to testing events related to sessions ('cancel', 'progress' and so on...).

Where do I can find some example of this kind of tests? Can you point me out any file in the repo?
Can you write me some basic examples? 

Many thanks for your great work,
Manuel

**Comment by egreenmachine** [comment]
Try taking a look at the [SIP.js test suite](https://github.com/onsip/SIP.js/tree/master/test) and see if that is what you are looking for.
