### ISSUE TITLE
Methods session.hold and session.unhold lack documentation on SIPJS.com

### ISSUE THREAD

**Issue by afr1983** [onsip/SIP.js#348]
These methods are used to send RE-INVITEs so the other side of a call can be put into hold. However, they do not appear in the API Reference.

**Comment by egreenmachine** [comment]
We have a ticket to do this on our website: https://github.com/onsip/sipjs.com/issues/17. We were waiting for things to stabilize before documenting it, but that has probably already happened. Please follow up with additional questions about the documentation there.
