### ISSUE TITLE
Turn servers credentials required

### ISSUE THREAD

**Issue by Klimashin** [onsip/SIP.js#351]
Hi! I've faced a problem, that username and password fields are required when defining turnServers object in sip.js. But in native RTCIceServer object credentials are optional. So is there a way i can use turn server without authorization?

**Comment by egreenmachine** [comment]
Hi @Klimashin,

Can you see if the commit referenced above fixes this issue?

Thanks

**Comment by james-criscuolo** [comment]
It's been 3 weeks since the fix, so I am going to close this issue. If the commit in question did not fix the issue, please re-open this issue or open another issue.

Thanks,
James

**Comment by egreenmachine** [comment]
Merged #367
