### ISSUE TITLE
SIP.js throws a web socket error when registration event happens during call setup (server crash)

### ISSUE THREAD

**Issue by terusus** [onsip/SIP.js#353]
Hello,

I have a server setup for VOIP calls that involves a node.js web server that provides a HTTP API in order to manage signalling with clients. The API server uses SIP over WSS to communicate with a FreeSwitch server. The API's server registration expires every 10 minutes and a reconnect event is automatically triggered by SIP.js.

Here are the UA configuration parameter:

```javascript
{
    uri: 'USER@DOMAIN',
    password: 'PASSWORD',
    wsServers: ['wss://DOMAIN'],
    wsServerMaxReconnection: Number.MAX_SAFE_INTEGER, // default is 3, 0 is not working
    wsServerReconnectionTimeout: 10, // seconds, default is 4
    rel100: 'supported', // reliable provisional responses for 'early media'
    traceSip: true,
    mediaHandlerFactory: function(session, options) { ... }
}
```

So, I noticed that from time to time the API server crashes. I provided the logs of the crash below. It appears that when the user makes a call and a registration event is fired at the same time the web socket library crashes.

I hope that together we can figure out if this is a bug in SIP.js or I did something wrong with the API server implementation or SIP.js configuration?
Or at minimum, how can I gracefully handle this exception in the API server?

```
timestamp | sip.transport | received WebSocket text message:

INVITE sip:DESTINATION SIP/2.0
Via: SIP/2.0/WSS SOMETHING.invalid;branch=BRANCH
Max-Forwards: 70
To: sip:DESTINATION
From: sip:SOURCE
Call-ID: SAME
CSeq: 3719 INVITE
Contact: <sip:CONTACT.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Content-Type: application/sdp
Supported: 100rel, outbound
User-Agent: SIP.js/0.7.5
Content-Length: 1700

SDP OFFER

timestamp | sip.transport | received WebSocket text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS SOMETHING.invalid;branch=BRANCH;received=IP;rport=PORT
To: sip:DESTINATION
From: sip:SOURCE
Call-ID: SAME
CSeq: 3719 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.6.9-16-d574870~64bit
Content-Length: 0

timestamp | sip.transport | received WebSocket text message:

SIP/2.0 407 Proxy Authentication Required
Via: SIP/2.0/WSS SOMETHING.invalid;branch=BRANCH;received=IP;rport=PORT
To: sip:DESTINATION
From: sip:SOURCE
Call-ID: SAME
CSeq: 3719 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.6.9-16-d574870~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Proxy-Authenticate: Digest realm="DOMAIN", nonce="...", algorithm=MD5, qop="auth"
Content-Length: 0

timestamp | sip.transport | sending WebSocket message:
ACK sip:DESTINATION
Via: SIP/2.0/WSS SOMETHING.invalid;branch=BRANCH
To: sip:DESTINATION
From: sip:SOURCE
Call-ID: SAME
Content-Length: 0
CSeq: 3719 ACK

timestamp | sip.transport | sending WebSocket message:
INVITE sip:DESTINATION SIP/2.0
Via: SIP/2.0/WSS SOMETHING.invalid;branch=BRANCH
Max-Forwards: 70
To: sip:DESTINATION
From: sip:SOURCE
Call-ID: SAME
CSeq: 3720 INVITE
Proxy-Authorization: Digest algorithm=MD5, username="USERNAME", realm="DOMAIN", nonce="...", uri="sip:DESTINATION", response="RESPONCE", qop=auth, cnonce="...", nc=00000001
Contact: <sip:CONTACT.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Content-Type: application/sdp
Supported: 100rel, outbound
User-Agent: SIP.js/0.7.5
Content-Length: 1700

SDP OFFER


timestamp | sip.transaction.ict | Timer D expired for INVITE client transaction BRANCH
timestamp | sip.transport | received WebSocket text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS SOMETHING.invalid;branch=BRANCH;received=IP;rport=PORT
To: sip:DESTINATION
From: sip:SOURCE
Call-ID: SAME
CSeq: 3720 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.6.9-16-d574870~64bit
Content-Length: 0

<><><>

timestamp | sip.transport | sending WebSocket message:

REGISTER sip:DOMAIN SIP/2.0
Via: SIP/2.0/WSS SOMETHING.invalid;branch=NEW_BRANCH
Max-Forwards: 70
To: sip:SOURCE
From: sip:SOURCE
Call-ID: NEW_CALL_ID
CSeq: 125 REGISTER
Authorization: Digest algorithm=MD5, username="USERNAME", realm="DOMAIN", nonce="...", uri="sip:DOMAIN", response="RESPONSE", qop=auth, cnonce="...", nc=00000001
Contact: <sip:CONTACT.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:UUID>";expires=600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: path, gruu, 100rel, outbound
User-Agent: SIP.js/0.7.5
Content-Length: 0

.../node_modules/ws/lib/Receiver.js:382
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^
RangeError: out of range index
    at RangeError (native)
    at fastCopy (.../node_modules/ws/lib/Receiver.js:382:24)
    at Receiver.add (.../node_modules/ws/lib/Receiver.js:82:3)
    at TLSSocket.firstHandler (.../node_modules/ws/lib/WebSocket.js:775:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
```

**Comment by james-criscuolo** [comment]
Hi @terusus,
  It looks like other people are [getting a similar RangeError](https://github.com/websockets/ws/issues/778) with `ws`. Upgrading `ws`, or downgrading `node`, or some combination, seems to be the answer here. If the answer is in fact upgrading `ws`, opening a PR once you've confirmed that indeed fixes it will surely get accepted.

I'd say we can do the testing ourselves, but we have not encountered this problem anywhere, so I'm not sure we have the setup for it.

Thanks,
James

**Comment by terusus** [comment]
Thank you for the solution @james-criscuolo.

I updated the node.js version right away to 6.6.0. And the services have been running for a couple of weeks now. They have been tested a few times. The WS crash appears to have disappeared.

I can also confirm - the problem was node.js 6.3.0.

**Comment by Sandhya1007** [comment]
Error: WebSocket closed wss://sip.vonzoo.com/wsrtc (code: undefined)
onWebSocketClose@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:151613:56
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:151454:42
dispatchEvent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:34155:31
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:34880:31
emit@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:3400:42
__callFunction@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2686:49
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2408:31
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2640:15
callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2407:21
callFunctionReturnFlushedQueue@[native code]


Getting this errror after registering in SIP
