### ISSUE TITLE
How do we use the in-band DTMF - rfc2833 in sipjs

### ISSUE THREAD

**Issue by alochym01** [onsip/SIP.js#354]
hi list

we made called out to PSTN and send DTMF to PSTN but PSTN only support in-band signaling how do we make it work in sipjs

refer from issue: https://github.com/onsip/SIP.js/issues/307

sipjs only support SIP INFO dtmf

thank you

**Comment by egreenmachine** [comment]
It looks like you answered your own question. SIPjs only supports SIP INFO. You would need to use a gateway such as [FreeSWITCH to convert it to RFC2833](https://freeswitch.org/confluence/display/FREESWITCH/Sofia+Configuration+Files#SofiaConfigurationFiles-liberal-dtmf). If you have questions about that please follow up with FreeSWITCH.
