### ISSUE TITLE
open or off video while making calls

### ISSUE THREAD

**Issue by quanvq** [onsip/SIP.js#355]
Hi all,
i want open or off video while making calls. But session no method, please help me.
thanks all and good luck today.

**Comment by james-criscuolo** [comment]
Hi @quanvq,
  The [mute function, with the correct arguments](http://sipjs.com/api/0.7.0/session/#muteoptions), will do this for you.

  Please direct quesitons like this to [our mailing list](https://groups.google.com/forum/#!forum/sip_js) in the future. We try to keep this space for bugs or feature requests.

James

**Comment by quanvq** [comment]
please demo for me. thanks you
ex: **i want on,off video media while making calls**
thanks you,

**Comment by klarrimore** [comment]
we'll get right on that.
