### ISSUE TITLE
options.extraHeaders don't appear when using Session cancel()

### ISSUE THREAD

**Issue by apparition47** [onsip/SIP.js#359]
I'm trying to call [`cancel([options])`](http://sipjs.com/api/0.7.0/session/#canceloptions) with `{options.extraHeaders: ['hello: test']}` but my `options.extraHeaders` aren't showing up in the SIP WS frame when I inspect it with Chrome. If I use [`UA.request([method, target, options])`](http://sipjs.com/api/0.7.0/ua/#requestmethod-target-options) , I can see the extraHeaders injected into the SIP WS frame but not with the `CANCEL`/`TERMINATE` methods. 

Test Details:

```
SIP.js 0.7.5
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
```

Any ideas?

Actual Result:

```
CANCEL sip:user1@example.com SIP/2.0
Via: SIP/2.0/WSS vmimouo7fjj1.invalid;branch=z9hG4bK8753359
To: <sip:user2@example.com>
From: <sip:user1@example.com>;tag=e37iusqofq
Call-ID: 26rq6d0rq5nlve5m7p0s
CSeq: 3570 CANCEL
Content-Length: 0
```

Expected Result:

```
CANCEL sip:user1@example.com SIP/2.0
Via: SIP/2.0/WSS vmimouo7fjj1.invalid;branch=z9hG4bK8753359
To: <sip:user2@example.com>
From: <sip:user1@example.com>;tag=e37iusqofq
Call-ID: 26rq6d0rq5nlve5m7p0s
CSeq: 3570 CANCEL
Content-Length: 0
hello: test
```

**Comment by egreenmachine** [comment]
This looks to be a bug in `Transactions.js` that we are not handling extra headers when we send a cancel. We will try and get it fixed or you can submit a pull request if you have already fixed it.

**Comment by egreenmachine** [comment]
@apparition47 Can you check if the commit above fixes your issue? If it does I will merge it into master.

**Comment by apparition47** [comment]
Hey @egreenmachine , thanks for the patch. It looks like it's almost working but there's a [minor issue with your commit](https://github.com/onsip/SIP.js/commit/3b06bb7a058242ea62ec02b0ffc727b1ef09f113#commitcomment-20145385). Please review the comment I made there. Thanks!

**Comment by egreenmachine** [comment]
Thanks for finding that bug. I have patched and merged to master so this will be included in our next release.
