### ISSUE TITLE
Selecting devices

### ISSUE THREAD

**Issue by kajzur** [onsip/SIP.js#361]
Hi :) How to select input and output audio devies?

**Comment by james-criscuolo** [comment]
Hi @kajzur,
  After calling getUserMedia, there will be a popup to select input device. Outputs are done system level, but an [experimental flag in Chrome](https://webrtc.github.io/samples/src/content/devices/input-output/) can show you where that may end up in the future.

  For questions like this, please use our [google group](https://groups.google.com/forum/#!forum/sip_js) after you have checked our [documentation and guides](http://sipjs.com/). We try to keep this space for bugs and feature requests.

James
