### ISSUE TITLE
Cannot hangup a received call.

### ISSUE THREAD

**Issue by fxl03080** [onsip/SIP.js#369]
When receiving a call from a sip phone or other sip client, calling the .bye() method does not hang up the call. It only works when sending an outbound call.

**Comment by fxl03080** [comment]
Forgot, this is using angularjs with a freeswitch server using sipjs 0.7.5

**Comment by egreenmachine** [comment]
This seems like an issue for our [mailing list](https://groups.google.com/forum/#!forum/sip_js). Could you please follow up there and include logs with [traceSip](http://sipjs.com/api/0.7.0/ua_configuration_parameters/#tracesip) true? Thanks.

**Comment by fxl03080** [comment]
I actually found the solution, what ended up happening was the session was showing up as undefined in my code. The solution was to assign it to a variable and do a logic check if it was null or undefined and to then call the .bye method.
