### ISSUE TITLE
In Firefox Invalid webrtc msid at level 0: Missing track id

### ISSUE THREAD

**Issue by ibaques** [onsip/SIP.js#371]
I'm calling a video conference server Acano from Firefox, the OK SDP response 

v=0
o=Acano 0 0 IN IP4 X.X.X.X
s=-
c=IN IP4 X.X.X.X
b=CT:5859
t=0 0
a=setup:active
a=msid-semantic: WMS siDT9mDnrufAO5TyHzfA6rYPTtqroi8N6kNb
a=fingerprint:sha-256 
a=group:BUNDLE sdparta_0 sdparta_1
m=audio 13926 UDP/TLS/RTP/SAVPF 109 9 0 8
a=ice-ufrag:AcTC
a=ice-pwd:6ERTqm3tJiR9QWaKcHweU4
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
**a=ssrc:1822943278 cname:gtkn56dw/345/12o
a=ssrc:1822943278 msid:siDT9mDnrufAO5TyHzfA6rYPTtqroi8N6kNb
a=ssrc:1822943278 mslabel:siDT9mDnrufAO5TyHzfA6rYPTtqroi8N6kNb**
a=mid:sdparta_0
a=sendrecv
a=rtcp:13926
a=rtcp-mux
m=video 13948 UDP/TLS/RTP/SAVPF 120
b=TIAS:5744000
a=content:main
a=rtcp-fb:* nack
a=rtcp-fb:* nack pli
a=rtcp-fb:* ccm fir
a=ice-ufrag:AcTC
a=ice-pwd:6ERTqm3tJiR9QWaKcHweU4
a=rtpmap:120 VP8/90000
**a=ssrc:497795445 cname:gtkn56dw/345/12o
a=ssrc:497795445 msid:siDT9mDnrufAO5TyHzfA6rYPTtqroi8N6kNb
a=ssrc:497795445 mslabel:siDT9mDnrufAO5TyHzfA6rYPTtqroi8N6kNb
a=ssrc:497795445 label:main**
a=label:11
a=mid:sdparta_1
a=sendrecv
a=rtcp:13948
a=rtcp-mux

The call is hangup with error:

DOMException [InvalidSessionDescriptionError: "Invalid webrtc msid at level 0: Missing track id."
code: 0
nsresult: 0x0]

A BYE with 488 is the sipjs response.

If i try with Chrome, audio and video works correctly. What is the problem with de SDP?

Thanks

**Comment by egreenmachine** [comment]
This seems like a problem similar to what we have seen with Jitsi. http://sipjs.com/api/0.7.0/ua_configuration_parameters/#hackcleanjitsisdpimageattr. You might need a hack similar to what we did to make Jitsi work.

**Comment by ibaques** [comment]
But, which is the line of the SDP that not work with Firefox?

Thanks!

**Comment by egreenmachine** [comment]
I am unsure. You can try removing them one by one to see which fixes the issue, or try following up with the Firefox team.
