### ISSUE TITLE
Multiplexing RTCP required in Chrome Canary

### ISSUE THREAD

**Issue by seanbright** [onsip/SIP.js#374]
Per [this announcement](https://groups.google.com/forum/#!topic/discuss-webrtc/eM57DEy89MY):

> As of the most recent Chrome Canary build, the default RTCP multiplexing policy is "require", instead of "negotiate". This will affect the next Chrome release, M57.

> For any application that doesn't yet support RTCP multiplexing, you can get the old behavior by explicitly setting the RTCRtpMuxPolicy to "negotiate" in the RTCConfiguration.

Some endpoints (Asterisk, for example) do not yet support rtcp-mux and will therefore stop working after the next Chrome release.

**Comment by egreenmachine** [comment]
This is not something we can do anything about in SIP.js. If you would like to discuss this further, I would recommend reaching out to Asterisk or you can discuss with other SIP.js users on our [mailing list](https://groups.google.com/forum/#!forum/sip_js). Thanks.

**Comment by seanbright** [comment]
Sorry? You could add a flag (similar to the `hack*` options) to pass `{rtcpMuxPolicy: "negotiate"}` when creating an `RTCPeerConnection`? Or is that out of scope?

**Comment by egreenmachine** [comment]
I'm sorry. You are correct. I did not read the announcement before replying and just used your summary as a basis for my reply. Yes, we should add yet another hack. Re-opening this issue.

**Comment by egreenmachine** [comment]
It should be noted that I tested this with FreeSWITCH 1.6.14 and RTPEngine and neither had issues with multiplexing RTCP with RTP. It appears that Asterisk is the lone issue here.
