### ISSUE TITLE
Dispose SIP.UA instances

### ISSUE THREAD

**Issue by u9520107** [onsip/SIP.js#376]
Is there away to cleanly dispose a SIP.UA instance? If the connection is no longer needed.
In my brief test, once SIP.UA instance is instantiated, even without connect to any server, I can not find a way to let GC clean it up.

**Comment by james-criscuolo** [comment]
Does [ua.stop](http://sipjs.com/api/0.7.0/ua/#stop) not cover this? If not, does deleting the object (`delete ua;`) afterward not cover this either?

**Comment by u9520107** [comment]
Don't think so. With each execution of the following line, the number of UA object in memory heap after forced GC increases. 

```javascript
var ua = new SIP.UA(); ua.stop(); ua = null;
```

**Comment by matthieusieben** [comment]
See #380 and #381. I believe these will be release with 0.7.8 ?

**Comment by matthieusieben** [comment]
By the way, my `Makefile` contains the following line:
```sh
sed -i "/'unload'/d" node_modules/sip.js/src/UA.js
```

**Comment by u9520107** [comment]
Looks promising, I'll check again after the 0.7.8 release.

**Comment by james-criscuolo** [comment]
Hi @u9520107,
  0.7.8 has been out for a little bit, can you please retest?

**Comment by u9520107** [comment]
@james-criscuolo OK. I'll test this out before next week.

**Comment by u9520107** [comment]
@james-criscuolo OK, I can confirm that UA objects gets GC'd properly on 0.7.8.

**Comment by james-criscuolo** [comment]
Great thanks! I'll close the issue.
