### ISSUE TITLE
Cannot show both Remote and Local Video at the same time

### ISSUE THREAD

**Issue by rflopes3** [onsip/SIP.js#379]
I'm trying to migrate from sipml5 to SIP.js because on sipml5 I cannot do attended transfers. So, I have migrated almost everything, I can make and receive video and audio calls BUT, I cannot show the locao video at the same time as remote video (Like on Facetime).

Here is the code of my onInvite event.

videoLocal = document.getElementById('video_local');
               videoRemote = document.getElementById('video_remote');
                
                var opt = {
                    media: {
                        constraints: {
                            audio: false,
                            video: true
                        },
                        render: {
                            remote: {video: videoRemote}, 
                            local: {video: videoLocal} 
                        }
                    }
                };   
                
                
                
                console.log('Chamada de VIDEO atendida...');
                callSession2 = s;
                callSession2.accept(opt);
                
                
                var localStreams = callSession2.getLocalStreams();
                var remoteStreams = callSession2.getRemoteStreams();
                
                
                
                SIP.WebRTC.MediaStreamManager.render(localStreams[0], videoLocal);
                SIP.WebRTC.MediaStreamManager.render(remoteStreams[0], videoRemote);
                
All works but the local video is NOT rendered.

Can anyone help ?

**Comment by james-criscuolo** [comment]
I believe the issue here is that you are calling `render`. You should not need to call render at all here, your `opt.render` should cover it.

For questions like this in the future, please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js). We try to keep this space for confirmed problems with the code or feature requests.

Thanks,
James
