### ISSUE TITLE
Memory leak of ua.stop()

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#380]
In out SPA, we manage and create several SIP.js UA during a single session. [The following line](https://github.com/onsip/SIP.js/blob/bae28258a4b705eb10239b00094985dc4baa314a/src/UA.js#L181) causes every ua to be referenced by `window` and never to be garbage collected.

In the case `us.start()` was never called, or `ua.stop()` was already called, this listener on `unload` **must** be removed!

**Comment by solispauwels** [comment]
+1

**Comment by james-criscuolo** [comment]
Fixed this here: https://github.com/onsip/SIP.js/commit/5747a068cb2a94263a7c6083a1b818c08035ab6f

Thanks again for the issue!

**Comment by matthieusieben** [comment]
Just a thought: Should we not be able to disable this behaviour ?

In most of the cases (e.g. peer with password) the unregistration will not be valid anyways.
