### ISSUE TITLE
Memory leak in sanityCheck()

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#381]
The `sanityCheck()` function, once called, will cause a reference to the ua to be kept in its scope. If the ua is stopped, and no longer referenced by other parts of the program, it will not be garbage collected because of this.

This is not the first memory leak I encounter (#380). Maybe a review of all of the possible leaks is needed ?

**Comment by james-criscuolo** [comment]
Thank you for reporting these leaks! These are definitely issues we would like to address in an urgent matter (or via PR).

In terms of a review of all possible leaks, we'd certainly welcome some help from the community for that kind of endeavor (possibly a testing refactor to include this?), but we do hope to address individual ones as they are brought to our attention.

**Comment by james-criscuolo** [comment]
I believe I have this one fixed here: https://github.com/onsip/SIP.js/commit/62ee7510fa3ef989170ca8f7634fc4ff1ce49904

Let me know if it works out, and thanks again!
