### ISSUE TITLE
websocket disconnected (code: 1002)

### ISSUE THREAD

**Issue by gnikolaev** [onsip/SIP.js#382]
For some reason websockets are getting disconnected on different occasions. Mostly is happening on outgoing calls. Also noticed that once it happened on an outgoing call, the immediate incoming call after that has the same result. 

Here is the Chrome console log which includes the SIP signalling as well: http://pastebin.com/2Ek5pZk3

Just to save you time reading through, line 209 is the websocket disconnect for the outbound call.
Line 755 is the wss disconnect for the inbound  call.

Now I see that the code is 1002 which is Protocol error, but have no idea what exactly that means. Searching the internet, it says that 1002 is used when the websocket implementation is incorrect.

Any suggestions/ideas are welcome.

**Comment by james-criscuolo** [comment]
You'll likely see better logs for this on the web socket server itself (wss://pbxdev.callplan.io:7443). I'm primarily used to seeing this bug when I connect to a non-https cert'ed server, so I have to accept the exception manually in the browser before continuing, but that does not appear to be the case here. That may be a clue for you here, but the only way of knowing would likely be on the server itself.

Also, for questions like this please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js). We try to keep this space for confirmed issues and feature request discussion.

Thanks,
James
