### ISSUE TITLE
Using SIP.js with Twillio

### ISSUE THREAD

**Issue by bhushan-firake** [onsip/SIP.js#384]
Hi,

I have been trying to use SIP.js with Twilio.

Possible Flow:

SIP.js will be used on client-side in the browsers from where user will initiate calls. Now Twilio SIP will be used to call to the number.

How can it be achieved? Any guidelines whether this can be done?

**Comment by wpp** [comment]
Hi,

this is probably better suited for the [mailing list](https://groups.google.com/forum/#!forum/sip_js).

Cheers

**Comment by james-criscuolo** [comment]
I can't say I'm too familiar with Twilio's offerings, but I know this can be done. Twilio [has a webrtc page](https://www.twilio.com/webrtc), the answers you seek likely lie there.

And yes, @wpp is correct, this is a question for the mailing list. We try to keep this space for problems and feature discussion.

James

**Comment by bhushan-firake** [comment]
@james-criscuolo & @wpp  Sorry to add it as an issue. I will post it in a mailing list as a solution. I have got it working with Twilio. Just wanted to see if anyone else has done anything similar and more efficiently.

**Comment by pimrie** [comment]
Hi bushan,

Did you post this in the Mailing list? I had a look there and didn't see anything, I am looking at a Twilio - sipJS integration. 

Thanks

**Comment by cristianmad** [comment]
@bhushan-firake, could you please post a link to your solution? I'm facing the same problem.

Thanks

**Comment by richavaidya** [comment]
@bhushan-firake, I am trying the same could you please share your solution?
