### ISSUE TITLE
Disable auto-stop of ua on unload

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#386]
In the case the sip peer requires credentials, performing ua.stop() during unload phase will only have one effect: send a REGISTER with a 0 timer (to unregister) with no credentials (the normal process would be REGISTER -> 403 + challenge -> REGISTER + credentials -> 200). This unauthenticated unregister will be ignored altogether by the server, as it should be (same applies for subscriptions, etc.).

In order to work around this issue, we have implemented an HTTP API which allows to manage peers, and which we can call using a synchronous HTTP request during the 'unload' of the app. Now I know this is not ideal but this is the only thing we could do due to the limitation of the browser.

My point here is: shouldn't this 'onunload' listener be removed altogether ? Or made optional (disabled by default if the peer has credentials) ?

**Comment by james-criscuolo** [comment]
I'd be for removing it altogether, I'm curious what @egreenmachine thinks as well before acting. Being able to do anything on unload has always been a problem without a solution, but I think this fix is unnecessary (as it doesn't do anything).

**Comment by egreenmachine** [comment]
Looked into this a bit and discussed with @james-criscuolo offline. I would like to see this work, but I don't see a good option besides causing the page to hang before closing. I am good with removing it.

**Comment by james-criscuolo** [comment]
So I toyed around with removing this, and the auto-stop does more than just attempt to unregister. If you have any sessions open, `stop` will also terminate them (successfully, as opposed to the unregister). This is valuable, and likely a preferred behavior, so completing removing the `stop` at this point seems unlikely.

We can still figure out a way to potentially remove the unnecessary signaling, but its no longer a question of just removing some listeners.

**Comment by matthieusieben** [comment]
Well, at least we know why this listener is there now!

I didn't think about the sessions..

**Comment by matthieusieben** [comment]
Feel free to close this issue if you are not planning to implement an alternate `lastChanceStop` function that only terminates ongoing sessions/subscriptions (?).

**Comment by james-criscuolo** [comment]
Yea, i think I'm going to close. There is no guarantee subscriptions do not run into the same problem, and there are even more than just sessions/subscriptions/registrations in that function, all of which may fall under this gray area. I'd rather go with a "rather safe than sorry" approach here.
