### ISSUE TITLE
Free the memory!

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#388]
`UA.configuration_skeleton` is used during the creation of the UA in order to set the properties of the `ua.configuration` object.

This object is, thus, only needed for a short period of time and should probably not remain in memory (even if all values are emptied) during the ua lifetime.

Same goes for `UA.configuration_check`. Why not make these object exist in memory only during the execution of `loadConfig`? 

IMO `settings` and `configuration_skeleton` should be merged together. And `configuration_check` should be created at the beginning of `loadConfig` and be un-referenced afterwards.

**Comment by james-criscuolo** [comment]
The quest for free memory continues! I'll try to take a look at this in the coming week.

**Comment by james-criscuolo** [comment]
This was done pretty much as described above here: [https://github.com/onsip/SIP.js/commit/1245245051b86be7e908d4913d149d35abf437c7](https://github.com/onsip/SIP.js/commit/1245245051b86be7e908d4913d149d35abf437c7). the configuration_check is need in Session as well, so it's now just wrapped in a function that can be called whenever. The skeleton is still built, but it's just to prepare for the `Object.defineProperties` call, so it doesn't live in memory any longer.

**Comment by matthieusieben** [comment]
Thanks ! 😁
