### ISSUE TITLE
WebRTC error on Chrome 57

### ISSUE THREAD

**Issue by raphaelhovsepyan** [onsip/SIP.js#389]
Unable to make calls with Demo Phone, browser throws an error
```
sip-0.7.3.js:2884 DOMException: Failed to set remote answer sdp: Session error code: ERROR_CONTENT. Session error description: rtcpMuxPolicy is 'require', but media description does not contain 'a=rtcp-mux'..
```

Works fine on previous Chrome versions

**Comment by gyumjibashyan** [comment]
We have the same issue and were not able to find a viable solution

This is very important. Our production systems rely on this and the new Chrome update seems to be breaking the functionality.

**Comment by matthieusieben** [comment]
Did you try setting the [rtcpmuxpolicy](https://sipjs.com/api/0.7.0/ua_configuration_parameters/#rtcpmuxpolicy) configuration setting to `"negociate"` ?

**Comment by james-criscuolo** [comment]
We've [updated to 0.7.7](https://groups.google.com/forum/#!topic/sip_js/8pGFj2tCphM) to fix this. The demo-phone is using 0.7.3, which we should update, but if you update to 0.7.7 and [set the rtcpMuxPolicy to 'negotiate'](https://sipjs.com/api/0.7.0/ua_configuration_parameters/#rtcpmuxpolicy), you should be ok.

James

**Comment by raphaelhovsepyan** [comment]
@matthieusieben  @james-criscuolo thanks, it works on 57
but still not working on `58.0.3004.3 / Linux 64 bit`

**Comment by matthieusieben** [comment]
I've been able to make it work on `Version 58.0.3004.3 (Official Build) dev (64-bit)` without problem after adding the `rtcpMuxPolicy: 'negotiate'` configuration.

**Comment by gyumjibashyan** [comment]
Thank you @matthieusieben @james-criscuolo for fixing this. It worked!!!
