### ISSUE TITLE
Release an NPM browser build

### ISSUE THREAD

**Issue by sdemjanenko** [onsip/SIP.js#390]
The bower.json file references a `dist` directory but the NPM version does not.  The `var pkg = require('../package.json')` makes it necessary for me to use a `json-loader` in my webpack config to get this library to work.  Your `npm publish` step should take care of properly building a `dist` that doesn't require any special loaders on my end.

**Comment by egreenmachine** [comment]
We agree that we should probably do this. We will look into doing this for our next tagged release.

**Comment by subramaniashiva** [comment]
I am also facing issues without a dist version in npm. Please include in the upcoming release. Thanks for spending your time on this feature request :)

**Comment by brunowego** [comment]
Yes, please add a production ready dist.

**Comment by james-criscuolo** [comment]
This is now released with 0.7.8 so I'm going to close this issue, please let us know if there are any further issues.
