### ISSUE TITLE
broken link in package.json

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#391]
The http://sipjs.com/authors/ link referenced in package.json seems to be broken.
I did not try any other links.

**Comment by egreenmachine** [comment]
Yeah that does appear to be broken. As far as I can tell it does not appear to have ever worked (looking at our git history for sipjs.com).  It should point to https://sipjs.com/aboutus/ (page needs to be updated itself). The other links appear to be ok. We can fix this in the next release.

**Comment by egreenmachine** [comment]
I forgot to update this on 0.8.0. I will try and get this resolved for our next release. Hopefully it won't be too far out. It is really not all that critical.
