### ISSUE TITLE
Failing to establish early media should use `terminate()`

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#396]
We recently faced the issue of the rtcpMuxPolicy on an old version of SIP.js. Our SIP stack is [patched](https://github.com/onsip/SIP.js/issues/211#issuecomment-132993517) to allow non rel-100 early media. Although I know that you won't support non 100rel early media, I believe this issue still applys to SIP.js.

All the following is in the case of a  ClientContext Session.

In this old setup, the rtcpMuxPolicy setting was causing the `setDescription().catch()` handler to be invoked with Chrome 57. The implementation of this catch handler was initially based on the [100rel implementation of SIP.js](https://github.com/onsip/SIP.js/blob/1245245051b86be7e908d4913d149d35abf437c7/src/Session.js#L1894) (I updated the snippet from #211 to reflect what I believe is the correct behaviour).

This catch handler used to do the following (to mimic [100rel behaviour](https://github.com/onsip/SIP.js/blob/1245245051b86be7e908d4913d149d35abf437c7/src/Session.js#L1921)):
```js
this.logger.warn(reason);
this.acceptAndTerminate(response, 488, 'Bad Media Description');
this.failed(response, SIP.C.causes.BAD_MEDIA_DESCRIPTION);
```
The result of making a call with this setup generats the follwoing sequence ([full log](http://pastebin.com/LrdJX1FL)):
- sending INVITE
- received TRYING
- received RINGING
- received PROGRESS
  - `setDescription()` catcher
    - `acceptAndTerminate()`
      - sending ACK
      - sending BYE
- receiving 200 OK
  - **'accepted' emitted!!!**

As you can see, the latest 200 OK message is not interpretted correctly by SIP.js which thinks the call was answered.

This is an issue because the call does not exist on the communication server anymore (due to the BYE). The same should apply with a 100rel.

I believe that the use of `acceptAndTerminate` is not correct here. Even the use of the word `accept` does not make sence in a *client* context. Shouldn't `terminate()` be used instead ?

**Comment by egreenmachine** [comment]
I vaguely remember looking at that code in recent history and saying that `acceptAndTerminate` is not great there, but we do not have any better options at the moment. My initial thought on this would be to check that a session is still active before emitting `accepted`. That would essentially fix your current issue, without having to figure out what to do instead of `acceptAndTerminate`.

**Comment by matthieusieben** [comment]
Note that our "[monkey patch](https://github.com/onsip/SIP.js/issues/211#issuecomment-132993517)" to support early media in non rel100 setup works great.

The use of `terminate` instead of `acceptAndTerminate` is mandatory in that code as some session instances end-up being stalled in an unrecoverable state when using `acceptAndTerminate`.

My point is, maybe `terminate` is not ideal but it is better than `acceptAndTerminate` since it destroys the session (and sends a 4xx message to the server).

**Comment by matthieusieben** [comment]
Note also that the 200 is a response to the BYE, and not a message indicating that the call was answered (see the full log).

**Comment by john-e-riordan** [comment]
The new API should allows for non rel100 early media by setting the `InviterOptions.earlyMedia` option to `true`. The new API code should not have this issue.

**Comment by james-criscuolo** [comment]
Closing as 0.16.0 only has the new API, which does not have the issue.

**Comment by m-yunus** [comment]
CAN I GET THE COMPLETE CODE
