### ISSUE TITLE
sipsjs is sending two 200 OK

### ISSUE THREAD

**Issue by andrewvmail** [onsip/SIP.js#398]
Im seeing some weird behaviour recently sipjs 
sipjs is sending two 200 okay not sure why.
Anyone got any ideas?
The first 200 OK have Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
But the second one is without that. 

<img width="1157" alt="developer_tools_-_file____android_asset_www_index_html_and_inspect_with_chrome_developer_tools" src="https://cloud.githubusercontent.com/assets/2431354/24285291/b84f35de-102c-11e7-9d03-2ed3e8fae667.png">

**Comment by james-criscuolo** [comment]
Hi @andrewvmail,

You're picture doesn't show times, but my guess is the 2nd 200 OK is a retransmission because you have not received the ACK yet. This is a standard RFC 3261 behavior. I'm not entirely sure about the absence of the allow header, but I don't believe the 200 OK being sent is incorrect.

**Comment by andrewvmail** [comment]
Hi @james-criscuolo do you know if we can change that value of when to retransmit if ack is not seen?
The picture don't show but those 2 200OK happens in the milli second range of each other.

**Comment by etamme** [comment]
The timers are controlled by the general SIP timers.  

https://github.com/onsip/SIP.js/blob/6ceb4ede59a4c4da4605484b255376446435b483/src/Timers.js

In general these are set per RFC recommendations, and you should not change them unless you have a very specific need to do so.

**Comment by james-criscuolo** [comment]
We would likely not accept a PR to do something that is non-standard, unless there was a very good reason to take it. I suggest fixing your SIP Server to be SIP-compliant, as this will not be the only problem you run into otherwise.

**Comment by james-criscuolo** [comment]
In terms of the allow header, the regular INVITE adds that header here](https://github.com/onsip/SIP.js/blob/1245245051b86be7e908d4913d149d35abf437c7/src/Session.js#L611). It's possible retransmissions ignore extraHeaders entirely, which may be a hint as to how to get to the bottom of this.

**Comment by andrewvmail** [comment]
@james-criscuolo thanks cool. One more thing. is it possible to intercept the invite just before its sent out and remove that header entirely? that way i dont have to hack in sip.js library.

**Comment by james-criscuolo** [comment]
The PR would be to add that header, not remove it, as we are likely out of standard by not having it (although I haven't checked).

I'm not sure about removing the header, you can probably send it empty by altering `SIP.UA.C.ALLOWED_METHODS.toString()` to return blank.

**Comment by andrewvmail** [comment]
@james-criscuolo cool thanks! closing issue
