### ISSUE TITLE
http://sipjs.com/ site is down

### ISSUE THREAD

**Issue by SinghSukhdeep** [onsip/SIP.js#400]
![sipjs](https://cloud.githubusercontent.com/assets/3210920/24674837/fb39f330-194a-11e7-8514-639bef0fce68.PNG)

**Comment by egreenmachine** [comment]
We are aware and are looking into it. Sorry for the inconvenience.

**Comment by SinghSukhdeep** [comment]
ok thanks

**Comment by egreenmachine** [comment]
Gitlab which we use for hosting changed their ip address. We have updated our DNS records for sipjs.com and the site should be back online shortly. Thanks!
