### ISSUE TITLE
Configurable UA.stop() on page unload

### ISSUE THREAD

**Issue by VicNumber21** [onsip/SIP.js#401]
I'd like to ask to make UA.stop() on 'unload' event to be configurable.
I think, most of users need the current behavior but I need UA.stop() not to be called to be able to recover call after page refresh.
If you are ok with making it configurable, I can implement it myself and create pull request for you.

To be more clear, I'm about the following piece of code in UA.js
```
  if (typeof environment.addEventListener === 'function') {
    // Google Chrome Packaged Apps don't allow 'unload' listeners:
    // unload is not available in packaged apps
    if (!(global.chrome && global.chrome.app && global.chrome.app.runtime)) {
      this.environListener = this.stop.bind(this);
      environment.addEventListener('unload', this.environListener);
    }
  }
```

I'd like to have it like the following:
```
  if (this.configuration.autostop && typeof environment.addEventListener === 'function') {
    // Google Chrome Packaged Apps don't allow 'unload' listeners:
    // unload is not available in packaged apps
    if (!(global.chrome && global.chrome.app && global.chrome.app.runtime)) {
      this.environListener = this.stop.bind(this);
      environment.addEventListener('unload', this.environListener);
    }
  }
```

Default value of 'autostop' could be true.

**Comment by egreenmachine** [comment]
We would definitely take a pull request for this. I would like to maintain backwards compatibility, so the default would be to autostop. Thanks!

**Comment by VicNumber21** [comment]
Please look at this change.

**Comment by VicNumber21** [comment]
Solved now, thanks a lot!
