### ISSUE TITLE
Is there a way to provide a set of defaultHeaders to SIP.JS UA instance via configuration?

### ISSUE THREAD

**Issue by kirill-konshin** [onsip/SIP.js#404]
Is there a way to provide a set of defaultHeaders to SIP.JS UA instance via configuration so that any request will always have them?

Something like:

```js
new SIP.UA({
    defaultHeaders: [...]
})
```

**Comment by james-criscuolo** [comment]
There is nothing that works quite as you mention, but you can pass a 'custom' object like:

```
new SIP.UA({
    custom: {
      defaultHeaders: [...]
    }
})
```

that will at least keep the headers tied to the UA and accessible through the configuration object. You'd still have to add the extraHeaders to every call, but you can keep the headers with the UA object.

**Comment by kirill-konshin** [comment]
I ended up adding things directly to `SIP.UA` instance because it's available everywhere. Can you please explain more about custom config? I `console.log`-ed everything from `SIP.UA`'s `configuration` property, but `custom` was not there.

**Comment by james-criscuolo** [comment]
I'm going to close this as it's now in a tagged release, 0.8.0.
