### ISSUE TITLE
Do not render audio before call is accepted

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#406]
When receiving an incoming call, the incoming stream should not be attached to the remote renderer before the call is accepted. This is particularly true when early media is established.

**Comment by matthieusieben** [comment]
My current workaround (only works if #407 is used too)

```js

session.progress = function (options) {
  options = Object.create(Session.desugar(options))

  Utils.optionsOverride(options, 'media', 'mediaConstraints', true, this.logger, this.ua.configuration.media)
  this.mediaHint = options.media

  // @hack: https://github.com/onsip/SIP.js/issues/406
  //
  // In case of success of the getDescription() method, the mediaHandler will
  // call `self.render()`. This means thar as soon as early media is
  // established, the remote media will start rendering on incoming sessions.
  // If the remote phone sends early media before the call was accepted, then
  // the callee will be able to hear the caller before he answered the call.
  // In order to prevent this, lets save the remote renderer, and set it back
  // later on, when the call is accepted.
  if (this.status !== Session.C.STATUS_CONFIRMED) {
    const remote = this.mediaHint.render && this.mediaHint.render.remote
    if (remote) {
      this.mediaHint.render.remote = null
      this.on('accepted', function () {
        if (!this.mediaHint.render.remote) {
          this.mediaHint.render.remote = remote
          this.mediaHandler.render()
        }
      })
    }
  }

  return InviteServerContext.prototype.progress.call(this, options)
}
```

**Comment by matthieusieben** [comment]
Note that this was an issue with Polycom phones sending voice instead of ringback through early media.

**Comment by egreenmachine** [comment]
Between this and #407 it seems like you want to do early media, but not render it until the call is accepted, correct?

**Comment by matthieusieben** [comment]
Indeed. And conceptually, it does seem strange to connect the renderer and the incoming stream before one accepted the call, doesn't it?

**Comment by egreenmachine** [comment]
Not necessarily. For calls to the PSTN for example, you may want to hear the ringback or early media. There are instances where error messages about lines being disconnected will not ever accept the call and will be done only via early media.

I think what you want to do is possible here. I have to review the media handling code.

**Comment by matthieusieben** [comment]
Note that i do wish to ear incoming media before they are accepted for *outgoing* calls, not for *incoming* calls.

**Comment by egreenmachine** [comment]
We believe that this issue may be resolved in the latest tagged version [0.8.0](https://github.com/onsip/SIP.js/releases/tag/0.8.0). Can you please retest with that version and let us know if this is still an issue. We will close this issue on 11/1/17 if we do not hear back. Thanks.

**Comment by matthieusieben** [comment]
Sadly, I no longer work for the same company and will not be able to check.

You should however be able to simulate the behaviour described here by reasoning on your new code.

Closing issues because you assume that your refactor fixed them all is a mistake that may affect the quality of your product in my opinion.

**Comment by egreenmachine** [comment]
This was not simply a refactor. The rendering of media is no longer handled by SIP.js but instead the client application. You cannot render media within SIP.js. Due to that, I cannot see how this issue would be relevant in 0.8.0. I am going to close this.
