### ISSUE TITLE
accept() will override progress()'s mediaHints

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#407]
On an incoming call (ServerContext) if you perform a `progress({ media: { render: { ... } } })`, the media option will be saved in `this.mediaHints`. If you then perform an `accept(null)`, the `session.mediaHints` will be overwritten with the configuration default, meaning that the mediaHints do not represent the actual hints requested by the user.

There may even be a race condition where the session is accepted after the call to progress, but before the async resolve handler of `mediaHandler.setDescritpion()`. In that case, the render media provided through the progress options will not be used at all.

**Comment by matthieusieben** [comment]
My current hack is as follows:
```js
session.accept =  function accept (options) {
  if (this.mediaHint && !isMediaElement(options)) {
    options = options || {}
    options.media = options.media || this.mediaHint
  }
  return InviteServerContext.prototype.accept.call(this, options)
}
```

**Comment by egreenmachine** [comment]
We believe that this issue may be resolved in the latest tagged version [0.8.0](https://github.com/onsip/SIP.js/releases/tag/0.8.0). Can you please retest with that version and let us know if this is still an issue. We will close this issue on 11/1/17 if we do not hear back. Thanks.

**Comment by matthieusieben** [comment]
Sadly, I no longer work for the same company and will not be able to check.

You should however be able to simulate the behaviour described here by reasoning on your new code.

Closing issues because you assume that your refactor fixed them all is a mistake that may affect the quality of your product in my opinion.

**Comment by egreenmachine** [comment]
The code was not simply refactored, but the media handling was completely re-written. I have tested this case pretty extensively, and this was simply a request for you to test your application to make sure I did not miss your specific case.

**Comment by james-criscuolo** [comment]
For further reference, all of the issues that were given the above ('please test or we will close') were in a similar boat, where  they were specifically posted on because they were directly addressed by the changes and tested. As @egreenmachine, this is more of a confirmation. We did not put this message on all of our issues, just the ones directly affected/tested.

**Comment by matthieusieben** [comment]
Alright, sorry if my comment was a little rude ;-)
