### ISSUE TITLE
send message timeout if via host include port

### ISSUE THREAD

**Issue by embbnux** [onsip/SIP.js#408]
Hi,
I send message using ua.message, but I get timeout error.
sipjs report: 'sip.sanitycheck | Via sent-by in the response does not match UA Via host value. Dropping the response'.
To resolve this error, I have to remove [the port from via host](https://github.com/ringcentral/ringcentral-web-phone/pull/121/files#diff-500f74e1a2a332c4bb6b99fc1dfb7c88R258).
Are there any suggestions to resolve this.
Thanks for help.

**Comment by egreenmachine** [comment]
https://tools.ietf.org/html/rfc3261#section-8.2.6.2 states that the via in the response must match the via in the request exactly. I think that SIP.js is doing the correct thing here.
