### ISSUE TITLE
setLocalDescriptionOnFailure in Chrome > 55

### ISSUE THREAD

**Issue by anshkatriya** [onsip/SIP.js#409]
I am getting this type of error in Chrome version  > 55. 
Scenario: I have dialed any extension from SIP.js I am holding call from SIP.js using FreeSWITCH command (uuid_hold UUID_OF_SIPJS_CALL) in the backend. Automatically, the call is being disconnected and I am getting below error in console log & also in chrome://webrtc-internals/ logs.

setLocalDescriptionOnFailure
Failed to set local answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set local audio description recv parameters.

**Comment by egreenmachine** [comment]
Can you include the SDP that you getting from FreeSWITCH?

**Comment by anshkatriya** [comment]
Hi, 
I am getting this SDP while hold.

type: answer, sdp: v=0
o=- 7887285094089519477 3 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS TSIf09y3b3DznDMyXySgZmwXQ4LzD6Ikt7cg
m=audio 49957 RTP/SAVPF 0 110
c=IN IP4 27.109.20.18
a=rtcp:48747 IN IP4 27.109.20.18
a=candidate:2208343791 1 udp 2122260223 192.168.3.53 40282 typ host generation 0 network-id 1
a=candidate:2719416092 1 udp 2122194687 10.42.0.1 49957 typ host generation 0 network-id 2 network-cost 10
a=candidate:2208343791 2 udp 2122260222 192.168.3.53 48747 typ host generation 0 network-id 1
a=candidate:2719416092 2 udp 2122194686 10.42.0.1 44303 typ host generation 0 network-id 2 network-cost 10
a=candidate:3441646111 1 tcp 1518280447 192.168.3.53 9 typ host tcptype active generation 0 network-id 1
a=candidate:3969188844 1 tcp 1518214911 10.42.0.1 9 typ host tcptype active generation 0 network-id 2 network-cost 10
a=candidate:3441646111 2 tcp 1518280446 192.168.3.53 9 typ host tcptype active generation 0 network-id 1
a=candidate:3969188844 2 tcp 1518214910 10.42.0.1 9 typ host tcptype active generation 0 network-id 2 network-cost 10
a=candidate:1974525755 2 udp 1686052606 27.109.20.18 48747 typ srflx raddr 192.168.3.53 rport 48747 generation 0 network-id 1
a=candidate:3768254868 2 udp 1685987070 27.109.20.18 44303 typ srflx raddr 10.42.0.1 rport 44303 generation 0 network-id 2 network-cost 10
a=candidate:3768254868 1 udp 1685987071 27.109.20.18 49957 typ srflx raddr 10.42.0.1 rport 49957 generation 0 network-id 2 network-cost 10
a=candidate:1974525755 1 udp 1686052607 27.109.20.18 40282 typ srflx raddr 192.168.3.53 rport 40282 generation 0 network-id 1
a=ice-ufrag:vB1R
a=ice-pwd:nJP8o0mO7Num6fxXhunnnUvz
a=fingerprint:sha-256 30:EB:74:99:F1:82:2F:80:F6:12:30:19:C7:2D:53:D7:9A:48:09:7C:10:A4:96:A0:7B:C8:53:54:08:62:6C:E7
a=setup:passive
a=mid:audio
a=recvonly
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtpmap:110 telephone-event/8000
a=ssrc:3812234735 cname:Xj6ERnpaDOhAQEDU
a=ssrc:3812234735 msid:TSIf09y3b3DznDMyXySgZmwXQ4LzD6Ikt7cg 224128b4-9b67-4570-927f-64c32ef24f03
a=ssrc:3812234735 mslabel:TSIf09y3b3DznDMyXySgZmwXQ4LzD6Ikt7cg
a=ssrc:3812234735 label:224128b4-9b67-4570-927f-64c32ef24f03

One more thing that this issue doesn't happens with FreeSWITCH Version 1.6.*. I am talking about FreeSWITCH 1.4.26 version.

Thanks.

**Comment by egreenmachine** [comment]
This is definitely going to be an issue with the SDP that Freeswitch is generating. We do not support Freeswitch 1.4.x. If you could follow up with Freeswitch on this, they might be able to help you.

**Comment by anshkatriya** [comment]
Hello @egreenmachine ,
Thanks for your reply. I have applied necessary changes in SIP.js source to solve this issue. It's working for me after changes.

**Comment by egreenmachine** [comment]
Just curious, what changes did you apply to SIP.js to get this to work?
