### ISSUE TITLE
accepted when rejected

### ISSUE THREAD

**Issue by salkat** [onsip/SIP.js#41]
I'm doing outgoing call. When destination side press 'reject' I recieve event 'accepted' with data.code '200'

**Comment by atukilham** [comment]
Same problem here.
I use asterisk 13.
i make call via softphone, it's all normal, no problem with asterisk.
when i try via webrtc with SIPjs, and i try make outgoing call from browser to my phone, then ty to rejected from my phone, in browser received event accepted.
Help me please..
(sorry fo my bad english)
