### ISSUE TITLE
Can not read header data set by asterisk server after call is answered 

### ISSUE THREAD

**Issue by adeshpandey** [onsip/SIP.js#410]
Hi,
I am using sipjs to make and receive webrtc calls with asterisk but we want to share some custom key between asterisk server and webrtc client when call is initiated or answered. I can send a custom header key from webrtc client to asterisk which is available there but the updated value for the key is not available at webrtc client. Is this not possible or not implemented in SIP.js?

**Comment by AnshumanKumar14** [comment]
Any update on this issue. I am also facing the same issue.

**Comment by james-criscuolo** [comment]
If the information comes back to in a header (you'd see it in your inspector with traceSip turned on), you'll be able to read it using [some functions on the response](https://sipjs.com/api/0.7.0/sipMessage/#getheadername). If Asterisk is not sending back the information, I'm not sure how SIP.js is expected to gain knowledge of any updates via Asterisk. There is the SUBSCRIBE-NOTIFY mechanism, but that doesn't really sound like your case either.

I'm closing this as I don't see a clear-cut bug or feature request.

**Comment by adeshpandey** [comment]
Hi,
Thanks for your prompt response on the git @james-criscuolo I have traceSip enabled in my request and I am setting a header info when the call is answered but I can not see that header data on the sip **progress** or **accepted** event in my sip.js code. Is there any other workaround?

**Comment by james-criscuolo** [comment]
It sounds like Asterisk is not sending the information back. There is nothing you can do about this client-side.

**Comment by adeshpandey** [comment]
Hi @james-criscuolo ,

Thank you very much for the clarification, but could you please suggest me a way to send data back from asterisk to the client? Thanks once again for your help.

**Comment by james-criscuolo** [comment]
I'm sorry, I can't say I'm too familiar with Asterisk, but I'm sure someone on the Asterisk forums would be helpful here, or potentially in our own google group.

**Comment by adeshpandey** [comment]
Thanks mate for your valuable help,
I will try to get the solution from somewhere else.
