### ISSUE TITLE
[Wishlist] SimpleWebRTC Settings

### ISSUE THREAD

**Issue by adekock11** [onsip/SIP.js#411]
Hi guys. I came across this: https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.js#L11-L36 and wanted to ask if it will be beneficial for the SIP.JS library to either use the SimpleWebRTC library or alternatively also include such settings when getting a media stream.

For example, we sometimes experience microphone problems which can be solved in JS, like Chrome's AGC that completely ignores microphone settings in Windows.

Currently, I don't know of a workaround to set settings such as `googAutoGainControl: false` in SIP.JS (unless I'm wrong).

**Comment by james-criscuolo** [comment]
This should be doable via the [options object to some functions](https://sipjs.com/api/0.7.0/ua/#invitetarget-elementoptions) (the link is for the invite function).

If a setting has a large enough use case to warrant being in the UA config, we'd consider adding it, but generally that is the exception to the rule.

**Comment by adekock11** [comment]
Hi @james-criscuolo. Thanks for the response.

Are you saying that this functionality actually already exists? I simply have to send it through the `options` parameter when for example doing a `UA.invite()`?

I actually thought that it would be at the point where one calls `SIP.WebRTC.getUserMedia()`.

**Comment by james-criscuolo** [comment]
I'm not unsure if this occurs during the RTCPeerConnection creation or while getting the streams (getUserMedia). If it's the former, then my directions are correct. If it's the latter, you can always call getUserMedia yourself, then pass the streams to SIP.js instead of SIP.js doing that legwork.

**Comment by adekock11** [comment]
Great! Thanks @james-criscuolo for the advice.

**Comment by juan-oa** [comment]
To disable Chrome's AGC pass through the following media constraint to getUserMedia
`var mediaConstraints = {
                        audio: {
                          optional: [
                            {googAutoGainControl: false}
                          ]
                        },
                        video: false
                    };
                    SIP.WebRTC.getUserMedia(mediaConstraints, function (stream) {}`
