### ISSUE TITLE
codec negotiation error(use freeswitch and chrome)

### ISSUE THREAD

**Issue by FengZStrong** [onsip/SIP.js#412]
2017-05-04 13:57:57.397234 [ERR] mod_sofia.c:2333 CODEC NEGOTIATION ERROR.  SDP:
v=0
o=- 294869547997164989 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS nv52oSGoqwnhgeTHoD4tHPzeWQhOWJfpJHNW
m=audio 64865 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 192.168.133.92
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=rtcp:64867 IN IP4 192.168.133.92
a=candidate:2522917088 1 udp 2113937151 192.168.133.92 64865 typ host generation 0 network-cost 50
a=candidate:2522917088 2 udp 2113937150 192.168.133.92 64867 typ host generation 0 network-cost 50
a=ice-ufrag:WGW6
a=ice-pwd:DfRdn5IpkFVvGxHFsaqLE6j2
a=fingerprint:sha-256 FC:04:D9:BF:87:26:D9:72:F4:58:DF:C9:8E:B5:30:00:3E:2B:97:8F:8D:B4:A8:A3:BB:8A:69:F7:E8:07:C3:46
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=rtcp-mux
a=rtcp-fb:111 transport-cc
a=ssrc:214618898 cname:keSO1hbdE0TU0yU6
a=ssrc:214618898 msid:nv52oSGoqwnhgeTHoD4tHPzeWQhOWJfpJHNW 783173e4-7c22-4f87-9bd6-479c2b987cd4
a=ssrc:214618898 mslabel:nv52oSGoqwnhgeTHoD4tHPzeWQhOWJfpJHNW
a=ssrc:214618898 label:783173e4-7c22-4f87-9bd6-479c2b987cd4

**Comment by etamme** [comment]
This is almost certainly an issue with your freeswitch configuration.

**Comment by FengZStrong** [comment]
However, sometimes it can run, and sometimes can not run, and did not modify any configuration

**Comment by i5possible** [comment]
We also got the same error. **Sometimes it runs OK, and sometimes the called is called immediately.** The configuration is exactly the same.
