### ISSUE TITLE
Getting streams on NodeJS without WebRTC?

### ISSUE THREAD

**Issue by jamesleeht** [onsip/SIP.js#414]
Is there any way to get the MediaStream on NodeJS, without using WebRTC or any frontend JS?

I want to get an audio stream from a call and send that over to a speech to text API. Is this possible using SIP.js or any other library?

I'm thinking of using the custom mediaHandlerFactory but I'm not sure how to use it to hook it up to a webrtc implementation in Node.

Thanks in advance :)

**Comment by cameron5906** [comment]
@jamesleeht Have you found anything for this? I'm wanting to do something similar and have been looking around for hours.

**Comment by jamesleeht** [comment]
@cameron5906 I ended up using this client library https://github.com/mscdex/sipster

The nodejs wrapper didn't work the best though so I ended up using the python library underneath (pjsip).
