### ISSUE TITLE
I can't listen Asterisk IVR or Playback on Firefox using SIP.JS in other that work correctly on chrome browser

### ISSUE THREAD

**Issue by safallah** [onsip/SIP.js#415]
Hi,
i can't listen Asterisk IVR or Playback on Firefox using SIP.JS in other that work correctly on chrome browser.

this is my configuration:

var config = {
  uri: 'xxxx@xx.com',
  ws_servers: 'wss://xx.com:xxxx/ws',
  authorizationUser: 'xxxx',
  password: 'xxxx',
  hackIpInContact: true,
  traceSip: true,
  stunServers: "stun:xx.com:xxxx"
};

thank you.

**Comment by egreenmachine** [comment]
This is most likely a problem with your Asterisk config. Please follow up with Asterisk on this. Our support of Asterisk extends just to what we cover in the guide. If you follow the guide exactly and there is still an issue we can look into it, but it is working for me currently.
