### ISSUE TITLE
Error parsing header "Contact"

### ISSUE THREAD

**Issue by VadimDez** [onsip/SIP.js#419]
When received `Contact` header on registration looks like this:
```
Contact: <sip:127.0.0.1:443;transport=wss;thinfo="VG8+PoIUYHSD/sWAZZw/BCEaSdGA=">
```
Parser throws an error:
```
Object { message: "Expected "!", "$", "%", "&", "'", "…", expected: Array[18], found: """, offset: 40, line: 1, column: 41, name: "SyntaxError", stack: "" }
```
To prevent  this error - i just removed `"` around `thinfo`'s value in js right before parse() function is called.

Now that i have 
```
Contact: <sip:127.0.0.1:443;transport=wss;thinfo=VG8+PoIUYHSD/sWAZZw/BCEaSdGA=>
```
Second issue arises, with `=` at the end
```
Object { message: "Expected "!", "$", "%", "&", "'", "…", expected: Array[21], found: "=", offset: 68, line: 1, column: 69, name: "SyntaxError", stack: "" }
```

---

Even if the initial received `Contact` header is without `=` at the end but has `"` around `thinfo`'s value, that are later removed before parsing by me.
```
Contact: <sip:127.0.0.1:443;transport=wss;thinfo="VG8+PoIUYHSD/sWAZZw/BCEaSdGA">
```
Log output is:
```
sip.registercontext | no Contact header pointing to us, response ignored
```

**Comment by egreenmachine** [comment]
Based on my reading of the BNF for the `Contact` header in the [SIP RFC](https://www.ietf.org/rfc/rfc3261.txt), I believe that our parser is correct here. The quotes and trailing equal sign are not valid.

**Comment by etamme** [comment]
For what it is worth - you can try enabling the dialog module on your opensips proxy. This will allow the dialog tracking to keep track of what needs to happen for topology hiding, instead of appending the contact parameter "tokens" for topology hiding.

I've mentioned it to the opensips team, but it also might be worth it if you brought it up to them.
