### ISSUE TITLE
Audio only 

### ISSUE THREAD

**Issue by murugancmi** [onsip/SIP.js#422]
How i make audio only call, When call my media constrains {audio: true ,video: false} but still i can see video codec v8 and V9 in freeswitch console

**Comment by james-criscuolo** [comment]
Please check our [making a call guide](https://sipjs.com/guides/make-call/).

For questions like this in the future, please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js). We try to keep this space for bugs and feature requests, instead of general questions.

**Comment by murugancmi** [comment]
i aleady did this  var options = {
        media: {
            constraints: {
                audio: true,
                video: true
            }
                   }
    };

session = userAgent.invite('sip:welcome@onsip.com', options);
but still i can see V8 and V9 in freeswitch

**Comment by james-criscuolo** [comment]
The video should be false? I would also recommend trying on the demo-phone: https://sipjs.com/demo-phone/

**Comment by murugancmi** [comment]
But i did this react-native-webrtc yes vide is false
