### ISSUE TITLE
Failed to set remote offer sdp.

### ISSUE THREAD

**Issue by Juli0GT** [onsip/SIP.js#423]
Hi, I'm using sip.js in a Vue.js project. Until Monday I was able to receive calls but I've tried it today and I'm getting those errors: 

`
Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.transport | received WebSocket text message:

INVITE sip:7o73mon0@nqr05hjgj96p.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 141.0.208.122:443;branch=z9hG4bK9484.920f7bb7.3
Max-Forwards: 24
From: "07490758661" <sip:07490758661@*******.callwise.net>;tag=63jDpm2HeSHaD
To: <sip:2022@141.0.208.122:5060>
Call-ID: 91c4339f-c632-1235-83bd-00259047caf4
CSeq: 108087252 INVITE
Contact: <sip:141.0.208.122:443;transport=wss;did=c38.815fb223>
User-Agent: FreeSWITCH-mod_sofia/1.4.21-35~64bit
Supported: timer, path, replaces
Privacy: none
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 272
X-Origin: mobile
P-Asserted-Identity: "07490758661" <sip:07490758661@*********.callwise.net>
Allow: INVITE, ACK, BYE, CANCEL

v=0
o=FreeSWITCH 1496822871 1496822872 IN IP4 141.0.208.117
s=FreeSWITCH
c=IN IP4 141.0.208.117
t=0 0
m=audio 23762 RTP/AVP 8 0 3 101 13
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:3 GSM/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20

sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.transport | sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 141.0.208.122:443;branch=z9hG4bK9484.920f7bb7.3
To: <sip:2022@141.0.208.122:5060>
From: "07490758661" <sip:07490758661@*********.callwise.net>;tag=63jDpm2HeSHaD
Call-ID: 91c4339f-c632-1235-83bd-00259047caf4
CSeq: 108087252 INVITE
Supported: outbound
User-Agent: SIP.js/0.7.7
Content-Length: 0

sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.dialog | new UAS dialog created with status EARLY
sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.transport | received WebSocket text message:

INVITE sip:1o5utnbk@3a0q6ffgljvn.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 141.0.208.122:443;branch=z9hG4bK9484.920f7bb7.4
Max-Forwards: 24
From: "07490758661" <sip:07490758661@********.callwise.net>;tag=63jDpm2HeSHaD
To: <sip:2022@141.0.208.122:5060>
Call-ID: 91c4339f-c632-1235-83bd-00259047caf4
CSeq: 108087252 INVITE
Contact: <sip:141.0.208.122:443;transport=wss;did=c38.815fb223>
User-Agent: FreeSWITCH-mod_sofia/1.4.21-35~64bit
Supported: timer, path, replaces
Privacy: none
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 272
X-Origin: mobile
P-Asserted-Identity: "07490758661" <sip:07490758661@********.callwise.net>
Allow: INVITE, ACK, BYE, CANCEL

v=0
o=FreeSWITCH 1496822871 1496822872 IN IP4 141.0.208.117
s=FreeSWITCH
c=IN IP4 141.0.208.117
t=0 0
m=audio 23762 RTP/AVP 8 0 3 101 13
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:3 GSM/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20

sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.transport | sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 141.0.208.122:443;branch=z9hG4bK9484.920f7bb7.4
To: <sip:2022@141.0.208.122:5060>
From: "07490758661" <sip:07490758661@**********.callwise.net>;tag=63jDpm2HeSHaD
Call-ID: 91c4339f-c632-1235-83bd-00259047caf4
CSeq: 108087252 INVITE
Supported: outbound
User-Agent: SIP.js/0.7.7
Content-Length: 0

**sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.dialog | new UAS dialog created with status EARLY
sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.inviteservercontext | invalid description**
LoggerFactory.print @ sip-0.7.7.js:2900
LoggerFactory.(anonymous function) @ sip-0.7.7.js:2917
Logger.(anonymous function) @ sip-0.7.7.js:2911
onFailure @ sip-0.7.7.js:5800
sip-0.7.7.js:2900 DOMException: Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.
LoggerFactory.print @ sip-0.7.7.js:2900
LoggerFactory.(anonymous function) @ sip-0.7.7.js:2917
Logger.(anonymous function) @ sip-0.7.7.js:2911
onFailure @ sip-0.7.7.js:5801
sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.transport | sending WebSocket message:

SIP/2.0 488 Not Acceptable Here
Via: SIP/2.0/WSS 141.0.208.122:443;branch=z9hG4bK9484.920f7bb7.3
To: <sip:2022@141.0.208.122:5060>;tag=b35e916mmc
From: "07490758661" <sip:07490758661@******.callwise.net>;tag=63jDpm2HeSHaD
Call-ID: 91c4339f-c632-1235-83bd-00259047caf4
CSeq: 108087252 INVITE
Supported: outbound
User-Agent: SIP.js/0.7.7
Content-Length: 0

**sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.inviteservercontext | invalid description**
LoggerFactory.print @ sip-0.7.7.js:2900
LoggerFactory.(anonymous function) @ sip-0.7.7.js:2917
Logger.(anonymous function) @ sip-0.7.7.js:2911
onFailure @ sip-0.7.7.js:5800
**sip-0.7.7.js:2900 DOMException: Failed to set remote offer sdp: Called with SDP without DTLS fingerprint.**
LoggerFactory.print @ sip-0.7.7.js:2900
LoggerFactory.(anonymous function) @ sip-0.7.7.js:2917
Logger.(anonymous function) @ sip-0.7.7.js:2911
onFailure @ sip-0.7.7.js:5801
sip-0.7.7.js:2900 Wed Jun 07 2017 15:43:53 GMT+0100 (BST) | sip.transport | sending WebSocket message:

**SIP/2.0 488 Not Acceptable Here**
Via: SIP/2.0/WSS 141.0.208.122:443;branch=z9hG4bK9484.920f7bb7.4
To: <sip:2022@141.0.208.122:5060>;tag=c802hm9mee
From: "07490758661" <sip:07490758661@***************>;tag=63jDpm2HeSHaD
Call-ID: 91c4339f-c632-1235-83bd-00259047caf4
CSeq: 108087252 INVITE
Supported: outbound
User-Agent: SIP.js/0.7.7
Content-Length: `

I used to have in my configuration rtcpMuxPolicy: 'authorise' but now it complaints unless I use rtcpMuxPolicy: 'require'.

I'm pretty new in RTCP and SIP technologies, would appreciate any help.

Bests,

**Comment by egreenmachine** [comment]
Please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js) for questions like this. We like to use the issue page for bugs and feature requests.

This is an issue with your FreeSWITCH instance not sending DTLS to SIP.js. Follow our [FreeSWITCH Guide](https://sipjs.com/guides/server-configuration/freeswitch/) and if you are still having trouble, you would have to follow up with FreeSWITCH.
