### ISSUE TITLE
There is no ringing horn (long and short) for an outgoing call.

### ISSUE THREAD

**Issue by Wolfaks** [onsip/SIP.js#424]
Hello. There is no ringing horn (long and short) for an outgoing call. 

I need to add a short beep for an outgoing call before the person will pick up the phone. and a fast beep if the caller is busy. How can I do that? I make a phone call like this:
`session = userAgent.invite('sip:' + number + '@mylink', options);`

Thanks you.

**Comment by james-criscuolo** [comment]
Hi @Wolfaks,
  This is something you'd do within your application code. There are several different ways to play audio via a web browser, from audio elements to the WebAudio API. The code to play would occur under that line, and the code to stop would likely occur in your `accepted` and `terminated` listeners.

  In the future, please try to keep questions like this to our [Google Group](https://groups.google.com/forum/#!forum/sip_js). We try to keep this space for feature requests and bugs.

Thanks,
James

**Comment by Wolfaks** [comment]
Help please, how can I get an event when the call is picked up of Interlocutor from my code? Please also tell me the method that will help me to finish the call. Thank you.

**Comment by james-criscuolo** [comment]
Please use [our guides](http://sipjs.com/guides/) to get basic use cases set up.

**Comment by Wolfaks** [comment]
I watched this section, but did not find it. Perhaps because I do not understand English well. Tell me please or give exact references, thanks.

**Comment by Wolfaks** [comment]
How to get the status of the call? When the handset was taken or when the handset is busy? There are no examples in the documentation! Thank you.
