### ISSUE TITLE
Microphone/audio permission issues when initiating call

### ISSUE THREAD

**Issue by vyshakhbabji** [onsip/SIP.js#427]
When receiving an incoming call or initiating an outgoing call, before audio stream is attached, the library should check if the microphone and speaker permissions are allowed for the browser. Currently, this check is not done by sipjs even before early media is established. This leads to call failures.

**Comment by egreenmachine** [comment]
Could you elaborate what you mean by this? SIP.js should throw a catchable error if it is unable to to do a `getusermedia` due to permission issue. I will make sure that this is also written into #426.

**Comment by egreenmachine** [comment]
I think that this is resolved in 0.9.X. We emit a `userMediaFailed` event if we are unable to get the user media. Can you confirm that you are still having issues? If we do not hear back from you on this by 3/15 we will consider it resolved, as we believe we have covered this case. Thanks.

**Comment by egreenmachine** [comment]
Closing due to the fact that we believe that this issue is resolved and have not heard back from the original reporter on it.
