### ISSUE TITLE
Set custom username in Contact's user part

### ISSUE THREAD

**Issue by VadimDez** [onsip/SIP.js#428]
Would it be possible to add option to send `settings.authorizationUser` instead of `SIP.Utils.createRandomToken()` in `Contact` ?

instead of
```js
...
uri: new SIP.URI('sip', SIP.Utils.createRandomToken(8), settings.viaHost, null, {transport: settings.contactTransport}),
...
```
to have this

```js
...
uri: new SIP.URI('sip', settings.authorizationUser, settings.viaHost, null, {transport: settings.contactTransport}),
...
```

With settings option:

```js
const user = settings.addRandomUser ? SIP.Utils.createRandomToken(8) : settings.authorizationUser;
...
uri: new SIP.URI('sip', user, settings.viaHost, null, {transport: settings.contactTransport}),
...
```

**Comment by egreenmachine** [comment]
I think that this would be alright. You would have to submit a pull request for it. I would say to have the option just take any string and use that as the contact uri if present. The default behavior should be to do what we are currently doing.
