### ISSUE TITLE
Electron/NW.js implementations

### ISSUE THREAD

**Issue by rainmak33r** [onsip/SIP.js#431]
When I'm trying to implement SIP.js + Angular in Electron, when I start to call I keep getting the error:
`[audio_send_stream.cc(90)] Failed to set up send codec state.` 
and when I try the same in NW.js I get one way audio for some reason. Does anybody has any examples on the matter?

**Comment by james-criscuolo** [comment]
Hi @rainmak33r,
  I believe you are just re-posting from the mailing list, I'd prefer if we keep this discussion there.

In terms of demos, we (OnSIP) are quite close to releasing our desktop app, which uses SIP.js with angular and electron with no changes to SIP.js necessary. Once its out, it should serve as an example, but I do promise, nothing is different.

**Comment by rainmak33r** [comment]
I'm not on a mailling list, sorry. I'm using it in my own app.

**Comment by james-criscuolo** [comment]
Here's the link, its just a google group: https://groups.google.com/forum/#!topic/sip_js/y7GExO5SEsE

**Comment by rainmak33r** [comment]
ah, well I didn't get a response there. 

Sorry.
