### ISSUE TITLE
Is there a way to PUBLISH RTCP-XR SIP message to the backend via SIP.JS UA instance?

### ISSUE THREAD

**Issue by vyshakhbabji** [onsip/SIP.js#433]
Sip JS UA currently allows only following methods   

ALLOWED_METHODS: [
      'ACK',
      'CANCEL',
      'INVITE',
      'MESSAGE',
      'BYE',
      'OPTIONS',
      'INFO',
      'NOTIFY',
      'REFER'
    ]

To collect QoS data via RTCP/XR (https://tools.ietf.org/html/rfc3611)  we need a way to SIP PUBLISH (https://www.ietf.org/rfc/rfc3903.txt) to the backend server.  Currently, i don't see a way to achieve this via sipjs. Could you please provide me information on how to do this using sipJS. If it isn't possible to include this in sipjs,  could you provide me insights on how to achieve my usecase ?

**Comment by egreenmachine** [comment]
It sounds like you are trying to collect RTCP data locally in the browser, then get it to your server. You could do this out of band via xhr request or similar. SIP.js currently does not support RFC3903, but we would take a PR adding the functionality.

**Comment by egreenmachine** [comment]
SIP.js now supports `PUBLISH` https://github.com/onsip/SIP.js/pull/551. Building in this specific functionality to SIP.js is out of scope, but all the pieces are in place that you could do it yourself. I am going to tag this as a `wontfix` and close, but if you have any further questions feel free to follow up here.
