### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by liberatomota** [onsip/SIP.js#437]
Hello,

I'm trying to make a test app using the demo-phone code. Running in Meteor js framework.

When the app tries to connect to the wsServers this is the response:
```
Refused to set unsafe header "sec-websocket-version"
Refused to set unsafe header "sec-websocket-key"
Refused to set unsafe header "sec-websocket-protocol"
Refused to set unsafe header "sec-websocket-extensions"
ERR_NAME_NOT_RESOLVED
XMLHttpRequest cannot load https://edge.sip.onsip.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://xxxxxxxxxxxl' is therefore not allowed access. 
```

Tried to insert costum headers but to no success
```
var config = {
    userAgentString: 'SIP.js/0.7.0 BB',
    traceSip: true,
    register: false,
    custom: {
      defaultHeaders: [["Access-Control-Allow-Origin", "*"],
        ["Access-Control-Allow-Headers": "https://edge.sip.onsip.com/"],
        ["Access-Control-Allow-Methods": "PUT, GET, POST, DELETE, OPTIONS"],
        ["Upgrade","WebSocket"],
        ["Upgrade","Connection"]
    ]
    }
  };
```

Runned the app in http and https (with ngnix), in chrome and firefox. Always fail to connect, but when I made the connection and registration code from server side and it worked and I was able to register a user.

When using the [jsfiddle example](https://jsfiddle.net/OnSIP/xv00uLur/) the browser accepts the connection. 
So, the browser doesn't let me make the connection but just on my app. The Meteor framework runs in node.js so nothing exoctic... 

Can you give some guides to debug and find a solution to this problem?

Thanks in advance

**Comment by james-criscuolo** [comment]
Nothing within SIP.js uses XHRs, so it seems like you are likely putting the value elsewhere. Meteor may intercept these types of things, I am unfamiliar with it.

**Comment by liberatomota** [comment]
Thank for the reply,
I was unable to get pass this problem so I put the code on a React test app... it worked.
The problem is framework specific, doesn't have nothing to do with Sip.js. Closing
