### ISSUE TITLE
Sip.js on WebView Android 6.0 or less is not working

### ISSUE THREAD

**Issue by bitsngeeks** [onsip/SIP.js#438]
I've built an app with a WebView (HTML page) and Sip.js (JS file). But when I try to invoke the method invite() from a device (Android 5.0) to another Device (Android 5.0) its not working. In fact, when I tried to invoke the invite() method from a device (Android 6.0) to another device (Android 6.0) the method is working fine. 
Here is the log of the first case:

`08-01 16:10:59.122 17523-17523/com.shopzeely.partner D/MediaPlayer: handleMessage msg:(6, 0, 0)
08-01 16:10:59.695 17523-17735/com.shopzeely.partner D/OpenGLRenderer: Flushing caches (mode 0)
08-01 16:10:59.696 17523-17735/com.shopzeely.partner D/Surface: Surface::disconnect(this=0x7f6de89200,api=1)
08-01 16:10:59.696 17523-17735/com.shopzeely.partner D/GraphicBuffer: unregister, handle(0x7f358527a0) (w:811 h:400 s:816 f:0x1 u:0x000b00)
08-01 16:10:59.696 17523-17735/com.shopzeely.partner D/GraphicBuffer: unregister, handle(0x7f5c9eb240) (w:811 h:400 s:816 f:0x1 u:0x000b00)
08-01 16:10:59.696 17523-17735/com.shopzeely.partner D/GraphicBuffer: unregister, handle(0x7f3589d700) (w:811 h:400 s:816 f:0x1 u:0x000b00)
08-01 16:10:59.698 17523-17735/com.shopzeely.partner D/OpenGLRenderer: Flushing caches (mode 0)
08-01 16:10:59.709 17523-17523/com.shopzeely.partner D/Dialog: dismissDialog
08-01 16:10:59.709 17523-17523/com.shopzeely.partner D/MediaPlayer: [HSM] MediaPlayer stop() uid: 10336, pid: 17523
08-01 16:10:59.711 17523-17523/com.shopzeely.partner D/AbsListView: onWindowFocusChanged: hasWindowFocus=true, this=android.widget.ListView{2bfcfb88 IFED.VC. ......ID -600,0-0,1134 #7f0d01b0 app:id/left_drawer}
08-01 16:10:59.711 17523-17523/com.shopzeely.partner V/InputMethodManager: onWindowFocus: android.webkit.WebView{9ae2735 VFEDHVC. .F...... 0,664-720,1134 #7f0d01e6 app:id/w_test} softInputMode=16 first=false flags=#81810100
08-01 16:10:59.714 17523-17523/com.shopzeely.partner D/MediaPlayer: handleMessage msg:(8, 0, 0)
08-01 16:10:59.723 17523-17523/com.shopzeely.partner D/WebView: Tue Aug 01 2017 16:10:59 GMT-0500 (PET) | sip.dialog | dialog qkclvmr1hlihlq7j0dp9f2avggj4g64onie431ca  changed to CONFIRMED state -- From line 2900 of file:///android_asset/webrtc/js_test/sip-0.7.7.js
08-01 16:10:59.729 17523-17523/com.shopzeely.partner D/WebView: Tue Aug 01 2017 16:10:59 GMT-0500 (PET) | sip.invitecontext.mediahandler | acquiring local media -- From line 2900 of file:///android_asset/webrtc/js_test/sip-0.7.7.js
08-01 16:10:59.735 17523-18264/com.shopzeely.partner E/chromium: [ERROR:media_stream_dispatcher_host.cc(229)] MSDH: Renderer requested a URL it's not allowed to use.`

I think the issue is on this line "[ERROR:media_stream_dispatcher_host.cc(229)] MSDH: Renderer requested a URL it's not allowed to use." but I dont know what is the issue there. Could you help me with this issue, please?

Thanks.

**Comment by egreenmachine** [comment]
My best guess is that it is a security thing on Android 6. The error is definitely a WebRTC error, not a SIP.js error. You also indicated it worked on Android 5. I would recommend that you follow up in the [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) group about this.
