### ISSUE TITLE
How to call PSTN through SIP

### ISSUE THREAD

**Issue by ostrichegret** [onsip/SIP.js#440]
Hi, 

I have a sip server, let's say this are my sip credentials:
username: user1
password: pass1
sip server: mysip.com

Using Zoiper i can connect to my sip server, then do calls to my regular phone number, let's say:
+62123123

How to do this with SIP.js?
I cannot find the documentation to connect to my sip then send command to forward calls to PSTN.

Thank you

**Comment by egreenmachine** [comment]
Hi,

Please check out [our guides](https://sipjs.com/guides/make-call/). Questions like this are also best suited for our [mailing list](groups.google.com/forum/#!forum/sip_js), so if you have any follow up questions please ask there. We like to reserve this area for bugs in the library.

Thanks
