### ISSUE TITLE
screen sharing in firefox is now possible, fails on ICE

### ISSUE THREAD

**Issue by gmaruzz** [onsip/SIP.js#441]
Hello,
thank you for your efforts!

now firefox can screen or window share, using 

mediaSource: "window"
or
mediaSource: "screen"

as video constraint.

See: https://mozilla.github.io/webrtc-landing/gum_test.html

Problem is, with SIP.js it fails with "ICE failed, ... see about:webrtc" message

Fails in the same way also if I put iceCheckingTimeout = 0

**Comment by gmaruzz** [comment]
Sun Aug 27 2017 00:01:10 GMT+0200 (CEST) | sip.dialog | new UAC dialog created with status CONFIRMED  sip.js:2900:3
Sun Aug 27 2017 00:01:10 GMT+0200 (CEST) | sip.invitecontext.mediahandler | stream added: {c9646150-e527-4007-936c-423499f37f79}  sip.js:2900:3
Sun Aug 27 2017 00:01:10 GMT+0200 (CEST) | sip.transport | sending WebSocket message:

ACK sip:3500@93.50.134.11:3360;transport=udp SIP/2.0

Via: SIP/2.0/WSS 1r9fhoujan0a.invalid;branch=z9hG4bK6959374

Max-Forwards: 70

To: <sip:3500@lab.telecomsolutions.com>;tag=p3ccr46ZNHg2F

From: <sip:1010@lab.telecomsolutions.com>;tag=2epn3h4jsp

Call-ID: u4phrl8kajd5bck40jku

CSeq: 8174 ACK

Supported: outbound

User-Agent: SIP.js/0.7.8 Sara

Content-Length: 0




  sip.js:2900:3
Sun Aug 27 2017 00:01:20 GMT+0200 (CEST) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK9298622  sip.js:2900:3
Sun Aug 27 2017 00:01:20 GMT+0200 (CEST) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK9298622  sip.js:2900:3
ICE failed, add a TURN server and see about:webrtc for more details (unknown)
Sun Aug 27 2017 00:01:42 GMT+0200 (CEST) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK6688060  sip.js:2900:3
Sun Aug 27 2017 00:01:42 GMT+0200 (CEST) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK6688060  sip.js:2900:3

**Comment by gmaruzz** [comment]
Sun Aug 27 2017 00:01:10 GMT+0200 (CEST) | sip.dialog | new UAC dialog created with status CONFIRMED  sip.js:2900:3
Sun Aug 27 2017 00:01:10 GMT+0200 (CEST) | sip.invitecontext.mediahandler | stream added: {c9646150-e527-4007-936c-423499f37f79}  sip.js:2900:3
Sun Aug 27 2017 00:01:10 GMT+0200 (CEST) | sip.transport | sending WebSocket message:

ACK sip:3500@93.50.134.11:3360;transport=udp SIP/2.0

Via: SIP/2.0/WSS 1r9fhoujan0a.invalid;branch=z9hG4bK6959374

Max-Forwards: 70

To: <sip:3500@lab.telecomsolutions.com>;tag=p3ccr46ZNHg2F

From: <sip:1010@lab.telecomsolutions.com>;tag=2epn3h4jsp

Call-ID: u4phrl8kajd5bck40jku

CSeq: 8174 ACK

Supported: outbound

User-Agent: SIP.js/0.7.8 Sara

Content-Length: 0




  sip.js:2900:3
Sun Aug 27 2017 00:01:20 GMT+0200 (CEST) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK9298622  sip.js:2900:3
Sun Aug 27 2017 00:01:20 GMT+0200 (CEST) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK9298622  sip.js:2900:3
ICE failed, add a TURN server and see about:webrtc for more details (unknown)
Sun Aug 27 2017 00:01:42 GMT+0200 (CEST) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK6688060  sip.js:2900:3
Sun Aug 27 2017 00:01:42 GMT+0200 (CEST) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK6688060  sip.js:2900:3

**Comment by gmaruzz** [comment]
actually it works

problem was on slow connections, while chrome worked flawlessly
shame on firefox

**Comment by LianJieZhang** [comment]
thanks, I know use screenshare
