### ISSUE TITLE
How to cancel accept request?

### ISSUE THREAD

**Issue by madox2** [onsip/SIP.js#446]
After accepting incoming call the user immediately clicks hangup button. Since the call was not yet accepted, I get an error coming from `createOfferAnswerError`:

```
sip.invitecontext.mediahandler | peerConnection is null
```

It can be reproduced with code below:

```javascript
userAgent.on('invite', session => {
  session.accept()
  session.bye() // or session.terminate()
}
```

As a workaround I can wait until `accepted` event is fired and then terminate the session.

**Comment by madox2** [comment]
Another use case for the same error:
- Alice calls Bob
- Bob accepts incoming call
- Alice hangs up while Bob's accepting is in progress
- Bob gets an error: peerConnection is null

**Comment by egreenmachine** [comment]
We are aware of some race conditions in the code with respect to this. There are actually some race conditions within the SIP protocol that contribute to this. Try using the `cancel()` function before the session is accepted to see if that works for you.

**Comment by madox2** [comment]
@egreenmachine there isn't `cancel()` function on inbound sessions.

**Comment by egreenmachine** [comment]
Yes, you are correct. I missed that part. Cancel is not valid on the incoming session. Can you provide a [gist](https://gist.github.com/) of some more detailed logging. Looking at the `bye` function, it should not rely on the media handler at all. There might be some async race condition going on, as the `createOfferAnswer` stuff happens outside of the main event thread.

**Comment by madox2** [comment]
@egreenmachine Exactly, `createOfferOrAnswer` function access asynchronously peer connection which has been already closed by `bye` function. Maybe it could emit some kind of error event instead of throwing uncaught exception.

**Comment by madox2** [comment]
My fault, the exception is actually not throwed but logged (with `console.error`). Since I am using react native, it looks like uncaughted exception. I can simply solve it by providing custom logger. @egreenmachine thanks for your feedback
