### ISSUE TITLE
Sound mute after disconnecting the HeadPhones.

### ISSUE THREAD

**Issue by diegomichel** [onsip/SIP.js#447]
Hello,

So I built a bare-bones app using Cordova and SIP.JS(0.7.8) and connected to a FreeSWITCH. I notice that after connecting the HeadPhones and disconnecting them the app doesn't release the Audio to the other devices be either the earpiece or speaker. So it kinda gets muted.

I would expect it the audio to go back either to the earpiece or the speaker.

I have noticed that if I receive a notification that makes a sound the audio gets toggled back to the speaker as it should.

Any ideas on how to fix it or workarounds?

Thank you

**Comment by egreenmachine** [comment]
This is going to be outside the control of SIP.js and in the underlying WebRTC libraries that you are using.
