### ISSUE TITLE
InvalidSessionDescriptionError: Offer is missing required setup attribute at level 0

### ISSUE THREAD

**Issue by Payetus** [onsip/SIP.js#448]
I'm calling a Firefox browser from  FreeSWITCH Version 1.5.14b4~64bit ( 64bit)

The problem started when I updated to Firefox 55.

v=0
o=FreeSWITCH 1506487096 1506487097 IN IP4 80.39.72.115
s=FreeSWITCH
c=IN IP4 80.39.72.115
t=0 0
a=msid-semantic: WMS hmFFZldKVKWC3qxXDnUFHws9yQkuGTrO
m=audio 16146 RTP/SAVPF 102 101 13
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; usedtx=1; maxaveragebitrate=20000; ptime=20; minptime=20; maxptime=20; samplerate=48000
a=rtpmap:101 telephone-event/8000
a=fingerprint:sha-256 4F:04:51:8A:03:26:BA:4A:88:B4:E9:B6:74:C2:87:1B:20:D5:5A:8D:7D:BA:79:86:51:B0:43:22:7A:27:C4:BB
a=rtcp-mux
a=rtcp:16146 IN IP4 80.39.72.115
a=ssrc:3721256842 cname:6XkV8owTZilSyJF1
a=ssrc:3721256842 msid:hmFFZldKVKWC3qxXDnUFHws9yQkuGTrO a0
a=ssrc:3721256842 mslabel:hmFFZldKVKWC3qxXDnUFHws9yQkuGTrO
a=ssrc:3721256842 label:hmFFZldKVKWC3qxXDnUFHws9yQkuGTrOa0
a=ice-ufrag:WqwuNOtbvDw2nNHj
a=ice-pwd:AR5y5riVzuDX39PPqba3Qt5c
a=candidate:7038872351 1 udp 659136 80.39.72.115 16146 typ host generation 0
a=candidate:7038872351 2 udp 659136 80.39.72.115 16146 typ host generation 0
a=ptime:20

I can't figure out what setup attribut is missing. 
Also Chrome works for me for inbound and outbound calls.
Firefox only works with Outbound calls (to FreeSwitch) and fails with inbound calls.

DOMException [InvalidSessionDescriptionError: "Offer is missing required setup attribute  at level 0"
code: 0
nsresult: 0x0]

![image](https://user-images.githubusercontent.com/3797659/30906752-13966c84-a379-11e7-901b-32633304a049.png)

**Comment by egreenmachine** [comment]
The `a=setup` is required for WebRTC to work. It appears that your FreeSWITCH instance is not setting it on the SDP. This is going to be a FreeSWITCH issue. See [RFC 4145](https://tools.ietf.org/html/rfc4145#page-4) for more information.

**Comment by Payetus** [comment]
Just to dispell any doubts would it not be failing also on google chrome ?

**Comment by james-criscuolo** [comment]
The handling of SDP is wildly different between browsers, so Chrome dropping the necessity of the setup line sounds perfectly plausible. The new modifiers work recently pulled into master should make quick work of this, but in the past we've also had a proxy sitting in front of freeswitch to sanitize SDP (could also likely be done within freeswitch).

**Comment by Payetus** [comment]
All cleared :+1:
