### ISSUE TITLE
Difference in ice candidates list between 7.8 and 8.1

### ISSUE THREAD

**Issue by Klimashin** [onsip/SIP.js#452]
Hello! I've updated sip.js from v7.8 to 8.1 and issues with sdp negotiation occurred. After some investigation, i've noticed that ice candidates list are different for 7.8 and 8.1, which, i think, is the case. Do you have any thoughts where can be the problem? Thank you!

======= 7.8 ======
v=0
o=- 8878032865215982187 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS suALGQLU5Af3Bc6bmkcADcai1NO6G0oJO3FU
m=audio 36393 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 46.236.143.244
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:211156821 1 udp 2122260223 192.168.1.5 36393 typ host generation 0 network-id 1 network-cost 10
a=candidate:2781507712 1 udp 1686052607 46.236.143.244 36393 typ srflx raddr 192.168.1.5 rport 36393 generation 0 network-id 1 network-cost 10
a=candidate:1108738981 1 tcp 1518280447 192.168.1.5 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:Ldjl
a=ice-pwd:c3R1z61H7UQf8eiE8+OY2e27
a=ice-options:trickle
a=fingerprint:sha-256 F4:20:2D:C1:E9:CE:84:28:0E:AD:F1:36:8E:9A:94:CD:31:04:E9:E8:5B:88:CD:A2:DF:F5:C8:A9:26:B0:F8:2F
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3878782299 cname:o2m3V9Ho/28/f5n5
a=ssrc:3878782299 msid:suALGQLU5Af3Bc6bmkcADcai1NO6G0oJO3FU 10c80dcf-7629-468c-97fe-6185f4b9a1f9
a=ssrc:3878782299 mslabel:suALGQLU5Af3Bc6bmkcADcai1NO6G0oJO3FU
a=ssrc:3878782299 label:10c80dcf-7629-468c-97fe-6185f4b9a1f9

====== 8.1 ========
v=0
o=- 2960142848794148400 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS gwXwFekzUMG8P7NXVlnoL3pfLiRR5doc5EAj
m=audio 41743 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 192.168.1.5
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:211156821 1 udp 2122260223 192.168.1.5 41743 typ host generation 0 network-id 1 network-cost 10
a=ice-ufrag:idPR
a=ice-pwd:4gB8KcZOKSWTbPKz+sFo75ZE
a=ice-options:trickle
a=fingerprint:sha-256 E0:9C:6B:61:02:4B:DC:19:2C:3D:13:79:F3:10:49:36:F7:34:96:98:5B:14:92:8C:2B:1B:27:27:A6:9E:85:D6
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:849266702 cname:ZVogc2TLFZVUtArD
a=ssrc:849266702 msid:gwXwFekzUMG8P7NXVlnoL3pfLiRR5doc5EAj 1108a027-8b47-4987-b6cc-2bcbad55a9c1
a=ssrc:849266702 mslabel:gwXwFekzUMG8P7NXVlnoL3pfLiRR5doc5EAj

**Comment by egreenmachine** [comment]
`0.8.1` looks cut off. Can you provide some details such as which browser you are using, and some more complete SIP.js logging in a [gist](https://gist.github.com/)? Thanks

**Comment by Klimashin** [comment]
Here are full console outputs for 8.1 and 7.8
0.8.1: https://gist.github.com/Klimashin/8679619b621e0c9f26038b1d511ebb60
0.7.8: https://gist.github.com/Klimashin/a6668c2412a5f92f166394daa1d9c1c1
I'm using Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by denzs** [comment]
I've seen the same change in behaviour from 0.7 to 0.8.
I am not sure if it is relevant but, in our scenario the SDP of the first invite contains only one IP address.
But when a Re-Invite is generated (like by putting the call on hold) the SDP contains two IP addresses.

**Comment by roman-yerin** [comment]
So guys, any luck with this issue? No external candidates results in call failure.

**Comment by egreenmachine** [comment]
Yeah. I tracked this down yesterday on our [mailing list](https://groups.google.com/forum/#!topic/sip_js/3UlbNTbluEs). I am putting together a new release to get it fixed, but setting the configuration option outlined should resolve the problem in the immediate term. Sorry for the trouble.

**Comment by roman-yerin** [comment]
Thanks a lot!

**Comment by egreenmachine** [comment]
commit 49c6ac45b673e9f8c490b8aa27041eb70ace8d48 which is included in [0.8.2](https://github.com/onsip/SIP.js/releases/tag/0.8.2) should fix this. I am closing this issue, but if it is still a problem please re-open.

**Comment by roman-yerin** [comment]
Still doesn't work in MS Edge, no candidates

**Comment by egreenmachine** [comment]
Can you provide full logs in a [gist](https://gist.github.com/) from SIP.js?

**Comment by roman-yerin** [comment]
Sure, here it is https://gist.github.com/roman-yerin/26cc784da471d11be3468b76a29157a3

**Comment by egreenmachine** [comment]
Sorry. Also need `traceSip: true` on the UA.

**Comment by roman-yerin** [comment]
https://gist.github.com/roman-yerin/5f845bddeffb9e043d73b82b30326357

**Comment by egreenmachine** [comment]
Your issue is with freeswitch `Reason: Q.850;cause=88;text="INCOMPATIBLE_DESTINATION"`

**Comment by roman-yerin** [comment]
That's because of no candidate found, read my comment here https://gist.github.com/roman-yerin/26cc784da471d11be3468b76a29157a3
As you can see, all the candidates are at rfc1918 networks

**Comment by egreenmachine** [comment]
Makes sense. The only thing that would affect this in SIP.js is the `iceCheckingTimeout`. The candidates are passed directly from the browser into the SDP (unless you have modifiers removing them).
