### ISSUE TITLE
SIP.js to SIP

### ISSUE THREAD

**Issue by nerdtron123** [onsip/SIP.js#454]
Currently this site I use uses SIP.js for sip calls, but I'd like to use X-Lite softphone.
I have the:
- URI in the form of "username@sip.website.com"
- Display Name
- Authorization User
- Password
- wsServers

My softphone asks for:
- User ID
- Domain
-Password
-Display Name
- Authorization name

for each, I put:

- User ID: username from the URI
- Domain: domain from the URI
- Password: Password
- Display Name: Display Name
- Authorization Name: Authorization Name

but it doesn't work.

**Comment by james-criscuolo** [comment]
Looks like this was meant to be opened elsewhere, so I'll close.
