### ISSUE TITLE
Re-invite event

### ISSUE THREAD

**Issue by VadimDez** [onsip/SIP.js#458]
For such cases like update display name on re-invite, would be useful to have such event.

**Comment by egreenmachine** [comment]
I agree. Knowing that you received a re-invite would be ideal. Currently it will emit `hold` `unhold` regardless of whether you were actually put on hold or not, so that should get fixed.

[Session 479](https://github.com/onsip/SIP.js/blob/master/src/Session.js#L479) is the code in question.
