### ISSUE TITLE
How I can add remoteAudio DOM tag to UA with sip.js v0.8.x?

### ISSUE THREAD

**Issue by johnmorenov** [onsip/SIP.js#462]
How I can add remoteAudio DOM tag with sip.js v0.8.x?, please give me an example, I don't want to use Simple mode, I want to know how it works for advanced developers.

Thanks.

**Comment by egreenmachine** [comment]
Our [Session Description Handler](https://sipjs.com/api/0.8.0/sessionDescriptionHandler/) documentation shows how to do this.
