### ISSUE TITLE
Not able to get session invite on firefox  . works fine on chrome. using sipjs 0.7.8

### ISSUE THREAD

**Issue by sumeet559** [onsip/SIP.js#463]
Not able to receive invite event in firefox whereas working fine on chrome. Using sipjs 0.7.8
```
userAgent.on('invite', (session)=>{ console.log("INVITE DATA",session); })
```

**Comment by sumeet559** [comment]
Tried on firefox 52.0, 55.0, 56.0

**Comment by sumeet559** [comment]
getting INVITE event in SIP trace, but not able to capture event using the above method.

**Comment by egreenmachine** [comment]
This is not a bug. I am following up on our [mailing list](https://groups.google.com/forum/#!forum/sip_js). Let's continue the discussion there.
