### ISSUE TITLE
Simple vs hold/unhold

### ISSUE THREAD

**Issue by jlaine** [onsip/SIP.js#465]
The "Simple" interface's hold / unhold methods make calls like:

this.session.isOnHold().local

However the "isOnHold" method does not exist anymore since commit 560f5b3762bb2352b763245a210499b8ac1f6064. There still is a local_hold member, but it's not part of the documented API. It would be good to provide a public getter and use it in Simple, as I expect a number of people will use Simple as their starting point for their own implementations.

**Comment by egreenmachine** [comment]
I created a bunch of states for `Simple` to track on it's own. That is probably what it should do here. The SIP session itself has no idea of hold or unhold which is why I removed it from the session. The assumptions made there were bad. I will get this fixed. Thanks for the find.

**Comment by ricardojlrufino** [comment]
I ended up finding the same problem.
Watching ...

**Comment by engineermusleh** [comment]
I am using sipjs 0.10.0 
No incoming and out going call is working   , log for outgoing call 
 Tue Jun 26 2018 18:13:02 GMT+0600 (+06) | sip.transport | sending WebSocket message:

INVITE sip:abc123_abc1_0_1002@musleh.vantageip.com SIP/2.0
Via: SIP/2.0/WSS cannkildkuul.invalid;branch=z9hG4bK4211093
Max-Forwards: 70
To: <sip:abc123_abc1_0_1002@musleh.vantageip.com>
From: <sip:abc123_abc1_0_1008@musleh.vantageip.com>;tag=m8bvp89oto
Call-ID: cigt4e0h01kk5l6k68rt
CSeq: 3639 INVITE
Contact: <sip:5b4bpl62@cannkildkuul.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound
User-Agent: SIP.js/0.10.0
Content-Type: application/sdp
Content-Length: 9335

v=0
o=mozilla...THIS_IS_SDPARTA-60.0.1 4072617226631351052 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 98:BF:31:0B:1C:AB:B2:3F:61:5E:D4:A7:B1:7E:00:22:D8:D6:92:9D:F0:5A:73:10:3C:1E:BC:C1:A6:E9:6B:E0
a=group:BUNDLE sdparta_0 sdparta_1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 58359 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 116.68.200.58
a=candidate:0 1 UDP 2122252543 10.0.0.114 52458 typ host
a=candidate:2 1 UDP 2122187007 10.0.0.85 47549 typ host
a=candidate:4 1 UDP 2122121471 172.18.0.1 57365 typ host
a=candidate:6 1 UDP 2122055935 172.21.0.1 50400 typ host
a=candidate:8 1 UDP 2121990399 172.20.0.1 39929 typ host
a=candidate:10 1 UDP 2121924863 172.22.0.1 43896 typ host
a=candidate:12 1 UDP 2121859327 172.19.0.1 41847 typ host
a=candidate:14 1 UDP 2121793791 172.17.0.1 33831 typ host
a=candidate:16 1 TCP 2105524479 10.0.0.114 9 typ host tcptype active
a=candidate:17 1 TCP 2105458943 10.0.0.85 9 typ host tcptype active
a=candidate:18 1 TCP 2105393407 172.18.0.1 9 typ host tcptype active
a=candidate:19 1 TCP 2105327871 172.21.0.1 9 typ host tcptype active
a=candidate:20 1 TCP 2105262335 172.20.0.1 9 typ host tcptype active
a=candidate:21 1 TCP 2105196799 172.22.0.1 9 typ host tcptype active
a=candidate:22 1 TCP 2105131263 172.19.0.1 9 typ host tcptype active
a=candidate:23 1 TCP 2105065727 172.17.0.1 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 10.0.0.114 51215 typ host
a=candidate:2 2 UDP 2122187006 10.0.0.85 55789 typ host
a=candidate:4 2 UDP 2122121470 172.18.0.1 51421 typ host
a=candidate:6 2 UDP 2122055934 172.21.0.1 55844 typ host
a=candidate:8 2 UDP 2121990398 172.20.0.1 33849 typ host
a=candidate:10 2 UDP 2121924862 172.22.0.1 54482 typ host
a=candidate:12 2 UDP 2121859326 172.19.0.1 56704 typ host
a=candidate:14 2 UDP 2121793790 172.17.0.1 39375 typ host
a=candidate:16 2 TCP 2105524478 10.0.0.114 9 typ host tcptype active
a=candidate:17 2 TCP 2105458942 10.0.0.85 9 typ host tcptype active
a=candidate:18 2 TCP 2105393406 172.18.0.1 9 typ host tcptype active
a=candidate:19 2 TCP 2105327870 172.21.0.1 9 typ host tcptype active
a=candidate:20 2 TCP 2105262334 172.20.0.1 9 typ host tcptype active
a=candidate:21 2 TCP 2105196798 172.22.0.1 9 typ host tcptype active
a=candidate:22 2 TCP 2105131262 172.19.0.1 9 typ host tcptype active
a=candidate:23 2 TCP 2105065726 172.17.0.1 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 116.68.200.58 58359 typ srflx raddr 10.0.0.114 rport 52458
a=candidate:3 1 UDP 1685987327 116.68.200.58 35380 typ srflx raddr 10.0.0.85 rport 47549
a=candidate:5 1 UDP 1685921791 116.68.200.58 15142 typ srflx raddr 172.18.0.1 rport 57365
a=candidate:7 1 UDP 1685856255 116.68.200.58 49641 typ srflx raddr 172.21.0.1 rport 50400
a=candidate:9 1 UDP 1685790719 116.68.200.58 6716 typ srflx raddr 172.20.0.1 rport 39929
a=candidate:11 1 UDP 1685725183 116.68.200.58 36491 typ srflx raddr 172.22.0.1 rport 43896
a=candidate:13 1 UDP 1685659647 116.68.200.58 4392 typ srflx raddr 172.19.0.1 rport 41847
a=candidate:15 1 UDP 1685594111 116.68.200.58 11723 typ srflx raddr 172.17.0.1 rport 33831
a=candidate:1 2 UDP 1686052862 116.68.200.58 22731 typ srflx raddr 10.0.0.114 rport 51215
a=candidate:3 2 UDP 1685987326 116.68.200.58 59919 typ srflx raddr 10.0.0.85 rport 55789
a=candidate:5 2 UDP 1685921790 116.68.200.58 38823 typ srflx raddr 172.18.0.1 rport 51421
a=candidate:7 2 UDP 1685856254 116.68.200.58 35692 typ srflx raddr 172.21.0.1 rport 55844
a=candidate:9 2 UDP 1685790718 116.68.200.58 27304 typ srflx raddr 172.20.0.1 rport 33849
a=candidate:11 2 UDP 1685725182 116.68.200.58 35646 typ srflx raddr 172.22.0.1 rport 54482
a=candidate:13 2 UDP 1685659646 116.68.200.58 51634 typ srflx raddr 172.19.0.1 rport 56704
a=candidate:15 2 UDP 1685594110 116.68.200.58 44402 typ srflx raddr 172.17.0.1 rport 39375
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:ca119b515f75ee0f4dc18e858d6c0399
a=ice-ufrag:0e81a2ec
a=mid:sdparta_0
a=msid:{8125df08-592a-44ad-8550-2222009afd46} {78611f16-8ce6-41c0-b110-137fac2d4801}
a=rtcp:22731 IN IP4 116.68.200.58
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:108541189 cname:{2070d0e1-e7f1-4179-812d-4183575754ce}
m=video 58829 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4 116.68.200.58
a=candidate:0 1 UDP 2122252543 10.0.0.114 45976 typ host
a=candidate:2 1 UDP 2122187007 10.0.0.85 42670 typ host
a=candidate:4 1 UDP 2122121471 172.18.0.1 34337 typ host
a=candidate:6 1 UDP 2122055935 172.21.0.1 44447 typ host
a=candidate:8 1 UDP 2121990399 172.20.0.1 53292 typ host
a=candidate:10 1 UDP 2121924863 172.22.0.1 54607 typ host
a=candidate:12 1 UDP 2121859327 172.19.0.1 35228 typ host
a=candidate:14 1 UDP 2121793791 172.17.0.1 48811 typ host
a=candidate:16 1 TCP 2105524479 10.0.0.114 9 typ host tcptype active
a=candidate:17 1 TCP 2105458943 10.0.0.85 9 typ host tcptype active
a=candidate:18 1 TCP 2105393407 172.18.0.1 9 typ host tcptype active
a=candidate:19 1 TCP 2105327871 172.21.0.1 9 typ host tcptype active
a=candidate:20 1 TCP 2105262335 172.20.0.1 9 typ host tcptype active
a=candidate:21 1 TCP 2105196799 172.22.0.1 9 typ host tcptype active
a=candidate:22 1 TCP 2105131263 172.19.0.1 9 typ host tcptype active
a=candidate:23 1 TCP 2105065727 172.17.0.1 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 10.0.0.114 50642 typ host
a=candidate:2 2 UDP 2122187006 10.0.0.85 33205 typ host
a=candidate:4 2 UDP 2122121470 172.18.0.1 54306 typ host
a=candidate:6 2 UDP 2122055934 172.21.0.1 39983 typ host
a=candidate:8 2 UDP 2121990398 172.20.0.1 47534 typ host
a=candidate:10 2 UDP 2121924862 172.22.0.1 47391 typ host
a=candidate:12 2 UDP 2121859326 172.19.0.1 53963 typ host
a=candidate:14 2 UDP 2121793790 172.17.0.1 45600 typ host
a=candidate:16 2 TCP 2105524478 10.0.0.114 9 typ host tcptype active
a=candidate:17 2 TCP 2105458942 10.0.0.85 9 typ host tcptype active
a=candidate:18 2 TCP 2105393406 172.18.0.1 9 typ host tcptype active
a=candidate:19 2 TCP 2105327870 172.21.0.1 9 typ host tcptype active
a=candidate:20 2 TCP 2105262334 172.20.0.1 9 typ host tcptype active
a=candidate:21 2 TCP 2105196798 172.22.0.1 9 typ host tcptype active
a=candidate:22 2 TCP 2105131262 172.19.0.1 9 typ host tcptype active
a=candidate:23 2 TCP 2105065726 172.17.0.1 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 116.68.200.58 58829 typ srflx raddr 10.0.0.114 rport 45976
a=candidate:3 1 UDP 1685987327 116.68.200.58 2543 typ srflx raddr 10.0.0.85 rport 42670
a=candidate:5 1 UDP 1685921791 116.68.200.58 40939 typ srflx raddr 172.18.0.1 rport 34337
a=candidate:7 1 UDP 1685856255 116.68.200.58 26802 typ srflx raddr 172.21.0.1 rport 44447
a=candidate:9 1 UDP 1685790719 116.68.200.58 24883 typ srflx raddr 172.20.0.1 rport 53292
a=candidate:11 1 UDP 1685725183 116.68.200.58 42487 typ srflx raddr 172.22.0.1 rport 54607
a=candidate:13 1 UDP 1685659647 116.68.200.58 15477 typ srflx raddr 172.19.0.1 rport 35228
a=candidate:15 1 UDP 1685594111 116.68.200.58 47561 typ srflx raddr 172.17.0.1 rport 48811
a=candidate:1 2 UDP 1686052862 116.68.200.58 38093 typ srflx raddr 10.0.0.114 rport 50642
a=candidate:3 2 UDP 1685987326 116.68.200.58 53885 typ srflx raddr 10.0.0.85 rport 33205
a=candidate:5 2 UDP 1685921790 116.68.200.58 28683 typ srflx raddr 172.18.0.1 rport 54306
a=candidate:7 2 UDP 1685856254 116.68.200.58 33960 typ srflx raddr 172.21.0.1 rport 39983
a=candidate:9 2 UDP 1685790718 116.68.200.58 2288 typ srflx raddr 172.20.0.1 rport 47534
a=candidate:11 2 UDP 1685725182 116.68.200.58 26902 typ srflx raddr 172.22.0.1 rport 47391
a=candidate:13 2 UDP 1685659646 116.68.200.58 2166 typ srflx raddr 172.19.0.1 rport 53963
a=candidate:15 2 UDP 1685594110 116.68.200.58 35696 typ srflx raddr 172.17.0.1 rport 45600
a=sendrecv
a=end-of-candidates
a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:121 max-fs=12288;max-fr=60
a=ice-pwd:ca119b515f75ee0f4dc18e858d6c0399
a=ice-ufrag:0e81a2ec
a=mid:sdparta_1
a=msid:{8125df08-592a-44ad-8550-2222009afd46} {a98c8ada-5a03-4b82-a7fb-c010917e6149}
a=rtcp:38093 IN IP4 116.68.200.58
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:121 VP9/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:1893400447 cname:{2070d0e1-e7f1-4179-812d-4183575754ce}

 sip.js:807:6

**Comment by engineermusleh** [comment]
here is  my  code  for ua  create 
// Create a Simple interface with a user named bob and a remote video element in the DOM
        var simple = new SIP.WebRTC.Simple({
            media: {
                remote: {
                    video: document.getElementById('remoteVideo'),
                    // This is necessary to do an audio/video call as opposed to just a video call
                    audio: document.getElementById('remoteVideo')
                },
                local:{
                    video: document.getElementById('localVideo')
                }
            },
            ua: {
                uri: "abc123_abc1_0_1008@musleh.vantageip.com",
                wsServers: ["wss://musleh.vantageip.com:8089/ws"],
                authorizationUser: "abc123_abc1_0_1008",
                password: "fFnRrgkhX5b6Ck93A0pU",
                hackViaTcp: true,
                register: true,
                hackIpInContact: true,
                hackWssInTransport: true,
                hackViaTcp: true,
                traceSip: true,
                rel100: SIP.C.supported.SUPPORTED,
                rtcpMuxPolicy: "negotiate",
                stunServers: []
            }
        });

        var callButton = document.getElementById('newCall');
        callButton.addEventListener("click", function () {
            simple.call("abc123_abc1_0_1002@musleh.vantageip.com");
        }, false);
        var endButton = document.getElementById('endCall');
        endButton.addEventListener("click", function () {
            simple.hangup();
        }, false);

        simple.on('registered', function() {
            console.log("Registered");

        })

        simple.on('new', function() {
            console.log("New call");
            simple.answer();
        })

**Comment by james-criscuolo** [comment]
While there may be an issue with the sdp, those logs are incomplete. That is just the INVITE, it is important to see how the INVITE is responded to. Please attach the full logs in a [gist](https://gist.github.com)

I also deleted the comment with your config, I'd recommend removing or falsifying the identifying information (mainly, the password, wsServers, and authUsername).

**Comment by engineermusleh** [comment]
This one create ua log  : https://gist.github.com/engineermusleh/d8d7363cb61907bc715d0add7367afe0
This one is outgoing  call  https://gist.github.com/engineermusleh/411392c563d746ca022b6e4c63081b0f

**Comment by james-criscuolo** [comment]
If that's all there is, your INVITE is not being responded to. It is possible your websocket server is unhappy with the packet being sent, that's where you should begin. You have a lot of ICE candidates, removing network interfaces usually cuts down on those, but that's only necessary if the packet is deemed too large. SIP.js also typically sends retransmissions as well, so it's hard to say why nothing else appears in those logs.

Lastly, I didn't realize your response was unrelated to the ticket, so once you investigate, if the problem looks to be in SIP.js please open a new issue or post in our google group.

Thanks,
James
