### ISSUE TITLE
Does SipJS employ UDP hole punching?

### ISSUE THREAD

**Issue by andrewvmail** [onsip/SIP.js#471]
Hi guys, just wondering i know sipsjs have ice (stun/turn) to deal with nat but i dont see any mentioned of udp hole punching in docs or source? or maybe combination of all = udp hole punching?  im interested in optimizing my server bandwidth usage limitting the usage of the my turn server. 

Cheers
Andrew

**Comment by egreenmachine** [comment]
SIP.js utilizes a media engine to handle any sort of media, so it would be up to whatever media engine you are using. In the majority of cases this is in a browser and WebRTC. So it would be if WebRTC supported the UDP "hole punching" that you wanted to. SIP.js is agnostic to all of this.

In the future, questions like this are best suited for our [mailing list](https://groups.google.com/forum/#!forum/sip_js).

**Comment by andrewvmail** [comment]
cool thanks!
