### ISSUE TITLE
How to set rtcpMuxPolicy to negotiate on Sip.JS 0.8.3

### ISSUE THREAD

**Issue by vyshakhbabji** [onsip/SIP.js#476]
I am currently on 0.7.8  and in the UA conf parameters , i could set rtcpMuxPolicy to negotiate by setting  rtcpMuxPolicy: "negotiate"

I don't find any ways to set rtcpMuxPolicy: "negotiate" on 0.8.3 via SIP.UA Configuration Parameters. Can you please give me pointers?

**Comment by jlaine** [comment]
sip.js 0.8.x allows you to set arbitrary options for the RTCPeerConnection like this:

```
ua = new SIP.UA({
  sessionDescriptionHandlerOptions: {
    peerConnectionOptions: {
      rtcConfiguration: {
        rtcpMuxPolicy: 'negotiate'
      }
    }
  }
})
```

**Comment by egreenmachine** [comment]
Answer above is correct. In the future, the [mailing list](https://groups.google.com/forum/#!forum/sip_js) is better suited for questions as we would like to keep Github for issue tracking.
