### ISSUE TITLE
Firefox - ICE failed. How to set iceTransportPolicy: 'all'

### ISSUE THREAD

**Issue by schirrmie** [onsip/SIP.js#481]
Hi,
with sip.js 0.8.3 I get the following error in Firefox 57:
`ICE failed, add a TURN server and see about:webrtc for more details`
I use a public stun server that works 100%.

I can reproduce this failure with the following test site: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

If I set the iceTransportPolicy to 'relay' I get the error. If I set 'iceTransportPolicy to 'all', all seems fine.

So how can I set 'iceTransportPolicy' in sip.js?
I tried this but with no success:

```
var configuration = {
...
sessionDescriptionHandlerFactoryOptions: {
  peerConnectionOptions: {
    iceTransportPolicy: 'all',
  },
},
...
ua = new SIP.UA(configuration);
```

Can You please help me with this?

Regards
schirrmie

**Comment by jlaine** [comment]
Try:

```
var configuration = {
  ...
  sessionDescriptionHandlerFactoryOptions: {
    peerConnectionOptions: {
      rtcConfiguration: {
        iceTransportPolicy: 'all'
      }
    }
  }
};
```

**Comment by jlaine** [comment]
Also, according to MDN, if iceTransportPolicy: 'all' seems to be the default:

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection#Parameters

**Comment by schirrmie** [comment]
Thank You for your fast answer.
I set the configuration but I get the same error on Firefox. With Chrome all works fine, but Firefox fails. Maybe an error in Firefox!?!
Do You have any hints for me to get this working in Firefox?

Regards
schirrmie

**Comment by schirrmie** [comment]
The error occour only by receive a call and not making a call. So only by session.accept.
I could fix the error with the following configuration in session.accept:
```
        session.accept( {
          sessionDescriptionHandlerOptions: {
            peerConnectionOptions: {
              rtcConfiguration: {
                iceTransportPolicy: 'all',
                iceServers: [{
                  urls: ['stun:stun.l.google.com:19302'],
                }],
              }
            }
          },
          media: {
            constraints: {
              audio: true,
              video: true,
            },
            render: {
              remote: render_remote,
              local: render_local,
            }
          }
        });
```

But still no video in firefox. I will try a little bit more.
Thank You for your help and this great library.

Regards
schirrmie
