### ISSUE TITLE
No media in Firefox 56 + 57

### ISSUE THREAD

**Issue by schirrmie** [onsip/SIP.js#482]
In Firefox 56 + 57 (i don't know if previous version also affected) desktop + mobile I don't have any video or audio. The SIP call is successfull and with wireshark I see the rtp packets. I think there is an error while attaching the media stream to the html video element. But I don't see any errors in the console.
Here is some example code:

```
        var render_local = document.getElementById('video_local');
        var render_remote = document.getElementById('video_remote');

        var options = {
          media: {
            constraints: {
              audio: true,
              video: true
            },
            render: {
              remote: render_remote,
              local: render_local
            }
          },
        };

        session = ua.invite(sip_uri, options);
```

Is this a known problem or is my code wrong?

Regards
schirrmie

**Comment by egreenmachine** [comment]
What version of SIP.js are you using? Can you include a [gist](https://gist.github.com/) of your logs?

**Comment by schirrmie** [comment]
Oh of course I use the latest Version 0.8.3.
I will collect logs and attach them.

**Comment by egreenmachine** [comment]
Your options are incorrect for `0.8.3`. https://sipjs.com/api/0.8.0/ua/#invitetarget-options-modifiers

**Comment by schirrmie** [comment]
Oh ok I will try it. So the "Make a call" guide (https://sipjs.com/guides/make-call/) is not for the 0.8.x version?

**Comment by egreenmachine** [comment]
That guide has not been updated yet. I will try and get to it soon. Sorry for the confusion.

**Comment by schirrmie** [comment]
Ok Thank You!
But I don't find the piece of code where I configure the html video elements?!?

Do I have to set this in the options like in 0.7.x or do I have to attach the streams manually for example in session.on('accepted' ... ?
Sorry for the questions but I don't find it.

**Comment by egreenmachine** [comment]
We removed the media attachment options from SIP.js. You need to attach the streams manually. There is an example in #426 on how to do this. Alternatively, [Simple](https://sipjs.com/api/0.8.0/simple/) will attach the media for you.

**Comment by schirrmie** [comment]
Thank You for your answer. I looked into the Simple source code and now it works.
You should update the documentation, maybe add a reference to the Simple source code as an example.

Regards
schirrmie
