### ISSUE TITLE
No camera and mic query in google chrome mobile

### ISSUE THREAD

**Issue by schirrmie** [onsip/SIP.js#483]
Hi,

in google chrome 62 mobile (Android 8), I don't get the question for the camera and the mic.
Firefox works as expected and other websites (webrtc demos) are also working, so for me is this a bug in sip.js.
Is this a known bug? I tried to load adapter.js before sip.js but without success.

Regards
schirrmie

**Comment by egreenmachine** [comment]
We do not have an Android 8 device to look into this currently. I know that SIP.js works on chrome 62 desktop and Android 7.

**Comment by egreenmachine** [comment]
We did find someone to do some basic tests on Android 8 (Pixel) and it appears to be working as intended (they get notifications for camera and mic). Could you maybe include some logs as to what you are seeing?

**Comment by schirrmie** [comment]
Hi,
i didn't know how to get the console output in mobile, but now I have the log and see this:

```
Mon Nov 20 2017 20:04:46 GMT+0100 (CET) | sip.invitecontext.sessionDescriptionHandler | acquiring local media
Mon Nov 20 2017 20:04:46 GMT+0100 (CET) | sip.invitecontext.sessionDescriptionHandler | unable to acquire streams
NotSupportedError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
```
So I have to use https, now its works! Thank You!
Sorry for my stupid problems.
