### ISSUE TITLE
Chrome not showing video or starting the call in simple demo

### ISSUE THREAD

**Issue by shamal** [onsip/SIP.js#490]
I'm trying to run [https://sipjs.com/guides/make-call/](https://sipjs.com/guides/make-call/). 
Hosted in localhost (using npm http-server).
When I access the page, The call does not start, webcam does not turn on. chrome doesn't even ask permission to use webcam.

**Comment by egreenmachine** [comment]
Sounds like you are not using https. This is required even when using localhost.

**Comment by egreenmachine** [comment]
I am going to close this at the end of the week if I do not hear back on it.

**Comment by shamal** [comment]
Yes, that was the issue. Thanks and that resolved it.
