### ISSUE TITLE
Mute local microphone

### ISSUE THREAD

**Issue by Pjata** [onsip/SIP.js#492]
Hello,
Is there anyway to mute the local microphone? 
Session.mute() doesnt seems to be working.
Best Regards,
Pjata

**Comment by egreenmachine** [comment]
You need to get the local tracks off of the peerConnection and then mute the tracks. This is outside of the scope of SIP.js. See [Session Description Handler documentation](https://sipjs.com/api/0.9.0/sessionDescriptionHandler/) for information on how to get the peer connection.

**Comment by Pjata** [comment]
I solved it like this:
```
session.getLocalStreams()[0].getAudioTracks()[0].stop()
```

**Comment by egreenmachine** [comment]
`session.getLocalStreams` is not forwards compatible with 0.8+. Y

**Comment by egreenmachine** [comment]
> You need to get the local tracks off of the peerConnection and then mute the tracks. This is outside of the scope of SIP.js. See [Session Description Handler documentation](https://sipjs.com/api/0.9.0/sessionDescriptionHandler/) for information on how to get the peer connection.

**Comment by mizhgun1021** [comment]
i did it this way

```
///mute
var pc = session.sessionDescriptionHandler.peerConnection;
pc.getLocalStreams().forEach(function (stream) {
    stream.getAudioTracks().forEach(function (track) {
        track.enabled = false;
    });
});
```

**Comment by keyroii** [comment]
> 
> 
> i did it this way
> 
> ```
> ///mute
> var pc = session.sessionDescriptionHandler.peerConnection;
> pc.getLocalStreams().forEach(function (stream) {
>     stream.getAudioTracks().forEach(function (track) {
>         track.enabled = false;
>     });
> });
> ```

Chrome says `peerConnection.getLocalStreams()` shouldnt be used anymore. Instead use:
`peerConnection.getSenders()` And `peerConnection.getReceivers()`

**Comment by KoshelevVasily** [comment]
in 0.15.0 version is it turned out to be done like this
```
const pc: any = this.session.sessionDescriptionHandler.peerConnection
    pc.getSenders().forEach((stream: any) => {
      stream.track.enabled = false
    })
```

**Comment by carloscarvallo** [comment]
thank you @koshelevvasya that worked for me!

**Comment by thanh-mel** [comment]
sorry was late to the party. how do i as the remote peer know the local peer has muted their microphone so that i can update the status from my end?

**Comment by koshelevvasya** [comment]
@thanh-mel , the remote peer does not need to know that the microphone is muted. Maybe you need to use hold?

> Any event would fire when a track is enabled/disabled
In my experience, yes. Because it is done using JavaScript
