### ISSUE TITLE
Never receiving reinvite event after hold function

### ISSUE THREAD

**Issue by alvarotreelogic** [onsip/SIP.js#495]
I'm migrating from 0.7.X to 0.9.X and i'm having problems with detecting response to hold/unhold functions. Until now there were specific events for achieving these, however now a new event reinvite is suposed to be emited after successful response. 

After reviewing the code, the response to C_INVITE request is handled by receiveReinviteResponse function which never emitts reinvite event after successful but ack event. 

In older code the response to C_INVITE was directly handled by receiveRequest which it calls to receiveReinvite function where you can find reinvite event

On the other hand, we have to control the local hold state to detect if the response of the action is hold or unhold, haven't we?

Thank you

**Comment by egreenmachine** [comment]
So you want to know when a reinvite is successful or not? This seems pretty reasonable, I will try and get it into a future release.

**Comment by alvarotreelogic** [comment]
Thank you. I would like to update visual interface depending on the response to invite request.
