### ISSUE TITLE
Simple interface does not emit mute/unmute events

### ISSUE THREAD

**Issue by cjnqt** [onsip/SIP.js#497]
Hey, thanks for a great library. 

The [documentation](https://sipjs.com/api/0.9.0/simple/) for the simple interface says that the interface emits `mute` and `unmute` events. This does not seem to be the case. The other events are emitted as expected, but there doesn't seem to be any event emitting code in the [toggleMute](https://github.com/onsip/SIP.js/blob/master/src/WebRTC/Simple.js#L352) function

**Comment by egreenmachine** [comment]
Yeah. Looks like we are not emitting the event. I will try and get this fixed for the next release. Thanks

**Comment by anshkatriya** [comment]
Hello Eric, I don't think that it's an bug. Because you are already emitting mute/unmute events for Simple. I have implemented Simple WebRTC and I am using default mute/unmute event. It's working fine also.
