### ISSUE TITLE
"Advanced" Simple Configuration Parameters docs

### ISSUE THREAD

**Issue by ghenry** [onsip/SIP.js#499]
Hi all,

Is https://sipjs.com/api/0.9.0/simple_configuration_parameters/ available via gitbooks or similar to submit doc patches?

I'd like to add these two very handy settings:

[https://github.com/onsip/SIP.js/blob/b2a22069c47aa0cf6d420223173423d6f40f7dd9/src/WebRTC/Simple.js#L83](https://github.com/onsip/SIP.js/blob/b2a22069c47aa0cf6d420223173423d6f40f7dd9/src/WebRTC/Simple.js#L83)

```
// Undocumented "Advanced" Options
traceSip:          this.options.ua.traceSip,
userAgentString: this.options.ua.userAgentString,
```

**Comment by ghenry** [comment]
They are part of a normal UA set up obviously, but it's handy via testing like so:

`const options = {
    media: {
      local: {
        video: document.getElementById('localVideo')
      },
      remote: {
        video: document.getElementById('remoteVideo'),
        // This is necessary to do an audio/video call as opposed to just a video call
        audio: document.getElementById('remoteVideo')
      }
    },
    ua: {
          displayName: "Gavin Henry",
          authorizationUser: '1000',
          password: '1000',
          wsServers: ['wss://xxx.psg.uk.suretec.net:7443'],
          traceSip: true,
          userAgentString: 'SureVoIP Portal ' + portalVersion,
    }
};
`

**Comment by egreenmachine** [comment]
https://gitlab.com/onsip/sipjs.com
