### ISSUE TITLE
How can I know if an incoming session has Video or not?

### ISSUE THREAD

**Issue by gvn182** [onsip/SIP.js#508]
`  simple.on('ringing', (session) => {
session.accept();
});`

**Comment by james-criscuolo** [comment]
This depends on if the incoming session has sdp or not. If it does not, you'll need to pass an extra header to determine what the other side wants to negotiate (there are certainly other solutions), or offer audio/video and see what they accept. If the session has SDP, you can parse it (`session.request.body`) for an m=video line.

In general please ask questions like this in our [google group](https://groups.google.com/forum/#!forum/sip_js). We try to keep this space for bugs and other issues.

Thanks,
James
