### ISSUE TITLE
can i use SIP.UA direct like Simple? I need to write audio play code myself?

### ISSUE THREAD

**Issue by winds2016** [onsip/SIP.js#510]
there is audio with Simple,but there is not audio with SIP.UA. I need to write play code myself,or my options set is wrong? 

    private mediaOptions(audio, video) {
        return {
            sessionDescriptionHandlerOptions: {
                constraints: {
                    audio: audio,
                    video: video
                },
                media: {
                    constraints: {
                        audio: audio,
                        video: video
                    },
                    render: {
                        local: {
                            video: this.videoRenderL
                        },
                        remote: {
                            video: this.videoRender,
                            // This is necessary to do an audio/video call as opposed to just a video call
                            audio: this.videoRender
                        }
                    },
                }
            }
        };
    }

**Comment by Milad** [comment]
Yes you can use SIP.UA, and you have to write media stuff yourself.

I put this together previously to test it, and this is the initial code that worked for me (a lot of improvements can be done). Focus on when you get the invite (session it provided to your callback) or send an invite (you listen to the accepted event and use the session). Then you can setup the media.

```es6
const loginButton = document.getElementById('loginButton');
const userSelect = document.getElementById('userSelect');
const callButton = document.getElementById('callButton');
const answerButton = document.getElementById('answerButton');
const phoneNumber = document.getElementById('phoneNumber');
const rejectButton = document.getElementById('rejectButton');
const cancelButton = document.getElementById('cancelButton');

loginButton.onclick = () => {
    const userAgent = new SIP.UA({
        uri: 'uri',
        wsServers: 'wsServers',
        authorizationUser: 'authorizationUser',
        password: 'password',
        sessionDescriptionHandlerFactoryOptions: {
            constraints: {
                audio: true,
                video: false
            },
            peerConnectionOptions: {
                iceCheckingTimeout: 5000,
                rtcConfiguration: {
                    rtcpMuxPolicy: 'require'
                }
            }
        }
    });

    userAgent.on('invite', (session) => {
        answerButton.onclick = () => {
            session.accept();
    
            console.log('answered');
        };
        
        rejectButton.onclick = () => {
            session.reject();
    
            console.log('rejected');
        };

        console.log('incoming call');

        session.on('accepted', () => {
            const domElement = document.getElementById('remoteAudio');
            const pc = session.sessionDescriptionHandler.peerConnection;
            const remoteStream = new MediaStream();
        
            pc.getReceivers().forEach(function(receiver) {
                const track = receiver.track;
                if (track) {
                    remoteStream.addTrack(track);
                }
            });
            domElement.srcObject = remoteStream;
            domElement.play();
        });
    });

    callButton.onclick = () => {
        console.log('Calling');
        const session = userAgent.invite(phoneNumber.value);

        cancelButton.onclick = () => {
            session.cancel();
        };

        session.on('accepted', () => {
            const domElement = document.getElementById('remoteAudio');
            const pc = session.sessionDescriptionHandler.peerConnection;
            const remoteStream = new MediaStream();
    
            pc.getReceivers().forEach(function(receiver) {
                const track = receiver.track;
                if (track) {
                    remoteStream.addTrack(track);
                }
            });
            domElement.srcObject = remoteStream;
            domElement.play();
        });
    };
};
```
You can copy it to your project and change it to your needs.

Later, I decided to do this:
`MySimple.prototype = Object.create(SIP.WebRTC.Simple.prototype);`

Check this also if you want to extend simple: https://www.digitalocean.com/community/tutorials/understanding-prototypes-and-inheritance-in-javascript

**Comment by winds2016** [comment]
thanks very much
