### ISSUE TITLE
No Audio on Unhold after register

### ISSUE THREAD

**Issue by vandykew** [onsip/SIP.js#514]
Outbound call 

Call connects --> 2 way audio --> Call put on hold --> Hold Music

sip.js registers while call on hold 

Unhold call --> No audio sent or received on sip.js

**Comment by egreenmachine** [comment]
Can you please include logs from SIP.js?

**Comment by vandykew** [comment]
How detailed do you want them, Also I noticed that it not when it registers this happens whenever the call is held for more than a few seconds ?

**Comment by egreenmachine** [comment]
Please enable `traceSip` and just give us the SIP.js default logs in a [gist](https://gist.github.com/)

**Comment by egreenmachine** [comment]
I am going to close this due to inactivity and as a duplicate of other more active issues, such as #543.
