### ISSUE TITLE
Suggestion: Change default DTMF intertone gap

### ISSUE THREAD

**Issue by seanbright** [onsip/SIP.js#519]
The INFO implementation of DTMF has a default intertone gap of 500ms which is obscenely long. The default intertone gap for `RTCDTMFSender` is 70ms. Consider reducing the default of the former to something closer to `RTCDTMFSender`'s default for parity.

**Comment by egreenmachine** [comment]
I think that `INFO` gap is so long due to compatibility with gateways converting it into inband dtmf. I would be alright with making it a configuration option on the UA.
