### ISSUE TITLE
Broken when I tried to make more than 17 concurrent calls

### ISSUE THREAD

**Issue by bharathkumardk** [onsip/SIP.js#520]
Hi,

I have a web application that could make calls between browser to softphone. When I tried to make concurrent calls, it failed after 17th call. Please find the error message below. Any thoughts to solve this? Thanks in advance.

Error Message:

sip.invitecontext.mediahandler | unable to acquire streams
c.print @ sip-0.7.8.min.js:36

sip-0.7.8.min.js:36 DOMException: Could not start source
c.print @ sip-0.7.8.min.js:3

**Comment by egreenmachine** [comment]
Please upgrade to the latest version of SIP.js. We are no longer supporting the media handler (0.7.X)

**Comment by bharath-inference** [comment]
Thanks @egreenmachine. I'm upgrading to sip 0.9.1 and will update the status soon

**Comment by bharath-inference** [comment]
Hi, I have upgraded to sip.js 9.1 but still the call is broken after 17 concurrent calls. Please find the error attached below. Any thoughts how to resolve this issue.

Error Message:

sip-0.9.1.js:807 Fri Mar 02 2018 10:48:48 GMT+1100 (AUS Eastern Summer Time) | sip.invitecontext.sessionDescriptionHandler | unable to acquire streams

DOMException: Could not start source

**Comment by egreenmachine** [comment]
I have answered this on our [mailing list](https://groups.google.com/forum/#!topic/sip_js/D6RUewGMHuM). Let's continue the discussion there.
