### ISSUE TITLE
meteor and callcentric

### ISSUE THREAD

**Issue by webmagnets** [onsip/SIP.js#522]
I'm using meteor with a callcentric number.
What do I need to put in the wsServers field?

**Comment by egreenmachine** [comment]
This is not a SIP.js issue. Please reach out to callcentric. Questions for the community go on our [mailing list](https://groups.google.com/forum/#!forum/sip_js) as this area is strictly for bugs.

**Comment by webmagnets** [comment]
Thanks. I needed to know if I would get that info from Meteor or from CallCentric.
