### ISSUE TITLE
How many concurrent calls could SIP.js handle?

### ISSUE THREAD

**Issue by bharath-inference** [onsip/SIP.js#526]
Hi, I just have this general question like did anyone tried making concurrent calls before? if so how many concurrent calls it could handle at a time? What is the sip.js version that you tried?

My observation: 

1. I have built a simple application where you can make calls from browser to softphone where the media is taken via RTP engine openSIPS

2. I used sip.js 0.7.8 to take care of signaling between browser and server

3. When I test making concurrent calls, it was working fine till 16 calls and broken after that so just wondering, whether it is an issue related to the version or Is there any concurrent call restriction by default. Please feel free to share your thoughts. Thanks

**Comment by egreenmachine** [comment]
This is not a bug. Please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js) for questions like this.
