### ISSUE TITLE
How to setup rtcp-mux policy 'negotiate' in sipjs 9.1

### ISSUE THREAD

**Issue by bharath-inference** [onsip/SIP.js#527]
When I try to make calls from browser to softphone where it goes via opensips. I'm getting the below error. Previously when I was using sipjs 0.7.8 I used to configure rtcpMuxPolicy: 'negotiate' with UA.configuration and it was working perfectly but not sure how to set up in  0.9.1. Any help to resolve this issue.

Code used to call the destination
```
` options = {
            media: {
                remote: {
                    audio: document.getElementById('remoteAudio')
                }
           },
            
            ua: {
                uri: myAuth + "@xx.xxx.xxx.xx",
                wsServers: "wss://xx.xxx.xxx.xx:4433",
                authorizationUser: '1000',
                password: '1000',
                rel100:SIP.C.supported.SUPPORTED      
            },
        };

simple = new SIP.WebRTC.Simple(options);
simple.call("xxxx@xx.xxx.xxx.xx"); `
```

Error Message:
sip-0.9.1.js:807 DOMException: Failed to set remote answer sdp: Session error code: ERROR_CONTENT. Session error description: rtcpMuxPolicy is 'require', but media description does not contain 'a=rtcp-mux'..

**Comment by egreenmachine** [comment]
You cannot set that option with `Simple`. You need to use the full SIP.js API. As this is not a bug, please use the [mailing list](https://groups.google.com/forum/#!forum/sip_js) for questions like this.
