### ISSUE TITLE
SessionDescriptionHandler addStream event documentation

### ISSUE THREAD

**Issue by adejongh** [onsip/SIP.js#528]
The documentation - https://sipjs.com/api/0.9.0/sessionDescriptionHandler/ - for the addStream event alleges that a "stream" will be passed to the listener.  It is actually the "event" from the underlying peerConnection that is passed, not the stream.  Either the docs or the code should probably change.

See:  https://github.com/onsip/SIP.js/blob/master/src/WebRTC/SessionDescriptionHandler.js#L434

**Comment by adejongh** [comment]
The addTrack event is probably similarly incorrect.

**Comment by egreenmachine** [comment]
I am currently working on making the process of getting streams easier. I will fix this in the next release. Documentation issues should go on our [documentation project](https://gitlab.com/onsip/sipjs.com).
