### ISSUE TITLE
Android Invite not sent - No error displayed - 0.9.1 - webKitRTCPeerConnection

### ISSUE THREAD

**Issue by NightOwlThe** [onsip/SIP.js#530]
SIP JS 0.9.2 does not work on Android.
Was working previously on 0.7.7 version
Registration to server and ice gathering completes successfully. Flow works fine right up to sip.invitecontext handling.
However, INVITE is not sent when triggered. _No error_ is displayed. No further logs were printed.
Below are the registration logs - the only thing that works.

Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | configuration parameters after validation:
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · viaHost: "XXX.XXX.XXX.XXX"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · uri: sip:XXXXX@XXX.com
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · wsServers: [{"ws_uri":"wss://XXX.com:443","sip_uri":"<sip:XXX.com:443;transport=ws;lr>","weight":0,"status":0,"scheme":"WSS"}]
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · custom: {}
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · displayName: "ABCD"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · password: NOT SHOWN
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · registerExpires: 600
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · register: true
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · registrarServer: sip:XXX.com
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · wsServerMaxReconnection: 3
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · wsServerReconnectionTimeout: 4
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · connectionRecoveryMinInterval: 2
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · connectionRecoveryMaxInterval: 30
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · keepAliveInterval: 0
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · extraSupported: []
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · usePreloadedRoute: false
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · userAgentString: "Android,8.0.0,Nexus 6P"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · noAnswerTimeout: 60000
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · traceSip: true
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · hackViaTcp: false
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · hackIpInContact: true
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · hackWssInTransport: true
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · hackAllowUnregisteredOptionTags: false
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · sessionDescriptionHandlerFactoryOptions: {"constraints":{"audio":true,"video":false},"iceCheckingTimeout":1000}
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · contactName: "ke7mkv7s"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · contactTransport: "wss"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · forceRport: false
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · autostart: true
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · autostop: true
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · rel100: "none"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · replaces: "none"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · sessionDescriptionHandlerFactory: function defaultFactory(session, options) {
    return new SessionDescriptionHandler(session, options);
  }
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · authenticationFactory: undefined
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · allowLegacyNotifications: false
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · allowOutOfDialogRefers: false
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · instanceId: "XXXXXXXX-XXX-XXX-XXX-XXXX"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · sipjsId: "XXXX"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · hostportParams: "XXX.com"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | · authorizationUser: "XXXXX"
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.ua | user requested startup...
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.transport | connecting to WebSocket wss://XXX.com:443
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.transport | unable to send message, WebSocket is not open
Tue Mar 06 2018 17:45:21 GMT+0530 (IST) | sip.transaction.nict | z9hG4bK9078112 | transport error occurred, deleting non-INVITE client transaction z9hG4bK9078112
Tue Mar 06 2018 17:45:22 GMT+0530 (IST) | sip.transport | WebSocket wss://XXX.com:443 connected
Tue Mar 06 2018 17:45:22 GMT+0530 (IST) | sip.ua | connection state set to 0
app.js:935 server (Connected)
Tue Mar 06 2018 17:45:22 GMT+0530 (IST) | sip.transport | sending WebSocket message:

REGISTER sip:XXX.com SIP/2.0
Via: SIP/2.0/WSS XXX.XXX.XXX.XXX;branch=z9hG4bK3208522
Max-Forwards: 70
To: "Bob" <sip:XXXXX@XXX.com>
From: "Bob" <sip:XXXXX@XXX.com>;tag=3adnmb4882
Call-ID: redv4ogfmauhm2js39quho
CSeq: 4770 REGISTER
Contact: <sip:ke7mkv7s@XXX.XXX.XXX.XXX;transport=wss>;reg-id=1;+sip.instance="<urn:uuid:XXXX-XXXX>";expires=600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: path, gruu, outbound
User-Agent: Android,8.0.0,Nexus 6P
Content-Length: 0

Tue Mar 06 2018 17:45:22 GMT+0530 (IST) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS XXX.XXX.XXX.XXX;branch=z9hG4bK3208522;rport=44293;received=YYY.YYY.YYY.YYY
To: "Bob" <sip:XXXXX@XXX.com>;tag=f90a910f0988997a840cd24075bbe8cc.e52e
From: "Bob" <sip:XXXXX@XXX.com>;tag=3adnmb4882
Call-ID: redv4ogfmauhm2js39quho
CSeq: 4770 REGISTER
WWW-Authenticate: Digest realm="XXX.com", nonce="Wp6HVlqehipu/m/R3R4GAlwptF+gvYVY"
Server: kamailio (5.0.5 (x86_64/linux))
Content-Length: 0

Tue Mar 06 2018 17:45:22 GMT+0530 (IST) | sip.transport | sending WebSocket message:

REGISTER sip:XXX.com SIP/2.0
Via: SIP/2.0/WSS XXX.XXX.XXX.XXX;branch=z9hG4bK5330678
Max-Forwards: 70
To: "Bob" <sip:XXXXX@XXX.com>
From: "Bob" <sip:XXXXX@XXX.com>;tag=3adnmb4882
Call-ID: redv4ogfmauhm2js39quho
CSeq: 4771 REGISTER
Authorization: Digest algorithm=MD5, username="XXXXX", realm="XXX.com", nonce="Wp6HVlqehipu/m/R3R4GAlwptF+gvYVY", uri="sip:XXX.com", response="9e3a8601229ea6d5da9df486ec0663bd"
Contact: <sip:ke7mkv7s@XXX.XXX.XXX.XXX;transport=wss>;reg-id=1;+sip.instance="<urn:uuid:XXXX-XXXX>";expires=600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: path, gruu, outbound
User-Agent: Android,8.0.0,Nexus 6P
Content-Length: 0

Tue Mar 06 2018 17:45:22 GMT+0530 (IST) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS XXX.XXX.XXX.XXX;branch=z9hG4bK5330678;rport=44293;received=YYY.YYY.YYY.YYY
To: "Bob" <sip:XXXXX@XXX.com>;tag=f90a910f0988997a840cd24075bbe8cc.a287
From: "Bob" <sip:XXXXX@XXX.com>;tag=3adnmb4882
Call-ID: redv4ogfmauhm2js39quho
CSeq: 4771 REGISTER
Contact: <sip:3n74dsqv@c2t9nosbulb1.invalid;transport=ws>;expires=473;received="sip:XXX.XX.XXX.XXX:56500;transport=ws";pub-gruu="sip:XXXXX@XXX.com;gr=urn:uuid:6ceef6da-af94-4c7c-8915-99c83b7d4310";temp-gruu="sip:uloc-5a93d8e6-40e5-d553-eb07a173@XXX.com;gr";+sip.instance="<urn:uuid:6ceef6da-af94-4c7c-8915-99c83b7d4310>";reg-id=1, <sip:ke7mkv7s@XXX.XXX.XXX.XXX;transport=wss>;expires=600;received="sip:YYY.YYY.YYY.YYY:44293;transport=ws";pub-gruu="sip:XXXXX@XXX.com;gr=urn:uuid:XXXX-XXXX";temp-gruu="sip:uloc-5a93d8e6-40e4-b183-eb07a173@XXX.com;gr";+sip.instance="<urn:uuid:XXXX-XXXX>";reg-id=1
Server: kamailio (5.0.5 (x86_64/linux))
Content-Length: 0

Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | initPeerConnection options.rtcConfiguration =  Object {iceServers: Array[1]}
Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | New peer connection created
Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | acquiring local media
undefined
Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | acquired local media streams
RTCSessionDescription {type: "offer", sdp: "v=0
↵o=- 5990712953388928241 2 IN IP4 127.0.0.1
↵s…9665 label:df4ae3be-5317-4cfb-9615-93b19166a434
↵"}
Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | ICE candidate received: candidate:152521221 1 udp 2113937151 YYY.YYY.YYY.YYY 49277 typ host generation 0 ufrag oMJg network-cost 50
Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | ICE candidate received: candidate:152521221 2 udp 2113937150 YYY.YYY.YYY.YYY 47263 typ host generation 0 ufrag oMJg network-cost 50
Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | ICE candidate received: candidate:842163049 1 udp 1677729535 YYY.YYY.YYY.YYY 49277 typ srflx raddr YYY.YYY.YYY.YYY rport 49277 generation 0 ufrag oMJg network-cost 50
Tue Mar 06 2018 17:50:46 GMT+0530 (IST) | sip.invitecontext.sessionDescriptionHandler | 4fmsl9mrubva0hh2cnhmim6gvg9mlb | ICE candidate received: candidate:842163049 2 udp 1677729534 YYY.YYY.YYY.YYY 47263 typ srflx raddr XXX.XX.XXX.XX

**Comment by egreenmachine** [comment]
What version of Android? And are you using Chrome on Android? If so, what version. Thanks

**Comment by egreenmachine** [comment]
You most likely need to write your own Session Description Handler. The one provided is built for web browsers, not cordova with crosswalk

**Comment by NightOwlThe** [comment]
@egreenmachine May I know the last version compatible with this setup?

**Comment by egreenmachine** [comment]
We have not supported this setup for a while. My guess would be that if 0.7.7. is working for you, then 0.7.8 should work as well. Some notes on that is that 0.7.8 uses deprecated WebRTC api calls and is no longer supported. It may continue to work for the time being, but we are not supporting it and the expectation is that it will break in the near future due to the moving API target of WebRTC.
