### ISSUE TITLE
Display caller video on ringing state

### ISSUE THREAD

**Issue by manishthakor** [onsip/SIP.js#532]
Is it possible to display caller video on ringing state to callee without answer call.

**Comment by james-criscuolo** [comment]
Hi @manishthakor,
You can negotiate early media using 183/PRACK, which should make this doable. You need to set rel100 to SUPPORTED or REQUIRED: https://sipjs.com/api/0.9.0/ua_configuration_parameters/#rel100

See also our documentation for progress:
https://sipjs.com/api/0.9.0/session/#progressoptions

Generally speaking we like to keep this space for bugs and feature requests. I'm going to close this issue, as it is a question, but please feel free to continue the conversation in our google group:
https://groups.google.com/forum/#!forum/sip_js

Thanks,
James
