### ISSUE TITLE
Failed to parse audio codecs correctly on 0.9.2 release

### ISSUE THREAD

**Issue by joshelson** [onsip/SIP.js#537]
Haven't had a ton of time to debug this one, but the 0.9.2 release has broken inbound calls to SIP.js, at least on a handful of the Asterisk 15.x releases we've been testing with. This appears to happen when early media is not being used.

 The error is:

`sip-0.9.2.js:807 DOMException: Failed to parse SessionDescription.  Failed to parse audio codecs correctly.
`

Reverting to 0.9.1 fixes the issue.

**Comment by james-criscuolo** [comment]
Hi @joshelson,
  Can you provide logs with traceSip enabled for 0.9.1 and 0.9.2? This will help us narrow down what is causing your issue.

Thanks,
James

**Comment by egreenmachine** [comment]
This is almost certainly a `modifier` issue. If you provide the logs with traceSip I can get it patched before releasing the next version.

**Comment by joshelson** [comment]
Here's the non-working 0.9.2 code:

sip-0.9.2.js:807 Wed Mar 28 2018 19:03:13 GMT-0600 (Mountain Daylight Time) | sip.transport | received WebSocket text message:

INVITE sip:0i0d41h7@206.124.1.198:64840;transport=ws SIP/2.0
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPj50e1d85d-2bc2-4cbc-b010-fcf33753b2bb;alias
From: "Joshua Elson" <sip:2125551212@server.com>;tag=90c4d227-6089-4652-8d9d-94dd8ed46849
To: <sip:0i0d41h7@206.124.1.198>
Contact: <sip:genie@server.com:5060;transport=ws>
Call-ID: 459cec18-48ae-4011-b0ec-7c16eb3f31bb
CSeq: 16805 INVITE
Allow: OPTIONS, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, REGISTER, MESSAGE, REFER
Supported: 100rel, replaces, norefersub
Max-Forwards: 70
User-Agent: FluentCloud Media v4
Content-Type: application/sdp
Content-Length:   845

v=0
o=genie 1196488598 1196488598 IN IP4 206.124.13.170
s=genie
c=IN IP4 206.124.13.170
t=0 0
m=audio 16922 UDP/TLS/RTP/SAVPF 0 107 9 97 18 8 101
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 A2:9D:41:17:F0:2C:FE:27:7C:7B:42:C9:72:EE:7D:11:B8:4D:B6:82:67:A7:EE:EF:F7:CF:D4:65:7C:42:42:32
a=ice-ufrag:060f4abe70441aca793f1dac01c85b73
a=ice-pwd:5f861bc12eccb7d1080bd59400970002
a=candidate:Hce7c0daa 1 UDP 2130706431 206.124.13.170 16922 typ host
a=candidate:Hce7c0daa 2 UDP 2130706430 206.124.13.170 16923 typ host
a=rtpmap:0 PCMU/8000
a=rtpmap:107 opus/48000/2
a=fmtp:107 useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:97 iLBC/8000
a=fmtp:97 mode=20
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:20
a=sendrecv
a=rtcp-mux


sip-0.9.2.js:807 Wed Mar 28 2018 19:03:13 GMT-0600 (Mountain Daylight Time) | sip.sipmessage | header "Content-Disposition" not present
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:13 GMT-0600 (Mountain Daylight Time) | sip.transport | sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPj50e1d85d-2bc2-4cbc-b010-fcf33753b2bb;alias
To: <sip:0i0d41h7@206.124.1.198>
From: "Joshua Elson" <sip:2125551212@server.com>;tag=90c4d227-6089-4652-8d9d-94dd8ed46849
Call-ID: 459cec18-48ae-4011-b0ec-7c16eb3f31bb
CSeq: 16805 INVITE
Supported: outbound
User-Agent: FluentCloud WebPhone
Content-Length: 0



sip-0.9.2.js:807 Wed Mar 28 2018 19:03:13 GMT-0600 (Mountain Daylight Time) | sip.dialog | 459cec18-48ae-4011-b0ec-7c16eb3f31bbuv7n6vpeus90c4d227-6089-4652-8d9d-94dd8ed46849 | new UAS dialog created with status EARLY
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:13 GMT-0600 (Mountain Daylight Time) | sip.transport | sending WebSocket message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPj50e1d85d-2bc2-4cbc-b010-fcf33753b2bb;alias
To: <sip:0i0d41h7@206.124.1.198>;tag=uv7n6vpeus
From: "Joshua Elson" <sip:2125551212@server.com>;tag=90c4d227-6089-4652-8d9d-94dd8ed46849
Call-ID: 459cec18-48ae-4011-b0ec-7c16eb3f31bb
CSeq: 16805 INVITE
Contact: <sip:0i0d41h7@192.0.2.133;transport=wss>
Supported: outbound
User-Agent: FluentCloud WebPhone
Content-Length: 0



sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.dialog | 459cec18-48ae-4011-b0ec-7c16eb3f31bbuv7n6vpeus90c4d227-6089-4652-8d9d-94dd8ed46849 | dialog 459cec18-48ae-4011-b0ec-7c16eb3f31bbuv7n6vpeus90c4d227-6089-4652-8d9d-94dd8ed46849  changed to CONFIRMED state
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | 459cec18-48ae-4011-b0ec-7c16eb3f31bb90c4d227-6089-4652-8d9d-94dd8ed46849 | initPeerConnection
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | 459cec18-48ae-4011-b0ec-7c16eb3f31bb90c4d227-6089-4652-8d9d-94dd8ed46849 | New peer connection created
phone.js:117 Setting up session
sip-0.9.2.js:11735 [Violation] 'message' handler took 2603ms
sip-0.9.2.js:807 DOMException: Failed to parse SessionDescription.  Failed to parse audio codecs correctly.
LoggerFactory.print @ sip-0.9.2.js:807
LoggerFactory.(anonymous function) @ sip-0.9.2.js:824
Logger.(anonymous function) @ sip-0.9.2.js:818
setRemoteDescriptionError @ sip-0.9.2.js:8878
Promise.catch (async)
setDescription @ sip-0.9.2.js:8876
accept @ sip-0.9.2.js:5601
handleInvite @ phone.js:72
EventEmitter.emit @ sip-0.9.2.js:964
UA.receiveRequest @ sip-0.9.2.js:7755
onMessage @ sip-0.9.2.js:11868
ws.onmessage @ sip-0.9.2.js:11736
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.transport | sending WebSocket message:

SIP/2.0 480 Temporarily Unavailable
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPj50e1d85d-2bc2-4cbc-b010-fcf33753b2bb;alias
To: <sip:0i0d41h7@206.124.1.198>;tag=uv7n6vpeus
From: "Joshua Elson" <sip:2125551212@server.com>;tag=90c4d227-6089-4652-8d9d-94dd8ed46849
Call-ID: 459cec18-48ae-4011-b0ec-7c16eb3f31bb
CSeq: 16805 INVITE
Supported: outbound
User-Agent: FluentCloud WebPhone
Content-Length: 0

phone.js:128 Got termination
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.inviteservercontext | 459cec18-48ae-4011-b0ec-7c16eb3f31bb90c4d227-6089-4652-8d9d-94dd8ed46849 | closing INVITE session 459cec18-48ae-4011-b0ec-7c16eb3f31bb90c4d227-6089-4652-8d9d-94dd8ed46849
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | 459cec18-48ae-4011-b0ec-7c16eb3f31bb90c4d227-6089-4652-8d9d-94dd8ed46849 | closing PeerConnection
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.dialog | 459cec18-48ae-4011-b0ec-7c16eb3f31bbuv7n6vpeus90c4d227-6089-4652-8d9d-94dd8ed46849 | dialog 459cec18-48ae-4011-b0ec-7c16eb3f31bbuv7n6vpeus90c4d227-6089-4652-8d9d-94dd8ed46849 deleted
sip-0.9.2.js:807 Wed Mar 28 2018 19:03:16 GMT-0600 (Mountain Daylight Time) | sip.transport | received WebSocket text message:

ACK sip:0i0d41h7@206.124.1.198:64840;transport=ws SIP/2.0
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPj50e1d85d-2bc2-4cbc-b010-fcf33753b2bb;alias
From: "Joshua Elson" <sip:2125551212@server.com>;tag=90c4d227-6089-4652-8d9d-94dd8ed46849
To: <sip:0i0d41h7@206.124.1.198>;tag=uv7n6vpeus
Call-ID: 459cec18-48ae-4011-b0ec-7c16eb3f31bb
CSeq: 16805 ACK
Max-Forwards: 70
User-Agent: FluentCloud Media v4
Content-Length:  0


Here's the working old one:


sip-0.9.1.js:807 Wed Mar 28 2018 19:07:42 GMT-0600 (Mountain Daylight Time) | sip.transport | received WebSocket text message:

INVITE sip:v5g90r3d@206.124.1.198:50165;transport=ws SIP/2.0
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPjfd7152a3-c613-4138-bc6c-7a50bd9a3896;alias
From: "Joshua Elson" <sip:2125551212@server.com>;tag=2741e8bc-f6ba-49b5-895f-2fb1bdb46247
To: <sip:v5g90r3d@206.124.1.198>
Contact: <sip:genie@server.com:5060;transport=ws>
Call-ID: ce2bd72d-5eb2-4b9a-a23b-b14209099445
CSeq: 19986 INVITE
Allow: OPTIONS, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, REGISTER, MESSAGE, REFER
Supported: 100rel, replaces, norefersub
Max-Forwards: 70
User-Agent: FluentCloud Media v4
Content-Type: application/sdp
Content-Length:   843

v=0
o=genie 954566670 954566670 IN IP4 206.124.13.170
s=genie
c=IN IP4 206.124.13.170
t=0 0
m=audio 19066 UDP/TLS/RTP/SAVPF 0 107 9 97 18 8 101
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 A2:9D:41:17:F0:2C:FE:27:7C:7B:42:C9:72:EE:7D:11:B8:4D:B6:82:67:A7:EE:EF:F7:CF:D4:65:7C:42:42:32
a=ice-ufrag:466c210016c6099a70d64deb37a12284
a=ice-pwd:275ea7112b8b776a019662cf0a11c5db
a=candidate:Hce7c0daa 1 UDP 2130706431 206.124.13.170 19066 typ host
a=candidate:Hce7c0daa 2 UDP 2130706430 206.124.13.170 19067 typ host
a=rtpmap:0 PCMU/8000
a=rtpmap:107 opus/48000/2
a=fmtp:107 useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:97 iLBC/8000
a=fmtp:97 mode=20
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:20
a=sendrecv
a=rtcp-mux


sip-0.9.1.js:807 Wed Mar 28 2018 19:07:42 GMT-0600 (Mountain Daylight Time) | sip.sipmessage | header "Content-Disposition" not present
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:42 GMT-0600 (Mountain Daylight Time) | sip.transport | sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPjfd7152a3-c613-4138-bc6c-7a50bd9a3896;alias
To: <sip:v5g90r3d@206.124.1.198>
From: "Joshua Elson" <sip:2125551212@server.com>;tag=2741e8bc-f6ba-49b5-895f-2fb1bdb46247
Call-ID: ce2bd72d-5eb2-4b9a-a23b-b14209099445
CSeq: 19986 INVITE
Supported: outbound
User-Agent: FluentCloud WebPhone
Content-Length: 0



sip-0.9.1.js:807 Wed Mar 28 2018 19:07:42 GMT-0600 (Mountain Daylight Time) | sip.dialog | ce2bd72d-5eb2-4b9a-a23b-b14209099445bnf7bdo17o2741e8bc-f6ba-49b5-895f-2fb1bdb46247 | new UAS dialog created with status EARLY
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:42 GMT-0600 (Mountain Daylight Time) | sip.transport | sending WebSocket message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPjfd7152a3-c613-4138-bc6c-7a50bd9a3896;alias
To: <sip:v5g90r3d@206.124.1.198>;tag=bnf7bdo17o
From: "Joshua Elson" <sip:2125551212@server.com>;tag=2741e8bc-f6ba-49b5-895f-2fb1bdb46247
Call-ID: ce2bd72d-5eb2-4b9a-a23b-b14209099445
CSeq: 19986 INVITE
Contact: <sip:v5g90r3d@192.0.2.42;transport=wss>
Supported: outbound
User-Agent: FluentCloud WebPhone
Content-Length: 0



sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.dialog | ce2bd72d-5eb2-4b9a-a23b-b14209099445bnf7bdo17o2741e8bc-f6ba-49b5-895f-2fb1bdb46247 | dialog ce2bd72d-5eb2-4b9a-a23b-b14209099445bnf7bdo17o2741e8bc-f6ba-49b5-895f-2fb1bdb46247  changed to CONFIRMED state
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | initPeerConnection
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | New peer connection created
phone.js:117 Setting up session
sip-0.9.1.js:11729 [Violation] 'message' handler took 1582ms
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | Using deprecated stream API
LoggerFactory.print @ sip-0.9.1.js:807
LoggerFactory.(anonymous function) @ sip-0.9.1.js:824
Logger.(anonymous function) @ sip-0.9.1.js:818
peerConnection.onaddstream @ sip-0.9.1.js:8973
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | stream added
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | track added
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | acquiring local media
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | acquired local media streams
sip-0.9.1.js:807 RTCSessionDescription {type: "answer", sdp: "v=0
↵o=- 710060747576955595 2 IN IP4 127.0.0.1
↵s=…6114 label:69e545d4-d61e-4fa0-9c61-3b544556346c
↵"}
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | RTCIceGatheringState changed: gathering
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | ICE candidate received: candidate:678820566 1 udp 2122260223 192.168.0.19 65432 typ host generation 0 ufrag 78S8 network-id 2
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | ICE candidate received: candidate:3404171324 1 udp 2122194687 192.168.0.159 63747 typ host generation 0 ufrag 78S8 network-id 1 network-cost 10
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | ICE candidate received: candidate:3731194626 1 udp 1686052607 206.124.1.198 65432 typ srflx raddr 192.168.0.19 rport 65432 generation 0 ufrag 78S8 network-id 2
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | ICE candidate received: candidate:1269796488 1 udp 1685987071 206.124.1.198 63747 typ srflx raddr 192.168.0.159 rport 63747 generation 0 ufrag 78S8 network-id 1 network-cost 10
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | ICE candidate received: candidate:1727399462 1 tcp 1518280447 192.168.0.19 9 typ host tcptype active generation 0 ufrag 78S8 network-id 2
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | ICE candidate received: candidate:2221176012 1 tcp 1518214911 192.168.0.159 9 typ host tcptype active generation 0 ufrag 78S8 network-id 1 network-cost 10
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | RTCIceGatheringState changed: complete
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPjfd7152a3-c613-4138-bc6c-7a50bd9a3896;alias
To: <sip:v5g90r3d@206.124.1.198>;tag=bnf7bdo17o
From: "Joshua Elson" <sip:2125551212@server.com>;tag=2741e8bc-f6ba-49b5-895f-2fb1bdb46247
Call-ID: ce2bd72d-5eb2-4b9a-a23b-b14209099445
CSeq: 19986 INVITE
Contact: <sip:v5g90r3d@192.0.2.42;transport=wss>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound
User-Agent: FluentCloud WebPhone
Content-Type: application/sdp
Content-Length: 1348

v=0
o=- 710060747576955595 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS liCWZvJLfvfP8a0mBrCP6agYXczL6R37DvEr
m=audio 65432 UDP/TLS/RTP/SAVPF 0 107 8 101
c=IN IP4 206.124.1.198
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:678820566 1 udp 2122260223 192.168.0.19 65432 typ host generation 0 network-id 2
a=candidate:3404171324 1 udp 2122194687 192.168.0.159 63747 typ host generation 0 network-id 1 network-cost 10
a=candidate:3731194626 1 udp 1686052607 206.124.1.198 65432 typ srflx raddr 192.168.0.19 rport 65432 generation 0 network-id 2
a=candidate:1269796488 1 udp 1685987071 206.124.1.198 63747 typ srflx raddr 192.168.0.159 rport 63747 generation 0 network-id 1 network-cost 10
a=ice-ufrag:78S8
a=ice-pwd:XQiwQqGtUyLC+1/qtVwa2sse
a=ice-options:trickle
a=fingerprint:sha-256 E2:05:57:F3:84:25:BE:0C:95:3E:9D:59:36:9B:96:32:DE:26:37:23:FA:6F:DC:72:91:C3:30:9E:C0:92:EA:A9
a=setup:active
a=mid:audio
a=sendrecv
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtpmap:107 opus/48000/2
a=fmtp:107 minptime=10;useinbandfec=1
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ssrc:328106114 cname:L8E0cXlJQ/cpZRiR
a=ssrc:328106114 msid:liCWZvJLfvfP8a0mBrCP6agYXczL6R37DvEr 69e545d4-d61e-4fa0-9c61-3b544556346c
a=ssrc:328106114 mslabel:liCWZvJLfvfP8a0mBrCP6agYXczL6R37DvEr
a=ssrc:328106114 label:69e545d4-d61e-4fa0-9c61-3b544556346c


phone.js:134 Got accepted
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:44 GMT-0600 (Mountain Daylight Time) | sip.transport | received WebSocket text message:

ACK sip:v5g90r3d@206.124.1.198:50165;transport=ws SIP/2.0
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPj0ab0e6a4-9fc6-45b2-bd62-8169ca6056b6;alias
From: "Joshua Elson" <sip:2125551212@server.com>;tag=2741e8bc-f6ba-49b5-895f-2fb1bdb46247
To: <sip:v5g90r3d@206.124.1.198>;tag=bnf7bdo17o
Call-ID: ce2bd72d-5eb2-4b9a-a23b-b14209099445
CSeq: 19986 ACK
Max-Forwards: 70
User-Agent: FluentCloud Media v4
Content-Length:  0



sip-0.9.1.js:807 Wed Mar 28 2018 19:07:50 GMT-0600 (Mountain Daylight Time) | sip.transport | received WebSocket text message:

BYE sip:v5g90r3d@206.124.1.198:50165;transport=ws SIP/2.0
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPjad0f5a82-6135-46d9-a785-52564123a2c0;alias
From: "Joshua Elson" <sip:2125551212@server.com>;tag=2741e8bc-f6ba-49b5-895f-2fb1bdb46247
To: <sip:v5g90r3d@206.124.1.198>;tag=bnf7bdo17o
Call-ID: ce2bd72d-5eb2-4b9a-a23b-b14209099445
CSeq: 19987 BYE
Max-Forwards: 70
User-Agent: FluentCloud Media v4
Content-Length:  0



sip-0.9.1.js:807 Wed Mar 28 2018 19:07:50 GMT-0600 (Mountain Daylight Time) | sip.transport | sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 206.124.13.170:8089;rport;branch=z9hG4bKPjad0f5a82-6135-46d9-a785-52564123a2c0;alias
To: <sip:v5g90r3d@206.124.1.198>;tag=bnf7bdo17o
From: "Joshua Elson" <sip:2125551212@server.com>;tag=2741e8bc-f6ba-49b5-895f-2fb1bdb46247
Call-ID: ce2bd72d-5eb2-4b9a-a23b-b14209099445
CSeq: 19987 BYE
Supported: outbound
User-Agent: FluentCloud WebPhone
Content-Length: 0



phone.js:128 Got termination
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:50 GMT-0600 (Mountain Daylight Time) | sip.inviteservercontext | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | closing INVITE session ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:50 GMT-0600 (Mountain Daylight Time) | sip.invitecontext.sessionDescriptionHandler | ce2bd72d-5eb2-4b9a-a23b-b142090994452741e8bc-f6ba-49b5-895f-2fb1bdb46247 | closing PeerConnection
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:50 GMT-0600 (Mountain Daylight Time) | sip.dialog | ce2bd72d-5eb2-4b9a-a23b-b14209099445bnf7bdo17o2741e8bc-f6ba-49b5-895f-2fb1bdb46247 | dialog ce2bd72d-5eb2-4b9a-a23b-b14209099445bnf7bdo17o2741e8bc-f6ba-49b5-895f-2fb1bdb46247 deleted
phone.js:153 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
attachMediaStream @ phone.js:153
onTerminated @ phone.js:130
g @ sip-0.9.1.js:1048
EventEmitter.emit @ sip-0.9.1.js:964
receiveRequest @ sip-0.9.1.js:5002
receiveRequest @ sip-0.9.1.js:5725
receiveRequest @ sip-0.9.1.js:3726
UA.receiveRequest @ sip-0.9.1.js:7808
onMessage @ sip-0.9.1.js:11862
ws.onmessage @ sip-0.9.1.js:11730
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:50 GMT-0600 (Mountain Daylight Time) | sip.transaction.nist | z9hG4bKPjad0f5a82-6135-46d9-a785-52564123a2c0 | Timer J expired for non-INVITE server transaction z9hG4bKPjad0f5a82-6135-46d9-a785-52564123a2c0
61phone.js:170 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
(anonymous) @ phone.js:170
setInterval (async)
ensureMediaPlaying @ phone.js:168
attachMediaStream @ phone.js:162
onTerminated @ phone.js:130
g @ sip-0.9.1.js:1048
EventEmitter.emit @ sip-0.9.1.js:964
receiveRequest @ sip-0.9.1.js:5002
receiveRequest @ sip-0.9.1.js:5725
receiveRequest @ sip-0.9.1.js:3726
UA.receiveRequest @ sip-0.9.1.js:7808
onMessage @ sip-0.9.1.js:11862
ws.onmessage @ sip-0.9.1.js:11730
sip-0.9.1.js:807 Wed Mar 28 2018 19:07:56 GMT-0600 (Mountain Daylight Time) | sip.transport | received WebSocket text message:

**Comment by egreenmachine** [comment]
Are you running a clean version of SIP.js without any hacks? Are you using any SDP modifiers or munging the SDP in any way?

**Comment by joshelson** [comment]
These are the modifiers that we're running on both versions:

var modifierArray = [
  SIP.WebRTC.Modifiers.stripTcpCandidates,
  SIP.WebRTC.Modifiers.stripG722,
  SIP.WebRTC.Modifiers.stripTelephoneEvent
];

**Comment by egreenmachine** [comment]
Can you try removing the `stripTelephoneEvent` modifier? It was broken in 0.9.1 and not actually doing anything. It looks like it doesn't fully remove that part of the SDP from your SDP.

If you believe that you actually need that modifier, I can modify it to fully remove that part of the SDP.

**Comment by joshelson** [comment]
That definitely did the trick @egreenmachine. I should have seen that one since I've been writing a few other modifiers and was aware of when they were getting fired in the SDP.

We did have a need for this at one point, but it probably isn't critical. Would be good to have it available, if possible or at least removed if it's not going to work.
