### ISSUE TITLE
sipjs.com is unavailable 

### ISSUE THREAD

**Issue by khalitovsv** [onsip/SIP.js#539]
Bad certificates and 404 (The page you're looking for could not be found.)

**Comment by Hakim-Bou** [comment]
@khalitovsv You can still access to the doc here -> https://gitlab.com/onsip/sipjs.com for the moment

**Comment by james-criscuolo** [comment]
We are investigating this. We suspect it's something with gitlab's new release, but we did not change anything. As @Hakim-Bou said, you can visit the gitlab repo for the documentation in the meantime.

Thanks,
James

**Comment by james-criscuolo** [comment]
This is now resolved. Thanks again for letting us know!
