### ISSUE TITLE
sip.transport | error connecting to WebSocket wss://xxx.yyy.zzz.vvv: TypeError: t is not a constructor

### ISSUE THREAD

**Issue by chefkoch009** [onsip/SIP.js#542]
I get this message if I start:

sip.transport | error connecting to WebSocket wss://xxx.yyy.zzz.vvv: TypeError: t is not a constructor

and later:

TypeError: Cannot set property 'binaryType' of null
    at i.connect (\node_modules\sip.js\dist\sip.min.js:38:189496)
    at new i (\node_modules\sip.js\dist\sip.min.js:38:187581)
    at o.start (\node_modules\sip.js\dist\sip.min.js:38:114349)
    at new o (\iobroker\node_modules\sip.js\dist\sip.min.js:38:111720)
    at Object.<anonymous> (\node_modules\iobroker.sip\main.js:17:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

this is my last program snippet:

const` SIP =  require('sip.js');
const bob = new SIP.UA({
    uri         :           'user@ip.of.my.sipserver',
    wsServers   :           'wss://ip.of.my.sipserver',
    register    :           true
});
bob.start();

I tried some different configurations, but no one solved the problem. The installation of sip.js was via npm.

**Comment by egreenmachine** [comment]
Are you running this in a web browser?

**Comment by chefkoch009** [comment]
No, in my dev-enviroment.

**Comment by egreenmachine** [comment]
Do you have websocket support? It appears that you are failing to connect to the websocket. You should see an error message along the lines of `error connecting to WebSocket`

**Comment by chefkoch009** [comment]
Thanks for your fast response. Is it possible to connect to the SIP server without webSocket? Btw I'm able to connect to the SIP server with the SIP client "microSIP".

**Comment by egreenmachine** [comment]
You need to define your own `Transport`. It has been done in the past, but it is currently not a straight forward endeavor. I am actively working on cleaning up this piece of the code and making it easier to define your own. It will not be in the next release of SIP.js, but it should be the release after that.

**Comment by chefkoch009** [comment]
Thanks for the information. For now I use askozia as SIP2WebRTC. But it makes all the Things much complex as it should. For example connecting to a door communication system. Or do you know an other way?

**Comment by JimGreenberg** [comment]
An update on this: the 0.11.0 release represents a huge refactor for the transport code- with the purpose of making this type of thing a lot easier. The UA now has a configuration parameter `transportConstructor` where you can give it a user-defined `Transport` (as @egreenmachine said). This will allow you write your own `Transport` around the connection type of your choice. There isn't a formal guide yet, but the [documentation](sipjs.com) has a writeup on both the `Transport` parent class, as well as the default websocket transport. This isn't going to be totally simple, but we tried to make it as straightforward as possible- as always, if you need help we have a [mailing list](https://groups.google.com/forum/#!forum/sip_js) that gets checked frequently.

**Comment by sudoGenie** [comment]
> An update on this: the 0.11.0 release represents a huge refactor for the transport code- with the purpose of making this type of thing a lot easier. The UA now has a configuration parameter `transportConstructor` where you can give it a user-defined `Transport` (as @egreenmachine said). This will allow you write your own `Transport` around the connection type of your choice. There isn't a formal guide yet, but the [documentation](https://sipjs.com) has a writeup on both the `Transport` parent class, as well as the default websocket transport. This isn't going to be totally simple, but we tried to make it as straightforward as possible- as always, if you need help we have a [mailing list](https://groups.google.com/forum/#!forum/sip_js) that gets checked frequently.

Is there a Update to where we can specify not to use WSS and strictly use our own Transport UDP (dgram) or TCP (net)
