### ISSUE TITLE
0.9.2 Chrome incoming call

### ISSUE THREAD

**Issue by host138** [onsip/SIP.js#546]
You wrote:
https://github.com/onsip/SIP.js/pull/426

Example of media handling in application
`session.on('accepted', function() {
    var streams = session.sessionDescriptionHandler.peerConnection.getRemoteStreams();
    var remoteElem = document.getElementById('remoteAudio');
    remoteElem.srcObject = streams[0];
    remoteElem.play();
});`

In firefox this work perfectly, but in Chrome 65 return null for getReceivers and getRemoteStreams with option rtcpMuxPolicy: 'negotiate'.

How to attach stream to media tag in browser?

**Comment by egreenmachine** [comment]
I cannot reproduce in Chrome. Can you please include full logs with `traceSip` enabled?

**Comment by host138** [comment]
i solve this problem with update asterisk from v11 to v13 and remove rtcpMuxPolicy option (by default - require)
