### ISSUE TITLE
chrome crash when hold/unhold call

### ISSUE THREAD

**Issue by vitconhocboi** [onsip/SIP.js#547]
Sometimes receiving a call, Chrome crashes when I unhold the call. This issue often happens when multi times receive the call and hold, unhold. I don't know something wrong, please help me. Sorry for my English

**Comment by egreenmachine** [comment]
Please include logs with traceSip enabled.

**Comment by vitconhocboi** [comment]
I don't see any abnormal logs, but I debug I see that chrome crashed when change toggleMute by assign ender.track.enabled = !mute. I think assignment pointed to invalidate memory cause chrome crashed

**Comment by egreenmachine** [comment]
Please include logs with traceSip enabled.

**Comment by vitconhocboi** [comment]
[siplog.txt](https://github.com/onsip/SIP.js/files/1969637/siplog.txt)
pls help me, chrome crash after the third call

**Comment by vitconhocboi** [comment]
pls help me, chrome crash after

**Comment by egreenmachine** [comment]
Please upgrade to the latest 0.10.0 release and let us know if the issue persists

**Comment by hitokiri82** [comment]
Has anyone been able to confirm if this issue is still present in 0.10.0?

**Comment by rodrigodc** [comment]
Hello, @vitconhocboi have you had any success with 0.10.0?

**Comment by egreenmachine** [comment]
I have tested hold/unhold on SIP.js in 0.11.2 in Chrome, Firefox, Safari, and Opera and have not had any crashes. Please let me know if you are still experiencing this with the latest SIP.js otherwise I will close this issue in a week.

**Comment by egreenmachine** [comment]
Due to lack of activity and the belief that we have fixed this, I am closing this issue. Please feel free to reopen if you test on the latest SIP.js and believe that it is still broken.
