### ISSUE TITLE
Error migrating from 0.7.5 to 0.10.0

### ISSUE THREAD

**Issue by babakyakhchali** [onsip/SIP.js#548]
Hi
I'm using sipjs 0.7.5 on a web client and everything works fine, but if I change to version 0.10.0 the same code throws this error in chrome console:
sip.invitecontext.sessionDescriptionHandler | unable to acquire streams
and
DOMException: Requested device not found
browser is 65.0.3325.181 (Official Build) (64-bit) (cohort: Stable)
and running win 10
how can I migrate to 0.10.0?
thanks

**Comment by egreenmachine** [comment]
Please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js) for questions like this.
