### ISSUE TITLE
Can't set establishment in Firefox in the direction of recvonly

### ISSUE THREAD

**Issue by ytian801** [onsip/SIP.js#550]
https://github.com/onsip/SIP.js/blob/master/src/WebRTC/SessionDescriptionHandler.js#L244

In this line, if I don't publish any stream and only want to receive in Firefox, disableRenegotiation is set to ture, so the establishment is failed

Any reason why?

**Comment by egreenmachine** [comment]
This was due to a bug in trying to hold video in Firefox when I was first working on that code. If I can get some time I will test to see if it is still happening.

**Comment by andriy-f** [comment]
I have commented that line recently, seems working

**Comment by egreenmachine** [comment]
The `disableRenegotiation` flag has been removed as of f96db107ede32741fc10637984fe8d2ee186668a
