### ISSUE TITLE
Transfer example ?

### ISSUE THREAD

**Issue by pengweichu** [onsip/SIP.js#552]
Hi, does there has example or demo which support the transfer and attended transfer ?

Thanks

**Comment by egreenmachine** [comment]
Please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js) for questions like this as it is not a bug with the library itself.

We have a [transfer guide](https://sipjs.com/guides/transfer/) that shows how to do a blind transfer. You will can pass an active session as a target to refer and that would be an attended transfer.
