### ISSUE TITLE
How can i disable ice?when i use in intranet,not internet

### ISSUE THREAD

**Issue by winds2016** [onsip/SIP.js#553]
Can i disable ice?
When i hold talk for a time,it will show ice failed,and then,unhold can success,but have not audio!
I use freeswitch as server.

**Comment by egreenmachine** [comment]
This is outside of the scope of SIP.js and is controlled by the underlying media layer, on the web it is WebRTC. As far as I know, there is no way to disable ICE on WebRTC. 

Please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js) for questions like this as it is not a bug in SIP.js.

**Comment by winds2016** [comment]
OK ,thanks
