### ISSUE TITLE
SIP.Subscription ERROR chan_sip.c:28431 handle_request_subscribe: SUBSCRIBE failure: no Accept header: pvt: stateid: -1, laststate: 0, dialogver: 0, subscribecont: 'XYZ', subscribeuri:

### ISSUE THREAD

**Issue by TayyabTalha** [onsip/SIP.js#554]
I'm using asterisk and trying to subscribe. On asterisk i get error **chan_sip.c:28431 handle_request_subscribe: SUBSCRIBE failure: no Accept header: pvt: stateid: -1, laststate: 0, dialogver: 0, subscribecont: 'XYZ', subscribeuri: ''**

The error is due to sipjs is not sending accept header so can resolve it by 
_subscription = ua.subscribe('123@XYX.com', 'presence', {extraHeaders:['Accept: application/pidf+xml']});_

Kindly add this header by default or document it in documentation

**Comment by egreenmachine** [comment]
SIP.js does not support RFC 3863 or RFC 5262, so adding the default header does not seem corret. The solution you have outlined is the best solution for your specific issue. If you wish to submit a PR adding support for those RFCs that would be much appreciated. Other than that I am not sure what documentation on our end could be updated. You can submit a PR to our documentation on [Gitlab]( https://gitlab.com/onsip/sipjs.com).
