### ISSUE TITLE
Inbound call leads to "ICE failed" in Firefox

### ISSUE THREAD

**Issue by tr1cks** [onsip/SIP.js#555]
Outbound calls looks like ok. At least I can establish connection and hear a echo, when doing local testing. But when I try to get inbound call in web SIP client it pass all phases of acceptance, but than I get "ICE failed, add a TURN server and see about:webrtc for more details." and no sound.

Environment:
1. Firefox 59.0.3 on Windows 10. My web client.
2. FreeSWITCH Version 1.6.18+git~20170612T211449Z~6e79667c0a~64bit.
3. Linphone Desktop 4.0 - Qt5.9.0, Core 3.11.2-158-g4c291e2 on Windows 10. As other side softphone.
4. Zoiper5 5.2.16 for Windows 64bit, Library revision: v2.8.95. Instead of Linphone with same result.

Can't try other browser, because all of them founded on Chrome code base and require https and wss. It making things hard with self-signed certificates, especially for wss (I don't found yet simple way to import it certificate).

Any thoughts about the problem? I can provide further diagnostic info, just say what needed.

**Comment by egreenmachine** [comment]
I need some more complete logs from SIP.js. It seems like the offer coming into the browser does not have an ICE candidate that WebRTC can connect to. As this is not a bug with SIP.js, please ask questions like this on our [mailing list](https://groups.google.com/forum/#!forum/sip_js).

**Comment by tr1cks** [comment]
Ok, let's continue in mailing list. What you mean by "ICE candidate"?
