### ISSUE TITLE
Can't accept call, createOfferOrAnswerError in Chrome55

### ISSUE THREAD

**Issue by vonvey** [onsip/SIP.js#559]
Can not accept the call in Chrome55

    session.accept({
            media: {
                constraints: {
                    audio: true,
                    video: false
                },
                render: {
                    remote: document.getElementById("audio_remote")
                }
            }
    });

**Comment by vonvey** [comment]
sip log

    Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | configuration parameters after validation:
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · viaHost: "192.0.2.166"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · uri: sip:60000019023@10.10.6.162
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · wsServers: [{"ws_uri":"wss://webrtc-1.ti-net.cn:80/ws","sip_uri":"<sip:webrtc-1.ti-net.cn:80;transport=ws;lr>","weight":0,"status":0,"scheme":"WSS"}]
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · custom: {}
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · displayName: ""
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · password: NOT SHOWN
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · registerExpires: 600
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · register: true
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · registrarServer: sip:10.10.6.162
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · wsServerMaxReconnection: 3
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · wsServerReconnectionTimeout: 4
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · connectionRecoveryMinInterval: 2
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · connectionRecoveryMaxInterval: 30
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · keepAliveInterval: 0
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · extraSupported: []
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · usePreloadedRoute: false
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · userAgentString: "SIP.js/0.9.1"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · noAnswerTimeout: 60000
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · traceSip: true
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · hackViaTcp: false
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · hackIpInContact: true
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · hackWssInTransport: false
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · hackAllowUnregisteredOptionTags: false
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · sessionDescriptionHandlerFactoryOptions: {"constraints":{"audio":true,"video":false},"peerConnectionOptions":{"iceCheckingTimeout":5000,"rtcConfiguration":{"iceServers":[{"urls":"turn:52.83.196.19:7478?transport=udp","username":"test","password":"test","credential":"test"}]}}}
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · contactName: "ig27h7ar"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · contactTransport: "ws"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · forceRport: false
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · autostart: true
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · autostop: true
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · rel100: "none"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · replaces: "none"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · sessionDescriptionHandlerFactory: function defaultFactory(session, options) {
        return new SessionDescriptionHandler(session, options);
      }
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · authenticationFactory: undefined
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · allowLegacyNotifications: false
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · allowOutOfDialogRefers: false
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · authorizationUser: "60000019023"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · instanceId: "9a7ba5c6-1161-44bd-ac29-643e7df6baf2"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · sipjsId: "tvg9f"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | · hostportParams: "10.10.6.162"
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | user requested startup...
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.transport | connecting to WebSocket wss://webrtc-1.ti-net.cn:80/ws
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.transport | WebSocket wss://webrtc-1.ti-net.cn:80/ws connected
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.ua | connection state set to 0
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    REGISTER sip:10.10.6.162 SIP/2.0
    Via: SIP/2.0/WSS 192.0.2.166;branch=z9hG4bK307536
    Max-Forwards: 70
    To: <sip:60000019023@10.10.6.162>
    From: <sip:60000019023@10.10.6.162>;tag=hul21964f8
    Call-ID: miqksg4ku85vl64fli4auh
    CSeq: 8883 REGISTER
    Contact: <sip:ig27h7ar@192.0.2.166;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:9a7ba5c6-1161-44bd-ac29-643e7df6baf2>";expires=600
    Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
    Supported: path, gruu, outbound
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    SIP/2.0 401 Unauthorized
    Via: SIP/2.0/WSS 192.0.2.166;rport=64671;received=114.251.47.68;branch=z9hG4bK307536
    Call-ID: miqksg4ku85vl64fli4auh
    From: <sip:60000019023@10.10.6.162>;tag=hul21964f8
    To: <sip:60000019023@10.10.6.162>;tag=z9hG4bK307536
    CSeq: 8883 REGISTER
    WWW-Authenticate: Digest  realm="asterisk",nonce="1527077939/648148757e09e8f9c37dbd0b1fc26816",opaque="1d1f38751358b5fd",algorithm=md5,qop="auth"
    Server: Asterisk PBX 13.20.0
    Content-Length:  0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    REGISTER sip:10.10.6.162 SIP/2.0
    Via: SIP/2.0/WSS 192.0.2.166;branch=z9hG4bK4549327
    Max-Forwards: 70
    To: <sip:60000019023@10.10.6.162>
    From: <sip:60000019023@10.10.6.162>;tag=hul21964f8
    Call-ID: miqksg4ku85vl64fli4auh
    CSeq: 8884 REGISTER
    Authorization: Digest algorithm=MD5, username="60000019023", realm="asterisk", nonce="1527077939/648148757e09e8f9c37dbd0b1fc26816", uri="sip:10.10.6.162", response="0fe2f6c7782b356eeddf3bf4fdab5b4f", opaque="1d1f38751358b5fd", qop=auth, cnonce="hes678s0hshh", nc=00000001
    Contact: <sip:ig27h7ar@192.0.2.166;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:9a7ba5c6-1161-44bd-ac29-643e7df6baf2>";expires=600
    Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
    Supported: path, gruu, outbound
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:18:59 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    SIP/2.0 200 OK
    Via: SIP/2.0/WSS 192.0.2.166;rport=64671;received=114.251.47.68;branch=z9hG4bK4549327
    Call-ID: miqksg4ku85vl64fli4auh
    From: <sip:60000019023@10.10.6.162>;tag=hul21964f8
    To: <sip:60000019023@10.10.6.162>;tag=z9hG4bK4549327
    CSeq: 8884 REGISTER
    Date: Wed, 23 May 2018 12:18:59 GMT
    Contact: <sip:ig27h7ar@114.251.47.68:64671;transport=ws>;expires=599
    Server: Asterisk PBX 13.20.0
    Content-Length:  0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:00 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    OPTIONS sip:ig27h7ar@114.251.47.68:64671;transport=ws SIP/2.0
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPja477c818-8611-4567-a9c2-4c42a4a17ec7;alias
    From: <sip:60000019023@ip-10-10-6-162>;tag=74ad2be0-030a-46b9-b8c2-3473bbf60f90
    To: <sip:ig27h7ar@114.251.47.68>
    Contact: <sip:60000019023@ip-10-10-6-162:5060;transport=ws>
    Call-ID: d2a7bc7c-6a10-46be-9ab4-88a609a52838
    CSeq: 9333 OPTIONS
    Max-Forwards: 70
    User-Agent: Asterisk PBX 13.20.0
    Content-Length:  0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:00 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    SIP/2.0 200 OK
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPja477c818-8611-4567-a9c2-4c42a4a17ec7;alias
    To: <sip:ig27h7ar@114.251.47.68>;tag=1nnsine00u
    From: <sip:60000019023@ip-10-10-6-162>;tag=74ad2be0-030a-46b9-b8c2-3473bbf60f90
    Call-ID: d2a7bc7c-6a10-46be-9ab4-88a609a52838
    CSeq: 9333 OPTIONS
    Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
    Accept: application/sdp,application/dtmf-relay
    Supported: outbound
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:13 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    OPTIONS sip:p2ffeh48@114.251.47.68:62879;transport=ws SIP/2.0
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj73d53798-89a0-44a9-88e6-8eb953751fc5;alias
    From: <sip:60000019023@ip-10-10-6-162>;tag=a40fd4cf-2bda-4665-bc4e-d337a958e75f
    To: <sip:p2ffeh48@114.251.47.68>
    Contact: <sip:60000019023@ip-10-10-6-162:5060;transport=ws>
    Call-ID: af996c5b-e541-4b71-a730-030bff61d1c6
    CSeq: 36621 OPTIONS
    Max-Forwards: 70
    User-Agent: Asterisk PBX 13.20.0
    Content-Length:  0


    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:56 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    INVITE sip:ig27h7ar@114.251.47.68:64671;transport=ws SIP/2.0
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj9aba1e55-1a5f-42d2-8b27-bbda00cf4d17;alias
    From: <sip:0000@ip-10-10-6-162>;tag=a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    To: <sip:ig27h7ar@114.251.47.68>
    Contact: <sip:asterisk@ip-10-10-6-162:5060;transport=ws>
    Call-ID: 475c6057-1bc0-4190-a55d-7d3125c61df5
    CSeq: 20906 INVITE
    Allow: OPTIONS, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, REGISTER, REFER, MESSAGE
    Supported: 100rel, timer, replaces, norefersub
    Session-Expires: 1800
    Min-SE: 90
    X-Asterisk-call_type: 4
    Max-Forwards: 70
    User-Agent: Asterisk PBX 13.20.0
    Content-Type: application/sdp
    Content-Length:   936

    v=0
    o=- 1300550734 1300550734 IN IP4 10.10.6.162
    s=Asterisk
    c=IN IP4 10.10.6.162
    t=0 0
    m=audio 12352 RTP/SAVPF 107 8 0 101
    a=connection:new
    a=setup:actpass
    a=fingerprint:SHA-256 CF:6B:3D:2E:C7:F5:91:45:FE:69:52:35:5F:64:F9:57:8E:00:2F:ED:3B:B0:60:CC:C0:F2:71:6C:E0:94:E9:10
    a=ice-ufrag:0f3069ba019789fb6d8d218f6bda0a5b
    a=ice-pwd:584d5b496c31c109070266ff2bf383d6
    a=candidate:Ha0a06a2 1 UDP 2130706431 10.10.6.162 12352 typ host
    a=candidate:S3453c4c1 1 UDP 1694498815 52.83.196.193 12352 typ srflx raddr 10.10.6.162 rport 12352
    a=candidate:Ha0a06a2 2 UDP 2130706430 10.10.6.162 12353 typ host
    a=candidate:S3453c4c1 2 UDP 1694498814 52.83.196.193 12353 typ srflx raddr 10.10.6.162 rport 12353
    a=rtpmap:107 opus/48000/2
    a=fmtp:107 maxaveragebitrate=12000;cbr=1;useinbandfec=1
    a=rtpmap:8 PCMA/8000
    a=rtpmap:0 PCMU/8000
    a=rtpmap:101 telephone-event/8000
    a=fmtp:101 0-16
    a=ptime:20
    a=maxptime:20
    a=sendrecv
    a=rtcp-mux


    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:56 GMT+0800 (中国标准时间) | sip.sipmessage | header "Content-Disposition" not present
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:56 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    SIP/2.0 100 Trying
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj9aba1e55-1a5f-42d2-8b27-bbda00cf4d17;alias
    To: <sip:ig27h7ar@114.251.47.68>
    From: <sip:0000@ip-10-10-6-162>;tag=a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    Call-ID: 475c6057-1bc0-4190-a55d-7d3125c61df5
    CSeq: 20906 INVITE
    Supported: outbound
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:56 GMT+0800 (中国标准时间) | sip.dialog | new UAS dialog created with status EARLY
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:56 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    SIP/2.0 180 Ringing
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj9aba1e55-1a5f-42d2-8b27-bbda00cf4d17;alias
    To: <sip:ig27h7ar@114.251.47.68>;tag=3kjlp6e0gf
    From: <sip:0000@ip-10-10-6-162>;tag=a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    Call-ID: 475c6057-1bc0-4190-a55d-7d3125c61df5
    CSeq: 20906 INVITE
    Contact: <sip:ig27h7ar@192.0.2.166;transport=ws>
    Supported: outbound
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.dialog | dialog 475c6057-1bc0-4190-a55d-7d3125c61df53kjlp6e0gfa0c933fb-25df-4c0d-9bad-6a9ec3f96a7d  changed to CONFIRMED state
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | initPeerConnection
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | New peer connection created
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | acquiring local media
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | Using deprecated stream API
    LoggerFactory.print @ sip-0.9.1.js?version=1.0.1:807
    LoggerFactory.(anonymous function) @ sip-0.9.1.js?version=1.0.1:824
    Logger.(anonymous function) @ sip-0.9.1.js?version=1.0.1:818
    peerConnection.onaddstream @ sip-0.9.1.js?version=1.0.1:8973
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | stream added
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | track added
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | acquired local media streams
    sip-0.9.1.js?version=1.0.1:807 RTCSessionDescription {type: "answer", sdp: "v=0
    ↵o=- 5034578631887129037 2 IN IP4 127.0.0.1
    ↵s…9362 label:954c47f7-5bb5-41ed-8813-a70a252d7284
    ↵"}
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:487145551 1 udp 2122063615 10.211.55.14 58662 typ host generation 0 ufrag nfjm network-id 2
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3944298907 1 udp 1685855999 114.251.47.68 59008 typ srflx raddr 10.211.55.14 rport 58662 generation 0 ufrag nfjm network-id 2
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1401601215 1 tcp 1518083839 10.211.55.14 9 typ host tcptype active generation 0 ufrag nfjm network-id 2
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:57 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3243962942 1 udp 41688831 52.83.196.193 52215 typ relay raddr 114.251.47.68 rport 59008 generation 0 ufrag nfjm network-id 2
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:59 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    OPTIONS sip:ig27h7ar@114.251.47.68:64671;transport=ws SIP/2.0
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPjc22489c8-e430-4d38-abf8-934e8bee64c8;alias
    From: <sip:60000019023@ip-10-10-6-162>;tag=4cd92a67-6782-4323-84c8-c9c84cb22635
    To: <sip:ig27h7ar@114.251.47.68>
    Contact: <sip:60000019023@ip-10-10-6-162:5060;transport=ws>
    Call-ID: 91076f61-d153-4117-851f-5fcba88bc688
    CSeq: 26759 OPTIONS
    Max-Forwards: 70
    User-Agent: Asterisk PBX 13.20.0
    Content-Length:  0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:19:59 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    SIP/2.0 200 OK
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPjc22489c8-e430-4d38-abf8-934e8bee64c8;alias
    To: <sip:ig27h7ar@114.251.47.68>;tag=n9q1dv6dup
    From: <sip:60000019023@ip-10-10-6-162>;tag=4cd92a67-6782-4323-84c8-c9c84cb22635
    Call-ID: 91076f61-d153-4117-851f-5fcba88bc688
    CSeq: 26759 OPTIONS
    Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
    Accept: application/sdp,application/dtmf-relay
    Supported: outbound
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:13 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    OPTIONS sip:p2ffeh48@114.251.47.68:62879;transport=ws SIP/2.0
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPjca2274ea-05fc-4952-97c3-f7093842df45;alias
    From: <sip:60000019023@ip-10-10-6-162>;tag=2fc855f4-3cea-4d80-af61-59d2d39f7dc6
    To: <sip:p2ffeh48@114.251.47.68>
    Contact: <sip:60000019023@ip-10-10-6-162:5060;transport=ws>
    Call-ID: e996bd5c-f3e5-401f-80f1-8ba515f75abc
    CSeq: 54888 OPTIONS
    Max-Forwards: 70
    User-Agent: Asterisk PBX 13.20.0
    Content-Length:  0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    CANCEL sip:ig27h7ar@114.251.47.68:64671;transport=ws SIP/2.0
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj9aba1e55-1a5f-42d2-8b27-bbda00cf4d17;alias
    From: <sip:0000@ip-10-10-6-162>;tag=a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    To: <sip:ig27h7ar@114.251.47.68>
    Call-ID: 475c6057-1bc0-4190-a55d-7d3125c61df5
    CSeq: 20906 CANCEL
    Reason: Q.850;cause=0
    Max-Forwards: 70
    User-Agent: Asterisk PBX 13.20.0
    Content-Length:  0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    SIP/2.0 200 OK
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj9aba1e55-1a5f-42d2-8b27-bbda00cf4d17;alias
    To: <sip:ig27h7ar@114.251.47.68>;tag=pbo599gsjc
    From: <sip:0000@ip-10-10-6-162>;tag=a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    Call-ID: 475c6057-1bc0-4190-a55d-7d3125c61df5
    CSeq: 20906 CANCEL
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

    SIP/2.0 487 Request Terminated
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj9aba1e55-1a5f-42d2-8b27-bbda00cf4d17;alias
    To: <sip:ig27h7ar@114.251.47.68>;tag=3kjlp6e0gf
    From: <sip:0000@ip-10-10-6-162>;tag=a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    Call-ID: 475c6057-1bc0-4190-a55d-7d3125c61df5
    CSeq: 20906 INVITE
    Supported: outbound
    User-Agent: SIP.js/0.9.1
    Content-Length: 0



    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.inviteservercontext | closing INVITE session 475c6057-1bc0-4190-a55d-7d3125c61df5a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.invitecontext.sessionDescriptionHandler | Using getRemoteStreams which is deprecated
    LoggerFactory.print @ sip-0.9.1.js?version=1.0.1:807
    LoggerFactory.(anonymous function) @ sip-0.9.1.js?version=1.0.1:824
    Logger.(anonymous function) @ sip-0.9.1.js?version=1.0.1:818
    value @ sip-0.9.1.js?version=1.0.1:8697
    close @ sip-0.9.1.js?version=1.0.1:4750
    terminated @ sip-0.9.1.js?version=1.0.1:5251
    receiveRequest @ sip-0.9.1.js?version=1.0.1:5653
    UA.receiveRequest @ sip-0.9.1.js?version=1.0.1:7760
    onMessage @ sip-0.9.1.js?version=1.0.1:11862
    ws.onmessage @ sip-0.9.1.js?version=1.0.1:11730
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.dialog | dialog 475c6057-1bc0-4190-a55d-7d3125c61df53kjlp6e0gfa0c933fb-25df-4c0d-9bad-6a9ec3f96a7d deleted
    sip-0.9.1.js?version=1.0.1:807 undefined
    LoggerFactory.print @ sip-0.9.1.js?version=1.0.1:807
    LoggerFactory.(anonymous function) @ sip-0.9.1.js?version=1.0.1:824
    Logger.(anonymous function) @ sip-0.9.1.js?version=1.0.1:818
    createOfferOrAnswerError @ sip-0.9.1.js?version=1.0.1:8917
    sip-0.9.1.js?version=1.0.1:807 Wed May 23 2018 20:20:27 GMT+0800 (中国标准时间) | sip.transport | received WebSocket text message:

    ACK sip:ig27h7ar@114.251.47.68:64671;transport=ws SIP/2.0
    Via: SIP/2.0/WSS 10.10.6.162:80;rport;branch=z9hG4bKPj9aba1e55-1a5f-42d2-8b27-bbda00cf4d17;alias
    From: <sip:0000@ip-10-10-6-162>;tag=a0c933fb-25df-4c0d-9bad-6a9ec3f96a7d
    To: <sip:ig27h7ar@114.251.47.68>;tag=3kjlp6e0gf
    Call-ID: 475c6057-1bc0-4190-a55d-7d3125c61df5
    CSeq: 20906 ACK
    Max-Forwards: 70
    User-Agent: Asterisk PBX 13.20.0
    Content-Length:  0

**Comment by vonvey** [comment]
error :
 
  sip-0.9.1.js?version=1.0.1:807 undefined
  LoggerFactory.print @ sip-0.9.1.js?version=1.0.1:807
  LoggerFactory.(anonymous function) @ sip-0.9.1.js?version=1.0.1:824
  Logger.(anonymous function) @ sip-0.9.1.js?version=1.0.1:818
createOfferOrAnswerError @ sip-0.9.1.js?version=1.0.1:8917

**Comment by egreenmachine** [comment]
Chrome 55 is very old. I do not have any expectations that the default session description handler will work in that browser. You will need to create a [custom session description handler](https://sipjs.com/api/0.10.0/sessionDescriptionHandler/).
