### ISSUE TITLE
sip.parser | error parsing header "m"

### ISSUE THREAD

**Issue by anshkatriya** [onsip/SIP.js#560]
SIP.js is not able to handle parsing of 200 OK packet while m header contains any string with # character.

Thu May 24 2018 11:22:55 GMT+0530 (IST) | sip.transport | received WebSocket text message:

```
SIP/2.0 200 OK
v:SIP/2.0/WSS 8r1po5314s38.invalid;branch=z9hG4bK9420222;received=X.X.X.X;rport=36874
From: "Ghanshyam Katriya" <sip:10001080@pbx.xyz>;tag=cv333cb995
t:"Ghanshyam Katriya"<sip:10001080@pbx.xyz>;tag=46UQm7ggKt1ZS
Call-ID: ve9co05i7flonpbq1p337s
CSeq: 83 REGISTER
m:<sip:34098f8f@8r1po5314s38.invalid;transport=ws;received=X.X.X.X:36874>;expires=600,<sip:10001080@x.x.x.x.x:65080;transport=tcp;received=x.x.x.x:62580>;expires=2353204,<sip:PBX#1000#905448737777@x.x.x.x>;expires=2519533,Date:Thu, 24 May 2018 05:52:55 GMT
User-Agent:FreeSWITCH-mod_sofia/1.6.20~64bit
Allow:INVITE,ACK,BYE,CANCEL,OPTIONS,MESSAGE,INFO,UPDATE,REGISTER,REFER,NOTIFY,PUBLISH,SUBSCRIBE
k:timer,path,replaces
l:0
```

**Comment by JimGreenberg** [comment]
Hi,
This is actually not an error- the "#" character is not supported in the grammar for the contact header outlined in https://tools.ietf.org/html/rfc3261#page-228

**Comment by anshkatriya** [comment]
But same thing is handled by all IP Phones & Soft-phone like linphone etc. what about them? Can't we handle it in SIP.js? @JimGreenberg

**Comment by JimGreenberg** [comment]
Ultimately, we are an RFC compliant library- if we stray from the spec we could inadvertently break something else in the library.
I've dealt with phones that which are strict in this sense, and would break in this instance- keeping RFC compliance makes it much easier to maintain as well.
That said, we'd be open to a pull request that allows this optional functionality, probably as a configuration option on the UA.

**Comment by egreenmachine** [comment]
Modifying the grammar to optionally support this is not going to be an easy task. I believe that it would be much simpler to fix the UA that is generating the offending contact. Additionally, if you escape the `#` in the contact, that would also solve your issue.
