### ISSUE TITLE
Sip .js version 11.0 - defaults to register with edge.sip.onsip.com in-spite of specifying different wsServer name

### ISSUE THREAD

**Issue by vineethbhargavan** [onsip/SIP.js#570]
**Describe the bug**
- I used to npm to install sip.js - version 11.0.
- the following is the code.
- **Note - the same works fine with Version 10**. - With no change in code.

`let configuration = {
                    uri: this.username + '@' + this.domain,
                    wsServers: ['wss://' + this.domain + ':8089/ws'],
                    authorizationUser: this.username,
                    password: this.password,
                    hackIpInContact: true,
                    hackViaTcp: true,
                    hackWssInTransport: true,
                    register: true
                };
                this.ua = new SIP.UA(configuration);`

**Logs**
`Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.ua | · authorizationUser: "199"
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.ua | · instanceId: "dd6d623a-3091-4e6f-a7b9-ab0c40cf4bf1"
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.ua | · sipjsId: "a335u"
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.ua | · hostportParams: "172.20.10.5"
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.ua | user requested startup...
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | configuration parameters after validation:
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | · wsServers: [{"scheme":"WSS","sip_uri":"<sip:edge.sip.onsip.com;transport=ws;lr>","weight":0,"ws_uri":"wss://edge.sip.onsip.com","isError":false}]
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | · connectionTimeout: 5
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | · maxReconnectionAttempts: 3
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | · reconnectionTimeout: 4
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | · keepAliveInterval: 0
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | · keepAliveDebounce: 10
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | · traceSip: false
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:38 GMT+1000 (Australian Eastern Standard Time) | sip.transport | connecting to WebSocket wss://edge.sip.onsip.com
sip.min.js?ecb2:1 Wed Jun 20 2018 13:46:40 GMT+1000 (Australian Eastern Standard Time) | sip.transport | WebSocket wss://edge.sip.onsip.com connected`

**To Reproduce (if possible)**

**Expected behavior**
- it UA registration should work fine as it does with version 10.0

**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**

**Comment by JimGreenberg** [comment]
This isn't a bug- the 0.11.0 release introduced a complete overhaul of the transport code. Without going into too much detail, this meant that some configuration parameters were moved. Fortunately, the fix is simple:
~~~javascript
let configuration = { foo: bar, transportOptions: { wsServers: "wss://my.favorite.server" } }
~~~
[Documentation of transport configuration options](https://sipjs.com/api/0.11.0/ws_transport_configuration_parameters/)

**Comment by vineethbhargavan** [comment]
Thanks for the clarification.
