### ISSUE TITLE
Outdated Simple API documentation

### ISSUE THREAD

**Issue by ArkmonSpirit** [onsip/SIP.js#574]
Hi guys,
introducing the commit d572f94, the documentation about your API has been outdated and that can be confusing for new people.
The new constructor is now `new SIP.Web.Simple([configuration])` (Web instead of WebRTC)

That's clearly minor but it can help a lot of people to easily integrated your awesome lib ;)

**Comment by JimGreenberg** [comment]
Thanks for pointing this out, I'll go through and fix
