### ISSUE TITLE
The documentation still mentions `SIP.WebRTC[.Modifiers]` even though it seems gone?

### ISSUE THREAD

**Issue by xmo-odoo** [onsip/SIP.js#575]
Aside from the interwebs having various mentions of it and the migration path being unclear (any guidance? Should one just replace `SIP.WebRTC.Modifiers` by `SIP.Web.Modifiers`?) the documentation's example for Modifiers [still accesses its modifier via WebRTC](https://sipjs.com/api/0.11.0/sessionDescriptionHandler/#modifiers-1).

The APIDoc section for [SIP.Session.descriptionHandler](https://sipjs.com/api/0.11.0/session/#sessiondescriptionhandler) also still documents it as a `SIP.WebRTC.SessionDescriptionHandler`.

**Comment by egreenmachine** [comment]
Good catch. I have updated the documentation. In the future for questions, please ask on our [mailing list](https://groups.google.com/forum/#!forum/sip_js) and for issues with the documentation please open and issue on the [documentation issue tracker](https://gitlab.com/onsip/sipjs.com/issues). We would like to reserve this space for bugs within the project itself. Thanks.
