### ISSUE TITLE
Typo in setDescription leads to calls not working on computers without webcams

### ISSUE THREAD

**Issue by EliAndrewC** [onsip/SIP.js#581]
I just upgraded to the latest 0.11.x line from 0.8.x and found that incoming calls stopped working.  In particular, I started getting an error about not being able to acquire streams, and it appeared to be trying to get my webcam even when I set ``video`` to ``false`` in my ``constraints``.

I tracked the problem down to this line:
https://github.com/onsip/SIP.js/blob/e3e373eca69f62450e5296d74488da465dd2c71b/src/Web/SessionDescriptionHandler.js#L220

It looks like the word ``constraints`` was typoed as ``constrains`` at some point.  After making that fix on my local copy everything went back to working.

I don't have time to file a merge request at the moment, but I'll try and see if I can do that tomorrow, though someone else is welcome to beat me to the punch if they happen to get to it before me.

**Comment by egreenmachine** [comment]
Fixed via 52c3d6c8d766eccd3197a7fc184cc8a5a900b0d1

Will get a new release out next week. Thanks.

**Comment by EliAndrewC** [comment]
Thanks so much for the quick response!  I'll upgrade next week when the new version is released, and in the meantime I've got this fixed locally.  Thanks again!
