### ISSUE TITLE
Clone option objects passed to session methods

### ISSUE THREAD

**Issue by EliAndrewC** [onsip/SIP.js#583]
I suspect I'm not alone in having options which I commonly pass to methods such as ``.accept()`` and ``invite()``.  For example, I have some code that looks like this:

```javascript
var CALL_OPTIONS = {
    sessionDescriptionHandlerOptions: {
        constraints: {
            audio: true,
            video: false
        }
    }
};

...

var placeCall = function (userAgent, target) {
    var session = userAgent.invite(target, CALL_OPTIONS);
    ...
};

var answerCall = function (session) {
    session.accept(CALL_OPTIONS);
    ...
};
```

This all worked great at first.  But then I found that having multiple different SIP sessions active for different extensions led to weird problems, like hanging up a call remotely not actually disconnecting the call in the browser.

I eventually realized that what was happening is that I was passing the same object in, and the different methods were mutating it, e.g. we set ``option.extraHeaders`` at
https://github.com/onsip/SIP.js/blob/26a4b4c55e3845b823e419607652ab6e63843f57/src/Session.js#L1363

My local solution was to replace ``CALL_OPTIONS`` with a ``makeCallOptions()`` function which just returns that object so as to not end up having e.g. two different sessions sharing the same ``extraHeaders`` array.

However, it took me several hours of sustained debugging to figure out that was what I needed, and I doubt I'm the only person who this will happen to.  I think we could avoid this by cloning the ``options`` object when it's passed in so that where we now say

```javascript
options = options || {};
```

we would instead say something like

```javascript
options = SIP.Utils.clone(options || {});
```

then people won't get tripped up.  Obviously that would require us to define a new ``SIP.Utils.clone`` method, for which I normally use something like jQuery or lodash, but which we could probably just draw from https://stackoverflow.com/a/728694/1694

If this seems like a worthwhile idea, I would be happy to file a pull request.

**Comment by egreenmachine** [comment]
I agree that this is something we should do and we would certainly take a PR. I hope that you could use the [MDN recommended approach for doing a deep clone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Deep_Clone).

**Comment by john-e-riordan** [comment]
This is addressed in the new API and should be an issue therein.

**Comment by james-criscuolo** [comment]
Closing as 0.16.0 is new API only, so the issue has been addressed.
