### ISSUE TITLE
iOS Chrome/Firefox supporting

### ISSUE THREAD

**Issue by ytian801** [onsip/SIP.js#584]
iOS Chrome/Firefox don't support getUserMedia now, it does support peerconnection, so we can receiving streams in them.

In these browsers, js will stop running in this line:
https://github.com/onsip/SIP.js/blob/master/src/Web/SessionDescriptionHandler.js#L47

If I set getUserMedia to null in these 2 specific browsers, I can receiving streams. Please considers these feature.

**Comment by egreenmachine** [comment]
You need to create your own [Session Description Handler](https://sipjs.com/api/0.11.0/sessionDescriptionHandler/) to handle this. We have no intention to support this in the default SDH.
