### ISSUE TITLE
Putting Session on Hold

### ISSUE THREAD

**Issue by 91Abdullah** [onsip/SIP.js#591]
Putting session on Hold is causing call disconnection.

**Logs**
`
sip.js:586 DOMException: Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
LoggerFactory.print @ sip.js:586
LoggerFactory.(anonymous function) @ sip.js:603
Logger.(anonymous function) @ sip.js:597
setRemoteDescriptionError @ sip.js:9702
Promise.catch (async)
setDescription @ sip.js:9701
receiveReinviteResponse @ sip.js:5071
receiveResponse @ sip.js:3902
InviteClientTransaction.receiveResponse @ sip.js:2997
UA.onTransportReceiveMsg @ sip.js:7892
EventEmitter.emit @ sip.js:743
onMessage @ sip.js:9003
sip.js:586 Mon Aug 13 2018 17:36:09 GMT+0500 (Pakistan Standard Time) | sip.inviteservercontext | Could not set the description in 2XX response
LoggerFactory.print @ sip.js:586
LoggerFactory.(anonymous function) @ sip.js:603
Logger.(anonymous function) @ sip.js:597
onFailure @ sip.js:5072
Promise.catch (async)
receiveReinviteResponse @ sip.js:5071
receiveResponse @ sip.js:3902
InviteClientTransaction.receiveResponse @ sip.js:2997
UA.onTransportReceiveMsg @ sip.js:7892
EventEmitter.emit @ sip.js:743
onMessage @ sip.js:9003
sip.js:586 DOMException: Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
`

**To Reproduce (if possible)**
1. On incoming invite call session.hold()
2. See error

**Expected behavior**
Observing call to get hold (music on hold).

**Observed behavior**
Call gets disconnected.

**Environment Information**
Using Laravel 5.6
Asterisk 15
sipjs 0.11.0

**Comment by egreenmachine** [comment]
Please include a [gist](https://gist.github.com/) with [traceSip](https://sipjs.com/api/0.11.0/ws_transport_configuration_parameters/#tracesip) enabled

**Comment by 91Abdullah** [comment]
https://gist.github.com/91Abdullah/f2337ae2d1efcdab2929cdd908a05778

**Comment by egreenmachine** [comment]
What browser are you running SIP.js in?

**Comment by 91Abdullah** [comment]
Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by egreenmachine** [comment]
It appears that Asterisk is doing something weird. I would recommend following up with them. It looks like SIP.js is doing what it is supposed to be doing. The browser may also be misbehaving, but it is tough to tell.

Essentially what is happening is that you initially set up an audio call. Then Asterisk goes to add video. It add MPV (rtp codec 32 which is MPEG) via RTP/AVP (unencrypted RTP). AFAIK all of this is not supported by Chrome and should be rejected on the spot, but Chrome answers it and allows it to go through. Then when you try to place the call on hold, it changes to UDP/TLS/RTP/SAVPF and includes a bunch of codecs that were not originally offered in the initial offer/answer. This is another place the browser may not be doing the right thing. When the answer SDP comes back for the hold, we pass it to the browser and the browser rejects it. SIP.js then sends the appropriate SIP messages. 

There is really not much we can do about this in SIP.js. From a SIP perspective we are doing all of the correct things with the information provided by the signaling and browser. I would try to get the initial renegotiation adding video to stop happening from Asterisk and see if that resolves your issue.

**Comment by 91Abdullah** [comment]
Thanks for looking into the issue. I'll do some more test or maybe downgrading asterisk or chrome what do you suggest?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by egreenmachine** [comment]
We do not use Asterisk much and really only support it to the extent of our [guide](https://sipjs.com/guides/server-configuration/asterisk/).

**Comment by 91Abdullah** [comment]
Hi @egreenmachine thanks for pointing out real issue. Actually you were right in renegotiation asterisk was adding video just because at trunk side I enabled video and after disabling video on trunk SIP this issue didn't arise again.
