### ISSUE TITLE
Failed to parse SIP Contact header when Topology Hiding is used on server

### ISSUE THREAD

**Issue by vasilevalex** [onsip/SIP.js#593]
If SIP proxy uses Topology Hiding, it encodes topology information in Contact field. And SIP.js reports error while parsing such header.
| sip.parser | error parsing header "Contact"

For example, 

SIP/2.0 200 OK
Via: SIP/2.0/WSS k4cqi8bdsk05.invalid;received=0:0:0:0:0:0:0:1;rport=34314;branch=z9hG4bK636618
From: "WSS 205" <sip:205@siptest.local>;tag=u543f8kcr4
To: <sip:*7@siptest.local>;tag=as6e067557
Call-ID: sol19a5ctkr7uukq9l6d
CSeq: 9042 INVITE
Server: asterisk
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss;thinfo="U2h5YhUORg5uUBNZW1dIUAQadlZjRlFWUV0DBHJXRGgWBhZdBwxxSWRaTVBWXxgGcF9pXVNUVg==">
Content-Type: application/sdp
Content-Length: 582

v=0
o=root 1492236005 1492236005 IN IP4 10.10.10.247
s=ipnordic
c=IN IP4 10.10.8.246
t=0 0
m=audio 10958 UDP/TLS/RTP/SAVPF 8 126
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=sendrecv
a=rtcp:10958
a=rtcp-mux
a=setup:active
a=fingerprint:sha-1 88:78:35:6D:55:77:4D:32:35:58:CB:D0:71:CA:76:16:B3:19:26:A7
a=ptime:20
a=ice-ufrag:D4HHbBzi
a=ice-pwd:q9CJDdddddUZbAwRIFdS
a=candidate:eSePKrNDiCsyf08i 1 UDP 2130706431 10.10.8.246 10958 typ host
a=candidate:h3V6UlbW1JuyzKHE 1 UDP 2130706175 2a03:3250:8000:1::246 11036 typ host

Or this:
OPTIONS sip:0rjpr7gh@k4cqi8bdsk05.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS [0:0:0:0:0:0:0:1]:8061;branch=z9hG4bKe61a.ff611026.0
Max-Forwards: 69
From: "asterisk" <sip:asterisk@siptest.local>;tag=as63bc007e
To: <sip:205@siptest.local>
Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss;thinfo="U2hDYhUORg4lFCcNEQsVDHYFfFJ9X1FMVFYGGnZTZFJWUlBXITQxAyNSUlpTSQEGalVjUE1QUl8MAXRRYw==">
Call-ID: 0c11b264352643c80a2febf24f4a59eb@10.10.20.247:5060
CSeq: 102 OPTIONS
User-Agent: ipnordic
Date: Mon, 20 Aug 2018 08:47:49 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0

**To Reproduce (if possible)**
Try to parse header
Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss;thinfo="U2h5YhUORg5uUBNZW1dIUAQadlZjRlFWUV0DBHJXRGgWBhZdBwxxSWRaTVBWXxgGcF9pXVNUVg==">

**Expected behavior**
No parsing error.

**Environment Information**
SIP.js v 0.11.3
Chrome Version 68.0.3440.106

**Additional context**
About topology hiding:
https://www.opensips.org/Documentation/Tutorials-Topology-Hiding

**Comment by vasilevalex** [comment]
BTW, I checked RFC 3261,
https://tools.ietf.org/html/rfc3261#section-25.1

Contact        =  ("Contact" / "m" ) HCOLON
                  ( STAR / (contact-param *(COMMA contact-param)))
contact-param  =  (name-addr / addr-spec) *(SEMI contact-params)
contact-params     =  c-p-q / c-p-expires
                      / contact-extension
contact-extension  =  generic-param
generic-param  =  token [ EQUAL gen-value ]
gen-value      =  token / host / quoted-string
quoted-string  =  SWS DQUOTE *(qdtext / quoted-pair ) DQUOTE
qdtext         =  LWS / %x21 / %x23-5B / %x5D-7E
                        / UTF8-NONASCII

So we get contact-params = contact-extension = generic-param
in generic param 'token' is 'thinfo' and gen-value is quoted-string,
which can be for example "U2h5YhUORg5uUBNZW1dIUAQadlZjRlFWUV0DBHJXRGgWBhZdBwxxSWRaTVBWXxgGcF9pXVNUVg=="
as symbol "=" is %x3D and qdtext can't contain only double quotes (%x22) and backslash (%x5C)

**Comment by seanbright** [comment]
Can you re-insert the message that is causing the problem but make sure to click the "Insert Code" editor button first? I ask because your From header is invalid as it appears in your first message so I assume the GitHub editor is doing something funky.

**Comment by vasilevalex** [comment]
Yes, sorry, I've not checked
There are examples:
```
OPTIONS sip:u3sbtgnh@n9g6ke4672g9.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS [0:0:0:0:0:0:0:1]:8061;branch=z9hG4bK3737.9716d362.0
Max-Forwards: 69
From: "asterisk" <sip:asterisk@siptest.local>;tag=as07da8976
To: <sip:205@siptest.local>
Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss;thinfo="U2hDYhUORg4lFCcNEQsVDHYFfFJ9X1FMVFYGGnZTZFJWUlBXITQxAyNSUlpTSQEGalVjUE1QUl8MAXRRYw==">
Call-ID: 1bf9d65b7b40bbb96fad31202e3ef626@10.10.10.247:5060
CSeq: 102 OPTIONS
User-Agent: asterisk
Date: Mon, 20 Aug 2018 13:44:42 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/WSS n9g6ke4672g9.invalid;received=0:0:0:0:0:0:0:1;rport=35504;branch=z9hG4bK4611047
From: "WSS 205" <sip:205@siptest.local>;tag=1v0bpcha30
To: <sip:*7@siptest.local>;tag=as48634327
Call-ID: k07f5snb8g6vkfvibu54
CSeq: 2182 INVITE
Server: asterisk
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss;thinfo="U2h5YhUORg5uUBNZW1dIUAQadlZjRlFWUV0DBHJXRGgWBhZdBwxxSWRaTVBWXxgGcF9pXVNUVg==">
Content-Type: application/sdp
Content-Length: 580

SDP...

```
Thanks.

**Comment by seanbright** [comment]
You quote the ABNF section of the RFC that deals with Contact parameters but `thinfo` is actually an attempt at a SIP URI parameter which cannot be a quoted-string. You will need to move the `thinfo` parameter after the SIP URI, so instead of this:

    Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss;thinfo="U2h5YhUORg5uUBNZW1dIUAQadlZjRlFWUV0DBHJXRGgWBhZdBwxxSWRaTVBWXxgGcF9pXVNUVg==">

It should be this:

    Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss>;thinfo="U2h5YhUORg5uUBNZW1dIUAQadlZjRlFWUV0DBHJXRGgWBhZdBwxxSWRaTVBWXxgGcF9pXVNUVg=="
                                                      ^ Move the > to here

**Comment by vasilevalex** [comment]
Sean, thank you very much for your explanation.
Yes, this is my mistake in reading spec. Of course, everything inside angle quotes (LAQUOT and RAQUOT) must fit addr-spec. And it can't contain double quotes and equal sign.
I asked OpenSIPS guys if topology hiding behavior matches RFC. When I'll find solution, I can write it here.

**Comment by seanbright** [comment]
@egreenmachine this is not a bug in SIP.js - feel free to close.

**Comment by vasilevalex** [comment]
Yes, this is bug in OpenSIPS. http://opensips-open-sip-server.1449251.n2.nabble.com/Does-topology-hiding-match-RFC3261-td7611813.html I'll open issue there.

**Comment by vasilevalex** [comment]
Fixed in OpenSIPS https://github.com/OpenSIPS/opensips/pull/1448
