### ISSUE TITLE
Documentation: Session Description Handler

### ISSUE THREAD

**Issue by Kasalehlia** [onsip/SIP.js#601]
The `rtcConfiguration` and `iceCheckingTimeout` config options of the Session Description Handler are not properly documented.

The page https://sipjs.com/api/0.11.0/sessionDescriptionHandler/#default-options suggests these are options to directly put into `sessionDescriptionHandlerFactoryOptions`, but they have to be put into the `peerConnectionOptions` Subobject. This is only documented in the get/setDescription methods.

**Comment by egreenmachine** [comment]
Issues with documentation should go on that repository https://gitlab.com/onsip/sipjs.com/issues
