### ISSUE TITLE
Support directly mediaStream input (instead of getUserMedia within sip.js)

### ISSUE THREAD

**Issue by betimer** [onsip/SIP.js#602]
**Is your feature request related to a problem? Please describe.**
I have a complex getUserMedia control outside (resulution, frameRate, and change device), so locally I control all the mediaStream. Instead of telling SIP that constriant to capture on the fly. Is there a way that I can capture mediaStream (all tracks) and just call sip to use the obtained media stream?

**Describe the solution you'd like**
A interface to reuse the captured media stream

**Describe alternatives you've considered**
Ideally just accept a media stream parameter. or alternatively extra parameters user put to call to get the media stream.

**Comment by egreenmachine** [comment]
You will need to create your own [Session Description Handler](https://sipjs.com/api/0.11.0/sessionDescriptionHandler/). We are not adding complexity to the default handler as it is not intended to be used for this.
