### ISSUE TITLE
Hold/unhold not updating sessionDescriptionHandler direction

### ISSUE THREAD

**Issue by gooseygamez** [onsip/SIP.js#604]
Hello,

Using the events 'reinviteAccepted' and 'directionChanged' to try and trigger if hold / unhold was successful but the sessionDescriptionHandler.direction never gets updated with the 200 response which contains a=recvonly

Tested with version 0.11.3. Hold from the audio point of view is working correctly.

```
SIP/2.0 200 OK
Via: SIP/2.0/WSS k41ld7nu8s8e.invalid;rport=53419;received=xxx.xx.xxx.xxx;branch=z9hG4bK2987212
Call-ID: mi5gs3oqbclsp6ep19l1
From: "xxx" <sip:xxx@xxx>;tag=s87khiqgpg
To: <sip:xxx@xxx>;tag=90144b3a-2cd8-45d5-b1db-f94e22ab2012
CSeq: 7151 INVITE
Contact: <sip:xxx.xx.xxx.xx:8089;transport=ws>
Allow: OPTIONS, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, REGISTER, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Server: Asterisk PBX 15.5.0
Content-Type: application/sdp
Content-Length:   947

v=0
o=- 3994504473 5 IN IP4 xxx.xx.xxx.xx
s=Asterisk
c=IN IP4 185.94.204.68
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE audio
m=audio 10780 UDP/TLS/RTP/SAVPF 0 8 126
a=connection:existing
a=setup:active
a=fingerprint:xxx
a=ice-ufrag:30ea03f24624c1f034e934db46ee672b
a=ice-pwd:21f91f9731f740db061cb0ad04a2ca2f
a=candidate:H534966c7 1 UDP 2130706431 2a04:e9c1:0:b::4 10780 typ host
a=candidate:H5bbe08d7 1 UDP 2130706431 fe80::21d:d8ff:feb7:1db1 10780 typ host
a=candidate:Hb95ecc44 1 UDP 2130706431 185.94.204.68 10780 typ host
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=ptime:20
a=maxptime:150
a=rtcp-mux
a=ssrc:2016684846 cname:349f2f0f-bbde-4782-9dda-e73f56cf4779
a=msid:a4d54a58-9d70-4bf1-a6f3-556958fbf0c7 3d8d322e-3282-434d-a857-d4c86b4325e0
a=mid:audio
a=recvonly
```

Also noticed that 'local_hold' on the session does not get reset on a fail, so cannot use this properly to determine if the session is on hold.

Let me know if you need more info.
Thanks!

**Comment by egreenmachine** [comment]
What is the direction after getting the 200?

**Comment by gooseygamez** [comment]
Sorry for delay in reply; the direction is `sendonly`
Which when reflecting I believe is correct on the `reinviteAccepted` because the server is saying it is only sending, not the client.

Happy to close this as not an issue if you agree.
Thanks

**Comment by egreenmachine** [comment]
That was my thought. The direction should reflect the direction of the client, not what was received in the last message from the other endpoint. Thanks.
