### ISSUE TITLE
Add default onError event listener to the WebSocket transport implementation

### ISSUE THREAD

**Issue by vkuzmenok** [onsip/SIP.js#606]
When using SIP.js as a Node.js library to connect to a SIP server over WebSocket, if the connection to a websocket drops or it is not possible to connect, server process fails with the error 

events.js:183 throw er; // Unhandled 'error'

To resolve the problem in the Transport.js I added the below code in the connectPromise

this.boundOnError = this.onError.bind(this);
this.ws.addEventListener("error", this.boundOnError);

I also added code to unbind all the methods in the disposeWs method and added initial setup of boundOnError at the beginning of the Transport class

**Comment by egreenmachine** [comment]
The default transport is not expected to work with Node. You should create your own Transport and pass that into the UA. You can use the default Transport as a template. If somebody made a Transport for Node, we would take it back into the library as a PR.

**Comment by vkuzmenok** [comment]
I agree that my case is quite unusual use of SIP.js, however, do not you agree that it makes sense to bind to the WebSocket error event and call Transport.onError like you do when you got an exception?

**Comment by egreenmachine** [comment]
Ah. I see what you are saying. Yes you are correct. I will re-open this. If you have done the work already we would appreciate it as a PR.
