### ISSUE TITLE
SIP Registration Fails

### ISSUE THREAD

**Issue by Tefojulius** [onsip/SIP.js#607]
I'm developing a soft phone using sip-0.11.3.min.js and I keep on getting "registration failed" after calling the UA.invite() function.

Can someone tell me why is my code not connecting or registering? Kindly point me to the right direction, here's my code below.

var userAgent = new SIP.UA({
            uri: myAuth + "@" + wsserver,
            password: extensionKey,
            wsServers: "wss://" + wsserver + ":443",
            traceSip: true,
            authorizationUser: myAuth,
            registerExpires: 1800,
            hackWssInTransport: true,
            stunServers: wsserver,
            keepAliveInterval: 59,
            rtcpMuxPolicy: "negotiate"
        });

var session = userAgent.invite("sip:" + dialNumber + "@" + wsserver, {
            media: {
                constraints: {
                    audio: true,
                    video: false
                }
            }
        });

userAgent.on('connecting', function () {
            $("#msg").html("Connecting...");
        });
        userAgent.on('connected', function () {
            $("#msg").html("Connected, attempting...");
        });
        userAgent.on('disconnected', function () {
            $("#msg").html("Disconnected");
        });
        userAgent.on('registered', function () {
            $("#msg").html("Registered!");
        });
        userAgent.on('registrationFailed', function () {
            $("#msg").html("Registration Failed");
        });
        userAgent.on('unregistered', function () {
            $("#msg").html("Unregistered, bye!");
        });

**Comment by egreenmachine** [comment]
This is not a bug. Please use our [google group](https://groups.google.com/forum/#!forum/sip_js).
