### ISSUE TITLE
180 + 183 Packets 

### ISSUE THREAD

**Issue by gwumkt** [onsip/SIP.js#608]
Hi,
when im ringing a client i cant hear a thing until he picks up.
basically im not getting 180 + 183 packets.
the issue is not in the conf of the asterisk because on zoiper its all good..
thanks.

**Comment by egreenmachine** [comment]
Early media works. This is almost certainly a config issue.

**Comment by gwumkt** [comment]
there is any conf for that on the sipjs library?

**Comment by egreenmachine** [comment]
This is not a bug. Please use our [google group](https://groups.google.com/forum/#!forum/sip_js).

**Comment by gwumkt** [comment]
For others reference, posted on google groups: https://groups.google.com/forum/#!topic/sip_js/AiFhmE80Rio

**Comment by stacybot123** [comment]
@gwumkt  are you able to resolve this? I have gone through your discussion on google. Doesn't seems to be resolved

**Comment by stoneLee81** [comment]
> Hi,
> when im ringing a client i cant hear a thing until he picks up.
> basically im not getting 180 + 183 packets.
> the issue is not in the conf of the asterisk because on zoiper its all good..
> thanks.

have you solve your problem?
