### ISSUE TITLE
Is that possible I could pass self-defined variables into extra headers to FreeSwitch? or any better way.

### ISSUE THREAD

**Issue by seasparta618** [onsip/SIP.js#612]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).
I am thinking to pass some extra self-defined variables when using invite method.
I referred to the document https://sipjs.com/api/0.5.0/ua/#invitetarget-options and thought to use 
`invite("target"[,options])`
I have tried 
`var options = {extraHeaders: ["X-Header: 2000", "X-pin: 2000","X-destination: xxxxxxxx"]
};userAgent.invite('9000', options );`
and in dialplan, try to get print it out using `<action application="log" data="INFO ${extraHeaders}"/>
				<action application="log" data="INFO ${options}"/>
				<action application="log" data="INFO ${X-Header}"/>
				<action application="log" data="INFO ${extraHeaders.X-Header}"/>
`
all cannot work.
I also tried 
`var extraHeadersArray = new Array();
    extraHeadersArray.push("2000");
    extraHeadersArray.push("2000");
    extraHeadersArray.push("xxxxxxxx");`
then 
`options = {
        extraHeaders : extraHeadersArray
    };
 userAgent.invite('9000', options);`
Cannot work either. So can I ask whether there are some better ways to do this? I need to pass some variables to FreeSwitch to do some further logic.

**Comment by egreenmachine** [comment]
This is not a bug. Please use our [google group](https://groups.google.com/forum/#!forum/sip_js).

**Comment by seasparta618** [comment]
I thought I have open a new question. But I did not see the label. I will go to group. Thanks.
