### ISSUE TITLE
Application demo / many to many audio call

### ISSUE THREAD

**Issue by log69** [onsip/SIP.js#614]
Dear Devs, thanks for your work.

Could you kindly direct me to a documentation or sample code or elaborate on how I can get the application demo (link below) work between 2 or more remote clients? Running it from an https host it requests permissions for video and audio when clicking the video button and video works, but no sound so far.

Do I need any kind of server side for this? Or the demo takes care of it by using a 3rd party?

What I'd like to achieve is a simple "many to many" audio call (no video) between 2 or more people for a closed circle of friends. So there is no need for registrations of new users. Thank you very much.

https://sipjs.com/guides/full-demo-app/

**Comment by egreenmachine** [comment]
This does not belong here. You can open an issue on our [documentation issue tracker](https://gitlab.com/onsip/sipjs.com) or start a discussion on our [mailing list](https://groups.google.com/forum/#!forum/sip_js).
