### ISSUE TITLE
Make new invite request available to reinvite event

### ISSUE THREAD

**Issue by jvanveen** [onsip/SIP.js#615]
**Is your feature request related to a problem? Please describe.**
I would like to be able to parse the rpid header on a reinvite, in order to show the transferred number/name on screen(platform doesn't use P-Asserted-Identity). The session.request is the old invite and there doesn't seem to way to get to the new invite request at the moment.

**Describe the solution you'd like**
Pass the request to the reinvite event. This makes it possible to parse/process any custom header.

**Describe alternatives you've considered**
Adding rpid parsing the same way as `P-Asserted-Identity` is passed. Having access to the new invite request is more flexible imo though.

**Comment by egreenmachine** [comment]
No need to have both an issue and PR. Closing in favor of the PR.
