### ISSUE TITLE
DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. [object Object] Expect line: v=

### ISSUE THREAD

**Issue by kakabara** [onsip/SIP.js#619]
**Describe the bug**
Not working libs correctly.

DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. [object Object] Expect line: v=
    at http://localhost/sip-0.11.4%20(1).js:9733:38

I got trouble in the same code section:

` /**
     * Set the remote description to the underlying media implementation
     * @param {String} sessionDescription The description provided by a SIP message to be set on the media implementation
     * @param {Object} [options] Options object to be used by getDescription
     * @param {MediaStreamConstraints} [options.constraints] MediaStreamConstraints https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints
     * @param {Object} [options.peerConnectionOptions] If this is set it will recreate the peer connection with the new options
     * @param {Array} [modifiers] Array with one time use description modifiers
     * @returns {Promise} Promise that resolves once the description is set
     */
    setDescription: { writable: true, value: function setDescription(sessionDescription, options, modifiers) {
        var _this = this;

        var self = this;

        options = options || {};
        if (options.peerConnectionOptions) {
          this.initPeerConnection(options.peerConnectionOptions);
        }

        modifiers = modifiers || [];
        if (!Array.isArray(modifiers)) {
          modifiers = [modifiers];
        }
        modifiers = modifiers.concat(this.modifiers);

        var description = {
          type: this.hasOffer('local') ? 'answer' : 'offer',
          sdp: sessionDescription
        };

        return SIP.Utils.Promise.resolve().then(function () {
          // Media should be acquired in getDescription unless we need to do it sooner for some reason (FF61+)
          if (this.shouldAcquireMedia && this.options.alwaysAcquireMediaFirst) {
            return this.acquire(this.constraints).then(function () {
              this.shouldAcquireMedia = false;
            }.bind(this));
          }
        }.bind(this)).then(function () {
          return SIP.Utils.reducePromises(modifiers, description);
        }).catch(function (e) {
          if (e instanceof SIP.Exceptions.SessionDescriptionHandlerError) {
            throw e;
          }
          var error = new SIP.Exceptions.SessionDescriptionHandlerError("setDescription", e, "The modifiers did not resolve successfully");
          _this.logger.error(error.message);
          self.emit('peerConnection-setRemoteDescriptionFailed', error);
          throw error;
        }).then(function (modifiedDescription) {
          self.emit('setDescription', modifiedDescription);
          return self.peerConnection.setRemoteDescription(modifiedDescription);
        }).catch(function (e) {
          if (e instanceof SIP.Exceptions.SessionDescriptionHandlerError) {
            throw e;
          }
          // Check the original SDP for video, and ensure that we have want to do audio fallback
          if (/^m=video.+$/gm.test(sessionDescription) && !options.disableAudioFallback) {
            // Do not try to audio fallback again
            options.disableAudioFallback = true;
            // Remove video first, then do the other modifiers
            return _this.setDescription(sessionDescription, options, [SIP.Web.Modifiers.stripVideo].concat(modifiers));
          }
          var error = new SIP.Exceptions.SessionDescriptionHandlerError("setDescription", e);
          _this.logger.error(error.error);
          _this.emit('peerConnection-setRemoteDescriptionFailed', error);
          throw error;
        }).then(function setRemoteDescriptionSuccess() {
          if (self.peerConnection.getReceivers) {
            self.emit('setRemoteDescription', self.peerConnection.getReceivers());
          } else {
            self.emit('setRemoteDescription', self.peerConnection.getRemoteStreams());
          }
          self.emit('confirmed', self);
        });
      } },`

**Comment by kakabara** [comment]
Insepct js code showed me that "modifiedDescription.sdp" is recursion object for sdp

**Comment by james-criscuolo** [comment]
Please post full logs in a gist. Are you trying to modify SDP yourself, or is this just trying to update from a previous version to the current version?

**Comment by kakabara** [comment]
Logs from asterisk or browser console?

**Comment by egreenmachine** [comment]
Browser console

**Comment by kakabara** [comment]
[gist] (https://gist.github.com/kakabara/d39058805af90637a62931893900fb55) but in firefox i got error with  "Failed to parse SDP: SDP Parse Error on line 1:  End of line beyond end of buffer.
"

**Comment by egreenmachine** [comment]
Asterisk is not sending ICE candidates. The issue in the gist is not the same issue that you stated above.

**Comment by kakabara** [comment]
Sorry, for my incorrect issue, it is first. I understand correct what my, caller send ice candidate, but asterisk not send to other client this?

**Comment by egreenmachine** [comment]
Sorry. I do not understand. WebRTC requires ICE and DTLS. This looks like an Asterisk issue so I am going to close this. Please follow up with the Asterisk project on your issues there.
