### ISSUE TITLE
Firefox Nightly WebRTC Error when answer incoming call

### ISSUE THREAD

**Issue by pavelsc** [onsip/SIP.js#621]
On incoming calls in FF Nightly (currently 64.0a1 (2018-10-15) (64-bit)) session _failed_ event with cause `SIP.C.causes.WEBRTC_ERROR` occurs right after `session.accept()`. Unless _terminate_ event was raised after _failed_ event, session still exists in calling state on the caller's end. Latest Chrome works correctly

**Logs**
> Tue Oct 16 2018 00:39:41 GMT+0300 (Moscow Standard Time) | sip.dialog | dialog 392c309715c7c9c255baad4e3f4e1224@10.2.0.65:50600ge600vmdjvas0a1f1df9  changed to CONFIRMED state sip-0.11.4.js:586:5
> Tue Oct 16 2018 00:39:41 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{},"peerConnectionOptions":{}} sip-0.11.4.js:586:5
> Tue Oct 16 2018 00:39:41 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | initPeerConnection sip-0.11.4.js:586:5
> Tue Oct 16 2018 00:39:41 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | New peer connection created sip-0.11.4.js:586:5
> Tue Oct 16 2018 00:39:42 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | track added sip-0.11.4.js:586:5
> Tue Oct 16 2018 00:39:42 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquiring local media sip-0.11.4.js:586:5
> Tue Oct 16 2018 00:39:42 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquired local media streams

WebRTC Error goes right after this part of log

**Comment by egreenmachine** [comment]
Can you provide full logs with `traceSip`? Also is this happening in an older version of FF such as 63 or 62? Lastly, does Chrome work?

**Comment by pavelsc** [comment]
In FF 62 it works, but with a delay, I mean when you accept a session then a call is answered in a 5 seconds:
Tue Oct 16 2018 15:50:51 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceChecking Timeout Triggered after 5000 milliseconds
Chrome works correctly as I mentioned above.

**FF 62 Logs**

> Tue Oct 16 2018 16:10:24 GMT+0300 (Moscow Standard Time) | sip.sipmessage | header "Content-Disposition" not present sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:24 GMT+0300 (Moscow Standard Time) | sip.dialog | new UAS dialog created with status EARLY sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.dialog | dialog 0a96afe02134de265c683ea47f6141ca@10.2.0.65:50600hpl94fgoi8as1d177283  changed to CONFIRMED state sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{},"peerConnectionOptions":{}} sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | initPeerConnection sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | New peer connection created sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | track added sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquiring local media sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquired local media streams sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: gathering sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:0 1 UDP 2122252543 10.6.1.10 53490 typ host sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2 1 UDP 2122187007 192.168.0.10 53491 typ host sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4 1 TCP 2105524479 10.6.1.10 9 typ host tcptype active sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:5 1 TCP 2105458943 192.168.0.10 9 typ host tcptype active sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:30 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3 1 UDP 1685987327 93.125.107.16 53491 typ srflx raddr 192.168.0.10 rport 53491 sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:35 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceChecking Timeout Triggered after 5000 milliseconds sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:35 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:36 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:41 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: complete sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:10:41 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate gathering complete

**FF 64 Logs**

> Tue Oct 16 2018 16:16:12 GMT+0300 (Moscow Standard Time) | sip.sipmessage | header "Content-Disposition" not present sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:12 GMT+0300 (Moscow Standard Time) | sip.dialog | new UAS dialog created with status EARLY sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.dialog | dialog 39dd2e270ad78163184d513c01c07391@10.2.0.65:506005jdbof07m5as507d5fc2  changed to CONFIRMED state sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{},"peerConnectionOptions":{}} sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | initPeerConnection sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | New peer connection created sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | track added sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquiring local media sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquired local media streams sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | closing INVITE session 39dd2e270ad78163184d513c01c07391@10.2.0.65:50600as507d5fc2 sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:15 GMT+0300 (Moscow Standard Time) | sip.dialog | dialog 39dd2e270ad78163184d513c01c07391@10.2.0.65:506005jdbof07m5as507d5fc2 deleted sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:16 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:17 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:19 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:23 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:27 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:31 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:35 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:39 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:43 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:47 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586:5
> Tue Oct 16 2018 16:16:47 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received for an extended period of time, terminating the call sip-0.11.4.js:586:5
> TypeError: this.dialog is undefined; can't access its "remote_target" property[Learn More] sip-0.11.4.js:4678:11 

**Chrome 69 Logs**

> Tue Oct 16 2018 18:27:13 GMT+0300 (Moscow Standard Time) | sip.sipmessage | header "Content-Disposition" not present sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:13 GMT+0300 (Moscow Standard Time) | sip.dialog | new UAS dialog created with status EARLY sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:20 GMT+0300 (Moscow Standard Time) | sip.dialog | dialog 4638fc6d3763106b02ea030e7119a95c@10.2.0.65:50600ilr2gd26mhas7f77ea21  changed to CONFIRMED state sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:20 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{},"peerConnectionOptions":{}} sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:20 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | initPeerConnection sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:20 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | New peer connection created sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:20 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | track added sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:20 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquiring local media sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:22 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquired local media streams sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:22 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: gathering sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:22 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1434301788 1 udp 2113937151 192.168.0.10 64927 typ host generation 0 ufrag 2CeD network-cost 999 sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:22 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:842163049 1 udp 1677729535 93.125.107.16 64927 typ srflx raddr 192.168.0.10 rport 64927 generation 0 ufrag 2CeD network-cost 999 sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:22 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: complete sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:22 GMT+0300 (Moscow Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate gathering complete sip-0.11.4.js:586 
> Tue Oct 16 2018 18:27:23 GMT+0300 (Moscow Standard Time) | sip.inviteservercontext | no ACK received, attempting to retransmit OK sip-0.11.4.js:586

**Comment by egreenmachine** [comment]
I need logs with [traceSip](https://sipjs.com/api/0.11.0/ws_transport_configuration_parameters/#tracesip)

**Comment by pavelsc** [comment]
Trace SIP was on:
```
this._userAgent = new SIP.UA({
	uri: this.extension + "@" + this.realm,
	transportOptions: {
		wsServers: [this.websocketUrl]
	},
	password: this.password,
	noAnswerTimeout: 3600,
	register: true,
	traceSip: true
});
```
Do I need any plug-in to get proper logs?

**Comment by james-criscuolo** [comment]
Please read the docs linked, that is the old way of setting traceSip and doesn't work with the current version of SIP.js. You'll know it works if you see SIP messages in your logs. Nothing extra is needed.

**Comment by pavelsc** [comment]
@james-criscuolo thanks

[FF 62 logs](https://pastebin.com/2y2LXDFA) (accepted after 5s delay)
[FF 64 logs](https://pastebin.com/tCuTZxj4) (session termination on accept)
[Chrome 69 logs](https://pastebin.com/74TFb35x) (works)

**Comment by egreenmachine** [comment]
There are 2 separate issues here. The 5s delay is the RTCIceChecking Timeout. That means that you have ICE candidates that are not returning. We see this a lot with virtual interfaces for VPN or VM. You can lower the timeout and it will go faster.

The more pressing issue is that you are sending `RTP/SAVPF` ([RFC 5124](https://tools.ietf.org/html/rfc5124)) from your PBX. My guess is that FF64 is no longer allowing it. You will need to use the `UDP/TLS/RTP/SAVPF` and that should resolve the issue.

As this is not a SIP.js issue, I am going to close this. Please follow up with your PBX provider. Thanks

**Comment by martsa** [comment]
> @james-criscuolo thanks
> 
> [FF 62 logs](https://pastebin.com/2y2LXDFA) (accepted after 5s delay)
> [FF 64 logs](https://pastebin.com/tCuTZxj4) (session termination on accept)
> [Chrome 69 logs](https://pastebin.com/74TFb35x) (works)



> Trace SIP was on:
> 
> ```
> this._userAgent = new SIP.UA({
> 	uri: this.extension + "@" + this.realm,
> 	transportOptions: {
> 		wsServers: [this.websocketUrl]
> 	},
> 	password: this.password,
> 	noAnswerTimeout: 3600,
> 	register: true,
> 	traceSip: true
> });
> ```
> Do I need any plug-in to get proper logs?

hey can u please show how to activate traceSip to true in current version . went through docs , but coluldnt find any solution

**Comment by egreenmachine** [comment]
https://sipjs.com/faq/
