### ISSUE TITLE
WebRTC incoming calls fail in FF 63 

### ISSUE THREAD

**Issue by vyshakhbabji** [onsip/SIP.js#623]
Ref: https://www.fxsitecompat.com/en-CA/docs/2018/webrtc-sdp-offer-now-requires-mid-property/

This is a Bug at FF end. This is fixed on FF64 Dev version : https://bugzilla.mozilla.org/show_bug.cgi?id=1495569

**Comment by egreenmachine** [comment]
I have already addressed this: https://groups.google.com/forum/#!topic/sip_js/HB44b-y0Afs

**Comment by vyshakhbabji** [comment]
Thanks @egreenmachine
