### ISSUE TITLE
crosswalk build failed

### ISSUE THREAD

**Issue by cnscns** [onsip/SIP.js#624]
step by step executing commands refrence to the  https://www.sipjs.com/guides/mobile/android-native/
**Describe the bug**

**Logs**
cns@pjsip-virtual-machine:~/crosswalk-5.34.104.5$ python make_apk.py --verbose  --manifest=../sipjs-examples/demo-phone/manifest.json 
Use xwalk's keystore by default for debugging. Please switch to your keystore when distributing it to app market.
Use aapt in /home/cns/adt/sdk.
Buildfile: /home/cns/crosswalk-5.34.104.5/scripts/ant/apk-codegen.xml

-mergemanifest:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] No libraries. Using project manifest only.

-code-gen:
    [mkdir] Created dir: /home/cns/crosswalk-5.34.104.5/out/res
    [mkdir] Created dir: /home/cns/crosswalk-5.34.104.5/out/gen
     [aapt] Generating resource IDs...
     [aapt] nothing matches overlay file multi_field_time_picker_dialog.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file two_field_date_picker.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file validation_message_bubble.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file autofill_text.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file color_picker_advanced_component.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file color_picker_dialog_content.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file color_picker_dialog_title.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file date_time_suggestion.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
Buildfile: /home/cns/crosswalk-5.34.104.5/scripts/ant/apk-package-resources.xml

-crunch:
   [crunch] Crunching PNG Files in source dir: /home/cns/crosswalk-5.34.104.5/DemoPhone/res
   [crunch] To destination dir: /home/cns/crosswalk-5.34.104.5/out/res
   [crunch] Processing image to cache: /home/cns/crosswalk-5.34.104.5/DemoPhone/res/drawable-hdpi/crosswalk.png => /home/cns/crosswalk-5.34.104.5/out/res/drawable-hdpi/crosswalk.png
   [crunch]   (processed image to cache entry /home/cns/crosswalk-5.34.104.5/out/res/drawable-hdpi/crosswalk.png: 53% size of source)
   [crunch] Processing image to cache: /home/cns/crosswalk-5.34.104.5/DemoPhone/res/drawable-ldpi/crosswalk.png => /home/cns/crosswalk-5.34.104.5/out/res/drawable-ldpi/crosswalk.png
   [crunch]   (processed image to cache entry /home/cns/crosswalk-5.34.104.5/out/res/drawable-ldpi/crosswalk.png: 0% size of source)
   [crunch] Processing image to cache: /home/cns/crosswalk-5.34.104.5/DemoPhone/res/drawable-mdpi/crosswalk.png => /home/cns/crosswalk-5.34.104.5/out/res/drawable-mdpi/crosswalk.png
   [crunch]   (processed image to cache entry /home/cns/crosswalk-5.34.104.5/out/res/drawable-mdpi/crosswalk.png: 69% size of source)
   [crunch] Processing image to cache: /home/cns/crosswalk-5.34.104.5/DemoPhone/res/drawable-xhdpi/crosswalk.png => /home/cns/crosswalk-5.34.104.5/out/res/drawable-xhdpi/crosswalk.png
   [crunch]   (processed image to cache entry /home/cns/crosswalk-5.34.104.5/out/res/drawable-xhdpi/crosswalk.png: 67% size of source)
   [crunch] Processing image to cache: /home/cns/crosswalk-5.34.104.5/DemoPhone/res/drawable/icon.png => /home/cns/crosswalk-5.34.104.5/out/res/drawable/icon.png
   [crunch]   (processed image to cache entry /home/cns/crosswalk-5.34.104.5/out/res/drawable/icon.png: 96% size of source)
   [crunch] Crunched 5 PNG files to update cache

-package-resources:
     [aapt] Creating full resource package...
     [aapt] Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
     [aapt] nothing matches overlay file multi_field_time_picker_dialog.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file two_field_date_picker.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file validation_message_bubble.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file autofill_text.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file color_picker_advanced_component.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file color_picker_dialog_content.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file color_picker_dialog_title.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
     [aapt] nothing matches overlay file date_time_suggestion.xml, for flavor ,,,,,,,,,,,,,,,,,,,v17
Buildfile: /home/cns/crosswalk-5.34.104.5/scripts/ant/apk-package.xml

-package:
[apkbuilder] Current build type is different than previous build: forced apkbuilder run.
[apkbuilder] Creating app-unsigned.apk for release...
Command "python scripts/gyp/finalize_apk.py --android-sdk-root=/home/cns/adt/sdk --unsigned-apk-path=out/app-unsigned.apk --final-apk-path=out/DemoPhone.apk --keystore-path=scripts/ant/xwalk-debug.keystore --keystore-alias=xwalkdebugkey --keystore-passcode=xwalkdebug" exited with non-zero exit code 1
**To Reproduce (if possible)**

**Expected behavior**

**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**

**Comment by egreenmachine** [comment]
Right at the top of that it says

**Comment by egreenmachine** [comment]
Right at the top of that guide it says

> This guide is out of date.
> We are no longer supporting this mobile guide. It is still here strictly for informational purposes. We do not expect this guide to still work.

I am not sure what you are looking for here, but it is not expected that crosswalk still works.
