### ISSUE TITLE
What is the type definition of sessionDescriptionHandlerFactoryOptions

### ISSUE THREAD

**Issue by bezbahadori** [onsip/SIP.js#625]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).
Hi I am working on typescript and I am not sure how I can find the typedef of sessionDescriptionHandlerFactoryOptions: sessionDescriptionHandlerFactoryOptions
I am trying to work with the version 11.6 and trying to register the new UA

```
> this.ua = new SIP.UA({
>     // User Configurable Options
>     uri:               this.options.ua.uri,
>     authorizationUser: this.options.ua.authorizationUser,
>     password:          this.options.ua.password,
>     displayName:       this.options.ua.displayName,
>     // Undocumented "Advanced" Options
>     userAgentString:   this.options.ua.userAgentString,
>     // Fixed Options
>     register:          true,
>     sessionDescriptionHandlerFactoryOptions: sessionDescriptionHandlerFactoryOptions,
>     transportOptions: {
>       traceSip: this.options.ua.traceSip,
>       wsServers: this.options.ua.wsServers
>     }
>   });
```

**Comment by egreenmachine** [comment]
Thanks for ignoring the issue template that we are using to try and prevent these types of questions here. 

>Please use our google group (https://groups.google.com/forum/#!forum/sip_js) If this doesn’t look right, choose a different type.

> These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).

How can we be more clear to prevent this in the future? We are looking to improve this process
