### ISSUE TITLE
Cannot read property 'hasHeader' of undefined

### ISSUE THREAD

**Issue by vegarda** [onsip/SIP.js#627]
This will be vague. Any comment will be appreciated.

One of out customers is getting "Cannot read property 'hasHeader' of undefined" randomly when not in a sip session.

**Logs**
`09:21:48 console Tue Nov 06 2018 09:21:48 GMT+0100 (sentraleuropeisk normaltid) | sip.parser | no CRLF found, not a SIP message, discarded`

`09:21:49 exception TypeError: Cannot read property 'hasHeader' of undefined`

Trace from sentry:
![image](https://user-images.githubusercontent.com/2388995/48053534-3d5d9300-e1ab-11e8-8fee-336c38b37634.png)

**To Reproduce (if possible)**
Unknown. Happens when not in session

**Environment Information**
SIP.js **0.11.4**
Chrome 70
Windows 10

**Comment by egreenmachine** [comment]
I am going to close this due to inactivity. Feel free to reopen it and provide SIP packets if you are still experiencing this.
