### ISSUE TITLE
TS7010 and TS2503 compile errors in TypeScript

### ISSUE THREAD

**Issue by Amaylia** [onsip/SIP.js#642]
**Describe the bug**
When compiling a project in TypeScript which includes SIP.js I get TS7010 and TS2503 compile errors.

**Logs**
../sipjs/types/session.d.ts(83,3): error TS7010: 'invite', which lacks return-type annotation, implicitly has an 'any' return type.
../sipjs/types/subscription.d.ts(16,57): error TS2503: Cannot find namespace 'C'.
../sipjs/types/subscription.d.ts(17,70): error TS2503: Cannot find namespace 'C'.
../sipjs/types/subscription.d.ts(18,60): error TS2503: Cannot find namespace 'C'.

**To Reproduce (if possible)**
Use SIP.js in a typescript project and compile the project.

**Expected behavior**
The project should build successfully without errors.

**Observed behavior**
Errors were produced and the project failed to build.

**Environment Information**
- TypeScript v3.2.2
- node v8.15
- npm v6.4.1

**Additional context**
I am using the following tsconfig.json to build my project:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "experimentalDecorators":true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "removeComments": true,
    "outDir": "build",
    "rootDir": "src"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

I was able to fix the compile errors by adding an import to https://github.com/onsip/SIP.js/blob/master/types/subscription.d.ts
```
import { C } from "./Constants";
```

And by changing https://github.com/onsip/SIP.js/blob/master/types/session.d.ts#L83 to
```
  invite(): this;
```

Thanks!  And sorry if I'm not doing something correctly.

**Comment by james-criscuolo** [comment]
Can you try this with Pull Request #639? There are instructions in the description to install it. That will soon be the next version of SIP.js, and completely changes our use of Typescript.

While we didn't run into this issue ourselves, we want to make sure that this issue is corrected with the new version.

**Comment by Amaylia** [comment]
Thank you for the quick response, I tried to compile my project with that version and got the following compile errors:
```
node_modules/sip.js/types/index.d.ts(13,25): error TS7010: 'sanityCheck', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/sip.js/types/index.d.ts(33,12): error TS7005: Variable 'Transactions' implicitly has an 'any' type.
node_modules/sip.js/types/index.d.ts(56,12): error TS7005: Variable 'SIP' implicitly has an 'any' type.
node_modules/sip.js/types/session.d.ts(79,32): error TS7051: Parameter has a name but no type. Did you mean 'arg0: OutgoingRequest'?
node_modules/sip.js/types/session.d.ts(79,49): error TS7051: Parameter has a name but no type. Did you mean 'arg1: DTMF'?
```

**Comment by james-criscuolo** [comment]
We have noImplicitAny turned off for the time being, due to an issue with the Grammar, but I've repushed the PR and compiled branch with fixes for those, if you wouldn't mind retesting.

**Comment by Amaylia** [comment]
Thank you very much, I updated my that package and the only errors I am getting now are the implicit any ones, but I don't really want to bug you anymore with that if that isn't a setting that you are using anyways.  Thanks a lot for your help!

**Comment by james-criscuolo** [comment]
I'm going to close, we'll be releasing that branch (now on master) in the coming days. Thanks for testing!
