### ISSUE TITLE
Expected event when ending remote call

### ISSUE THREAD

**Issue by weltongbi** [onsip/SIP.js#649]
**Describe the bug**
There are no events when the Inbound Call is terminated by remote..
```
The events during the answered call.
Events
1 - answer call 
...
iceCandidate sip-0.13.2.min.js:1:13777
iceCandidate sip-0.13.2.min.js:1:13777
iceCandidate sip-0.13.2.min.js:1:13777
iceGatheringComplete sip-0.13.2.min.js:1:13777
directionChanged sip-0.13.2.min.js:1:13777
getDescription sip-0.13.2.min.js:1:13777
stateChanged sip-0.13.2.min.js:1:13777
accepted sip-0.13.2.min.js:1:13777
connected sip-0.13.2.min.js:1:13777
messageSent sip-0.13.2.min.js:1:13777
message sip-0.13.2.min.js:1:13777
confirmed sip-0.13.2.min.js:1:13777
iceConnectionConnected sip-0.13.2.min.js:1:13777
iceGatheringComplete sip-0.13.2.min.js:1:13777
iceCandidate sip-0.13.2.min.js:1:13777
iceGatheringComplete sip-0.13.2.min.js:1:13777
stateChanged sip-0.13.2.min.js:1:13777
transactionDestroyed sip-0.13.2.min.js:1:13777

2 - during the conversation
...
iceConnectionDisconnected sip-0.13.2.min.js:1:13777
iceConnectionConnected sip-0.13.2.min.js:1:13777
iceConnectionDisconnected sip-0.13.2.min.js:1:13777
iceConnectionConnected

3 - Remote ended call.

iceConnectionDisconnected sip-0.13.2.min.js:1:13777

4 - after a few seconds

iceConnectionFailed sip-0.13.2.min.js:1:13777
ICE failed, add a TURN server and see about:webrtc for more details
```

**To reproduce (if possible)**
      1. Inbound Call accepted
      2. inbound call disconnect

**Expected behavior**
Event: __ended__ or __terminated__

**Environment Information**
"sip.js": "0.13.2"
FreeSwitch 1.8
Chrome 72 and FireFox 65 on windows.

**Comment by egreenmachine** [comment]
Please give us full logs with traceSip enabled

**Comment by weltongbi** [comment]
***log***
[1.txt](https://github.com/onsip/SIP.js/files/2845878/1.txt)

do not remove events.

**Comment by egreenmachine** [comment]
You will only get an `ended` or `terminated` event when the sip session has ended. The SIP session is still active, but it looks like the media stream has failed for some reason outside of SIP.js.

**Comment by weltongbi** [comment]
this is a normal body. Do I have to call the disconnect function on the client? otherwise it remains connected. and the call has ended on the far side.

**Comment by egreenmachine** [comment]
According to your logs you do not get a `BYE` packet. Just terminating the media will not terminate the call.

This is an example `BYE` packet.
```
BYE sip:alice@pc33.atlanta.com SIP/2.0
Via: SIP/2.0/UDP 192.0.2.4;branch=z9hG4bKnashds10
Max-Forwards: 70
From: Bob <sip:bob@biloxi.com>;tag=a6c85cf
To: Alice <sip:alice@atlanta.com>;tag=1928301774
Call-ID: a84b4c76e66710
CSeq: 231 BYE
Content-Length: 0
```

**Comment by egreenmachine** [comment]
If you are terminating from the SIP.js side you will need to call [`session.bye()`](https://sipjs.com/api/0.13.0/session/#byeoptions)
