### ISSUE TITLE
Not able to make audio calls

### ISSUE THREAD

**Issue by AmitOhal** [onsip/SIP.js#653]
Not able to make voice calls.
I am using OnSIP's  demo project and have updated the sip.js library from version 6 to 13.
I am getting the following error when I placed call in Chrome browser version 72.

Please let me know how to resolve the issue.
![sip_js_13](https://user-images.githubusercontent.com/40357758/53166055-48bdb880-35fa-11e9-9d67-239b17dfccbf.PNG)

**Comment by james-criscuolo** [comment]
What is the demo project you describe? Jumping from 6 to 13 won't "just work", it is very likely at least a few changes would need to occur. Also we need full logs (preferably in a gist).

**Comment by pgade-cemtrexlabs** [comment]
I think OnSIP's demo application Means Web phone give in [https://developer.onsip.com/docs/guides/b-webrtc-phone](url)

**Comment by james-criscuolo** [comment]
It looks like you had a post that you deleted pointing here: https://developer.onsip.com/docs/guides/b-webrtc-phone

We will work on getting that site updated later today, for now please use the code and guides we have available here: https://sipjs.com

I'm going to close as this isn't an issue with the library.
