### ISSUE TITLE
Uncaught (in promise) SESSION_DESCRIPTION_HANDLER_ERROR: Error with Session Description Handler

### ISSUE THREAD

**Issue by Franweb79** [onsip/SIP.js#654]
Since some weeks ago, My WebRTC client stopped working.when pressing the "Accept call" button.  It was using SIPjs 0.11.6. Until then, it worked fine.

I thought maybe it was a problem of library with latest browser or maybe a FreeSWITCH problem. 

I downloaded the latest SIPjs version, and when pressing the "Accept call" button, i get this error,maybe is the same problem but on 0.11.6 I got no such error:

 **Uncaught (in promise) SESSION_DESCRIPTION_HANDLER_ERROR: Error with Session Description Handler at line:sip-0.13.5.js:18864**

When I go into that line of the SIPjs file, I found this:

![imagen](https://user-images.githubusercontent.com/30956748/53427226-dc232f00-39e8-11e9-8a0c-5a99265bb880.png)

The error is firing when I use this function:

![imagen](https://user-images.githubusercontent.com/30956748/53427359-1a205300-39e9-11e9-8bbb-c80988a5c48d.png)

The getSessionDescriptionHandlerOptions() code is:

![imagen](https://user-images.githubusercontent.com/30956748/53427483-489e2e00-39e9-11e9-8cac-5c203c587f5e.png)

And the self.session returns this:

![imagen](https://user-images.githubusercontent.com/30956748/53427916-17722d80-39ea-11e9-987a-478f0e034124.png)
![imagen](https://user-images.githubusercontent.com/30956748/53427939-222cc280-39ea-11e9-8f67-f6a7b759016f.png)

I am using FreeSWITCH 1.6.20 and Chrome 72.0.3626.119.

In Firefox the call gets accepted but it suddenly closes, here is the log 

REGISTER sip:example.com SIP/2.0
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK7015546
Max-Forwards: 70
To: "Main Agent (1011)" <sip:1011@example.com>
From: "Main Agent (1011)" <sip:1011@example.com>;tag=i6ccama974
Call-ID: idpr19l6g01qmvpu9fq1e5
CSeq: 6574 REGISTER
Contact: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:481461df-d01b-4ef6-97ef-54263f1bdc71>";expires=600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: path, gruu, replaces, outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK7015546;received=146.4.10.10;rport=58845
From: "Main Agent (1011)" <sip:1011@example.com>;tag=i6ccama974
To: "Main Agent (1011)" <sip:1011@example.com>;tag=tcDQ3QNy1HSgK
Call-ID: idpr19l6g01qmvpu9fq1e5
CSeq: 6574 REGISTER
User-Agent: UCP SIP
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE
Supported: precondition, 100rel, timer, path, replaces
WWW-Authenticate: Digest realm="example.com", nonce="2031011a-39e2-11e9-8178-6f712dec771c", algorithm=MD5, qop="auth"
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | sending WebSocket message:

REGISTER sip:example.com SIP/2.0
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK5898454
Max-Forwards: 70
To: "Main Agent (1011)" <sip:1011@example.com>
From: "Main Agent (1011)" <sip:1011@example.com>;tag=i6ccama974
Call-ID: idpr19l6g01qmvpu9fq1e5
CSeq: 6575 REGISTER
Authorization: Digest algorithm=MD5, username="1012", realm="example.com", nonce="2031011a-39e2-11e9-8178-6f712dec771c", uri="sip:example.com", response="944c18bf7a055067e4c8988e448723ce", qop=auth, cnonce="ne5mrcpp9t1f", nc=00000001
Contact: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:481461df-d01b-4ef6-97ef-54263f1bdc71>";expires=600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: path, gruu, replaces, outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK5898454;received=146.4.10.10;rport=58845
From: "Main Agent (1011)" <sip:1011@example.com>;tag=i6ccama974
To: "Main Agent (1011)" <sip:1011@example.com>;tag=UN6F5j61ytF3e
Call-ID: idpr19l6g01qmvpu9fq1e5
CSeq: 6575 REGISTER
Contact: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>;expires=600
Date: Tue, 26 Feb 2019 16:18:17 GMT
User-Agent: UCP SIP
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE
Supported: precondition, 100rel, timer, path, replaces
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | sending WebSocket message:

SUBSCRIBE sip:1012@example.com SIP/2.0
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK6305996
Max-Forwards: 70
To: <sip:1012@example.com>
From: "Main Agent (1011)" <sip:1011@example.com>;tag=bmlipjj8i2
Call-ID: sl4h7otm652ic19jv6ue
CSeq: 9996 SUBSCRIBE
Event: presence
Expires: 3600
Contact: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: replaces, outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | sending WebSocket message:

SUBSCRIBE sip:1013@example.com SIP/2.0
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK9102729
Max-Forwards: 70
To: <sip:1013@example.com>
From: "Main Agent (1011)" <sip:1011@example.com>;tag=k3tilmhq3g
Call-ID: sl4h786munkji2j3prij
CSeq: 1049 SUBSCRIBE
Event: presence
Expires: 3600
Contact: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: replaces, outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | sending WebSocket message:

SUBSCRIBE sip:1014@example.com SIP/2.0
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK8883176
Max-Forwards: 70
To: <sip:1014@example.com>
From: "Main Agent (1011)" <sip:1011@example.com>;tag=0r1k9b16qg
Call-ID: sl4h7hs2cl4fddpbbu9a
CSeq: 5477 SUBSCRIBE
Event: presence
Expires: 3600
Contact: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: replaces, outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | received WebSocket text message:

SIP/2.0 202 Accepted
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK6305996;received=146.4.10.10;rport=58845
From: "Main Agent (1011)" <sip:1011@example.com>;tag=bmlipjj8i2
To: <sip:1012@example.com>;tag=0UpT82VTUSQx
Call-ID: sl4h7otm652ic19jv6ue
CSeq: 9996 SUBSCRIBE
Contact: <sip:1012@91.135.71.170:5070>
Expires: 3600
User-Agent: UCP SIP
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE
Supported: precondition, 100rel, timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Subscription-State: active;expires=3600
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | received WebSocket text message:

SIP/2.0 202 Accepted
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK9102729;received=146.4.10.10;rport=58845
From: "Main Agent (1011)" <sip:1011@example.com>;tag=k3tilmhq3g
To: <sip:1013@example.com>;tag=DQcOlXbDWwxp
Call-ID: sl4h786munkji2j3prij
CSeq: 1049 SUBSCRIBE
Contact: <sip:1013@91.135.71.170:5070>
Expires: 3600
User-Agent: UCP SIP
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE
Supported: precondition, 100rel, timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Subscription-State: active;expires=3600
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:17 GMT+0100 (hora estándar de Europa central) | sip.transport | received WebSocket text message:

SIP/2.0 202 Accepted
Via: SIP/2.0/WSS 30p1cmfmteba.invalid;branch=z9hG4bK8883176;received=146.4.10.10;rport=58845
From: "Main Agent (1011)" <sip:1011@example.com>;tag=0r1k9b16qg
To: <sip:1014@example.com>;tag=m8J6WyDNiSwg
Call-ID: sl4h7hs2cl4fddpbbu9a
CSeq: 5477 SUBSCRIBE
Contact: <sip:1014@91.135.71.170:5070>
Expires: 3600
User-Agent: UCP SIP
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE
Supported: precondition, 100rel, timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Subscription-State: active;expires=3600
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:27 GMT+0100 (hora estándar de Europa central) | sip.transport | received WebSocket text message:

INVITE sip:09lb6msj@30p1cmfmteba.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 91.135.71.170:5070;rport;branch=z9hG4bKSy4y437S507ca
Route: <sip:09lb6msj@146.4.10.10:58845>;transport=wss
Max-Forwards: 69
From: "Third Agent (1013)" <sip:1013@example.com>;tag=e2F0Zp1NB1ZvD
To: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>
Call-ID: fd7440cc-b484-1237-a988-901b0e538b46
CSeq: 1045161 INVITE
Contact: <sip:mod_sofia@91.135.71.170:5070>
User-Agent: UCP SIP
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE
Supported: precondition, 100rel, timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 893
X-UCP-ACTION: open-the-door
X-UCP-DEVICEID: 1235124
X-FS-Support: update_display,send_info

Remote-Party-ID: "Third Agent (1013)" <sip:1013@example.com>;party=calling;screen=yes;privacy=off

v=0

o=FreeSWITCH 1551177589 1551177590 IN IP4 91.135.71.170

s=FreeSWITCH

c=IN IP4 91.135.71.170

t=0 0

a=msid-semantic: WMS JaZDrEZXnCMEHERJk1tQKXTWr1Zk94eI

m=audio 20318 RTP/SAVPF 102

a=rtpmap:102 SILK/8000

a=fmtp:102 useinbandfec=1; usedtx=0

a=fingerprint:sha-256 3D:31:63:0A:35:84:28:91:9E:94:0F:6A:5A:E2:99:1A:DC:AA:36:4C:86:81:C7:EE:72:EB:0D:F4:A8:87:2E:AA

a=setup:actpass

a=rtcp-mux

a=rtcp:20318 IN IP4 91.135.71.170

a=ssrc:1485715459 cname:43cmy19LuMf1gXBr

a=ssrc:1485715459 msid:JaZDrEZXnCMEHERJk1tQKXTWr1Zk94eI a0

a=ssrc:1485715459 mslabel:JaZDrEZXnCMEHERJk1tQKXTWr1Zk94eI

a=ssrc:1485715459 label:JaZDrEZXnCMEHERJk1tQKXTWr1Zk94eIa0

a=ice-ufrag:PV7pIRbZI1aIVfgQ

a=ice-pwd:9j2yb29vEfnL3O3IA1X8IZYh

a=candidate:2992343502 1 udp 659136 91.135.71.170 20318 typ host generation 0

a=candidate:2992343502 2 udp 659136 91.135.71.170 20318 typ host generation 0

a=ptime:20

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:27 GMT+0100 (hora estándar de Europa central) | sip.sipmessage | header "Replaces" not present sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:27 GMT+0100 (hora estándar de Europa central) | sip.transport | sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 91.135.71.170:5070;rport;branch=z9hG4bKSy4y437S507ca
To: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>
From: "Third Agent (1013)" <sip:1013@example.com>;tag=e2F0Zp1NB1ZvD
Call-ID: fd7440cc-b484-1237-a988-901b0e538b46
CSeq: 1045161 INVITE
Supported: replaces, outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0

sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:27 GMT+0100 (hora estándar de Europa central) | sip.dialog | fd7440cc-b484-1237-a988-901b0e538b4672utnimupte2F0Zp1NB1ZvD | new UAS dialog created with status EARLY sip-0.11.6.min.js:1:8973
Tue Feb 26 2019 17:18:27 GMT+0100 (hora estándar de Europa central) | sip.transport | sending WebSocket message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 91.135.71.170:5070;rport;branch=z9hG4bKSy4y437S507ca
To: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>;tag=72utnimupt
From: "Third Agent (1013)" <sip:1013@example.com>;tag=e2F0Zp1NB1ZvD
Call-ID: fd7440cc-b484-1237-a988-901b0e538b46
CSeq: 1045161 INVITE
Contact: <sip:09lb6msj@30p1cmfmteba.invalid;transport=ws>
Supported: replaces, outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0

**Comment by james-criscuolo** [comment]
https://groups.google.com/forum/#!topic/sip_js/yFduTs7hgfw

**Comment by StoneGH** [comment]
@Franweb79 Has the problem been solved?

**Comment by kiennguyen07** [comment]
Anyone know if the problem solved?
