### ISSUE TITLE
receiveNotify testing for messageBody.statusCode instead of messageBody.status_code

### ISSUE THREAD

**Issue by amessina** [onsip/SIP.js#663]
I'm testing out REFER with 0.13.6 and found that SIP.js didn't terminate it's part of the call after a successful refer (initiated from SIP.js as the referrer).

In the receiveNotify function at https://github.com/onsip/SIP.js/blob/cdaf18a0ceec15e2ae742af672381f80444e7112/src/Session.ts#L2061

https://github.com/onsip/SIP.js/blob/cdaf18a0ceec15e2ae742af672381f80444e7112/src/Session.ts#L2075

Above test refers to `messageBody.statusCode` which doesn't exist in the `messageBody` object, though `messageBody.status_code` does, and enables SIP to properly terminate it's part of the session after a successful REFER.

**Comment by james-criscuolo** [comment]
Good catch, we should be doing a release early next week with this.

**Comment by amessina** [comment]
@james-criscuolo Thank you kindly!
