### ISSUE TITLE
Strange bug on "Contact" header parsing.

### ISSUE THREAD

**Issue by kuzinmv** [onsip/SIP.js#665]
**contact.uri undefined after a call contacts = response.getHeaders("contact")**
 Uncaught TypeError: Cannot read property 'user' of undefined.
https://github.com/onsip/SIP.js/blob/master/src/RegisterContext.ts#L277

**Logs**
https://gist.github.com/kuzinmv/2a0089530492cfad9799f8640db4d05b#file-onsip-array-iteration-bug-L311

Seems like there is extra unaccounted array keys/values if
If server answer with several contact in the "Contact" header like in the log above then i got the bug "Cannot read property 'user' of undefined."

**Observed behavior**
![Снимок экрана 2019-03-26 в 14 34 21](https://user-images.githubusercontent.com/6621928/54982773-b08a6900-4fd5-11e9-9cbd-9109c8cba330.png)
When parser iterate trough "parsed" array first three indexes looks well 0,1,2 but after it had 2 extra indexes "pushOnce" and "popAll" and added whole raw contact header string twice to a message.headers

**Environment Information**
 - Browser Chrome 73.0.3683.86

**Comment by egreenmachine** [comment]
It looks like you were modifying the Array prototype which was causing the issue. We were iterating the contact array in an unsafe manner. I have fixed the issue and it will go out with our next version release. Thanks for finding this.
