### ISSUE TITLE
Document .terminate() method

### ISSUE THREAD

**Issue by Rob--W** [onsip/SIP.js#67]
I am currently considering to replace JsSIP in an existing application with SIP.js, and noticed that the `terminate()` method is missing from the documentation. It seemed extremely weird that API users have to manually keep track of the call state and call `bye()`, `cancel()`, etc. depending on the tracked call state when I want to end a call.

The source code of Session.js shows that `terminate()` *does* exist, so why is it not documented?

**Comment by klarrimore** [comment]
Regardless of whether "terminate" sticks around long term, there should be at least some mention in the Session docs and example code that simply implementing "bye" and "cancel" listeners isn't a failsafe method of determining a session ended.

**Comment by wakamoleguy** [comment]
I've added some documentation for the `terminated` method.  It doesn't always work as you'd expect in 0.6.x versions.  http://sipjs.com/api/0.6.0/session/#terminated

**Comment by klarrimore** [comment]
You guys are awesome.
