### ISSUE TITLE
Ignore the call failed and it will show incoming call page again

### ISSUE THREAD

**Issue by JackZong** [onsip/SIP.js#670]
**Describe the bug**
when I received an incoming call called by myself, then I can see two sending INVITE events. then I will receive two INVITE events. and it seems that this event happened two times. 

**Logs**

SIP/2.0 200 OK  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK1490413  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=aps1Aw  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1683 REGISTER  Content-Length: 0  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;expires=49;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>" | 427 | 16:38:42.496
-- | -- | --
REGISTER sip:sip-xmnup.lab.nordigy.ru SIP/2.0  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK9543419  Max-Forwards: 70  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1684 REGISTER  Authorization: Digest algorithm=MD5, username="58614006", realm="sip-xmnup.lab.nordigy.ru", nonce="XKMffFyjHlABfZ3g5IWiFbefLaaXAvvv", uri="sip:sip-xmnup.lab.nordigy.ru", response="8c93f11de468da82ab1d00733f539b9c"  P-rc-endpoint-id: Hq-HgfjLToC4kudVAb4QTw  Client-id:85JMPVhcQMeVtOF5qLANSw  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>";expires=600  Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER  Supported: path, gruu, outbound  User-Agent: RingCentral for Outlook/2.0.49 Macintosh-Intel-Mac-OS-X-10_13_6 RCWEBPHONE/0.6.3  Content-Length: 0 | 948 | 16:39:28.505
SIP/2.0 200 OK  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK9543419  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=3tDv3C  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1684 REGISTER  Content-Length: 0  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;expires=49;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>" | 427 | 16:39:28.509
REGISTER sip:sip-xmnup.lab.nordigy.ru SIP/2.0  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK7150094  Max-Forwards: 70  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1685 REGISTER  Authorization: Digest algorithm=MD5, username="58614006", realm="sip-xmnup.lab.nordigy.ru", nonce="XKMffFyjHlABfZ3g5IWiFbefLaaXAvvv", uri="sip:sip-xmnup.lab.nordigy.ru", response="8c93f11de468da82ab1d00733f539b9c"  P-rc-endpoint-id: Hq-HgfjLToC4kudVAb4QTw  Client-id:85JMPVhcQMeVtOF5qLANSw  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>";expires=600  Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER  Supported: path, gruu, outbound  User-Agent: RingCentral for Outlook/2.0.49 Macintosh-Intel-Mac-OS-X-10_13_6 RCWEBPHONE/0.6.3  Content-Length: 0 | 948 | 16:40:14.517
SIP/2.0 100 Trying  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK7150094  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1685 REGISTER  Content-Length: 0 | 277 | 16:40:14.544
SIP/2.0 401 Unauthorized  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK7150094  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=3lg2hH  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1685 REGISTER  Content-Length: 0  Www-Authenticate: Digest realm="sip-xmnup.lab.nordigy.ru", nonce="XKMhGlyjH+5E0uRe+tSNAale8ojzLqbD" | 395 | 16:40:14.549
REGISTER sip:sip-xmnup.lab.nordigy.ru SIP/2.0  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK4273135  Max-Forwards: 70  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1686 REGISTER  Authorization: Digest algorithm=MD5, username="58614006", realm="sip-xmnup.lab.nordigy.ru", nonce="XKMhGlyjH+5E0uRe+tSNAale8ojzLqbD", uri="sip:sip-xmnup.lab.nordigy.ru", response="d72bf80c2bc22a50b36fcf876db0cd1f"  P-rc-endpoint-id: Hq-HgfjLToC4kudVAb4QTw  Client-id:85JMPVhcQMeVtOF5qLANSw  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>";expires=600  Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER  Supported: path, gruu, outbound  User-Agent: RingCentral for Outlook/2.0.49 Macintosh-Intel-Mac-OS-X-10_13_6 RCWEBPHONE/0.6.3  Content-Length: 0 | 948 | 16:40:14.552
SIP/2.0 100 Trying  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK4273135  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1686 REGISTER  Content-Length: 0 | 277 | 16:40:14.590
SIP/2.0 200 OK  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK4273135  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=3EOqLT  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1686 REGISTER  Content-Length: 0  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;expires=51 | 354 | 16:40:14.605
REGISTER sip:sip-xmnup.lab.nordigy.ru SIP/2.0  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK7991195  Max-Forwards: 70  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1687 REGISTER  Authorization: Digest algorithm=MD5, username="58614006", realm="sip-xmnup.lab.nordigy.ru", nonce="XKMhGlyjH+5E0uRe+tSNAale8ojzLqbD", uri="sip:sip-xmnup.lab.nordigy.ru", response="d72bf80c2bc22a50b36fcf876db0cd1f"  P-rc-endpoint-id: Hq-HgfjLToC4kudVAb4QTw  Client-id:85JMPVhcQMeVtOF5qLANSw  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>";expires=600  Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER  Supported: path, gruu, outbound  User-Agent: RingCentral for Outlook/2.0.49 Macintosh-Intel-Mac-OS-X-10_13_6 RCWEBPHONE/0.6.3  Content-Length: 0 | 948 | 16:41:02.609
SIP/2.0 200 OK  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK7991195  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=39N5do  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1687 REGISTER  Content-Length: 0  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;expires=51;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>" | 427 | 16:41:02.626
REGISTER sip:sip-xmnup.lab.nordigy.ru SIP/2.0  Via: SIP/2.0/WSS s820174b7u0v.invalid;branch=z9hG4bK1277343  Max-Forwards: 70  To: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>  From: <sip:18552085154*102@sip-xmnup.lab.nordigy.ru>;tag=0vt52cmhap  Call-ID: ugrrphkktt3p7db5nu121j  CSeq: 1688 REGISTER  Authorization: Digest algorithm=MD5, username="58614006", realm="sip-xmnup.lab.nordigy.ru", nonce="XKMhGlyjH+5E0uRe+tSNAale8ojzLqbD", uri="sip:sip-xmnup.lab.nordigy.ru", response="d72bf80c2bc22a50b36fcf876db0cd1f"  P-rc-endpoint-id: Hq-HgfjLToC4kudVAb4QTw  Client-id:85JMPVhcQMeVtOF5qLANSw  Contact: <sip:706ouvmp@s820174b7u0v.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:ee1ef663-76ab-47fa-b0da-6f45d736e9cb>";expires=600  Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER  Supported: path, gruu, outbound  User-Agent: RingCentral for Outlook/2.0.49 Macintosh-Intel-Mac-OS-X-10_13_6 RCWEBPHONE/0.6.3  Content-Length: 0 | 948 | 16:41:51.541
  |   |  

**To Reproduce (if possible)**
1. this will happens only from time to time
**Expected behavior**
when I ignore the incoming call, I incoming call page should disappear.
**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**

**Comment by egreenmachine** [comment]
Can we please get full SIP.js logs in a [gist](https://gist.github.com/)

**Comment by JackZong** [comment]
> Can we please get full SIP.js logs in a [gist](https://gist.github.com/)

hi @egreenmachine ， I try to created a log file https://gist.github.com/JackZong/f215bfbfed7f7f0158c7bd799a90b8e2

**Comment by egreenmachine** [comment]
That is not SIP.js logs. Looking at the logs, it appears that the clients are also not SIP.js. I am closing this as invalid.
