### ISSUE TITLE
SDP not matching up...

### ISSUE THREAD

**Issue by chadstachowicz** [onsip/SIP.js#675]
I send this from freeswitch...

   INVITE sip:zomnio8@zomnio.onsip.com SIP/2.0
   Via: SIP/2.0/UDP 34.213.223.189;rport;branch=z9hG4bKrat3vF5138U2B
   Max-Forwards: 70
   From: "Outbound Call" <sip:+19803338415@34.213.223.189>;tag=eyB8SHg4SrK5N
   To: <sip:zomnio8@zomnio.onsip.com>
   Call-ID: d6845bda-d99b-1237-fca1-06efd6a1998a
   CSeq: 3084164 INVITE
   Contact: <sip:mod_sofia@34.213.223.189:5060>
   User-Agent: FreeSWITCH-mod_sofia/1.9.0+git~20181120T210412Z~968c76b29c~64bit
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
   Supported: timer, path, replaces
   Allow-Events: talk, hold, conference, refer
   Content-Type: application/sdp
   Content-Disposition: session
   Content-Length: 224
   X-FS-Support: update_display,send_info
   Remote-Party-ID: "Outbound Call" <sip:+19803338415@34.213.223.189>;party=calling;screen=yes;privacy=off
   
   v=0
   o=FreeSWITCH 1555255275 1555255276 IN IP4 34.213.223.189
   s=FreeSWITCH
   c=IN IP4 34.213.223.189
   t=0 0
   m=audio 20638 RTP/AVP 0 101
   a=rtpmap:0 PCMU/8000
   a=rtpmap:101 telephone-event/8000
   a=fmtp:101 0-16
   a=ptime:20

but I get this in from Onsip..

INVITE sip:r4sbltdj@104.12.253.127:50719;transport=ws;nat=yes;aor=zomnio8%40zomnio.onsip.com SIP/2.0
Record-Route: <sip:199.7.173.180:443;transport=wss;r2=on;lr;ftag=S6eQ93gZBcN2j>
Record-Route: <sip:199.7.173.180;r2=on;lr;ftag=S6eQ93gZBcN2j>
Record-Route: <sip:199.7.173.100;lr;ftag=S6eQ93gZBcN2j;did=f5f.ef44b7d1;ns=1;pr=3>
Record-Route: <sip:199.7.175.104;lr;ftag=S6eQ93gZBcN2j;did=f5f.0e110717>
Via: SIP/2.0/WSS 199.7.173.180:443;branch=z9hG4bK7921.1bae42f4.0
Via: SIP/2.0/UDP 199.7.173.100:5060;rport=5060;received=199.7.173.100;branch=z9hG4bK7921.e79154b2.0
Via: SIP/2.0/UDP 199.7.175.104:5060;branch=z9hG4bK7921.14dd7971.0
Via: SIP/2.0/UDP 34.213.223.189;received=34.213.223.189;rport=5060;branch=z9hG4bK68UyNaHKU5K8D
Max-Forwards: 67
From: "Outbound Call" <sip:+19803338415@34.213.223.189>;tag=S6eQ93gZBcN2j
To: <sip:zomnio8@zomnio.onsip.com>
Call-ID: f1a17c16-d99c-1237-fca1-06efd6a1998a
CSeq: 3084402 INVITE
Contact: <sip:mod_sofia*34.213.223.189!5060@199.7.175.104;gr>
User-Agent: FreeSWITCH-mod_sofia/1.9.0+git~20181120T210412Z~968c76b29c~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, refer
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 742
X-FS-Support: update_display,send_info
Remote-Party-ID: "Outbound Call" <sip:+19803338415@34.213.223.189>;party=calling;screen=yes;privacy=off

v=0
o=FreeSWITCH 1555252420 1555252421 IN IP4 34.213.223.189
s=FreeSWITCH
c=IN IP4 199.7.173.72
t=0 0
m=audio 56314 UDP/TLS/RTP/SAVPF 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:56315
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-1 80:83:4E:98:41:C0:31:A6:21:1F:F5:66:A9:E0:D6:EC:5C:03:94:D9
a=ptime:20
a=ice-ufrag:Kf9UcGlz
a=ice-pwd:uQ76P5jXrS01egG6IHRvMwR3Wp
a=candidate:cuTqtaglS3SOQlSh 1 UDP 2130706431 199.7.173.72 56314 typ host
a=candidate:M8O7nmReSRUC6zJi 1 UDP 2130706175 2620:104:2031::2048 51994 typ host
a=candidate:cuTqtaglS3SOQlSh 2 UDP 2130706430 199.7.173.72 56315 typ host
a=candidate:M8O7nmReSRUC6zJi 2 UDP 2130706174 2620:104:2031::2048 51995 typ host

LogRocket.min.js:1 

This end up in Onsip returning a 480 temporarily unavailable? Is this a SIP.js setting to turn off secure RTP with the backend?

Chad

**Comment by egreenmachine** [comment]
Please contact [OnSIP support](https://support.onsip.com) for help with the OnSIP platform. This is not a SIP.js issue.

**Comment by chadstachowicz** [comment]
It actually was, it was solved with a sip.js upgrade.
