### ISSUE TITLE
Breaking Change in Options for session.terminate() 0.12.0 -> 0.13.0

### ISSUE THREAD

**Issue by timo-klarshift** [onsip/SIP.js#676]
**Describe the bug**
Before Version 0.13.0 we were able to use this:

`session.terminate({reason_phrase: foobar})`

Now we have to use:

`session.terminate({reasonPhrase: foobar})`

See: https://sipjs.com/api/0.13.0/session/#terminateoptions

I think it is related to: "Most internal use of underscored_variables has been converted to camelCase." - See changelogs for 0.13.0

This is not a problem directly, but the Documentation does still use the underscored_variables. So either you should update the Documentation or also parse the legacy Options. I think this affects the public API and is not referring to "internal use" of the library. I am not sure if the Change does affect other public methods of the API too.

**Logs**

**before 0.13.0**

```
CANCEL sip:xxxx@xxxx SIP/2.0
Via: SIP/2.0/WSS 192.0.2.175;branch=z9hG4bK6494185
To: <sip:xxxx@xxxx>
From: <sip:1100@xxxx>;tag=gm3t8tjo18
Call-ID: jf7rdffskeu941d0au7h
Max-Forwards: 70
CSeq: 7953 CANCEL
Reason: SIP;cause=487;text="user-cancelled"
Content-Length: 0
```

**>= 0.13.0**

```
CANCEL sip:xxxx@xxxx SIP/2.0
Via: SIP/2.0/WSS 192.0.2.131;branch=z9hG4bK1435797
Max-Forwards: 70
To: <sip:xxxx@xxxx>
From: <sip:1100@xxxx>;tag=399id9jvb7
Call-ID: tucopm7t6eq19uck7orv
CSeq: 3162 CANCEL
Supported: 100rel, outbound
User-Agent: xxxx/softphone
Content-Length: 0
```

**To Reproduce (if possible)**
1. Make an Outbound Call
2. Try to terminate the Call before it is established (session.temrinate)
3. Call is not ended

**Expected behavior**
The Parameters should not be missing in the SIP Headers and the Call should be ended correctly.

**Observed behavior**
SIP Headers missing and incorrect.

**Comment by james-criscuolo** [comment]
I've updated our documentation and added a line to those release notes regarding the breaking change. Thank you for reporting.
