### ISSUE TITLE
Breaking Change in how Headers are handled on session.terminate()

### ISSUE THREAD

**Issue by timo-klarshift** [onsip/SIP.js#677]
**Describe the bug**
When upgrading from 0.13.6 to 0.13.7 a simple session.terminate() stops working for me.

broken with 0.13.7

```
CANCEL sip:xxxx@xxxx SIP/2.0
Via: SIP/2.0/WSS 192.0.2.103;branch=z9hG4bK4491706
Max-Forwards: 70
To: <sip:xxxx@xxxx>
From: <sip:1100@xxxx>;tag=mih9m8ht2b
Call-ID: hcc94ru71t2ohdmoct7i
CSeq: 8393 CANCEL
Supported: 100rel, outbound
User-Agent: xxxx
Content-Length: 0
```

working with 0.13.6

```
CANCEL sip:xxxx@xxxx SIP/2.0
Via: SIP/2.0/WSS 192.0.2.232;branch=z9hG4bK4832835
To: <sip:xxxx@xxxx>
From: <sip:1100@xxxx>;tag=u3d5hkm1fi
Call-ID: rk39ondbvqg5rrdrg4gm
Max-Forwards: 70
CSeq: 3997 CANCEL
Content-Length: 0
```
    
rel100: SIP.C.supported.SUPPORTED for both cases

0.13.7 is including more Headers than 0.13.6 - also I do not know if that is whats causing the termination to fail.

**Logs**
Please include a [gist](https://gist.github.com/) or attached file with full logs. If this is not included, the first response will likely be requesting them.

**To Reproduce (if possible)**
1. Start a call
2. session.terminate() before session established.

**Expected behavior**
Call is ended.

**Observed behavior**
Call is not ended.

**Comment by james-criscuolo** [comment]
Can we get full logs in a gist? I'm curious how your server is responding.

**Comment by anshkatriya** [comment]
I'm having same issue in case of Outbound call. When I am terminating existing session before established server responding with **SIP/2.0 481 Call/Transaction Does Not Exist**

```
sipjs.js:20005 Fri Apr 19 2019 15:42:12 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionConnected
sipjs.js:20005 Fri Apr 19 2019 15:42:12 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionCompleted
sipjs.js:20005 Fri Apr 19 2019 15:42:16 GMT+0530 (India Standard Time) | sip.inviteclientcontext | canceling RTCSession
sipjs.js:20005 Fri Apr 19 2019 15:42:16 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

CANCEL sip:2014_99049@192.168.1.35:7443 SIP/2.0
Via: SIP/2.0/WSS f9grffti4ij5.invalid;branch=z9hG4bK8468826
Max-Forwards: 70
To: <sip:2014_99049@192.168.1.35:7443>
From: "callcenter" <sip:123@192.168.1.35:7443>;tag=de7bi9m9pm
Call-ID: usfqfvam59o0rtsrav79
CSeq: 243 CANCEL
Supported: 100rel, outbound
User-Agent: SIP.js/0.13.7
Content-Length: 0



sipjs.js:20005 Fri Apr 19 2019 15:42:16 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
sipjs.js:20005 Fri Apr 19 2019 15:42:16 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | resetIceGatheringComplete
VM637 jquery-2.1.1.min.js:4117 [Violation] 'click' handler took 180ms
sipjs.js:20005 Fri Apr 19 2019 15:42:16 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 481 Call/Transaction Does Not Exist
Via: SIP/2.0/WSS f9grffti4ij5.invalid;branch=z9hG4bK8468826;received=192.168.1.53;rport=42422
From: "callcenter" <sip:123@192.168.1.35:7443>;tag=de7bi9m9pm
To: <sip:2014_99049@192.168.1.35:7443>;tag=y99v02e23Bgea
Call-ID: usfqfvam59o0rtsrav79
CSeq: 243 CANCEL
Content-Length: 0



sipjs.js:20005 Fri Apr 19 2019 15:42:16 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionClosed

```

While using < 0.13.7, it works normally.

```
CANCEL sip:2013_99049@192.168.1.35:7443 SIP/2.0
Via: SIP/2.0/WSS pt1scsdsclu3.invalid;branch=z9hG4bK2190492
To: <sip:2013_99049@192.168.1.35:7443>
From: "callcenter" <sip:123@192.168.1.35:7443>;tag=samhtgmg9s
Call-ID: qku74ia8rtj8vpvhr4ul
Max-Forwards: 70
CSeq: 1073 CANCEL
Content-Length: 0



sipjs.js:516 Fri Apr 19 2019 15:41:09 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
jquery-2.1.1.min.js:4117 [Violation] 'click' handler took 242ms
sipjs.js:516 Fri Apr 19 2019 15:41:09 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS pt1scsdsclu3.invalid;branch=z9hG4bK2190492;received=192.168.1.53;rport=41694
From: "callcenter" <sip:123@192.168.1.35:7443>;tag=samhtgmg9s
To: <sip:2013_99049@192.168.1.35:7443>;tag=NQX4QDvHtyyFF
Call-ID: qku74ia8rtj8vpvhr4ul
CSeq: 1073 CANCEL
Content-Length: 0


```

**Comment by john-e-riordan** [comment]
Again, can we get full logs in a gist?

In particular, we would like all the logs from (all the requests to the server and responses from the server) from initial INVITE message up to and including the 481 Call/Transaction Does Not Exist.

While the CANCEL message in 0.13.7 does include "Supported" and "User-Agent" headers, those headers should not have any impact on how the CANCEL behaves or is handled (they are optional and informative only).

In short, as a standalone message, there is no problem that can be discerned from CANCEL message alone, but the 481 response suggest a problem related to earlier SIP messages. So it would be helpful to see those earlier SIP messages.

A "481 Call/Transaction Does Not Exist" indicates the server did not match the CANCEL to the initial INVITE which is a process that depends on values in different headers (not the Supported or User-Agent headers) in the messages exchanged starting with the initial INVITE until the server sends the 481.

**Comment by georgechaduneli** [comment]
https://gist.github.com/georgechaduneli/ed33151b6eeac5a0db52342890d45eb8

**Comment by john-e-riordan** [comment]
@georgechaduneli Thank you.
