### ISSUE TITLE
Are the cancel and bye (and failed) events mutually exclusive?

### ISSUE THREAD

**Issue by Rob--W** [onsip/SIP.js#68]
JsSIP has "ended" for termination of an established call, and "failed" for termination of a non-established call.

SIP.js has "failed", "cancel" and "bye" (and "rejected", but I've ignored it since it is documented that the "failed" event is always triggered thereafter).

Are these events mutually exclusive? I have written a wrapper around the JsSIP class, and the "ended" and "failed" events provides me the required functionality to reliably implement a destructor that is called exactly once for a RTCSession.

Does SIP.js provide such guarantees? Are the failed/bye/cancel events mutually exclusive, and is exactly one of them going to be triggered regardless of whether the call is established? If so, please document this.

**Comment by wakamoleguy** [comment]
I **think** that I covered all of the discussed behavior in the branch I merged in.  Testing was done soley via unit tests, and I'm going to follow up with some live testing soon.  Likely the demo-phone and then the developer.onsip.com front page.

**Comment by wakamoleguy** [comment]
FWIW, we also plan to document these events better on sipjs.com for the rollout of 0.7.0

**Comment by wakamoleguy** [comment]
These seem to be behaving as expected, with the exception of an unintended issue with Transport failure (#167).  There is another ticket for that, so I'm going to close this one.
