### ISSUE TITLE
Calls hung up after 32 seconds due to weird signalling from SIP.js with multiple Contact headers.

### ISSUE THREAD

**Issue by mamikk** [onsip/SIP.js#684]
**Describe the bug**
We have an issue with SIP.js where calls are hung up after 32 seconds.

It does not happen for every user and not for every call.

The SIP signaling is like this:

1. Server sends INVITE to SIP.js.
2. SIP.js sends 100 Trying.
3. SIP.js sends 180 Ringing with Contact o7q9sp25@qcduek7n2i0b.invalid;transport=ws.
4. The user answers the call.
5. SIP.js sends 200 OK with multiple Contact (and Allow) headers. Contact jl1ho683@cbiikcli5cch.invalid;transport=ws;ob is sent five times and Contact sip:o7q9sp25@qcduek7n2i0b.invalid;transport=ws is sent once.
6. The server sends ACK to sip:jl1ho683@cbiikcli5cch.invalid;transport=ws;ob.
7. SIP.js rejects this ACK (sip.ua | Request-URI does not point to us)
8. Retransmissions goes on for a while until SIP.js gives up and hangs up the call with BYE.

Also in the middle of this SIP.js sends multiple REGISTERs with both Contact headers.

Once the bug triggers. It will happen for all calls until the web application which is using SIP.js is re-loaded in the browser. Then it starts working again.

**Logs**
Logs: https://gist.github.com/mamikk/9cb8fd8365351bfe00b9d9d034f41271
(Logs are slightly edited to obfuscate phone numbers and IP-addresses)

**To Reproduce (if possible)**
I do not know how to reproduce this consistently. It happens for multiple users of our web application, but we have not been able to reproduce it locally. Also it usually takes multiple hours to trigger for the users which are having problems.

**Expected behavior**
I expect SIP.js to send consisent Contact/Allow headers in SIP signalling and that the call is not hung up after 32 seconds.

**Observed behavior**
SIP.js sends multiple Contact/Allow headers in SIP signalling and rejects ACK.

**Environment Information**
Backend SIP Proxy: Kamailio (5.1)
Browser: Chrome
SIP.js version 0.13.8

**Additional context**

**Comment by egreenmachine** [comment]
Can you test if this is still happening in `0.14.1`? We believe that it should be resolved in that version.

**Comment by mamikk** [comment]
Thanks. We will update our version to 0.14.1 and let you know if the bug triggers again.

**Comment by james-criscuolo** [comment]
Closing this since it appears we are resolved here, but feel free to re-open or open a new issue if the issue returns.
