### ISSUE TITLE
Holding/Unholding failed handeling

### ISSUE THREAD

**Issue by m-vellinga** [onsip/SIP.js#685]
**Is your feature request related to a problem? Please describe.**
Whenever you (UN)HOLD a call and the re-invite fails the session state is not adjusted. To give an example:

```
level=info message='[app] [Call][7pibyLMTS] on hold'
level=debug message='[sip.transport] sending WebSocket message:  INVITE
level=debug message='[sip.transport] received WebSocket text message:  SIP/2.0 100 Giving a try
level=debug message='[sip.transport] received WebSocket text message:  SIP/2.0 408 Request Timeout
level=info message='[app] [Call][7pibyLMTS] on hold'
level=debug message='[sip.inviteservercontext] Session is already on hold, cannot put it on hold again'
```
This leads to 2 things:

1. Due to localHold state it seems like the call is on hold but it actually isn't. This can lead to really awkward situation where someone can hear you while you expect they can't
2. Due to localHold state you can't retry to put it on hold because it breaks out early.

**Describe the solution you'd like**
A way to determine/listen if (un)holding succeeded and the ability to call (un)hold again when it failed.

**Describe alternatives you've considered**
We are currently investigating listening to the reinviteFailed emit and tracking/altering the localHold state ourselves. This will allow us to give feedback about the failed hold and have to ability to call .hold() again on the session.

**Additional context**
If you have any suggestions on how you would see this implemented (if at all) in SIP.js we could start things off with a pull request.

**Comment by egreenmachine** [comment]
We believe that this should be resolved with #682

**Comment by m-vellinga** [comment]
Alright! I'll keep an eye out. Thanks for the quick response!

**Comment by egreenmachine** [comment]
We believe that this should be resolved in `0.14.1` release. Can you please test and let us know?

**Comment by m-vellinga** [comment]
I'll have a look if we can, requires some mocking on our end as the 408 Request Timeout message was only send in very specific scenario's in our infrastructure.

**Comment by james-criscuolo** [comment]
Closing this since it appears we are resolved here, but feel free to re-open or open a new issue if the issue returns.

**Comment by m-vellinga** [comment]
:+1:
