### ISSUE TITLE
UA.stop() does not disconnect the transport

### ISSUE THREAD

**Issue by kmduk** [onsip/SIP.js#689]
With version 0.14.0 when stop() is called on a UA instance it doesn't disconnect the transport meaning that the websocket remains connected.

Version 0.13.8 does stop the transport but doesn't emit the disconnected event on the transport.

The previous version we were using 0.10.0 also disconnected the websocket and emitted a disconnected event on the UA object.

**Comment by john-e-riordan** [comment]
The transport not disconnecting on call to stop() is a bug. I'm gonna fix that.

**Comment by egreenmachine** [comment]
The disconnected event on the UA has been removed for a little while now. You can get a disconnected event by listening to `ua.transport.on('disconnected', () => {...});`.

**Comment by john-e-riordan** [comment]
Pushed fix in #691

**Comment by kmduk** [comment]
> The disconnected event on the UA has been removed for a little while now. You can get a disconnected event by listening to `ua.transport.on('disconnected', () => {...});`.

In 0.13.8 this event is not fired after stop() is called on the UA instance even though the transport does get stopped.

We've found that we need to keep track of the transport status because calling register() or sending 'OPTIONS' requests() on the UA instance when the transport is not connected causes an error.

**Comment by egreenmachine** [comment]
I see the issue. We are working on a refactor of the events to make them more consistent and reliable. This will get covered in that upcoming work.
