### ISSUE TITLE
Commit 20687bb680f2d00628bb6b9b92f7d9d7db9e2736 broke log level integers

### ISSUE THREAD

**Issue by kylekurz** [onsip/SIP.js#690]
The commit mentioned in the title seems to have gone all the way to now being the opposite of #660. Previously ( <= 0.13.8), we were using `level: 3`, but after updating to 0.14.0, I got an error from the UA constructor `Invalid "level" parameter value: 3`. If I change to the string "debug", it works fine.

**Comment by john-e-riordan** [comment]
Yes. Bug. Pushed fix in #691.
