### ISSUE TITLE
Can i make call with custom mediaStream object instead microphone?

### ISSUE THREAD

**Issue by iMegaMaximus2** [onsip/SIP.js#696]
Can i make call with custom mediaStream object instead microphone?

Like this
===
```javascript
var session = myUA.invite('bob@example.com', {
    mediaStream: customMediaStream // here we set custom output mediaStream
    sessionDescriptionHandlerOptions: {
        constraints: {
            audio: true,
            video: false
        }
    }
});
```

**Comment by james-criscuolo** [comment]
You cannot do this out of the box, but copying the default web session description handler and making your own custom one should make this obtainable.

Closing this as we prefer to keep this space for primarily bugs. Please use the [google group](https://groups.google.com/forum/#!forum/sip_js) for any follow up.
