### ISSUE TITLE
How to use jsonrpc when I register wss server? Use Freeswitch Verto

### ISSUE THREAD

**Issue by quyuan-fore** [onsip/SIP.js#698]
Now I the SIP.js in my project to build a softphone application, 
when I start to register Wss server , I find some difference between Freeswitch's demo ( picture above ) and SIP.js.
The above demo image use jsonrpc, I can't find the solution in api file ;
Can you give me some help? Thanks.
![issue1](https://user-images.githubusercontent.com/22470429/59423306-7a0a0080-8e04-11e9-96af-d4d64df91cde.png)
![issue-sipjs](https://user-images.githubusercontent.com/22470429/59423307-7b3b2d80-8e04-11e9-9244-ace1e0f0ce05.png)

**Comment by james-criscuolo** [comment]
I am not familiar with jsonrpc, so I can't say whether it works with SIP.js or not. In terms of our documentation, the configuration parameters for setting up a user agent are here: https://sipjs.com/api/0.14.0/ua_configuration_parameters/

And we also have a guide: https://sipjs.com/guides/user-agent-construction/

In the future, please use our google group for questions like these, we like to keep this space for primarily bug requests: https://groups.google.com/forum/#!forum/sip_js
