### ISSUE TITLE
Update missing dependency on tslib

### ISSUE THREAD

**Issue by kylekurz** [onsip/SIP.js#699]
Updated from 0.14.2 to 0.14.4 and had to manually add tslib as a dependency to our project. Since SIP.js relies on tslib, it should probably be included as part of the project.

**Comment by james-criscuolo** [comment]
There is no direct dependency on tslib, and it is also in the package-lock, so if it was needed, even as a dependency of a dependency, I think it would be covered. At most, I'd expect it to be a dev-dependency, as what we deliver to be used is javascript (either via bundle or lib folder).

Do you have some way to recreate the issue? What does/did the error look like? We did not have to add tslib to our application, but I could believe that a different set up could potentially lead to something.

**Comment by james-criscuolo** [comment]
I posted too soon, this is due to the addition of `importHelpers`... We'll get another release out, thanks for catching this.
