### ISSUE TITLE
Use one MediaHandler per Session

### ISSUE THREAD

**Issue by josephfrazier** [onsip/SIP.js#7]
Having a single handler per session (instead of a separate handler for each early dialog) provides at least two benefits:
1. Reusing the same media for multiple early dialogs would be easier to do automatically, without the application needing to know anything about it.
2. WebRTC.MediaHandler.getRemoteStreams could return the early media streams if available, and the on-call streams otherwise (again, without the application having to dig out the early dialog and its streams).

**Comment by olivermt** [comment]
We are currently playing with a new MediaHandler per getDescription/setDescription (to get fresh peerConnections for reINVITE scenarios and on-the-fly handling of adding/removing screens).

Will keep you posted on our progress if that is an approach that would be satisfactory for merging into upstream as well.

**Comment by egreenmachine** [comment]
This is fixed in [0.8.0](https://github.com/onsip/SIP.js/releases/tag/0.8.0).
