### ISSUE TITLE
not able to hear receiver voice , however receiver is able to listen dialler voice

### ISSUE THREAD

**Issue by piyushSinghalDemo** [onsip/SIP.js#702]
var socket = new JsSIP.WebSocketInterface(‘domain ip’);

           // Add the sip uri, socket and password and pass it to User Agent
           var configuration = {
               stun_server: “stun.l.google.com:19302”,
               sockets: [socket],
               uri: ‘uri’,
               password: number,
               authorization_user: number + “”,
               display_name: number + “”,
               hostport_params: “domain”,
               // no_answer_timeout: 60000,
               realm: “domain”,
               register: true,
               // register_expires: 600,
               use_preloaded_route: false,
               session_timers: false
           };

           using media 
         "https://www.soundjay.com/button/sounds/beep-01a.mp3"

**Comment by james-criscuolo** [comment]
That is not this project.
