### ISSUE TITLE
Fix on documentation for extracontactheaderparams

### ISSUE THREAD

**Issue by sboily** [onsip/SIP.js#703]
**Describe the bug**
The documentation for extracontactheaderparams is wrong. The good information is header=value instead of header: value.

https://sipjs.com/api/0.13.0/register/#extracontactheaderparams

**Comment by james-criscuolo** [comment]
Fixed, thanks for reporting. In the future, please put these issues here: https://github.com/onsip/sipjs.com

**Comment by sboily** [comment]
thank you! I will.
