### ISSUE TITLE
Parser.ts's parseHeader should allow multiple headers

### ISSUE THREAD

**Issue by dsandras** [onsip/SIP.js#704]
In Parser.ts, `parseHeader` parses well-known headers and falls back to         `message.setHeader(headerName, headerValue);`
when the header is unknown.

I am trying to get the various Diversion headers in the INVITE message we receive. I think `parseHeader` should use `addHeader` in order to be able to use `getHeaders` in user client software.

Uncommon headers might be present several times.

**Comment by james-criscuolo** [comment]
Good call @dsandras, this has been pushed up on master and will go out with the next release, which we anticipate within a week (waiting to land the two PRs).
