### ISSUE TITLE
P-Asserted-Identity support in Parser.js

### ISSUE THREAD

**Issue by lancedouglas1** [onsip/SIP.js#707]
As my first contribution, I'd like to provide support for Parsing the common P-Asserted-Identity header within lib/Parser.js

Header would be parsed with a startRule of Name_Addr_Header.

I'm using this currently in my custom SIP parsing application that relies on SIP.js.

Opening this issue to create a PR against, and plan to create a feature branch with this change.

**Comment by james-criscuolo** [comment]
Closing this in favor of just tracking the PR at #708
