### ISSUE TITLE
No audio when using peerConnectionOptions to set iceCheckingTimeout

### ISSUE THREAD

**Issue by kross-italk** [onsip/SIP.js#711]
**Describe the bug**
https://github.com/onsip/SIP.js/issues/484
https://github.com/onsip/SIP.js/issues/531
https://groups.google.com/forum/#!searchin/sip_js/iceCheckingTimeout|sort:date/sip_js/EuddDib0Q2A/aTG3Lt2rCgAJ

All indicate that setting peerConnectionOptions will overwrite them and cause audio to stop. Sure enough, this is the case.
Can I get a response on how you expect iceCheckingTimeout to be lowered? We can post logs but it seems pretty logical what's going on. If I set peerConnectionOptions the code will use them directly
https://github.com/onsip/SIP.js/blob/ed5a6ce738379eb9c79aa9c41b1b1cf716b893d4/src/Web/SessionDescriptionHandler.ts#L102
and is missing whatever defaults are supposed to be in there. 

Something isn't right after touching peerConnectionOptions since setting an ice timeout of 5000 or higher should be the same as default behavior. iceCheckingTimeout is the only parameter being tweaked. 

**Logs**
Please include a [gist](https://gist.github.com/) or attached file with full logs. If this is not included, the first response will likely be requesting them.

**To Reproduce (if possible)**
1. We are using invite, accept sessionDescriptionHandlerOptions to have per-session ice timeouts. 
2. Set a sessionDescriptionHandlerOptions.peerConnectionOptions.iceCheckingTimeout to 5000, the default
3. No audio 

**Expected behavior**
How do we change iceCheckingTimeout? 

**Observed behavior**
No audio over RTP 

**Environment Information**
Asterisk 16.3.0
Sipjs 0.11.6

**Additional context**

**Comment by egreenmachine** [comment]
The `iceCheckingTimeout` option is in a bad spot. It is not really where it belongs... We will work on getting this fixed which would clear up this issue. In the meantime... do you need to control the `iceCheckingTimeout` on a per call basis? Or can you set it on the UA, which would resolve your problem.

**Comment by kross-italk** [comment]
Awesome thanks. Yes, we are modifying it on invite, separate from the value in UA.

**Comment by john-e-riordan** [comment]
Hi,

#815 is a new implementation which I believe/hope addresses this issue.

The ICE gathering timeout may now be set on a per call basis (when sending an INVITE).

```
  /**
   * The maximum duration to wait in ms for ICE gathering to complete.
   * No timeout if undefined or zero.
   */
  iceGatheringTimeout?: number;
```

**Comment by james-criscuolo** [comment]
As there was no response and we believe this is fixed, we are going to close the issue. Please test with 0.17.0 and re-open if there is still an issue there.
