### ISSUE TITLE
How to catch MediaStreamError ?

### ISSUE THREAD

**Issue by lukaszkups** [onsip/SIP.js#716]
How to catch this error properly? 

![image](https://user-images.githubusercontent.com/17531363/61895792-c40df800-af13-11e9-8f91-ebb16230fb61.png)

I think I've tried already all `.on()` events I've found in the docs, but only `ended` is working when this error occurs (but I don't think this is a proper to use as a error handler) - any ideas/thoughts? 

EDIT:

adding some context: I'm testing it locally via `http` (I know that browsers now lock mic/cam access on it by default) but wanted to handle it as well - any ideas?

**Comment by egreenmachine** [comment]
This is a question not a bug. In the future please use our [mailing list](https://groups.google.com/forum/#!forum/sip_js) for these types of things.

The SDH emits a [`userMediaFailed` event](https://github.com/onsip/SIP.js/blob/master/src/Web/SessionDescriptionHandler.ts#L623). A better way might be to extend the Web SDH and override the [getMediaStream](https://github.com/onsip/SIP.js/blob/master/src/Web/SessionDescriptionHandler.ts#L402) function.
