### ISSUE TITLE
getting error in Firefox 68.0.1 as ICE failed, add a TURN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by naveenkumarvrp** [onsip/SIP.js#718]
am using sipjs 14.6 and firefox 68.0.1 broser, after receiving an incoming call if i put that call in hold after some time it sis showing 
ICE failed, add a TURN server and see about:webrtc for more details
[Uploading icefailedlogs.txt…]()

am creating ua object in following way
var configuration = {
    		uri : $("#domain").val(),
    		displayName : $("#userPart").val(),
    		authorizationUser : $("#userPart").val(),
    		password : $("#userPart").val(),
			transportOptions:{
				wsServers : $("#wsServers").val(),
				traceSip : true,
			},
			sessionDescriptionHandlerFactoryOptions:{
				constraints: { audio: true, video: true },
				iceCheckingTimeout: 5000,
			},
    		rtcpMuxPolicy: "negotiate",
    		hackWssInTransport : false,
    		contactTransport : $("#wsType").val()

    	};
    	var userAgent = new SIP.UA(configuration);

any one help me to solve this, i googled but am not getting any solution.

**Comment by naveenkumarvrp** [comment]
thsi is log am getting in web console : 

sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{"audio":true,"video":true},"iceCheckingTimeout":5000} 
sip.invitecontext.sessionDescriptionHandler | initPeerConnection
sip.invitecontext.sessionDescriptionHandler | New peer connection created

Incomming Call recieved 

sip.invitecontext.sessionDescriptionHandler | track added sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | acquiring local media sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | acquired local media streams sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | createAnswer sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | resetIceGatheringComplete sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | Setting local sdp. sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | sdp is v=0

o=mozilla...THIS_IS_SDPARTA-68.0.1 4505811826748971887 0 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 59:1F:6E:5C:26:77:80:8B:F8:77:54:77:2B:E6:1D:74:C0:D2:3E:CF:DE:DD:1D:7B:09:33:3B:87:9A:98:84:55
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 RTP/SAVPF 0 101
c=IN IP4 0.0.0.0
a=sendrecv
a=fmtp:101 0-15
a=ice-pwd:84b1194a8d89ce7044e70a21ca83add7
a=ice-ufrag:81ac096c
a=mid:0
a=msid:{5e815eb7-4461-4423-9278-ecda5e29ae52} {7539c173-a4cc-4ecf-862b-850a47783379}
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000/1
a=setup:active
a=ssrc:885486223 cname:{b04f19ba-b3ba-4c2a-8192-d7bbd22dde1c}


sip.invitecontext.sessionDescriptionHandler | waitForIceGatheringComplete sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE is not complete. Returning promise sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: gathering sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:0 1 UDP 2122252543 172.19.71.69 57079 typ host sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionChecking sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2 1 TCP 2105524479 172.19.71.69 9 typ host tcptype active sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:0 2 UDP 2122252542 172.19.71.69 57080 typ host sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2 2 TCP 2105524478 172.19.71.69 9 typ host tcptype active sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1 1 UDP 1686052863 124.153.81.170 57079 typ srflx raddr 172.19.71.69 rport 57079
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1 2 UDP 1686052862 124.153.81.170 57080 typ srflx raddr 172.19.71.69 rport 57080
sip.invitecontext.sessionDescriptionHandler | ICE candidate received: 
sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: complete
sip.invitecontext.sessionDescriptionHandler | ICE candidate gathering complete 
sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionConnected 
sip.invite-dialog | No ACK for 2xx response received, attempting retransmission 
sip.invite-dialog | INVITE dialog 4b8e8f395f1cf1ba43b7d03e296b76eb@172.19.71.109:5060ft04fha47oas206f93cd received ACK request
sip.invite-dialog | INVITE dialog 4b8e8f395f1cf1ba43b7d03e296b76eb@172.19.71.109:5060ft04fha47oas206f93cd received ACK request


Incomming Call holded
Fri Jul 26 2019 15:32:52 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | createOffer
Fri Jul 26 2019 15:32:52 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | resetIceGatheringComplete
Fri Jul 26 2019 15:32:52 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | Setting local sdp.
Fri Jul 26 2019 15:32:52 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | sdp is v=0

o=mozilla...THIS_IS_SDPARTA-68.0.1 4505811826748971887 1 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 59:1F:6E:5C:26:77:80:8B:F8:77:54:77:2B:E6:1D:74:C0:D2:3E:CF:DE:DD:1D:7B:09:33:3B:87:9A:98:84:55
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 57079 RTP/SAVPF 0 8 101 109 9
c=IN IP4 124.153.81.170
a=candidate:0 1 UDP 2122252543 172.19.71.69 57079 typ host
a=candidate:2 1 TCP 2105524479 172.19.71.69 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 172.19.71.69 57080 typ host
a=candidate:2 2 TCP 2105524478 172.19.71.69 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 124.153.81.170 57079 typ srflx raddr 172.19.71.69 rport 57079
a=candidate:1 2 UDP 1686052862 124.153.81.170 57080 typ srflx raddr 172.19.71.69 rport 57080
a=sendonly
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:101 0-15
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=ice-pwd:84b1194a8d89ce7044e70a21ca83add7
a=ice-ufrag:81ac096c
a=mid:0
a=msid:{5e815eb7-4461-4423-9278-ecda5e29ae52} {7539c173-a4cc-4ecf-862b-850a47783379}
a=rtcp:57080 IN IP4 124.153.81.170
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000/1
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=setup:actpass
a=ssrc:885486223 cname:{b04f19ba-b3ba-4c2a-8192-d7bbd22dde1c}


sip.invitecontext.sessionDescriptionHandler | waitForIceGatheringComplete
sip.invitecontext.sessionDescriptionHandler | ICE is already complete. Return resolved.
sip.invite-dialog | INVITE dialog 4b8e8f395f1cf1ba43b7d03e296b76eb@172.19.71.109:5060ft04fha47oas206f93cd sending INVITE request
sip.invitecontext.sessionDescriptionHandler | ICE candidate gathering complete
sip.invite-dialog | INVITE dialog 4b8e8f395f1cf1ba43b7d03e296b76eb@172.19.71.109:5060ft04fha47oas206f93cd sending ACK request
sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionDisconnected
sip.invitecontext.sessionDescriptionHandler | ICE Connection State changed to iceConnectionFailed

ICE failed, add a TURN server and see about:webrtc for more details

Incomming Call Unholded 
sip.invitecontext.sessionDescriptionHandler | createOffer sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | resetIceGatheringComplete sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | Setting local sdp. sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | sdp is v=0

o=mozilla...THIS_IS_SDPARTA-68.0.1 4505811826748971887 2 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 59:1F:6E:5C:26:77:80:8B:F8:77:54:77:2B:E6:1D:74:C0:D2:3E:CF:DE:DD:1D:7B:09:33:3B:87:9A:98:84:55
a=group:BUNDLE 1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 57079 RTP/SAVPF 0 8 101 109 9
c=IN IP4 124.153.81.170
a=candidate:0 1 UDP 2122252543 172.19.71.69 57079 typ host
a=candidate:2 1 TCP 2105524479 172.19.71.69 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 172.19.71.69 57080 typ host
a=candidate:2 2 TCP 2105524478 172.19.71.69 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 124.153.81.170 57079 typ srflx raddr 172.19.71.69 rport 57079
a=candidate:1 2 UDP 1686052862 124.153.81.170 57080 typ srflx raddr 172.19.71.69 rport 57080

a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:101 0-15
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=ice-pwd:84b1194a8d89ce7044e70a21ca83add7
a=ice-ufrag:81ac096c
a=mid:1
a=msid:{5e815eb7-4461-4423-9278-ecda5e29ae52} {7539c173-a4cc-4ecf-862b-850a47783379}
a=rtcp:57080 IN IP4 124.153.81.170
a=rtcp-mux
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000/1
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=setup:actpass
a=ssrc:885486223 cname:{b04f19ba-b3ba-4c2a-8192-d7bbd22dde1c}


sip.invitecontext.sessionDescriptionHandler | waitForIceGatheringComplete
sip.invitecontext.sessionDescriptionHandler | ICE is already complete. Return resolved. sip-0.14.6.js:9900:25
sip.invite-dialog | INVITE dialog 4b8e8f395f1cf1ba43b7d03e296b76eb@172.19.71.109:5060ft04fha47oas206f93cd sending INVITE request sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | ICE candidate gathering complete sip-0.14.6.js:9900:25
sip.invite-dialog | INVITE dialog 4b8e8f395f1cf1ba43b7d03e296b76eb@172.19.71.109:5060ft04fha47oas206f93cd sending ACK request sip-0.14.6.js:9900:25
sip.invitecontext.sessionDescriptionHandler | track added

**Comment by egreenmachine** [comment]
The endpoints cannot communicate directly. You will need to use an intermediary to relay the media. This is not a bug, please use our mailing list for questions like this.
