### ISSUE TITLE
set ice candidate timeout in Simple

### ISSUE THREAD

**Issue by jmordica** [onsip/SIP.js#719]
**Is your feature request related to a problem? Please describe.**
When using `Simple` in v0.14.xand below, the ice candidate gathering process takes to long (3-5 seconds) even when multiple candidates are received. This adds post dial delay to an outgoing call. 

**Describe the solution you'd like**
I don't believe you can set the timeout for ice candidates in `Simple` and i'd like to be able to do that when `Simple` is ported to the new version 0.16.x if possible.

I also may be mistaken and you can actually set a timeout in `Simple` but I haven't been able to get it to work.

**Comment by egreenmachine** [comment]
We are looking into making Simple more flexible. This will probably make it in there.
