### ISSUE TITLE
Inviter and UserAgent reference error

### ISSUE THREAD

**Issue by pavelsc** [onsip/SIP.js#722]
Hello,
migration doc says:

> The 0.15.x release contains both the new API and the legacy API, but the two are not compatible. That is, you may use one or the other but cannot "mix" the usage of the two. For example, a Session created with the legacy API is not compatible with a Session in the new API.

```
const userAgent = new SIP.UserAgent();
const session = new SIP.Inviter(userAgent);
```

But actually sip.js does not contain neither UserAgent nor Inviter classes. 

**Logs**
Uncaught TypeError: SIP.UserAgent is not a constructor

Latest sip-0.15.3.js still does not have new API

**Comment by ksitko** [comment]
sip-0.15.3.js does contain the new API, but you are not importing it correctly. The new API is located in [/api](https://github.com/onsip/SIP.js/tree/master/src/api). Try to import it like so: 
`import * as SIP from "sip.js/lib/api";` 
or 
`import { UserAgent, UserAgentOptions, Inviter, InviterOptions} from "sip.js/lib/api";`

**Comment by egreenmachine** [comment]
The new API is not available in our pre-compiled bundles at the moment. You will need to build SIP.js yourself to get them.

**Comment by pavelsc** [comment]
If I got it right I should use both sip-api.js and sip-core.js from dist directory after building a bundle, shouldn't I?

**Comment by egreenmachine** [comment]
You only need `sip-api.js` which includes the core

**Comment by pavelsc** [comment]
@egreenmachine thanks, it works

**Comment by pavelsc** [comment]
@egreenmachine thanks, it works
