### ISSUE TITLE
Transport does not emit 'close' event in some cases

### ISSUE THREAD

**Issue by adaxi** [onsip/SIP.js#727]
**Describe the bug**
The `Transport` does not emit the `closed` event, when waking up from sleep. It attempts to reconnect but fails. Our application expected a `closed` event, to be able to react to the incident, but it was not emitted.

**Logs**
You will be able to find logs in the console of the Developer tools, when running the [example](https://jsfiddle.net/wqfa7et4/2/).
My [logs](https://gist.github.com/adaxi/7ffb015f1cace0c7e1359dc4203fe0bf) in case you cannot reproduce the issue.

**To Reproduce**
Steps to reproduce the behavior: (tested on Windows 7 and Windows 10)
1. Open [jsfiddle](https://jsfiddle.net/wqfa7et4/2/) example.
2. Open the Developer tools.
3. Put the computer in sleep mode.
4. Wake computer from sleep.

**Expected behavior**
The `Transport` attempts to reconnect 3 times (as specified in the configuration).
The `Transport` emits a `closed` event.

**Observed behavior**
The `Transport` attempts to reconnect 3 times (as specified in the configuration).
No events are emitted indicating that the transport is closed.

**Environment Information**
 - Reproduced on Windows 7 and Windows 10.
 - Wired or wireless connection does not matter.  
 - Chrome 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
We can consistently reproduce this issue when going to sleep and waking up, but users have reported similar issues when switching from wired to wireless connection and vice-versa.

**Comment by egreenmachine** [comment]
Yeah. The events coming out of the web transport are definitely not consistent. It is on my list to go clean up.

**Comment by john-e-riordan** [comment]
In the new API version, this was fixed as part of the web transport rewrite in 0.15.8.
It is not fixed in the old API.
