### ISSUE TITLE
New API Session hold, unhold, and dtmf

### ISSUE THREAD

**Issue by pavelsc** [onsip/SIP.js#733]
New API since 0.15.x versions does not have `hold`, `unhold`, and `dtmf` methods in Session.
Are they being developed now and will be released in the nearest future?

**Comment by egreenmachine** [comment]
Please stop opening issues for questions. We have a [mailing list](https://groups.google.com/forum/#!forum/sip_js) for questions.

**Comment by egreenmachine** [comment]
`hold` and `unhold` are not a thing in SIP. It is an in dialog invite which we do support in the new API https://github.com/onsip/SIP.js/blob/master/src/api/session.ts#L462. We are working on improving our Simple layer which could have a `hold` and `unhold` function.

For DTMF you would have to send an INFO packet or if you are interested in doing in band DTMF you would need to implement this yourself in your own SDH. We expect to make this easier for users in our upcoming changes to the Simple.

**Comment by mbarinov** [comment]
@egreenmachine May I ask you for some help. I faced some troubles with the new API (0.15.6) too.  I could not find how to hang up, hold / unhold during an outgoing call. It looks like Inviter should handle this, but there are not such methods.
