### ISSUE TITLE
No sound safari

### ISSUE THREAD

**Issue by vlad574** [onsip/SIP.js#734]
Hi. I have no sound when calling from safari. here is the code. Please help!!!

  window.AudioContext = window.AudioContext || window.webkitAudioContext;
$(function () {
    if (document.getElementById('audio_cnt')) {
    var options = {
      media: {
        remote: {
          audio: document.getElementById('audio_cnt'),
          video: false,
        },
      },

      ua: {
        register: false,
        autostart: false,
        wsServers: "wss://myAstrisk:8089/ws",
        usePreloadedRoute: true,
        password: "***",
        displayName: "***",
        authorizationUser: "***",
        uri: "***",
        realm: "asterisk",
        traceSip: true,
        contact_uri: "sip:***",
        stunServers: ["stun:stun.l.google.com:19302", "stun:stunserver.org:3478"],
        iceCheckingTimeout: 30,
        sessionDescriptionHandlerFactory: function (session, options) {
          return new SessionDescriptionHandler(session, options);
        },
        alwaysAcquireMediaFirst: true,
        hackWssInTransport: true,
        allowLegacyNotifications: true,

      }
    };
    var simple = new SIP.Web.Simple(options);

    $('.call').click(function () {
      $('.call_cnt button').addClass('cbutton--click');
      $.get("make/?key=" + call_key, function (data) {
      }).then(function (response) {
        if (typeof response.about != 'undefined') {
         // show hide btns
         }
      });
    });
    simple.on('ringing', function (request) {
      console.log('ringing');
      simple.answer();
    });
  }
});

**Comment by egreenmachine** [comment]
Configuration Issue. https://sipjs.com/api/0.14.0/simple_configuration_parameters/

Next time use the [Google Group](https://groups.google.com/forum/#!forum/sip_js)

**Comment by vlad574** [comment]
Best help!!!

пт, 16 авг. 2019 г., 18:12 Eric Green <notifications@github.com>:
