### ISSUE TITLE
Safari/FireFox terminates session after network disconnect reconnect SIPJS  11

### ISSUE THREAD

**Issue by bezbahadori** [onsip/SIP.js#735]
When the network connection is lost and then reconnects and the user is using Safari or Firefox, Sip js terminates the Session and sends a SIP Bye , we set  log to debug to get more information however it didn't write anything extra. This doesn't happen on Chrome, the connection wont drop and the audio still continues to go after we reconnect .  when in safari or firefox reconnects we have audio for few little seconds and then terminates

`Wed Aug 21 2019 18:16:24 GMT-0700 (PDT) | sip.inviteclientcontext | terminating Session`
`[Log] Wed Aug 21 2019 18:16:24 GMT-0700 (PDT) | sip.transport | sending WebSocket message:

BYE sip:user1@domain.com;transport=udp SIP/2.0
Via: SIP/2.0/WSS 01fkj3kmptk5.invalid;branch=z9hG4bK8611807
Max-Forwards: 70
To: <sip:user1@domain.com>;tag=2DU0F2tatBZ2S
From: <sip:user2@domain.com>;tag=a7cqd5q17f
Call-ID: 9v8fhsnobkojvllt0cd2
CSeq: 2625 BYE
Supported: outbound
User-Agent: SIP.js/0.11.6
Content-Length: 0
`

**Comment by james-criscuolo** [comment]
Closing this in favor of the google group post: https://groups.google.com/forum/#!topic/sip_js/mkL0eVqlge0
