### ISSUE TITLE
PUBLISH

### ISSUE THREAD

**Issue by ravindra30** [onsip/SIP.js#736]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).

I have following code to publish.
var pidf = this.createPidfXml();
		var extrahdr = [ 
			'Event: presence', 
			'Content-Type: application/pidf+xml'
		];
		var pubReq = this.ua.request('PUBLISH', 'xxxx@xxxx', { 			 
			extraHeaders: extrahdr,
			body: pidf
		});
		pubReq.request.setHeader('Expires', '10'); 
		pubReq.on('accepted', function (response, cause) { 
			console.log('accepted Res -> ', response);
			console.log('accepted cause -> ', cause);
			if(fnAccepted){
				fnAccepted(response, cause);
			}
		}); 
		pubReq.on('rejected', function (response, cause) { 
			console.log('rejected Res -> ', response);
			console.log('rejected cause -> ', cause);
			if(fnAccepted){
				fnRejected(response, cause);
			} 
		}); 
		pubReq.send();

following is PIDF generated by createPidfXml()

`<?xml version="1.0" encoding="UTF-8"?>
<presence xmlns="urn:ietf:params:xml:ns:pidf"entity="sip:XXXXXXXXX@XXXXXX">
	<tuple id="32">
		<status>
			<basic>open</basic>
		<status>
		<note>
			Available
		</note>
	</tuple>
</presence>`

Sending following as request to freeSwitch 

PUBLISH sip:XXXX@XXXXX SIP/2.0
Via: SIP/2.0/WSS xxx.xxx.xxx.xxx;branch=z9hG4bK3399700
Max-Forwards: 70
To: <sip:XXXX@XXXX>
From: "XXXXX XXXXX" <sip:XXXX@XXXXX>;tag=iilifd36kb
Call-ID: 406819cgm8b3rcvqul25
CSeq: 3073 PUBLISH
Expires: 10
Event: presence
Content-Type: application/pidf+xml
Supported: outbound
User-Agent: SIP.js/0.7.0 BB
Content-Length: 0

**_I found Content-Length as 0_**

I am getting following response from FreeSwitch

SIP/2.0 200 OK
Via: SIP/2.0/WSS ip;branch=z9hG4bK8782019;received=xxx.xxx.xxx.xxx;rport=<port>
From: "xxxx xxxxx" <sip:xxxx.xxxx@xxxx>;tag=b85dnvgsb3
To: <sip:xxxx.xxxx@xxxx>;tag=HSmyyZc1rve0g
Call-ID: 40681bvu5qedu7lirtdc
CSeq: 1687 PUBLISH
Contact: <sip:ip:port>
Expires: 3600
User-Agent: FreeSWITCH-mod_sofia/1.8.1+git~20180724T160524Z~b33bc925c5~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
SIP-ETag: 9BhaaxGJ
Content-Length: 0

After all happened I am not able to publish presence status.  **_I found Content-Length as 0_** and pidf message is not found.
Can anyone guide me what I am missing?

**Comment by egreenmachine** [comment]
These are typically directed to the google group.
