### ISSUE TITLE
Create a conference

### ISSUE THREAD

**Issue by cremfert** [onsip/SIP.js#74]
Dear all,

first of all, thanks for SIP.js - I switched from another library and yours is some much more comfortable :+1: 

I have two questions right now:
- How can I create a conference, meaning have a call with more than two participants
- Can user credentials used by more than one person at a time? For example, I want to store one generic user on a webpage, so that everybody who has this webpage open gets called and the first who answers should receive the call. Is that possible?

Thanks and best regards,
Chris

**Comment by misjaz** [comment]
Does anyone have an example of implementation for conference call without conference server ?

**Comment by seanbright** [comment]
@misjaz https://groups.google.com/forum/#!forum/sip_js

**Comment by misjaz** [comment]
@josephfrazier  do you by any chance still have guide for conference call implementation without conference server? link form your comment is no longer available

**Comment by seanbright** [comment]
@misjaz https://groups.google.com/forum/#!forum/sip_js

**Comment by josephfrazier** [comment]
sorry @misjaz, I don't work on SIP.js anymore, and I can't help you :/
