### ISSUE TITLE
How to send (screen sharing stream) with SIPJS 14 ?

### ISSUE THREAD

**Issue by okaily** [onsip/SIP.js#743]
hello
i wrote post on google forums , but no answer yet , so im hoping that i can find one here pls 
and here is the link to google question
[My question on google forums](https://groups.google.com/forum/#!topic/sip_js/Mu40ctgJqdY)

I'm using **SIPJS** to make calls between 2 callers using web browser.

Now i want to add (**Screen sharing**) feature , so far i managed to open chrome screen sharing window and i get the stream and played it in video element.

But what i really need is to **send this stream to the other caller so he can see my screen sharing.**

What I've tried so far:

- After i get the (screen sharing stream) i pass it to **``session.sessionDescriptionHandler.peerConnection``** , and then catch the stream (or track) using these events **``onTrackAdded , onaddTrack , onaddStream , onstream``**<br/>
But none of there events get anything.
- Also tried to send the stream with **`video constraint`** before the call start<br/> 
```
video: {
mandatory: {
chromeMediaSource: 'desktop',
// chromeMediaSourceId: event.data.sourceId,
maxWidth: window.screen.width > 1920 ? window.screen.width : 1920,
maxHeight: window.screen.height > 1080 ? window.screen.height : 1080
},
optional: []
}
```
- Even tried to send the stream with `video constraint`
```
navigator.mediaDevices.getDisplayMedia(constraints)
    .then(function(stream) {
      //We've got media stream
      console.log("----------then triggered-------------");
      var options = {
            sessionDescriptionHandlerOptions: {
              constraints: {
                  audio: true,
                  video: stream
              }
            }
          } 
        pub_session = userAgent.invite(reciver_name,options);
    })
    .catch(function(error) {
      console.log("----------catch-------------");
      console.log(error);
    });
```
also didn't work.

Here is my Code

First get the screen sharing stream and send it to the other user

 

    // Get screen sharing and send it.
     navigator.mediaDevices.getDisplayMedia(constraints)
        .then(function(stream) {
          //We've got media stream
          console.log("----------then triggered-------------");
          var pc = session.sessionDescriptionHandler.peerConnection;
          stream.getTracks().forEach(function(track) {
            pc.addTrack(track, stream);
          });      
        })
        .catch(function(error) {
          console.log("----------catch-------------");
          console.log(error);
        });

Then catch that stream at the other side

    // Reciving stream or track
    userAgent.on('invite', function (session) {
        session.on('trackAdded', function() {
            console.log('-------------trackAdded triggered--------------');
          });
    
          session.on('addTrack', function (track) {
            console.log('-------------addTrack triggered--------------');
          });
    
          session.on('addStream', function (stream) {
            console.log('-------------addStream triggered--------------');
          });
    
          session.on('stream', function (stream) {
            console.log('-------------stream triggered--------------');
          });
    });

But still get nothing from that code above

So how can i pass that **stream** or **track** to the other caller after the call starts ?

thank you so much

**Comment by james-criscuolo** [comment]
Instead of hacking into the session description handler, I recommend making your own custom session description handler. That should make it very straightforward to see what is going on. You can likely just copy/paste the default one, then make a few changes to at least test that it would work.
