### ISSUE TITLE
iOS 11 -- WebRTC Support

### ISSUE THREAD

**Issue by lylepratt** [onsip/SIP.js#746]
iOS 11 supports WebRTC now:
https://bloggeek.me/webrtc-ios-support/

Vendors like TokBox are supporting it:
https://tokbox.com/blog/why-were-excited-about-webrtc-support-in-ios-11-and-safari/

Any plans or known roadblocks for SIP.js?

**Comment by james-criscuolo** [comment]
SIP.js has worked in iOS safari for a while now, and given that iOS 11 is 2 years old, the timelines probably line up. I don't believe Chrome or Firefox will work, but Safari will.
