### ISSUE TITLE
Inconsistent casing within InviterOptions

### ISSUE THREAD

**Issue by bradwarwick** [onsip/SIP.js#747]
**Describe the bug**
All properties within InviterOptions are camel case except _SessionDescriptionHandlerModifiers_  (first letter should be lower case)

**Additional context**
This took me a while to spot as I had incorrectly assumed the option to pass would be _sessionDescriptionHandlerModifiers_. Is there any reason it has different casing or could this potentially be changed?

_sessionDescriptionHandlerModifiers_ is correctly used within _InviterInviteOptions_

**Comment by egreenmachine** [comment]
Looks like a typo. We will get it fixed. Thanks
