### ISSUE TITLE
Unable to setSinkId

### ISSUE THREAD

**Issue by jpb55116** [onsip/SIP.js#748]
It appears that sip is ignoring my setSinkID, after passing it the ID of my (non-default) speaker. Does SIP honor setSinkID? Are users able to toggle which output they'd like to utilize?

**Comment by james-criscuolo** [comment]
SIP.js does not get in the middle of media, so it's not likely that SIP.js is the issue here. Assuming this is the same as your google group post, it would appear this is an issue with an audio tag more than anything else.

**Comment by Fiser12** [comment]
Maybe it's related to this old-reported issue. It's been on hold for years.

https://bugs.chromium.org/p/chromium/issues/detail?id=697877

Remember that for getting visibility on chromium, you should “Start" it with your Google account to help to the Chromium team to understand its importance.
