### ISSUE TITLE
How can I set the ring tone when SIP JS can't receive the freeswitch? I tried many methods, but they couldn't do it

### ISSUE THREAD

**Issue by yuexiajiayan** [onsip/SIP.js#753]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).
 rel100:SIP.C.supported.SUPPORTED have No effect

**Comment by james-criscuolo** [comment]
As you mention, this belongs on the google group. Logs would help when you post there (in a gist).
