### ISSUE TITLE
Early media causes problem if 200 comes fast

### ISSUE THREAD

**Issue by AlekseyKost** [onsip/SIP.js#771]
In our project we have two types of phone numbers:
- the number using early media on 183 "progress" with custom tone music
- the number with answering machine, where 200 answer comes immediately after a 183 and where we are getting an error, causes by "Bad media description"

In our service we have a handler which allows early media to work: 

```
sipSession.on('progress', (response) => {
	if (response.statusCode === 183) {
	    sipSession.sessionDescriptionHandler.setDescription(response.body).catch((exception) => {
	        sipSession.logger.warn(exception);
	        sipSession.failed(response, 'Bad Media Description');
	        sipSession.terminate({
	            statusCode: 488,
	            reason_phrase: 'Bad Media Description'
	        });
	    });
```

The problem is during an outgoing session, when a 200 answer comes immediately after a 183, we are getting error with fields in "failed" response:
statusCode: 200
reasonPhrase: "OK"

So the implemented workaround for this case is a timeout with the delay just to call setDescription() in our service exactly after setDescription() in SIP.js was called in InviteClientContext.prototype.onAccept handler: 
 
```
sipSession.on('progress', (response) => {
    if (response.statusCode === 183) {
	    this.waitingForApplyingAnswer(sipSession, response);
    }	
...
});	

private waitingForApplyingAnswer(session, response) {
    let i = 1,
        clearTimer;
    setTimeout(function check() {
        i++;
        clearTimer = setTimeout(check, 10);
        if ( session.hasAnswer || i > 14) {
            if ( session.hasAnswer ) {
                clearTimeout(clearTimer);
            } else if ( i === 15 ) {
            	clearTimeout(clearTimer);
                session.sessionDescriptionHandler.setDescription(response.body).catch((exception) => {
                    session.logger.warn(exception);
                    session.failed(response, 'Bad Media Description');
                    session.terminate({
                        statusCode: 488,
                        reason_phrase: 'Bad Media Description'
                    });
                });
            }
        }
    }, 10);
}
```

Is it appropriate approach to solve this issue from SIP.JS perspective? Could it cause some problems?
Could you propose some better solution?

**Comment by egreenmachine** [comment]
Why are you calling into the SDH from outside of SIP.js? SIP.js will handle the early media for you.

**Comment by AlekseyKost** [comment]
Early media doesn't work without setDescription for SDH. It works exactly when we call it in our service.

**Comment by egreenmachine** [comment]
Early media definitely works within SIP.js. We can support the built in early media handling - but trying to hack early media support outside of SIP.js is something we cannot support. If you get your code working with the built in early media handling and are still hitting this race please re-open this issue.
