### ISSUE TITLE
Make protocol an configurable parameter in creating new websocket.

### ISSUE THREAD

**Issue by jadedevin13** [onsip/SIP.js#772]
https://github.com/onsip/SIP.js/blob/167539923c03723cd9562641e7af2e24dff80afc/src/Web/Transport.ts#L201

It would be awesome, If we could make this configurable.

**Comment by egreenmachine** [comment]
The entire transport can be passed in via [UserAgent configuration](https://github.com/onsip/SIP.js/blob/master/src/api/user-agent-options.ts#L232). You can make your own transport and configure it how you would like.
