### ISSUE TITLE
Simple Interface: Configure STUN/TURN 

### ISSUE THREAD

**Issue by wonder75** [onsip/SIP.js#783]
The Simple interface is very nice to use and sufficient for an app I am developing.
The only thing missing for me is the ability to configure STUN and TURN servers.

As these configuration options seem to be pretty essential, even for a simple SIP client, because
the absence of them can break connectivity, I'd like to suggest adding those options to the Simple Configuration Parameters.

Tnx for sip.js.

**Comment by james-criscuolo** [comment]
The Simple Interface is deprecated for the SimpleUser interface and will be gone in 0.16.0.
