### ISSUE TITLE
Constraints for getUserMedia in the Simple interface

### ISSUE THREAD

**Issue by jakub-zawislak** [onsip/SIP.js#786]
**Is your feature request related to a problem? Please describe.**
I want to set the `facingMode` in `MediaDevices.getUserMedia()` constraints

**Describe the solution you'd like**
The `constraints` options for the `call` and `answer` methods like in the `sessionDescriptionHandlerOptions` of normal API

**Temporary solution**
I have managed to get it work by using this hack:
```js
let simple = new SIP.Web.Simple({ /**/ });
simple.video = { facingMode: 'environment' }
simple.call(number)
```

**Comment by egreenmachine** [comment]
Simple is now part of the legacy API. Please [upgrade to `SimpleUser`](https://github.com/onsip/SIP.js/blob/master/docs/migration-simple.md) which allows you to do what you are asking.
