### ISSUE TITLE
No outbound audio on hold/unhold Chromium 80

### ISSUE THREAD

**Issue by grxnola** [onsip/SIP.js#789]
**Describe the bug**
After a hold and unhold (set sdp a=sendonly, set sdp a=sendrecv) there is no more outbound audio. I have tested this on Chromium but cannot test on firefox due to an unrelated websockets bug. The code I'm currently using to hold is from (I believe) the Simple user though I do it through the API
```
reducers[consts.HOLD] = (state, { target }) => {
  const { session } = state.ongoingCalls.get(target);

  const holdModifier = description => {
    if (!description.sdp)
      return Promise.resolve(description);

    if (!(/a=(sendrecv|sendonly|recvonly|inactive)/).test(description.sdp)) {
      description.sdp = description.sdp.replace(/(m=[^\r]*\r\n)/g, "$1a=sendonly\r\n");
    } else {
      description.sdp = description.sdp.replace(/a=sendrecv\r\n/g, "a=sendonly\r\n");
      description.sdp = description.sdp.replace(/a=recvonly\r\n/g, "a=inactive\r\n");
    }

    return Promise.resolve(description);
  }

  session.invite({
    requestDelegate: {
      onReject: response => {
        console.log(`DEV:: response:`, response);
        reducers[consts.BYE](state, response);
      }
    },
    sessionDescriptionHandlerModifiers: [holdModifier],
  });

  return state;
}
```
Unhold simply sends a regular reinvite, constraints in the SDH factory are `{ audio: true, video: false }`. I believe the issue is related to #728. The workaround in #728 will no longer work as one cannot trigger trackAdded() on the observer (it's private) or session emit userMedia.

**Comment by john-e-riordan** [comment]
Hi,

#815 is a new implementation which I believe/hope addresses this issue.

**Comment by james-criscuolo** [comment]
As there was no response and we believe this is fixed, we are going to close the issue. Please test with 0.17.0 and re-open if there is still an issue there.
