### ISSUE TITLE
RFC 3892 Support

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#79]
https://tools.ietf.org/html/rfc3892

I believe basic support for this can be achieved application-side, but @funkycode suggested that including default behavior may be nice.  From an API perspective, I could see this as an option passed to the `refer()` method, as well as an optional argument to `followRefer()` for the referee to opt in or out when copying the headers over.

See the original pull request for some commentary and code:

https://github.com/onsip/SIP.js/pull/77

**Comment by egreenmachine** [comment]
Can you try out #459? I think that I have addressed this issue there. 

* Due to the age of this issue, if we do not hear any feedback on this we will close it once we merge the pull request.
