### ISSUE TITLE
Contact undefined

### ISSUE THREAD

**Issue by philjones88** [onsip/SIP.js#793]
**Describe the bug**
Trying to alter the demo to talk to my Drachtio server which then proxies to a Cisco Meeting Server (a MCU that accepts SIP)

I get a `Contact undefined` error point to this file:

https://github.com/onsip/SIP.js/blob/master/src/core/dialogs/dialog.ts#L55

**Logs**

https://gist.github.com/philjones88/a8a865570de8f9f89679ace46261da02

192.168.4.31 = drachtio server
192.168.1.237 (philcms.vqlive.com) = cisco meeting server

The drachtio server is listening on 5060 + 5061 (tls) and for WS 5080 + 5081 (tls)

**To Reproduce (if possible)**

Pretty hard as you need a drachtio + cisco meeting server

**Expected behavior**

It to show remote video

**Observed behavior**

shows local video then errors with `Contact undefined`

**Environment Information**
 - Drachtio
 - Cisco Meeting Server
 - Firefox

**Additional context**

**Comment by David-Melo** [comment]
Getting this also when making an audi only call

**Comment by john-e-riordan** [comment]
Throwing an error is arguably a bug in response handling (as per the TODO in the code). So I addressed that and now we will simply log an error when the Contact is missing on a dialog forming response.

The 180 response with a to-tag from the Acano CallBridge MUST have a Contact header as it is a dialog forming response. And the response does not. That said, I'm not sure it is going to matter practically in your cases as the server seems to be answer the call immediately after the 180.

Anyway, from the RFC...

https://tools.ietf.org/html/rfc3261#section-12.1

12.1 Creation of a Dialog

   Dialogs are created through the generation of non-failure responses
   to requests with specific methods.  Within this specification, only
   2xx and 101-199 responses with a To tag, where the request was
   INVITE, will establish a dialog.

... and ...

https://tools.ietf.org/html/rfc3261#section-12.1.1

12.1.1 UAS behavior

   When a UAS responds to a request with a response that establishes a
   dialog (such as a 2xx to INVITE), the UAS MUST copy all Record-Route
   header field values from the request into the response (including the
   URIs, URI parameters, and any Record-Route header field parameters,
   whether they are known or unknown to the UAS) and MUST maintain the
   order of those values.  The UAS MUST add a Contact header field to
   the response.
