### ISSUE TITLE
SimpleUser DTMF event

### ISSUE THREAD

**Issue by jakub-zawislak** [onsip/SIP.js#794]
**Is your feature request related to a problem? Please describe.**
I want to receive DTMF using the `SimpleUser` API

**Describe the solution you'd like**
`onDtmf` in `SimpleUserDelegate`

**Describe alternatives you've considered**
Exposing a session attribute to public in `SimpleUser` would also resolve my issue

**Additional context**
The DTMF event was available in old `Simple` API

**Comment by john-e-riordan** [comment]
Added `onCallDTMFReceived` to `SimpleUserDelegate`.

**Comment by james-criscuolo** [comment]
This has been merged, please let us know if it works on `0.15.11`.
