### ISSUE TITLE
SimpleUser is not exported in the SIP.Web object

### ISSUE THREAD

**Issue by jakub-zawislak** [onsip/SIP.js#795]
**Describe the bug**
In the [SimpleUser migration guide](https://github.com/onsip/SIP.js/blob/master/docs/migration-simple.md) we can see `SIP.Web.SimpleUser(...)` but in the `SIP.Web` there is no `SimpleUser` attribute available.

**Environment Information**
- SIP.js 0.15.10

**Additional context**
I have resolved this by adding
```js
export { SimpleUser } from "../platform/web/simple-user/simple-user";
```
in the `src/Web/index.ts`

**Comment by john-e-riordan** [comment]
Fixed. Well, sidestepped really. Regardless, the guide is no longer wrong. Thanks.

**Comment by james-criscuolo** [comment]
This has been merged, closing. Thanks again!
