### ISSUE TITLE
getDisplayMedia no longer exists

### ISSUE THREAD

**Issue by crobibero** [onsip/SIP.js#796]
**Describe the bug**
The function `navigator.mediaDevices.getDisplayMedia()` no longer exists in latest master, existed in 0.15.10
Used for sharing screens.

Is there a new method of sharing screens in 0.16.0?

**Comment by james-criscuolo** [comment]
That function does not appear in our code, and it also still exists as of Chrome 81. It's a browser function, so you are likely calling it somewhere in your own code.
