### ISSUE TITLE
do not add Contact transport parameter always

### ISSUE THREAD

**Issue by qermit** [onsip/SIP.js#807]
**SIP.js always generates contact with transport parameter**
transport uri parameter is optional and not required for correct SIP communication.

in version **0.7.8** there was an option `contactTransport` that allowed to put any string into a transport parameter

At this moment the only way to change it from `ws` to `wss` is to set `hackWssInTransport=true`
There should be something more flexible, for instance:
- `contactTransport` = `false/undefined` -> SIP.js does not put transport parameter at all
- `contactTransport` = true -> automatic detection based on `viaHost` URI scheme
- `contactTransport` = "string" -> put transport=string

**Comment by john-e-riordan** [comment]
Related to #791

**Comment by egreenmachine** [comment]
Fixed in 61ce62802cd760569659d96fdca4f602ec4c6362
