### ISSUE TITLE
does Sip.js also support react-native ?

### ISSUE THREAD

**Issue by ragevua** [onsip/SIP.js#808]
willing to know **Sip.js** supports **react-native** or not ?

As i can see on the documentation this is not specified anywhere sip.js supports react-native or not,but i found following file link on the source code which is posted around 6 months ago so willing to know is **Sip.js** really support react-native or there is any way you can suggest if we have to implement on react-native.

https://github.com/onsip/SIP.js/blob/master/src/platform/react/react-native-webrtc.d.ts

**Comment by james-criscuolo** [comment]
Please use our [google group](https://groups.google.com/forum/#!forum/sip_js) for questions, we reserve this space primarily for bugs.
