### ISSUE TITLE
doubts about viaHost

### ISSUE THREAD

**Issue by ifzm** [onsip/SIP.js#814]
Hello ~
Doubts about `viaHost`, why not allow custom settings to be my own host (

**Expect：**
```log
| sip.ua | configuration parameters after validation:
| sip.ua | · viaHost: "fs.sipjs.com"
| sip.ua | · uri: sip:1000@fs.sipjs.com
```

**Actual：**
```log
| sip.ua | configuration parameters after validation:
| sip.ua | · viaHost: "ssd3g2ns4bm9.invalid"
| sip.ua | · uri: sip:1000@fs.sipjs.com
```

`hackIpInContact` makes `viaHost` a random local ip, which may be useful, but not what I want ...

hope to get help :)

**Comment by ifzm** [comment]
In the new version, a new parameter `viaHost` is added, allowing us to set it, but the `contactName` parameter is disabled again, and we need to pass a strange hack #791 

whether to consider a contactOptions )

**Comment by john-e-riordan** [comment]
Fixed in https://github.com/onsip/SIP.js/commit/9a9413702015437b1e0abe6226afc1c1b6bb69ea
