### ISSUE TITLE
Documentation for receiving a video stream on a node.js server instead of a browser.

### ISSUE THREAD

**Issue by ajhool** [onsip/SIP.js#817]
**Is your feature request related to a problem? Please describe.**
We would like to record a webrtc conversation, server-side, but have no easy way to ingest a webRTC call in a headless server. T

**Describe the solution you'd like**
We need to create a headless peer to ingest and process the audio + video. It is unclear whether SIP.js is capable of receiving a voice / video call without a browser. If so, this would be a great feature to document!

**Describe alternatives you've considered**
Similar open-source webrtc implementations like Jitsi. Headless chrome.

**Additional context**

**Comment by egreenmachine** [comment]
Hi. This is possible with SIP.js, but you will need to write your own Session Description Handler to deal with the audio/video in whatever environment you choose. The SDH is fully overridable at run time. If you do write it, we would consider taking it as PR to the library.

**Comment by ajhool** [comment]
Okay, great to know. Pretend that I'm somewhat competent, would you
estimate this to be a day, week, or month+ type project?

**Comment by egreenmachine** [comment]
Probably in the week range. For compatibility with SIP.js you need to implement the [SDH interface](https://github.com/onsip/SIP.js/blob/master/src/api/session-description-handler.ts). It is all about how comfortable you are with the underlying media platform.

**Comment by ajhool** [comment]
@egreenmachine thank you very much
