### ISSUE TITLE
Recommended version for production ready application

### ISSUE THREAD

**Issue by carloscarvallo** [onsip/SIP.js#822]
Between the version 0.15.x and 0.16.x I see substantials changes, what is the recommended version for a production ready application? This API would be stable for the next versions?

Thank you in advance.

**Comment by james-criscuolo** [comment]
Every version is production ready. You can read about the shift in the API here: https://github.com/onsip/SIP.js/blob/0.16.0/docs/migration-0.15-0.16.md

The shift to 0.16.0 was likely the biggest we've undergone and plan to undergo, but we still have planned API changes ahead. You can read about them here: https://github.com/onsip/SIP.js/blob/master/docs/TODO.md
