### ISSUE TITLE
EventEmitter not found

### ISSUE THREAD

**Issue by hrantbagdasarian** [onsip/SIP.js#824]
**Describe the bug**
I've been trying to get SIP.js 0.16.1 (also tried 0.16.0) integrated with LitElement (https://open-wc.org), but to no success.
It leads to the following error, on both Safari and Chrome:

Safari Version 13.1.1 (15609.2.9.1.2): SyntaxError: Importing binding name 'EventEmitter' is not found.
Chrome Version 83.0.4103.106 (Official Build) (64-bit): Uncaught SyntaxError: The requested module '../../../../events/events.js' does not provide an export named 'EventEmitter'

**To Reproduce**
1. npm init @open-wc 
2. Scaffold a new project
3. Web Component
4. Typescript
5. Give it a name
6. Write to disk and install node modules
7. Import sip.js in the file that was created in the src directory
8. Anywhere in the file create a new UserAgent object
9. npm run start
10. A browser will open and open the console to view the error

**Expected behavior**
I'd expect SIP.js to be loaded correctly.

**Observed behavior**
Error thrown for the EventEmitter.

**Environment Information**
Mac OS 10.15.5

**Additional context**
Not sure if this helps, but here is the tsconfig.json. 
tsconfig.json
`
 {
  "compilerOptions": {
    "target": "es2018",
    "module": "esnext",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "lib": ["es2017", "dom"],
    "strict": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "outDir": "dist",
    "sourceMap": true,
    "inlineSources": true,
    "rootDir": "./"
  },
  "include": ["**/*.ts"]
}
`

**Comment by john-e-riordan** [comment]
Addressed in #815.

The dependency on events.js has been removed.

**Comment by hrantbagdasarian** [comment]
@john-e-riordan, thanks for confirming it's already fixed in a future release. Any ETA on the next version?

**Comment by hrantbagdasarian** [comment]
I've built the source from your pull request, and tested it with my web component. I can confirm the error no longer exists.

**Comment by james-criscuolo** [comment]
Closing as 0.17.0 is now released.
