### ISSUE TITLE
add support for early media

### ISSUE THREAD

**Issue by zhouJiecode** [onsip/SIP.js#826]
**Is your feature request related to a problem? Please describe.**
when i call others, i can't hear early media, so i don't know the status of the other side
it feels not good

**Describe the solution you'd like**
get a way to play early media

**Comment by james-criscuolo** [comment]
https://github.com/onsip/SIP.js/blob/52ea867c5437aacb1b02966a31969c4a354e7487/docs/api/sip.js.inviteroptions.earlymedia.md

**Comment by Mrhan5199** [comment]
how to solve this problem
