### ISSUE TITLE
failed to execute 'removeTrack' on  'RTCPEERCONNECTION'

### ISSUE THREAD

**Issue by zhouJiecode** [onsip/SIP.js#827]
**Describe the bug**
when someone call in, i call answer method, then the call is ened with a error

**Logs**
failed to execute 'removeTrack' on  'RTCPEERCONNECTION'
[https://raw.githubusercontent.com/zhouJiecode/notes/master/324.png](https://raw.githubusercontent.com/zhouJiecode/notes/master/324.png)

**To Reproduce (if possible)**
1， someone call in
2， call answer method
it's occasionally appear

**Observed behavior**
the call is ened with a error
[https://raw.githubusercontent.com/zhouJiecode/notes/master/324.png](https://raw.githubusercontent.com/zhouJiecode/notes/master/324.png)

**Environment Information**
 - Backend Server
    - freeswitch
 - SIPJS 0.11.6 chrome 83+

**Additional context**

**Comment by egreenmachine** [comment]
Please use the latest version of SIP.js
