### ISSUE TITLE
TypeError: this.transactionConstructor is not a constructor

### ISSUE THREAD

**Issue by m-heinemann** [onsip/SIP.js#830]
**Bug**
I am trying to migrate to version 0.16.1 since we were having various issues in the older versions.  
When I call the `Inviter.invite()` method, I get the following error in the console:
`TypeError: this.transactionConstructor is not a constructor
    at InviteUserAgentClient.init (VM244 app.bundle.js:553)
    at new UserAgentClient (VM244 app.bundle.js:276)
    at new InviteUserAgentClient (VM244 app.bundle.js:18691)
    at UserAgentCore.invite (VM244 app.bundle.js:17934)
    at Inviter.sendInvite (VM244 app.bundle.js:5615)
    at VM244 app.bundle.js:5418`

**Logs**
https://gist.github.com/m-heinemann/f1ea5ba5150c6c7a8f82955458ad1d94

**Expected behavior**
The Inviter.Invite() function should initiate a new session.

**Observed behavior**
The above error message was printed in the console and no session was created.

**Environment Information**
 - node v10.13.0
 - Google Chrome v83

**Comment by m-heinemann** [comment]
This was solved by updating webpack to the latest vesion

**Comment by james-criscuolo** [comment]
I'm going to close, as this appears to have been resolved. What version of webpack were you on, and what did you update to?

**Comment by m-heinemann** [comment]
I was on webpack version 2.6.1 and I migrated to version 4.43.0
