### ISSUE TITLE
Problem with Mozilla Firefox on incoming calls

### ISSUE THREAD

**Issue by Daniel-Donev** [onsip/SIP.js#831]
Sometimes when I receive an incoming call on Mozilla Firefox 78.0.1 (64-bit) they can hear me and I can't hear them...

Anyone else with a similar problem?

Tue Jul 07 2020 18:00:44 GMT+0300 (Eastern European Summer Time) | sip.Invitation | Invitation.accept logger-factory.ts:109:16
Tue Jul 07 2020 18:00:44 GMT+0300 (Eastern European Summer Time) | sip.Invitation | Session 76fbafe2315a21f06d8cd8fb1c771fce@217.145.95.95:0as2d8bf8a8 transitioned to state Establishing logger-factory.ts:109:16
Tue Jul 07 2020 18:00:44 GMT+0300 (Eastern European Summer Time) | sip.SimpleUser | [Anonymous] session state changed to Establishing logger-factory.ts:109:16
Tue Jul 07 2020 18:00:57 GMT+0300 (Eastern European Summer Time) | sip.Transport | Received WebSocket text message:

OPTIONS sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws SIP/2.0

Via: SIP/2.0/WS 217.145.95.95:0;branch=z9hG4bK150ce632;rport

Max-Forwards: 70

From: "asterisk" <sip:asterisk@217.145.95.95:0>;tag=as2cab830f

To: <sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws>

Contact: <sip:asterisk@217.145.95.95:0;transport=ws>

Call-ID: 7a7592bf3fc725cd29acb7b817eb302e@217.145.95.95:0

CSeq: 102 OPTIONS

User-Agent: Asterisk PBX 13.20.0

Date: Tue, 07 Jul 2020 15:00:56 GMT

Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

Supported: replaces, timer

Content-Length: 0

logger-factory.ts:109:16
Tue Jul 07 2020 18:00:57 GMT+0300 (Eastern European Summer Time) | sip.Transport | Sending WebSocket message:

SIP/2.0 200 OK

Via: SIP/2.0/WS 217.145.95.95:0;branch=z9hG4bK150ce632;rport

From: "asterisk" <sip:asterisk@217.145.95.95:0>;tag=as2cab830f

To: <sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws>;tag=f2nm1r1lhm

CSeq: 102 OPTIONS

Call-ID: 7a7592bf3fc725cd29acb7b817eb302e@217.145.95.95:0

Supported: outbound

User-Agent: SIP.js/0.17.0

Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,REGISTER,SUBSCRIBE

Accept: application/sdp,application/dtmf-relay

Content-Length: 0

logger-factory.ts:109:16
Tue Jul 07 2020 18:00:58 GMT+0300 (Eastern European Summer Time) | sip.Transport | Sending WebSocket message:

SIP/2.0 200 OK

Via: SIP/2.0/WS 217.145.95.95:0;branch=z9hG4bK7537009e;rport

From: "Agent 6671" <sip:6671@217.145.95.95:0>;tag=as2d8bf8a8

To: <sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws>;tag=tm4rm9u2h0

CSeq: 102 INVITE

Call-ID: 76fbafe2315a21f06d8cd8fb1c771fce@217.145.95.95:0

Supported: outbound

User-Agent: SIP.js/0.17.0

Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,REGISTER,SUBSCRIBE

Contact: <sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws>

Content-Type: application/sdp

Content-Length: 1043

v=0

o=mozilla...THIS_IS_SDPARTA-78.0.1 6990638714066169440 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 D5:76:75:A6:76:EE:96:FF:6B:EE:BA:71:C1:F7:C7:28:7B:6F:6B:7F:35:70:73:4C:4F:F1:B0:3C:85:04:29:AA

a=ice-options:trickle

a=msid-semantic:WMS *

m=audio 57072 RTP/SAVPF 0 8 101

c=IN IP4 217.145.95.134

a=candidate:0 1 UDP 2122187007 172.16.10.113 57072 typ host

a=candidate:2 1 UDP 2122252543 192.168.1.2 57073 typ host

a=candidate:4 1 TCP 2105458943 172.16.10.113 9 typ host tcptype active

a=candidate:5 1 TCP 2105524479 192.168.1.2 9 typ host tcptype active

a=candidate:1 1 UDP 1685987327 217.145.95.134 57072 typ srflx raddr 172.16.10.113 rport 57072

a=sendrecv

a=fmtp:101 0-15

a=ice-pwd:f378d5233ebd5a4b192d8f7906f02b36

a=ice-ufrag:c377b5d4

a=mid:0

a=msid:{01eaa5ab-df0b-404b-9a9f-6d121d455272} {e18ffc20-55c7-4c59-be9d-f5917d71cde5}

a=rtcp-mux

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:101 telephone-event/8000

a=setup:active

a=ssrc:1209610743 cname:{d47cdd77-fc79-4c3b-9b72-c066e5517c2b}

logger-factory.ts:109:16
Tue Jul 07 2020 18:00:58 GMT+0300 (Eastern European Summer Time) | sip.Invitation | Session 76fbafe2315a21f06d8cd8fb1c771fce@217.145.95.95:0as2d8bf8a8 transitioned to state Established logger-factory.ts:109:16
Tue Jul 07 2020 18:00:58 GMT+0300 (Eastern European Summer Time) | sip.SimpleUser | [Anonymous] session state changed to Established logger-factory.ts:109:16
[SIP.js Demo] Call answered demo-1.ts:45:12
Tue Jul 07 2020 18:00:58 GMT+0300 (Eastern European Summer Time) | sip.Transport | Received WebSocket text message:

ACK sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws SIP/2.0

Via: SIP/2.0/WS 217.145.95.95:0;branch=z9hG4bK42214902;rport

Max-Forwards: 70

From: "Agent 6671" <sip:6671@217.145.95.95:0>;tag=as2d8bf8a8

To: <sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws>;tag=tm4rm9u2h0

Contact: <sip:6671@217.145.95.95:0;transport=ws>

Call-ID: 76fbafe2315a21f06d8cd8fb1c771fce@217.145.95.95:0

CSeq: 102 ACK

User-Agent: Asterisk PBX 13.20.0

Content-Length: 0

logger-factory.ts:109:16
Tue Jul 07 2020 18:00:58 GMT+0300 (Eastern European Summer Time) | sip.invite-dialog | INVITE dialog 76fbafe2315a21f06d8cd8fb1c771fce@217.145.95.95:0tm4rm9u2h0as2d8bf8a8 received ACK request logger-factory.ts:109:16
Tue Jul 07 2020 18:00:58 GMT+0300 (Eastern European Summer Time) | sip.Invitation | Session.onAckRequest logger-factory.ts:109:16
Tue Jul 07 2020 18:01:57 GMT+0300 (Eastern European Summer Time) | sip.Transport | Received WebSocket text message:

OPTIONS sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws SIP/2.0

Via: SIP/2.0/WS 217.145.95.95:0;branch=z9hG4bK12c2f28e;rport

Max-Forwards: 70

From: "asterisk" <sip:asterisk@217.145.95.95:0>;tag=as4fc1cd49

To: <sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws>

Contact: <sip:asterisk@217.145.95.95:0;transport=ws>

Call-ID: 7b0c33777bfe2b495e3839465dd9b939@217.145.95.95:0

CSeq: 102 OPTIONS

User-Agent: Asterisk PBX 13.20.0

Date: Tue, 07 Jul 2020 15:01:57 GMT

Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

Supported: replaces, timer

Content-Length: 0

logger-factory.ts:109:16
Tue Jul 07 2020 18:01:57 GMT+0300 (Eastern European Summer Time) | sip.Transport | Sending WebSocket message:

SIP/2.0 200 OK

Via: SIP/2.0/WS 217.145.95.95:0;branch=z9hG4bK12c2f28e;rport

From: "asterisk" <sip:asterisk@217.145.95.95:0>;tag=as4fc1cd49

To: <sip:2tmp73g7@us7glcthk1tu.invalid;transport=ws>;tag=csab0iv750

CSeq: 102 OPTIONS

Call-ID: 7b0c33777bfe2b495e3839465dd9b939@217.145.95.95:0

Supported: outbound

User-Agent: SIP.js/0.17.0

Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,REGISTER,SUBSCRIBE

Accept: application/sdp,application/dtmf-relay

Content-Length: 0

**Comment by james-criscuolo** [comment]
This is likely Asterisk related. Please use the google group for further questions on this.
