### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by dimas3821** [onsip/SIP.js#832]
I created a topic in a group, but did not receive an answer to my question
https://groups.google.com/forum/#!topic/sip_js/Bads2j6h1_U
Using sip.0.16.1
I create a UA and register it
`
inviter = new Inviter(this.UA, target);
inviter.invite()

this.inviter.stateChange.addListener((newState) => {
          var mediaElement = document.getElementById('audioRemote');
          let remoteStream = new MediaStream();
          function setupRemoteMedia(session) {
            session.sessionDescriptionHandler.peerConnection.getReceivers().forEach((receiver) => {
              if (receiver.track) {
                remoteStream.addTrack(receiver.track);
              }
            });
            mediaElement.srcObject = remoteStream;
            mediaElement.play();
          }

          function cleanupMedia() {
            mediaElement.srcObject = null;
            mediaElement.pause();
          }
          switch (newState) {
            case SessionState.Establishing:
              break;
            case SessionState.Established:
              setupRemoteMedia(inviter);
              break;
            case SessionState.Terminated:
              cleanupMedia();
              break;
            default:
              break;
          }
        });`
The call goes and is accepted, but I do not hear my interlocutor and he does not hear me. The microphone on the page is connected, but there is no sound
What could be the problem? I did not find a single example of the use of UA. All examples using simple user.

**Comment by egreenmachine** [comment]
This is not a SIP.js issue. We will answer the question on google group when we have time to do so.
