### ISSUE TITLE
Conference chat

### ISSUE THREAD

**Issue by AlbyGNinja** [onsip/SIP.js#839]
Hello people, i've posted this also on GGroup but no answers.
I've enabled conference rooms on asterisk server, but conference chat won't work following [this guide here](https://wiki.asterisk.org/wiki/display/AST/Conference+Participant+Messaging) and it works on JsSip but not with SIPJs.
Because of conference works perfectly i would like to understand if chat is possible too, it would be a very nice feature

**Comment by james-criscuolo** [comment]
We'll respond in the google doc when we have time. In the meantime, you can see how to provide more information on this in our FAQ: https://sipjs.com/faq/

Without investigating, I'd say that unless the mechanism used is an out of dialog refer, SIP.js is capable of it, but our API is different so it makes sense that following the guide for another library would not work. Seeing the SIP messages, and determining which ones you can not send, is the first step to figuring out how to do it.

If this is an out of dialog refer, we already have an issue for that here: https://github.com/onsip/SIP.js/issues/834
