### ISSUE TITLE
Modifying ICE Candidates in offer SDP?

### ISSUE THREAD

**Issue by slavikbialik** [onsip/SIP.js#849]
Hi all,
I've been trying to find a way to modify the ICE candidates in the SDP.
The reason is that when we make an offer (200 OK) there are multiple ICE candidates being gathered, and most of them are not relevant at all as they're some virtual NICs on my PC. Most of the times, the non-relevant ICE candidates are getting higher priority and it is making a big delay in a call.
Question is if you know a way to change ICE candidates or making chosen one being prioritized (although I doubt it is in the SIP.JS level, right?).

What I tried to do is doing the following:
```
        var sdpModifier = function (description: RTCSessionDescriptionInit) {
            console.log(description);
            //description.sdp = description.sdp?.replace(....... making some replace REGEX here .....);
            console.log(description.sdp?.toString());
            return Promise.resolve(description);
        };

        var invitationAcceptOptions = {
            "sessionDescriptionHandlerModifiers": [sdpModifier]
        };
  
        invitation.accept(invitationAcceptOptions);
```

But when I see in the console.log I'm making in the sdpModifier function is that it has the whole SDP body, all except the ICE candidates themselves, so I can't really modify something here. So I assume that the ICE gathering process happens somewhere after this step. Can I modify it after candidates are gathered and put into the SDP? Or any other better solutions?

Thanks!

**Comment by LegendL3n** [comment]
I'm experiencing the same issue, however, I think your solution isn't the most viable, I'm thinking that the problem here is that SIP.js doesn't support Trickle ICE. (or does it?)

Also, I only experience this in Firefox, on Chrome it is fast to establish the call. (might be a good idea to try Chrome on your side)

**Comment by LegendL3n** [comment]
Oh and I tried setting `iceCheckingTimeout` on the `SessionDescriptionHandlerOptions` of `UserAgentOption` to 500 and didn't notice any difference at all.

I am using the version 0.15 of the Lib.

**Comment by LegendL3n** [comment]
@egreenmachine Any updates on this?

**Comment by slavikbialik** [comment]
> Oh and I tried setting `iceCheckingTimeout` on the `SessionDescriptionHandlerOptions` of `UserAgentOption` to 500 and didn't notice any difference at all.
> 
> I am using the version 0.15 of the Lib.

Hi!
Regarding your previous reply, I tested it on Chrome & FireFox, and it behaves the same for me.
Regarding the "iceCheckingTimeout", for me I can tell for sure it will not help because the problem on my end is actually that the RTPEngine is the one that takes the list of the ICE candidates and try to do ICE checking for all candidates. The issue is that the offer (200 OK) or an initial INVITE from SIP.JS (although SIP.JS lib is not to blame here) is placing multiple ICE candidates with some strange priorities (at least for me) so RTPEngine makes the ICE checking according to this priority list, so when it tries to check the first one which is not accessible for him it delays the whole process, and that's why I tried to approach it with deleting irrelevant ICE candidates when there's "onicecandidate" event (while they're gathered).

**Comment by LegendL3n** [comment]
@slavikbialik Yes, I understood your issue, I was just commenting mine because it had the same "outcome" (the delay). 😋

**Comment by slavikbialik** [comment]
OK, I was able to find the proper way to code what I initially wanted in my post.
First needed a way to detect the creation of the session description handler and only then I could hook a delegation of the "onicecandidate" event. So something like that (only I didn't accomplished the removal of ice candidates that I don't need, but it is possible within this code as far as I recall):

```
        CallTaking.inviter.delegate = {
            onSessionDescriptionHandler: (
                sessionDescriptionHandler: SessionDescriptionHandler,
                provisional: boolean
            ) => {
                var sdh = (CallTaking.inviter.sessionDescriptionHandler as Web.SessionDescriptionHandler);
                sdh.peerConnectionDelegate = {
                    onicecandidate(event: RTCPeerConnectionIceEvent) {
                        console.log(event);
                    }
                };
                console.log("A session description handler was created");
            }
        };
```

**Comment by slavikbialik** [comment]
> Oh and I tried setting `iceCheckingTimeout` on the `SessionDescriptionHandlerOptions` of `UserAgentOption` to 500 and didn't notice any difference at all.
> 
> I am using the version 0.15 of t

Can you please assist me with the code you implemented to change `iceCheckingTimeout`?
I'm trying to understand how to code it to change this timer, and I'm not able to get a hold of it.
Although I'm using SIP.JS 0.17, so it might be a little different (hope not).

**Comment by LegendL3n** [comment]
@slavikbialik Try setting it in the `sessionDescriptionHandlerOptions` of your `SessionInviteOptions`.

**Comment by slavikbialik** [comment]
> @slavikbialik Try setting it in the `sessionDescriptionHandlerOptions` of your `SessionInviteOptions`.

Thanks! I just found out now that `iceCheckingTimeout` is not part of the SIP.JS 0.17, cannot find it in the code and in non of the documents for that version. No idea how I can reduce the time for building up the INVITE, as it takes me around 5 seconds until the INVITE is being ready and sent out. Opened a new issue on that.

**Comment by LegendL3n** [comment]
Weird, because I found it on the docs here in this GitHub.
