### ISSUE TITLE
Ringback during Connecting

### ISSUE THREAD

**Issue by lylepratt** [onsip/SIP.js#85]
Hi guys!

I'm curious how others are approaching playing a ringback tone when making calls. Currently I don't get any audio until a call is actually connected. Do I need to manually play an audio file locally, or should I be hearing early media from my FS server?

Might be a dumb question, apologies if it is!

**Comment by svarunan** [comment]
Hi @lylepratt 
In Freeswitch make sure you set "ignore_early_media=false" before bridge and Follow below link
https://github.com/onsip/SIP.js/issues/211
Thanks to @matthieusieben for help. I was looking for this :)
