### ISSUE TITLE
setRemoteDescription not called until after accept

### ISSUE THREAD

**Issue by ryanmcclure4** [onsip/SIP.js#851]
I'm using v0.15.11 and I've noticed that on outbound calls the remote description isn't set until after the callee has accepted the call. This in turn delays the ice connection state change until after the callee has accepted and begun speaking, and for ~3-5 seconds while the ice connection is going from _checking_ to _connected_ there is no audio for either party. When inspecting the webrtc events of other softphones I see that the remote description is typically set before the callee's device begins ringing, and so the ice connection is established before the callee answers.

Is this behavior expected?  If so, is it fixed in a newer release? If not, what might I be doing wrong?

**Comment by ryanmcclure4** [comment]
Looks like if I set the remote description in the onProgress callback when code is 183, it solves the problem. Why wouldn't this be default built-in behavior?

**Comment by egreenmachine** [comment]
Yes. This is expected behavior. It sounds like you do not have early media enabled. You can enable early media on the [InviterOptions](https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.inviteroptions.md)

**Comment by ryanmcclure4** [comment]
@egreenmachine This option appears to work for code on the master branch, but not for v0.15.11 - I'm using this, as it's the highest version with api docs on sipjs.com. Looking at the diff between 15.x and 17.x there seem to be many changes - is 17.x considered stable?

**Comment by egreenmachine** [comment]
Yes. 17.X is stable. We moved out api [docs to github](https://github.com/onsip/SIP.js/blob/master/docs/README.md). I see our header on the website is not updated everywhere. I will get that fixed.

**Comment by ryanmcclure4** [comment]
Great, I'll upgrade. Thanks!

**Comment by ryanmcclure4** [comment]
@egreenmachine So early media solves the issue for outbound calls, however this isn't applicable for inbound calls in which case I'm still experiencing a delay. What I'm seeing is that the ice connection takes about 3-5 seconds to complete after the sip.js phone answers the call. So if the caller begins speaking immediately when their phone shows connected, the audio is cut off until a few seconds in. Does sip.js provide a way to mitigate this?
