### ISSUE TITLE
No Contact header pointing to us, dropping response when I try to register a user in sip with asterisk,but always get this error

### ISSUE THREAD

**Issue by guygubaby** [onsip/SIP.js#852]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).

No Contact header pointing to us, dropping response

**Comment by guygubaby** [comment]
Call-ID: 19bedvila15qbe8u4q7k
CSeq: 3 REGISTER
Server: JustPBX
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Expires: 1200
Contact: <sip:90001@117.25.82.5:53951;transport=ws>;expires=1200
Date: Mon, 31 Aug 2020 09:25:47 GMT
Content-Length: 0

**Comment by guygubaby** [comment]
@egreenmachine 
why close this without any response

**Comment by egreenmachine** [comment]
From the issue template that you left in your original message...

> These are typically directed to the [google group](https://groups.google.com/g/sip_js).

Additionally this is not a SIP.js issue. Your asterisk server or something outside of SIP.js is mucking with the contact in the response that is being sent to the SIP.js endpoint. The contact is not for the SIP.js client so the message is dropped. As the log line correctly indicates.

**Comment by guygubaby** [comment]
> From the issue template that you left in your original message...
> 
> > These are typically directed to the [google group](https://groups.google.com/g/sip_js).
> 
> Additionally this is not a SIP.js issue. Your asterisk server or something outside of SIP.js is mucking with the contact in the response that is being sent to the SIP.js endpoint. The contact is not for the SIP.js client so the message is dropped. As the log line correctly indicates.

thanks a lot

**Comment by rushikeshkoli** [comment]
@guygubaby I am also facing the same problem.. How did you solve the problem? At my side when I register the state is transitioned to 'unregister'.
