### ISSUE TITLE
refer function on webRTC question

### ISSUE THREAD

**Issue by QuangMInh09** [onsip/SIP.js#853]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).
Hi,

Currently I'm working with 0.17.1.
when i using logLevel: "debug" and i make outbound out-of-dialog REFER requests. Status code only send me status 100 trying 
and not auto hangup in spite of target refer accepted, after accepted 30s code send status code 408 request time out, still not hangup and make noise between caller and refer target and when i reject the call, it remains the same . Until i must hangup middle call manually. 

Can someone please give me the solution (a simple code example would be very much appreciated).
Thanks!

**Comment by egreenmachine** [comment]
How are you sending the refer?

**Comment by QuangMInh09** [comment]
> How are you sending the refer?
First i receive call then using session to refer like this:        
        
        const transferTarget = SIP.UserAgent.makeURI(`sip:${toNumber}@${TestSipjs.domain}`);
        
        window.SimpleUser.session.refer(transferTarget,{
          onNotify(e){
            console.log(e);
          },          
          requestDelegate: {
            onAccept(){
              window.SimpleUser.session.bye();
              console.log("ok");
            },
            onReject(){              
              self.setupInCall();
            }
          }
        } 
);

**Comment by egreenmachine** [comment]
Creating a transfer (REFER) with SimpleUser is not supported. You need to use the full API. 

Out of dialog refer is not supported at all with SIP.js at the moment. Your hack is an in dialog refer.

This is definitely not a SIP.js bug but a question about implementation. Please direct this towards the [Google Group](https://groups.google.com/g/sip_js)
