### ISSUE TITLE
Allow number sign char in SIP URI

### ISSUE THREAD

**Issue by zek** [onsip/SIP.js#856]
**Is your feature request related to a problem? Please describe.**
We have some testing extensions which starts with `#` (number sign)

I can make calls from zoiper. 

However sip.js doesn't accept `sip:#1@127.0.0.1:5060` as a valid uri. 
 
**Describe the solution you'd like**

Is it possible if we can update grammar to allow `#`? https://github.com/onsip/SIP.js/blob/master/src/grammar/pegjs/src/grammar.pegjs

**Comment by egreenmachine** [comment]
According to the [SIP RFC BNF](https://tools.ietf.org/html/rfc3261#section-25) the `#` is not allowed in the user portion. You must escape the `#` and that should work according to our grammar.

**Comment by zek** [comment]
I have escaped # as %23 but sipjs drops incoming SIP messages

**Comment by egreenmachine** [comment]
It should state in the logs why the message was dropped.
