### ISSUE TITLE
Multiple allow and contact headers

### ISSUE THREAD

**Issue by VincentdeWit94** [onsip/SIP.js#858]
**Describe the bug**
We have an issue where for some users multiple allow and contact headers are sent randomly. It does not always happen, or on a specific time or after specific steps, but really random. Almost the same issue as mentioned in issue 684: https://github.com/onsip/SIP.js/issues/684.

**Logs**
Here is an example of an invite being sent from SIP.js 0.15.11.
`
INVITE sip:303@xxx.xxx SIP/2.0
Via: SIP/2.0/WSS cqi6p1i2mfjt.invalid;branch=z9hG4bK770885
To: <sip:303@xxx.xxx>
From: <sip:81a7c251fe8396ae1c9f@xxx.xxx>;tag=0dklb1b8jb
CSeq: 1 INVITE
Call-ID: pge6o4r426tqbr5u1lqe
Max-Forwards: 70
Contact: <sip:e3p86dp7@cqi6p1i2mfjt.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Contact: <sip:e3p86dp7@cqi6p1i2mfjt.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Contact: <sip:e3p86dp7@cqi6p1i2mfjt.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Contact: <sip:e3p86dp7@cqi6p1i2mfjt.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Contact: <sip:e3p86dp7@cqi6p1i2mfjt.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Contact: <sip:e3p86dp7@cqi6p1i2mfjt.invalid;transport=ws;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound
User-Agent: SIP.js/0.15.11
Content-Type: application/sdp
Content-Length: 2015

v=0
o=- 6036058402000603978 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS hrW66WCJKKuX3se8zBecoR6kjAHVUlk2Sm67
m=audio 54839 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 18.157.73.64
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2279323705 1 udp 2122260223 192.168.252.118 64040 typ host generation 0 network-id 1
a=candidate:3994155000 1 udp 1686052607 45.95.69.xxx 64040 typ srflx raddr 192.168.252.118 rport 64040 generation 0 network-id 1
a=candidate:97535431 1 udp 41885951 18.157.73.64 54839 typ relay raddr 45.95.69.xxx rport 64040 generation 0 network-id 1
a=ice-ufrag:j6js
a=ice-pwd:CPO6la3QzfjRUsFLYi2NV++o
a=ice-options:trickle
a=fingerprint:sha-256 46:F1:B9:1B:E9:D6:A8:09:6F:7B:FD:7C:CD:84:DA:59:85:70:DF:66:71:19:7D:DF:30:BC:B9:7E:5F:17:9C:74
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:hrW66WCJKKuX3se8zBecoR6kjAHVUlk2Sm67 b8fb08a5-34fa-4607-92d1-45bfef89950c
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1005814267 cname:oj6XcaduBqhWF+Pt
a=ssrc:1005814267 msid:hrW66WCJKKuX3se8zBecoR6kjAHVUlk2Sm67 b8fb08a5-34fa-4607-92d1-45bfef89950c
a=ssrc:1005814267 mslabel:hrW66WCJKKuX3se8zBecoR6kjAHVUlk2Sm67
a=ssrc:1005814267 label:b8fb08a5-34fa-4607-92d1-45bfef89950c
`

**To Reproduce (if possible)**
-

**Expected behavior**
Expected behavior is to see a correct SIP packet with only one Allow and one Contact header

**Environment Information**
- Kamailio SBC
- Chrome browser (in Electron)

**Comment by egreenmachine** [comment]
Can you update to the latest version and see if it is still happening there?

**Comment by egreenmachine** [comment]
I am closing this issue as we have not heard back from you. We believe that this should be fixed in the latest version of SIP.js.
