### ISSUE TITLE
CDNJS is no longer updated sinds 0.16.1

### ISSUE THREAD

**Issue by mjrider** [onsip/SIP.js#859]
**Describe the bug**
Sinds 0.16.1 cdnjs is no longer updated
https://cdnjs.com/libraries/sip.js

**Logs**
N/A

**To Reproduce (if possible)**
N/A

**Expected behavior**
that newer releases are publisch on cdnjs

**Observed behavior**
sinds 0.16.1 no new releases are published

**Environment Information**
N/A

**Additional context**
N/A

**Comment by james-criscuolo** [comment]
Please follow https://github.com/cdnjs/packages/pull/431

Once that is accepted, I'll close this.

**Comment by james-criscuolo** [comment]
Ticket was merged, closing.
