### ISSUE TITLE
sip.Transport | WebSocket closed unexpectedly

### ISSUE THREAD

**Issue by martyrs** [onsip/SIP.js#860]
**Describe the bug**
When initiating calls [as soon as INVITE goes to server] I am getting `WebSocket closed unexpectedly` randomly. Like 4 of 10 calls. Tested with self-signed / my wildcard / letsencrypt cert.

**Logs**
```
Wed Sep 09 2020 12:16:14 GMT+0300 (GMT+03:00) | sip.Transport | WebSocket error occurred. logger-factory.js:85
Wed Sep 09 2020 12:16:14 GMT+0300 (GMT+03:00) | sip.Transport | WebSocket closed unexpectedly logger-factory.js:89
Wed Sep 09 2020 12:16:14 GMT+0300 (GMT+03:00) | sip.Transport | WebSocket closed wss://1xx.7x.7x.12:7443/wss (code: 1006) logger-factory.js:93
```

**To Reproduce (if possible)**
Just initiate a call.

**Expected behavior**

**Observed behavior**

**Environment Information**
0.17.1 sip.js
Freeswitch master branch
Mozilla 77.0.1
Google Chrome | 83.0.4103.106

**Additional context**
I have tested multiple freeswitch installations at different locations like digitalocean, my own network, without any NAT. also used freeswitch vanilla configuration.

**Comment by egreenmachine** [comment]
Chrome is reporting that the websocket is closed unexpectedly and has an error code of 1006. This is outside the control of SIP.js and almost certainly caused by the Websocket server. In this case Freeswitch. I would recommend following up with Freeswitch.

**Comment by luanyata** [comment]
hi i have the same problem, did i solve it?

**Comment by Irfanwani** [comment]
Hello, did anyone solved this problem. I am getting this issue on android only, websocket never connects.
