### ISSUE TITLE
Alternative for iceCheckingTimeout in SIP.JS 0.17.x?

### ISSUE THREAD

**Issue by slavikbialik** [onsip/SIP.js#861]
Hi all,
I was trying to implement the `iceCheckingTimeout` but I found out that it is not part of 0.17 anymore.
What I'm trying to achieve is reducing the time of making an outgoing call. It takes me something like 5 seconds until the INVITE is built up and being sent out. I found a way to print the "onicecandidate" event and I see the gathering process is fast, so all it's left is the time of the ICE checking probably that delays the INVITE.

What can I add in my code on SIP.JS 0.17 that can reduce this time?
I see that there's only `iceGatheringTimeout`, but it will probably won't help me as the gathering itself is fast. Not to mention that even that I cannot implement because when trying to pass it in the 
`Inviter.invite({sessionDescriptionHandlerOptions: {iceGatheringTimeout: 500}})`
it cannot recognize the `iceGatheringTimeout` because it only knows of the `constraints`.

Hope that someone already tackled this issue and knows the solution :)
Thanks!

**Comment by john-e-riordan** [comment]
Hey,

`iceCheckingTimeout` was renamed `iceGatheringTimeout` to be more clear about what the setting does.

The default is 5000 ms.

`Web.SessionDescriptionHandlerOptions` extends `SessionDescriptionHandlerOptions` so you should be able to pass that to `Inviter.invite`.

Something like...

```
import { Web } from "sip.js";

const options: Web.SessionDescriptionHandlerOptions = {
  iceGatheringTimeout: 500,
  constraints: { audio: true }
}

Inviter.invite({sessionDescriptionHandlerOptions})
```

The docs for the options for the web session description handler options are here:
https://github.com/onsip/SIP.js/blob/master/docs/session-description-handler/sip.js.sessiondescriptionhandleroptions.md

**Comment by slavikbialik** [comment]
> Hey,
> 
> `iceCheckingTimeout` was renamed `iceGatheringTimeout` to be more clear about what the setting does.
> 
> The default is 5000 ms.
> 
> `Web.SessionDescriptionHandlerOptions` extends `SessionDescriptionHandlerOptions` so you should be able to pass that to `Inviter.invite`.
> 
> Something like...
> 
> ```
> import { Web } from "sip.js";
> 
> const options: Web.SessionDescriptionHandlerOptions = {
>   iceGatheringTimeout: 500,
>   constraints: { audio: true }
> }
> 
> Inviter.invite({sessionDescriptionHandlerOptions})
> ```
> 
> The docs for the options for the web session description handler options are here:
> https://github.com/onsip/SIP.js/blob/master/docs/session-description-handler/sip.js.sessiondescriptionhandleroptions.md

Thank you! Sounds promising! I'll test it tomorrow and let you know.

**Comment by slavikbialik** [comment]
> Hey,
> 
> `iceCheckingTimeout` was renamed `iceGatheringTimeout` to be more clear about what the setting does.
> 
> The default is 5000 ms.
> 
> `Web.SessionDescriptionHandlerOptions` extends `SessionDescriptionHandlerOptions` so you should be able to pass that to `Inviter.invite`.
> 
> Something like...
> 
> ```
> import { Web } from "sip.js";
> 
> const options: Web.SessionDescriptionHandlerOptions = {
>   iceGatheringTimeout: 500,
>   constraints: { audio: true }
> }
> 
> Inviter.invite({sessionDescriptionHandlerOptions})
> ```
> 
> The docs for the options for the web session description handler options are here:
> https://github.com/onsip/SIP.js/blob/master/docs/session-description-handler/sip.js.sessiondescriptionhandleroptions.md

Thanks! It's working! 👍
