### ISSUE TITLE
Placing calll with video enabled and no camera causes error

### ISSUE THREAD

**Issue by crobibero** [onsip/SIP.js#864]
**Describe the bug**
Place / receive call with constraints
```
constraints: {
                audio: true
                video: true
            }
```

**Logs**
```
Tue Oct 13 2020 13:48:22 GMT-0600 (Mountain Daylight Time) | sip.SessionDescriptionHandler | SessionDescriptionHandler.getDescription failed - NotFoundError: The object can not be found here.
Tue Oct 13 2020 13:48:22 GMT-0600 (Mountain Daylight Time) | sip.Inviter | Session.getOffer: SDH getDescription rejected...
Tue Oct 13 2020 13:48:22 GMT-0600 (Mountain Daylight Time) | sip.Inviter | The object can not be found here.
```
**To Reproduce (if possible)**
1. Set video constraint to `true`
2. Unplug / disable camera
3. Place call

**Expected behavior**
Call should proceed without video.

**Observed behavior**
Call errors.

**Environment Information**
 - SIP.js 0.17.1
 - Firefox 81.0.1 x64

**Additional context**
This also errors if the user rejects camera permissions.

**Comment by john-e-riordan** [comment]
Not a bug. Behavior is as expected. If you wish to implement a different behavior, you can do so. See: https://github.com/onsip/SIP.js/blob/main/docs/session-description-handler.md#how-do-i-override-how-local-media-is-obtained
