### ISSUE TITLE
Prevent 180 progress on invite when user is busy on another call

### ISSUE THREAD

**Issue by jamesaylett** [onsip/SIP.js#865]
**Describe the bug**
The current SIP.js does not allow me to prevent sending 180 when receiving an invite. My scenario is that the user is already on a call, so I reject any further invites with a 486, but SIP.js sends a 180 which with my media server will play a burst of ringing to the other user.

**Logs**
n/a - See https://github.com/onsip/SIP.js/blob/f11dfd584bc9788ccfc94e03034020672b738975/src/api/invitation.ts#L194-L210 for area of code this has been noted in.

**To Reproduce (if possible)**
1. Create UA with rel100 supported
2. Receive invite to UA
3. Call session reject

**Expected behavior**
Ability with SIP.js to turn off the autoSendAnInitialProvisionalResponse if the developer wishes so.

**Observed behavior**
Unable to turn off autoSendAnInitialProvisionalResponse without changing the rel100 options.

**Environment Information**
 - SIP.js 0.17.1

**Additional context**
Would you accept a pull request to include a new UA configuration parameter to turn off auto progress?

**Comment by james-criscuolo** [comment]
Thanks again, closing as this is now released in 0.19.0.
