### ISSUE TITLE
Stale remote audio tracks not replaced in Electron

### ISSUE THREAD

**Issue by ryanmcclure4** [onsip/SIP.js#866]
I have a React app that bundles into both a webapp and Electron app. Once I upgraded to the latest SIP.js version (v0.17.1) I noticed that after performing a hold, then un-hold, the remote audio track had an "ended" readyState. Strangely, on the webapp the audio continued to stream through just fine, but in Electron it stops working.

I looked through the SessionDescriptionHandler class and saw that `setRemoteTrack` only updates the remote track as long as the track doesn't already exist with the same id. Adding some logs in there, I noticed that in the hold/unhold case even though the track existed with the same id, it was in an "ended" readyState. Removing the following lines solves the issue, as it always updates the track:

```
if (remoteStream.getTrackById(track.id)) {
            this.logger.debug(`SessionDescriptionHandler.setRemoteTrack - have remote ${track.kind} track`);
}
```

I tried adding a check to see if the track existed and was in an "ended" state, in which case it would continue to replace the track on the remoteStream, however I noticed that in some random cases it still wasn't working. So removing the check altogether solves the problem.

Why would this issue be present in Electron vs Chrome with the webapp?

**Comment by slavikbialik** [comment]
Had a similar issue. When a RE-INVITE occurs (hold and un-hold also trigger a RE-INVITE) and SDP negotiated again in an existing call, I've noticed that the first remote track is being stopped and a new one is being created - like you've mentioned. And what I actually experienced is that I have no audio from the caller side.
So I ended with implementing the following solution (for example when answering a call and when detecting that session state transitioned to `Established`).
So I'm using `assignStream` function on answer to add the initial stream, and then I'm listening to `onTrack` events, so when an `onTrack` event will arrive I assume that there's a new media stream in place and I assign it immediately to the audio HTML element.

```
var audioElement = getAudio("remoteAudio");
invitation.stateChange.addListener((newState: SessionState) =>
{
	switch (newState)
	{
		case SessionState.Establishing:
			// do something...
			break;
		case SessionState.Established:
			const sessionDescriptionHandler = invitation.sessionDescriptionHandler as Web.SessionDescriptionHandler;
			assignStream(sessionDescriptionHandler.remoteMediaStream, audioElement);
			sessionDescriptionHandler.peerConnectionDelegate = {
				// NOTE:: SB - Allowing to get onTrack events to know when a new track added to the peer connection.
				// When we get a new track event, we'll assign the last new remote media stream to HTML audio element source.
				// Mostly will occur when RE-INVITEs will happen.
				ontrack(event: Event)
				{
					self.assignStream(sessionDescriptionHandler.remoteMediaStream, self.audioElement);
				}
			}
			break;
			...
			...
			...
	}
}

...
...
...
	
// Assign a MediaStream to an HTMLMediaElement and update if tracks change.
assignStream(stream: MediaStream, element: HTMLMediaElement): void
{
    // Set element source.
    element.autoplay = true; // Safari does not allow calling .play() from a non user action
    element.srcObject = stream;

    // Load and start playback of media.
    element.play().catch((error: Error) =>
    {
        console.error("Failed to play media");
        console.error(error);
    });

    // If a track is added, load and restart playback of media.
    stream.onaddtrack = (): void =>
    {
        element.load(); // Safari does not work otheriwse
        element.play().catch((error: Error) =>
        {
            console.error("Failed to play remote media on add track");
            console.error(error);
        });
    };

    // If a track is removed, load and restart playback of media.
    stream.onremovetrack = (): void =>
    {
        element.load(); // Safari does not work otheriwse
        element.play().catch((error: Error) =>
        {
            console.error("Failed to play remote media on remove track");
            console.error(error);
        });
    };
}
```

Hope it helps.

**Comment by ryanmcclure4** [comment]
I ended up writing a very similar solution for updating the active stream - but didn't realize we could subscribe to ontrack in the peerConnectionDelegate. That's perfect. Thanks!
