### ISSUE TITLE
User Agent onInvite delegate cannot reach methods outside of it's scope

### ISSUE THREAD

**Issue by slavikbialik** [onsip/SIP.js#867]
**Describe the bug**
The issue is when I'm trying to use the `onInvite` delegation on the `UserAgentOptions` I cannot access to any method or variable in my main class.
I'm not sure if it's a SIP.JS bug, or just a misunderstanding with how to implement it using code. Hopefully you can assist with shedding some light on it.

I tried to implement it like that (it resides in some class that handles all my call taking operations):
```
registerExtensionCommand() {
    ...
    setting some class variables
    ...
    const userAgentOptions: UserAgentOptions = {
        authorizationPassword: password,
        authorizationUsername: username,
        viaHost: userDomain,
        transportOptions,
        uri,
        delegate: {
            onInvite: this.onCallRecieve
        }
    };
}

..
..

onCallRecieve(invitation: Invitation)
{
    console.log("heyyy we have a new call! ");
    var self = this.getCallTakingObject();
    console.log(this.myextension);
    console.log(self.myextension);
}
```
Tried to set `var self = this` and also tried to create an additional method in my class that returns itself (like in the above example) but it also cannot see the method.

So for the above code I'm getting `undefined` on all methods / variables I'm trying to get inside the scope of the `onInvite`.

BUT! When I'm doing it like that IT WORKS fine:

```
registerExtensionCommand() {
	const userAgentOptions: UserAgentOptions = {
		authorizationPassword: password,
		authorizationUsername: username,
		viaHost: userDomain,
		transportOptions,
		uri
	};
	var self = this;
	this.extension = "2000";
	
	this.userAgent.delegate = {
		onInvite(invitation: Invitation): void
		{
			console.log("heyyy we have a new call! ");
			console.log(self.myextension);
		}
	}
}
```

Can't understand the difference, both ways should use the same interface and same method. No?
As far as I see when I'm printing `this` in the scope of `onInvite` it prints the `onInvite` function, which makes sense. But if I want to get the main object that this register command and the delegation of `onInvite` resides... is it possible at all in the first implementation?
Is it because the `onInvite` in my 2nd implementation has the `var self = this` before the `onInvite` which can be passed inside?
Or maybe there's a more complex way to doing this?
```
        delegate: {
            onInvite: this.onCallRecieve
        }
```
and also passing an additional variable where I can just pass the main object as a second parameter besides the `invitation: Invitation` parameter it gets.

Thanks!

**Logs**
The only log I can provide is when calling some method in the `onInvite` scope and I'm getting this error:
```
CallTaking.ts:1213 Uncaught (in promise) TypeError: Cannot read property 'getExtension' of undefined
    at Object.onCallRecieve [as onInvite] (CallTaking.ts:1213)
    at user-agent.js:635
onCallRecieve @ CallTaking.ts:1213
(anonymous) @ user-agent.js:635
Promise.then (async)
onInvite @ user-agent.js:630
receiveOutsideDialogRequest @ user-agent-core.js:642
receiveRequest @ user-agent-core.js:467
receiveRequestFromTransport @ user-agent-core.js:333
receiveIncomingRequestFromTransport @ user-agent-core.js:165
onTransportMessage @ user-agent.js:821
transport.onMessage @ user-agent.js:718
onWebSocketMessage @ transport.js:410
(anonymous) @ transport.js:202
```

**Environment Information**
 - SIP.JS 0.17.1
 - Chrome 86.0.4240.111

**Comment by egreenmachine** [comment]
Not a SIP.js issue, but a lack of understanding of the javascript `this` variable and how it scopes to functions and how they are called. Questions like this should be asked on our [Google Group](https://groups.google.com/forum/#!forum/sip_js). 

You need to set the this reference when setting the callback. You can do it using [`.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) or using [ES6 Fat Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

Bind
```
registerExtensionCommand() {
    ...
    setting some class variables
    ...
    const userAgentOptions: UserAgentOptions = {
        authorizationPassword: password,
        authorizationUsername: username,
        viaHost: userDomain,
        transportOptions,
        uri,
        delegate: {
            onInvite: this.onCallRecieve.bind(this)
        }
    };
}

..
..

onCallRecieve(invitation: Invitation)
{
    console.log("heyyy we have a new call! ");
    var self = this.getCallTakingObject();
    console.log(this.myextension);
    console.log(self.myextension);
}
```

Fat arrow function
```
registerExtensionCommand() {
    ...
    setting some class variables
    ...
    const userAgentOptions: UserAgentOptions = {
        authorizationPassword: password,
        authorizationUsername: username,
        viaHost: userDomain,
        transportOptions,
        uri,
        delegate: {
            onInvite: (invitation) => this.onCallRecieve(invitation)
        }
    };
}

..
..

onCallRecieve(invitation: Invitation)
{
    console.log("heyyy we have a new call! ");
    var self = this.getCallTakingObject();
    console.log(this.myextension);
    console.log(self.myextension);
}
```

**Comment by slavikbialik** [comment]
> Not a SIP.js issue, but a lack of understanding of the javascript `this` variable and how it scopes to functions and how they are called. Questions like this should be asked on our [Google Group](https://groups.google.com/forum/#!forum/sip_js).
> 
> You need to set the this reference when setting the callback. You can do it using [`.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) or using [ES6 Fat Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).
> 
> Bind
> 
> ```
> registerExtensionCommand() {
>     ...
>     setting some class variables
>     ...
>     const userAgentOptions: UserAgentOptions = {
>         authorizationPassword: password,
>         authorizationUsername: username,
>         viaHost: userDomain,
>         transportOptions,
>         uri,
>         delegate: {
>             onInvite: this.onCallRecieve.bind(this)
>         }
>     };
> }
> 
> ..
> ..
> 
> onCallRecieve(invitation: Invitation)
> {
>     console.log("heyyy we have a new call! ");
>     var self = this.getCallTakingObject();
>     console.log(this.myextension);
>     console.log(self.myextension);
> }
> ```
> 
> Fat arrow function
> 
> ```
> registerExtensionCommand() {
>     ...
>     setting some class variables
>     ...
>     const userAgentOptions: UserAgentOptions = {
>         authorizationPassword: password,
>         authorizationUsername: username,
>         viaHost: userDomain,
>         transportOptions,
>         uri,
>         delegate: {
>             onInvite: (invitation) => this.onCallRecieve(invitation)
>         }
>     };
> }
> 
> ..
> ..
> 
> onCallRecieve(invitation: Invitation)
> {
>     console.log("heyyy we have a new call! ");
>     var self = this.getCallTakingObject();
>     console.log(this.myextension);
>     console.log(self.myextension);
> }
> ```

Thanks a lot, I'll check this.
Next time I'll open similar questions on the Google group.
