### ISSUE TITLE
shorter or flexlible re-REGISTER time

### ISSUE THREAD

**Issue by qermit** [onsip/SIP.js#870]
https://github.com/onsip/SIP.js/blob/f41b9c9aac39fce991b47b439f8f13e708d7fbf3/src/api/registerer.ts#L659

The re-REGISTER be performed before previous one expires. 3 seconds is perfect in case of perfect connection but might be not long enough in real world.

I suggest to use either 50% of **expires** time or configurable.

**Comment by qermit** [comment]
My PR
https://github.com/onsip/SIP.js/pull/871

**Comment by james-criscuolo** [comment]
Released in 0.20.0.
