### ISSUE TITLE
Chrome Stereo Bug issue 8133,  Stereo converted to mono, and send 2 both channels.

### ISSUE THREAD

**Issue by hostbbb** [onsip/SIP.js#875]
**Describe the bug**
https://bugs.chromium.org/p/webrtc/issues/detail?id=8133

In 0.7.8 we hacked the SDP.  Chrome needs to have stereo=1 added before setLocalDescription  in order for the stereo to pass thru chrome from FreeSwitch  If not set... chrome converts to mono and sends same audio on both channels.

Looking at using 0.17.1 I see where i can hack this again in very low level, and compile the typescript.

But is looks like the best way may be to add this rule like chromeStereo 
https://github.com/onsip/SIP.js/blob/af4ab4e261d24fe7d31a2b804254a8823b725024/src/platform/web/modifiers/modifiers.ts

so a modifier is added to add stereo=1 in the UA for chrome/edge browsers like is done for other SDP rewrites.

Is this the correct approach?   

are these modifers changed before setLocalDescription?

**Additional context**

with 0.17.1   the offer send to freeswitch is still missing stereo=1 iin fmtm line.
this needs to be set on local description, and sent to Freeswitch to enable stereo in chome

Note: if the change is made and browser if Firefox. Firefox throws error telling you its illegal to change the local :) 
if sdp rewrite is conditional on browser useragent.

a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10;useinbandfec=1 NEEDS ;stereo=1
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:111 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

**Comment by egreenmachine** [comment]
Yes. Using modifiers is the correct approach. You should be able to pass the modifiers into SIP.js without recompiling. You can pass the modifiers to the UserAgent or on a per call basis. Modifiers are applied before `setLocalDescription`. One caveat is that at the moment the modifiers are also applied to remote descriptions.

**Comment by hostbbb** [comment]
Thanks, i added it to modifers.ts, and it works.

+++ b/src/platform/web/modifiers/modifiers.ts
@@ -131,8 +131,19 @@ export function stripRtpPayload(payload: string): SessionDescriptionHandlerModif
 export function stripVideo(description: RTCSessionDescriptionInit): Promise<RTCSessionDescriptionInit> {
   description.sdp = stripMediaDescription(description.sdp || "", "video");
   return Promise.resolve(description);
+  }
+
+
+ /**
+ * Modifier.
+ * @public
+ */
+export function chromeStereo(description: RTCSessionDescriptionInit): Promise<RTCSessionDescriptionInit> {
+  description.sdp = (description.sdp || "").replace(/useinbandfec=1/,"useinbandfec=1; stereo=1");
+  return Promise.resolve(description);
 }
