### ISSUE TITLE
UserAgent.delegate property is always empty even if defined in UserAgentOptions

### ISSUE THREAD

**Issue by jbreitung** [onsip/SIP.js#876]
Hi there,

i am currently implementing a web based phone using SIP.js library. I got it to work for outgoing calls but I am not able to get the incoming calls to work. I am stuck on the error that the "delegate" property of the UserAgent is always an empty JSON (the default value of it). 

I assigned it directly to the UserAgentOptions, also directly to the UserAgent.delegate property by bypassing the constructor and so on. I've tried multiple ways but eveytime it is still empty.

Here you can see my current code snippet trying to assign the user delegate:

```
    window.sipjs = require("sip.js");
    window.userSipURI = sipjs.UserAgent.makeURI("sip:" + userSipAddress);

    window.userAgentOptions = {
        authorizationPassword: sipPassword,
        authorizationUsername: caller,
        transportOptions: {
            server: server
        },
        uri: userSipURI,
        delegate: {
            onConnect: onUAConnect,
            onDisconnect: onUADisconnect,
            onInvite: onUAInvite,
            onMessage: onUAMessage,
            onNotify: onUANotify
        }
    };

    window.userAgent = new sipjs.UserAgent(userAgentOptions);

    window.registerer = new sipjs.Registerer(userAgent);
```

The functions I've assigned to the delegate:

```
window.onUAConnect = function () {
    console.log("Received onConnect event.");
};
window.onUADisconnect = function (error) {
    console.log("Received onDisconnect event.");
};
window.onUAInvite = function (invitation) {
    console.log("Received onInvite (new call) event.");
};
window.onUAMessage = function (message) {
    console.log("Received onMessage event.");
};
window.onUANotify = function (notification) {
    console.log("Received onNotify event.");
};
```

When opening my web page containing the SIP.js implementation, the constructor of the UserAgent class will log the defined properties of the passed UserAgentOptions. Every time I tried I see the following log:

`Thu Nov 12 2020 10:33:58 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · delegate: {}`

You can see I've set the delegate property to the userAgentOptions which are passed to the UserAgent's constructor... But it seems that they got lost anywhere. All other properties are working fine. I have not answer for this issue...

If anybody has a helpful answer to me, I would be very thankful for that :-)

I've reported this as a "bug", because currently this looks like one for me. Correct me if I am wrong.

**Comment by slavikbialik** [comment]
what is `window`? Is this the object name where all of those functions included?
Or are you referring to `window` as the global JS object? If so, I don't see any reason why to write `window` here. 
Just declare your variables like that:
`var userAgentOptions = ...`
And also the functions can be:
`function onUAInvite (invitation) { ... }` 

Then I have a feeling it will work. Because I'm doing the same (without the `window` of course, and it is working for me - at least with SIP.JS 0.17.1)

**Comment by jbreitung** [comment]
Hi, thanks for your reply.

I am using this "window" declaration because I use Vaadin Framework (version 14) to provide the UI. When embedding and using an own JS-File there I have to declare the functions like this to call them from the framework (as far as I know, because non-globally defined functions cannot be called)

If found out something interesting... I made a console log of the delegate I defined. From the const variable I declared before initializing the UA and from the delegate property out of my instanciated UA. Both are printing out the declared delegate I defined.

Why does the logging then output just "{}" when running through the constructor of the UA? I am still searching for the reason why I am not getting any calls to my delegated functions.

Here you can see the logging I wrote about:

```
Creating new UserAgent using options: [object Object]
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | Configuration:
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · allowLegacyNotifications: false
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · authorizationHa1: ""
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · authorizationPassword: NOT SHOWN
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · authorizationUsername: "web1001"
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · autoStart: false
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · autoStop: true
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · delegate: {}
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · displayName: ""
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · forceRport: false
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · hackAllowUnregisteredOptionTags: false
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · hackIpInContact: false
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · hackViaTcp: false
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · hackWssInTransport: false
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · logBuiltinEnabled: true
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · logConfiguration: true
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · logConnector: undefined
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · logLevel: "log"
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · noAnswerTimeout: 60
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · preloadedRouteSet: []
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · reconnectionAttempts: 0
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · reconnectionDelay: 4
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · sessionDescriptionHandlerFactory: (t,r)=>{void 0===e&&(e=Object(i.a)());var n={iceGatheringTimeout:void 0!==(null==r?void 0:r.iceGatheringTimeout)?null==r?void 0:r.iceGatheringTimeout:5e3,peerConnectionConfiguration:Object.assign(Object.assign({},Object(s.a)()),null==r?void 0:r.peerConnectionConfiguration)},o=t.userAgent.getLogger("sip.SessionDescriptionHandler");return new a.a(o,e,n)}
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · sessionDescriptionHandlerFactoryOptions: {}
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · sipExtension100rel: "Unsupported"
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · sipExtensionReplaces: "Unsupported"
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · sipExtensionExtraSupported: []
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · sipjsId: "hrt4m"
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · transportConstructor: o
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · transportOptions: {"server":"wss://**sip.server.ip.address**:8089/ws"}
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · uri: sip:web1001@**sip.server.ip.address**
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · userAgentString: "SIP.js/0.17.1"
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:875 Thu Nov 12 2020 11:30:15 GMT+0100 (Mitteleuropäische Normalzeit) | sip.UserAgent | · viaHost: "b7tb63oapmmo.invalid"
vaadin-bundle-bb8a28e408dde8fce97d.cache.js:2453 UserAgent delegate is: [object Object]
```

(sorry for the many vaadin-bundle-xxxx prefixes...)

The first log line is the one I make before instanciating a new UA and the last line is printing out the instanciated UAs property. When debugging both objects are containing the correct values. The log shows it as "[object Object]".

I am doing the assignment of the delegate for sessions on the same way, also using the global window object. There it works fine and I can execute and control outgoing calls without any problems.

**Comment by slavikbialik** [comment]
Ahhh OK, I've never used this kind of framework so wasn't familiar with it.
But I'm wondering... if you are declaring the functions with `window.functionName`, so maybe you need to configure your delegate like that:
```
        delegate: {
            onConnect: windw.onUAConnect,
            onDisconnect: window.onUADisconnect,
            onInvite: window.onUAInvite,
            onMessage: window.onUAMessage,
            onNotify: window.onUANotify
        }
```

Note that I added a `window.` before the function names.

**Comment by jbreitung** [comment]
After a few days I found out what my problem was. The UserAgent I've initialized was using the "random.invalid" contact header. After adding the viaHost and the hackWssInTransport options to the UserAgentOptions, I got the web phone to work! 

Looks like Asterisk PBX does not like the .invalid in contact headers. But it had not shown me any useful error messages to get to this point...

But, @slavikbialik thanks for your help!

**Comment by slavikbialik** [comment]
> Looks like Asterisk PBX does not like the .invalid in contact headers. But it had not shown me any useful error messages to get to this point...

Oh great! Who would've thought?
I'm using FreeSWITCH, and it has no issues with the contact. Probably Asterisk is more sensitive.
