### ISSUE TITLE
Get the exception when make call to a URI: sip:##102@test.com

### ISSUE THREAD

**Issue by pengweichu** [onsip/SIP.js#877]
**Describe the bug**
When I use SimpleUser.call method to make the call to a URI: sip:##101@test.com, the exception was thrown.

**Logs**
There no logs output for this exception.

**To Reproduce (if possible)**
1. Register to the SIP PBX
2. Make the call to sip:##101@test.com by SimpleUser.call method
3. The exception is throw

**Expected behavior**
Just make the call as normal. Note, make calls to sip:**101@test.com is no problem.

**Observed behavior**
The exception is throw

**Environment Information**
 - Backend Server and version: PortSIP PBX v12.3
 - Browser and version: OS is Windows 10 2004,  Google Chrome version 86.0.4240.198 (Official Build) (64-bit)

**Additional context**

**Comment by seanbright** [comment]
Not a bug, please see my comments on #872
