### ISSUE TITLE
about early media setting invalid

### ISSUE THREAD

**Issue by ifzm** [onsip/SIP.js#885]
Hope to get help from kind people

After I use the early media parameter settings, I don’t know how to transmit to audio playback. Is there an example that I can refer to?

```js
simpleUser.call(`sip:1000@127.0.0.1`, { earlyMedia: true })
```
with the simple settings above, I don't seem to hear a sound after the call :(
should I use event ? eg: https://groups.google.com/g/sip_js/c/0HnzSuKN_wE/m/cCTKWYVZAwAJ

**Comment by egreenmachine** [comment]
Early media will not work with `SimpleUser`. You need to use the full API.

**Comment by ifzm** [comment]
@egreenmachine thank you for taking the time to reply, for the early media settings, do you have any examples you can provide for reference, thank you very much )

**Comment by egreenmachine** [comment]
https://sipjs.com/guides/attach-media/

**Comment by ifzm** [comment]
Thanks )

**Comment by kvsur** [comment]
> Early media will not work with `SimpleUser`. You need to use the full API.

Is SimpleUser support earlyMedia now ？
