### ISSUE TITLE
How to toggle video source during the call

### ISSUE THREAD

**Issue by yashpalsingh6840** [onsip/SIP.js#886]
I have implemented the Video call in my application using **SIP.js** and **SimpleUser** API. 

My requirement is to switch the video source to other camera, like while taking the call from mobile it by default uses the front camera however my application requires user to switch/make the video call from back camera from mobile device.

I assume there will be a way but being new to this library I am not able to find that option. 
Any help will be much appreciated in this regard.

**Comment by egreenmachine** [comment]
You will need to use the full API and probably create a custom SDH. This is not a SIP.js issue but a question which should be directed to our [Google Group](https://groups.google.com/forum/#!forum/sip_js) in the future.
