### ISSUE TITLE
Wrong name of contactOptions/contactParams in release note of sip.js 0.18.0

### ISSUE THREAD

**Issue by jbreitung** [onsip/SIP.js#890]
Hi there, 

for those who used the _hackInWssInTransport_ parameter in the UserAgentOptions and now have to migrate to the new parameter in 0.18.0, be aware of the wrong name of it in the release notes of sip.js 0.18.0!

The release notes say, you have to replace the old _hackInWssInTransport_ parameter with `contactOptions: { transport: "wss" }`. But after trying this out, nothing worked except outgoing calls. After reading the console logs of sip.js I found out why:

The new parameter you have to replace _hackInWssInTransport_ is **NOT named contactOptions**. It is named **contactParams**! So after replacing hackInWssInTransport with `contactParams: { transport: "wss" }` everything will work fine :-)

Just read the release note using **contactParams instead of contactOptions**. For the developers, please update the release note.

Best regards!

**Comment by james-criscuolo** [comment]
Fixed, sorry about that.
