### ISSUE TITLE
No audio using TURN server and answering after several seconds

### ISSUE THREAD

**Issue by Jase3000** [onsip/SIP.js#893]
Hello,
when using a TURN server, if an outgoing call is answered quickly (ie, less than 2 seconds typically) then everything is OK.
But if the call is answered later then there is no audio in either direction.

Asterisk 13 is the backend (configured with the same TURN server)
Most testing done with Firefox, but reproducible with Chrome

ps, jssip works OK for this (but with different problems elsewhere so rather stick with sip.js)

**Comment by egreenmachine** [comment]
This seems like an issue with your set up, not a SIP.js bug. It should be directed at our [google group](https://groups.google.com/g/sip_js). Additionally no good information for determining what the problem actually is has been provided. There is an entire Issue template that outlines all of this, which you had to delete to post this.
