### ISSUE TITLE
Add support for Node.js require

### ISSUE THREAD

**Issue by mhammo** [onsip/SIP.js#895]
**Is your feature request related to a problem? Please describe.**
We're looking to use the API layer from this library for SIP signalling in Node.js, but the ESM exports can't be imported due to the browser specific implementation of `import` used by Node.js. From your FAQ it seems you're open to having support for other platforms.

We'll be overriding the SessionDescriptionHandlers and Transport for Node.js, so we'd just need the library to support `require()` for it to work in Node.js for what we're doing.

**Describe the solution you'd like**
Locally I've made the following changes (mimicking [Redux](https://github.com/reduxjs/redux/blob/master/package.json)'s package.json), and it works on Node.js 14:
- Removed `"type": "module"` from package.json
- Added a tsconfig.json for commonjs which extends `src/tsconfig.json`
- Added a `npm run build-cjs` command, and added this to the `build` script
- Compiled CommonJS output to a `cjs/` folder, and referenced this in the `"main"` property of package.json

Node can then use the common.js provided in `"main"`, and bundlers will pickup the existing `"module"` property for ESM support.
This is the method used by D3, apollo-client, redux and others; I can clean it up and submit a PR.

**Describe alternatives you've considered**
Our app doesn't use a transpiler, and I'd rather avoid adding one to support this module, but we could fork the repo and transpile it ourselves to get around this.

**Additional context**
If you have a preferred way of implementing this, let me know and I can raise a PR.
If you're not interested in having Node.js support out of the box, let me know and we'll look into alternatives.

**Comment by james-criscuolo** [comment]
We currently run sip.js in browser and Node.js environments with no alterations. We have a custom Transport for UDP interfaces, but that is not a hack, SIP.js is built to support it.

I'm curious if there are other alternatives out there for tying together old and new. With Node 10 becoming EOL in a few months, all supported Node versions will work with ESM.

**Comment by james-criscuolo** [comment]
You may want to investigate this: https://www.npmjs.com/package/esm

We used it while transitioning forward, but it's no longer needed. It's a one line fix.

**Comment by mhammo** [comment]
We're using Node 14, but the ESM implementation in Node.js uses URL resolution, so if I try to import the module, it throws the following error:

`Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/mark/git/node/sip-tests/node_modules/sip.js/lib/api' is not supported resolving ES modules imported from /home/mark/git/node/sip-tests/node_modules/sip.js/lib/index.js`

https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_mandatory_file_extensions

Are you using the `--es-module-specifier-resolution=node` to run this without alterations?

**Comment by james-criscuolo** [comment]
No, but we use `--experimental-specifier-resolution=node`.

**Comment by mhammo** [comment]
Thanks for clarifying, it'll work if you enable that experimental flag and then use ESM throughout your project, which I've just tried and I can confirm. Unfortunately we use the default CommonJS module syntax, so this doesn't work in our case.

The solution I listed at the top works with CommonJS and bundlers, though it'd break your own setup if you're using the experimental flag to treat `"main"` as an ESM module in Node.js, so that's a no go.

In practice you'd need to provide .cjs files to enable CommonJS support, which would need something like rollup.
If you're open to using rollup for packaging I can look into creating a PR, but if not we can look at solving this on our end in a forked repo instead.

**Comment by james-criscuolo** [comment]
We do have a webpack'ed version of our repo that we attach to our release page here: https://github.com/onsip/SIP.js/releases

Every release has a `.js` and `.min.js`. If you are going to further bundle, using the non-minified is recommended. Would this fix the situation?

**Comment by james-criscuolo** [comment]
Closing this as I hope the webpack version provides a reasonable workaround.
