### ISSUE TITLE
Codec incompatible

### ISSUE THREAD

**Issue by kim709394** [onsip/SIP.js#899]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).

server: Freeswitch 1.10.2
client A to B:
A:  Google Chrome broswer built with web: SIP.js
B: Bria Android 6.3.4 (a kind of  softphone client )

result:
```
"SIP/2.0 400 Bad Request
Via: SIP/2.0/WS 192.168.0.190;branch=z9hG4bK9223993;received=192.168.0.159;rport=62509
Max-Forwards: 70
From: "1002" <sip:1002@192.168.0.190:5060>;tag=irjp8b21bu
To: <sip:1001@192.168.0.190:5060>;tag=FBgyjK4aKXyDB
Call-ID: vaipsfa18rcqsthq7fk8
CSeq: 874 INVITE
User-Agent: FreeSWITCH-mod_sofia/1.10.5-release.8~64bit
Accept: application/sdp
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
Allow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer
Reason: Q.850;cause=88;text="INCOMPATIBLE_DESTINATION"
Content-Length: 0
Remote-Party-ID: "1001" <sip:1001@192.168.0.190>;party=calling;privacy=off;screen=no
"
```

If client A and client B are the same "Google Chrome broswer built with web sip.js" ,they can build a session successfully.
So i believe the reason of question  "400 Bad Request"   is that codecs of both clients are incompatible.
Can i set the codec of SIP.js ? or how solve this question  ? 
Hope the anwser, Please help, Thanks much!

**Comment by kim709394** [comment]
I checked my Bria account , it only support "G.711u" and "G.711a" .
Could codec of SIP.js support "G.711u" and "G.711a" ?

**Comment by egreenmachine** [comment]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).
