### ISSUE TITLE
Kamailio registration always returns "wrong password"

### ISSUE THREAD

**Issue by antonio-couto** [onsip/SIP.js#901]
Im using Kamailio 5.4 Sip Proxy and using the last version to register and Kamailio returns always wrong password.
Using the old version sip-0.10.0 it works fine, some has information about this problem? .

[v-0.19.0-ERROR.log](https://github.com/onsip/SIP.js/files/5929432/v-0.19.0-ERROR.log)
[v-0.10.0-OK.log](https://github.com/onsip/SIP.js/files/5929433/v-0.10.0-OK.log)

thanks in advance

**Comment by egreenmachine** [comment]
Questions for our [Google Group](https://groups.google.com/forum/#!forum/sip_js)
