### ISSUE TITLE
Inviter can not work on Firefox

### ISSUE THREAD

**Issue by SnowZhang0215** [onsip/SIP.js#908]
**Describe the bug**
I use the demo code to invite someone,it can work well on chrome , but when I run on Firefox 
it can not work. 

**Logs**
TypeError:this. _peerConnection. getTransceiver is not a function

**To Reproduce (if possible)**

**Expected behavior**

**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**

**Comment by SnowZhang0215** [comment]
version 0.19

**Comment by james-criscuolo** [comment]
Logs and version of firefox please.

**Comment by SnowZhang0215** [comment]
Thank you. I update my Firefox. it can work

**Comment by SnowZhang0215** [comment]
good
