### ISSUE TITLE
Allow synchronous unregister on unload-Events

### ISSUE THREAD

**Issue by jbreitung** [onsip/SIP.js#916]
Hi there,

I am currently trying to implement an unregister of the UserAgent when the user closes his browser tab. So I added an "onunload"-Event Listener which calls the Registerer.unregister() function followed by the UA.close() function. On my SIP registrar server (Asterisk PBX) I never receive any unregister messages. The websocket connection just closes apruptly, which causes the SIP peer staying "registered" but just like a half-dead one which will be cleaned up by my registrar after some timeouts. This is no clean behavior...

Does anybody has some ideas to implement a clean unregister on page unload? Or may this be a useful new feature?

Best regards!

**Comment by james-criscuolo** [comment]
Any register process (registering and unregistering use the same messages) involves sending a request, receiving a response, and sending a second request with information from the response. It is asynchronous, there is no way around it. I'd recommend a shorter registration timeout, or force the user to wait on unload (shorter timeout is probably better).

I'm going to close this as I don't think there is anything to be done, but if you'd like to continue the conversation with the community, please make a new topic in our google group.
