### ISSUE TITLE
registered user agent and contact presence

### ISSUE THREAD

**Issue by MarwaAbuEssa** [onsip/SIP.js#917]
hi,
I'm using SIPJS API V19 and I'm trying to get the current registered user agent and other contacts presence 
I found out this example :
https://sipjs.com/api/0.15.0/subscription/subscription/#subscribe

but I can't find subscribe function for the user agent, any help?

**Comment by slavikbialik** [comment]
Not sure what you need... are you looking for how to make a subscription? If so, from 0.16, it's by using the Subscriber object.
https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.subscriber.md

You also have a very good example over there.

**Comment by james-criscuolo** [comment]
Please use our google group for questions.

**Comment by md-riaz** [comment]
`async function subscribeContactExt(contact, account) {
    try {

        // get userAgent from sipAccounts
        const sessionManager = sipAccounts[account.id].sessionManager;

        const userAgent = sessionManager.userAgent;

        // Create a new subscriber.
        const targetURI = new URI("sip", contact.number, account.domain);
        const eventType = "presence";
        const subscriber = new Subscriber(userAgent, targetURI, eventType);

        // Add delegate to handle event notifications.
        subscriber.delegate = {
            onNotify: (notification) => {
                // send a response
                notification.accept();
                // handle notification here
                console.log('Notification received:', notification);
                
                updateContactPresence(contact, notification.request.body);
            },
            onSubscribe: (subscription) => {
                console.log('Subscribed to contact:', contact);
                updateContactPresence(contact, 'subscribed');
            },
            onRefresh: (subscription) => {
                console.log('Refreshed subscription:', contact);
            }
        };

        // Monitor subscription state changes.
        subscriber.stateChange.addListener((newState) => {
            switch (newState) {
                case SubscriptionState.Terminated:
                    console.log('Subscription terminated');
                    updateContactPresence(contact, 'terminated');
                    break;
                case SubscriptionState.Subscribed:
                    console.log('Subscription subscribed');
                    updateContactPresence(contact, 'subscribed');
                    break;
                case SubscriptionState.NotifyWait:
                    console.log('Subscription notify wait');
                    updateContactPresence(contact, 'notify wait');
                    break;
                default:
                    console.log('Subscription state changed:', newState);
                    break;
            }
        });

        // Attempt to establish the subscription
        await subscriber.subscribe();

        // add subscriber to subscription
        sipAccounts[account.id].subscribers[contact.number] = subscriber;

        console.log('Subscription established:', contact.number);
    

    } catch (error) {
        console.error('Error subscribing to contact:', error);
    }
}`

after running this code i only get,
console.log('Subscription notify wait');

console.log('Subscription established:', contact.number);

and after sometime, 
console.log('Subscription terminated');

does this work with userAgent of sessionManager?
