### ISSUE TITLE
CANCEL message as response to incoming invitation accept not handling

### ISSUE THREAD

**Issue by iHateYourGlasses** [onsip/SIP.js#918]
Sometimes after 200 ok message sent on incoming invite i get this message from server in response:

CANCEL sip:3edud8lj@ip_was_here;transport=ws SIP/2.0
Via: SIP/2.0/WSS ip_was_here;branch=z9hG4bKfd66.53b9ae163d82233c5f5c6a0253e543b0.1
From: <sip:ip_was_here>;tag=269f42b3-b8fa-4a5d-b3b8-d6561d2946b6
To: <sip:ip_was_here>
Call-ID: f30b30d6-ffa6-439e-95ed-3f8dc18fc95a
CSeq: 3519 CANCEL
Max-Forwards: 69
Content-Length: 0
Reason: SIP;cause=200;text="Call completed elsewhere"

but it seems like sip.js ignores this message and continues to try to get ACK response with this message in logger:

SIP.js log: No ACK for 2xx response received, attempting retransmission;  sip.invite-dialog  No ACK for 2xx response received, attempting retransmission

and eventually ends with this message

SIP.js debug: Timer L expired for INVITE server transaction z9hG4bK1e05.e1f0547826bca51d23b9d1b212583707.1.;  sip.transaction.ist z9hG4bK1e05.e1f0547826bca51d23b9d1b212583707.1 Timer L expired for INVITE server transaction z9hG4bK1e05.e1f0547826bca51d23b9d1b212583707.1.

Here's how it looks in browser WS debug tool. Obviously, sip should not try to resend 200 OK after CANCEL message from server, but for some reason it just keeps trying despite of CANCEL message

![image](https://user-images.githubusercontent.com/14814468/112025098-e3748280-8b45-11eb-8451-769937a3f744.png)

**Full logs:** 

SIP.js debug: Constructing INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Constructing INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js log: Invitation.progress;  sip.Invitation  Invitation.progress

SIP.js debug: Constructing INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Constructing INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js log: Invitation.progress;  sip.Invitation  Invitation.progress

 SIP.js log: INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 constructed;  sip.invite-dialog  INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 constructed

 SIP.js log: Invitation.accept;  sip.Invitation  Invitation.accept

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Establishing;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Establishing

 SIP.js debug: SessionDescriptionHandler.constructor;  sip.SessionDescriptionHandler  SessionDescriptionHandler.constructor

 SIP.js debug: SessionDescriptionHandler.initPeerConnectionEventHandlers;  sip.SessionDescriptionHandler  SessionDescriptionHandler.initPeerConnectionEventHandlers

 SIP.js debug: SessionDescriptionHandler.hasDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.hasDescription

 SIP.js debug: SessionDescriptionHandler.setDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setDescription

 SIP.js debug: SessionDescriptionHandler.getLocalMediaStream;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getLocalMediaStream

 SIP.js log: Connecting ;  sip.Transport  Connecting 

 SIP.js debug: SessionDescriptionHandler.setLocalMediaStream;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setLocalMediaStream

 SIP.js debug: SessionDescriptionHandler.setLocalMediaStream - adding sender audio track;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setLocalMediaStream - adding sender audio track

 SIP.js debug: SessionDescriptionHandler.applyModifiers;  sip.SessionDescriptionHandler  SessionDescriptionHandler.applyModifiers

 SIP.js debug: SessionDescriptionHandler.setRemoteSessionDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteSessionDescription

 SIP.js debug: SessionDescriptionHandler.onsignalingstatechange have-remote-offer;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onsignalingstatechange have-remote-offer

 SIP.js debug: SessionDescriptionHandler.ontrack audio enabled;  sip.SessionDescriptionHandler  SessionDescriptionHandler.ontrack audio enabled

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack - adding remote audio track;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack - adding remote audio track

 SIP.js debug: SessionDescriptionHandler.ontrack video enabled;  sip.SessionDescriptionHandler  SessionDescriptionHandler.ontrack video enabled

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack - adding remote video track;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack - adding remote video track

 SIP.js debug: SessionDescriptionHandler.getDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getDescription

 SIP.js debug: SessionDescriptionHandler.getLocalMediaStream;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getLocalMediaStream

 SIP.js debug: SessionDescriptionHandler.createLocalOfferOrAnswer - creating SDP answer;  sip.SessionDescriptionHandler  SessionDescriptionHandler.createLocalOfferOrAnswer - creating SDP answer

 SIP.js debug: SessionDescriptionHandler.applyModifiers;  sip.SessionDescriptionHandler  SessionDescriptionHandler.applyModifiers

 SIP.js debug: SessionDescriptionHandler.setLocalSessionDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setLocalSessionDescription

 SIP.js debug: SessionDescriptionHandler.onsignalingstatechange stable;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onsignalingstatechange stable

 SIP.js debug: SessionDescriptionHandler.waitForIceGatheringToComplete;  sip.SessionDescriptionHandler  SessionDescriptionHandler.waitForIceGatheringToComplete

 SIP.js debug: SessionDescriptionHandler.waitForIceGatheringToComplete - timeout in 5000;  sip.SessionDescriptionHandler  SessionDescriptionHandler.waitForIceGatheringToComplete - timeout in 5000

 SIP.js debug: SessionDescriptionHandler.onicegatheringstatechange gathering;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicegatheringstatechange gathering

 SIP.js debug: SessionDescriptionHandler.oniceconnectionstatechange checking;  sip.SessionDescriptionHandler  SessionDescriptionHandler.oniceconnectionstatechange checking
4
 SIP.js debug: SessionDescriptionHandler.onicecandidate;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicecandidate

 SIP.js debug: SessionDescriptionHandler.onconnectionstatechange connecting;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onconnectionstatechange connecting
 SIP.js debug: SessionDescriptionHandler.oniceconnectionstatechange connected;  sip.SessionDescriptionHandler  SessionDescriptionHandler.oniceconnectionstatechange connected

 SIP.js debug: SessionDescriptionHandler.onicegatheringstatechange complete;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicegatheringstatechange complete

 SIP.js debug: SessionDescriptionHandler.iceGatheringComplete;  sip.SessionDescriptionHandler  SessionDescriptionHandler.iceGatheringComplete

 SIP.js debug: SessionDescriptionHandler.iceGatheringComplete - clearing timeout;  sip.SessionDescriptionHandler  SessionDescriptionHandler.iceGatheringComplete - clearing timeout

 SIP.js debug: SessionDescriptionHandler.iceGatheringComplete - resolving promise;  sip.SessionDescriptionHandler  SessionDescriptionHandler.iceGatheringComplete - resolving promise

 SIP.js debug: SessionDescriptionHandler.getLocalSessionDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getLocalSessionDescription

 SIP.js debug: State change to "Accepted" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 State change to "Accepted" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Established;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Established

 SIP.js debug: SessionDescriptionHandler.onicecandidate;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicecandidate

 SIP.js debug: SessionDescriptionHandler.onconnectionstatechange connected;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onconnectionstatechange connected

 SIP.js log: No ACK for 2xx response received, attempting retransmission;  sip.invite-dialog  No ACK for 2xx response received, attempting retransmission

 SIP.js log: Connecting ;  sip.Transport  Connecting 

 SIP.js log: No ACK for 2xx response received, attempting retransmission;  sip.invite-dialog  No ACK for 2xx response received, attempting retransmission

 SIP.js debug: Timer L expired for INVITE server transaction z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Timer L expired for INVITE server transaction z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js debug: Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js debug: State change to "Terminated" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 State change to "Terminated" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js debug: Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js log: Invitation.onAckTimeout;  sip.Invitation  Invitation.onAckTimeout

 SIP.js log: No ACK received for an extended period of time, terminating session;  sip.Invitation  No ACK received for an extended period of time, terminating session

 SIP.js log: INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 sending BYE request;  sip.invite-dialog  INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 sending BYE request

 SIP.js debug: Constructing non-INVITE client transaction with id z9hG4bK1142919.;  sip.transaction.nict z9hG4bK1142919 Constructing non-INVITE client transaction with id z9hG4bK1142919.

 SIP.js log: INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 destroyed;  sip.invite-dialog  INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 destroyed

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Terminated;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Terminated

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 in state Terminated is being disposed;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 in state Terminated is being disposed

 SIP.js debug: SessionDescriptionHandler.close;  sip.SessionDescriptionHandler  SessionDescriptionHandler.close SIP.js log: INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 constructed;  sip.invite-dialog  INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 constructed

 SIP.js log: Invitation.accept;  sip.Invitation  Invitation.accept

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Establishing;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Establishing

 SIP.js debug: SessionDescriptionHandler.constructor;  sip.SessionDescriptionHandler  SessionDescriptionHandler.constructor

 SIP.js debug: SessionDescriptionHandler.initPeerConnectionEventHandlers;  sip.SessionDescriptionHandler  SessionDescriptionHandler.initPeerConnectionEventHandlers

 SIP.js debug: SessionDescriptionHandler.hasDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.hasDescription

 SIP.js debug: SessionDescriptionHandler.setDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setDescription

 SIP.js debug: SessionDescriptionHandler.getLocalMediaStream;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getLocalMediaStream

 SIP.js log: Connecting ;  sip.Transport  Connecting wss

 SIP.js debug: SessionDescriptionHandler.setLocalMediaStream;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setLocalMediaStream

 SIP.js debug: SessionDescriptionHandler.setLocalMediaStream - adding sender audio track;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setLocalMediaStream - adding sender audio track

 SIP.js debug: SessionDescriptionHandler.applyModifiers;  sip.SessionDescriptionHandler  SessionDescriptionHandler.applyModifiers

 SIP.js debug: SessionDescriptionHandler.setRemoteSessionDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteSessionDescription

 SIP.js debug: SessionDescriptionHandler.onsignalingstatechange have-remote-offer;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onsignalingstatechange have-remote-offer

 SIP.js debug: SessionDescriptionHandler.ontrack audio enabled;  sip.SessionDescriptionHandler  SessionDescriptionHandler.ontrack audio enabled

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack - adding remote audio track;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack - adding remote audio track

 SIP.js debug: SessionDescriptionHandler.ontrack video enabled;  sip.SessionDescriptionHandler  SessionDescriptionHandler.ontrack video enabled

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack

 SIP.js debug: SessionDescriptionHandler.setRemoteTrack - adding remote video track;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setRemoteTrack - adding remote video track

 SIP.js debug: SessionDescriptionHandler.getDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getDescription

 SIP.js debug: SessionDescriptionHandler.getLocalMediaStream;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getLocalMediaStream

 SIP.js debug: SessionDescriptionHandler.createLocalOfferOrAnswer - creating SDP answer;  sip.SessionDescriptionHandler  SessionDescriptionHandler.createLocalOfferOrAnswer - creating SDP answer

 SIP.js debug: SessionDescriptionHandler.applyModifiers;  sip.SessionDescriptionHandler  SessionDescriptionHandler.applyModifiers

 SIP.js debug: SessionDescriptionHandler.setLocalSessionDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.setLocalSessionDescription

 SIP.js debug: SessionDescriptionHandler.onsignalingstatechange stable;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onsignalingstatechange stable

 SIP.js debug: SessionDescriptionHandler.waitForIceGatheringToComplete;  sip.SessionDescriptionHandler  SessionDescriptionHandler.waitForIceGatheringToComplete

 SIP.js debug: SessionDescriptionHandler.waitForIceGatheringToComplete - timeout in 5000;  sip.SessionDescriptionHandler  SessionDescriptionHandler.waitForIceGatheringToComplete - timeout in 5000

 SIP.js debug: SessionDescriptionHandler.onicegatheringstatechange gathering;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicegatheringstatechange gathering

 SIP.js debug: SessionDescriptionHandler.oniceconnectionstatechange checking;  sip.SessionDescriptionHandler  SessionDescriptionHandler.oniceconnectionstatechange checking

 SIP.js debug: SessionDescriptionHandler.onicecandidate;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicecandidate

 SIP.js debug: SessionDescriptionHandler.onconnectionstatechange connecting;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onconnectionstatechange connecting

 SIP.js debug: SessionDescriptionHandler.oniceconnectionstatechange connected;  sip.SessionDescriptionHandler  SessionDescriptionHandler.oniceconnectionstatechange connected

 SIP.js debug: SessionDescriptionHandler.onicegatheringstatechange complete;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicegatheringstatechange complete

 SIP.js debug: SessionDescriptionHandler.iceGatheringComplete;  sip.SessionDescriptionHandler  SessionDescriptionHandler.iceGatheringComplete

 SIP.js debug: SessionDescriptionHandler.iceGatheringComplete - clearing timeout;  sip.SessionDescriptionHandler  SessionDescriptionHandler.iceGatheringComplete - clearing timeout

 SIP.js debug: SessionDescriptionHandler.iceGatheringComplete - resolving promise;  sip.SessionDescriptionHandler  SessionDescriptionHandler.iceGatheringComplete - resolving promise

 SIP.js debug: SessionDescriptionHandler.getLocalSessionDescription;  sip.SessionDescriptionHandler  SessionDescriptionHandler.getLocalSessionDescription

 SIP.js debug: State change to "Accepted" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 State change to "Accepted" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Established;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Established

 SIP.js debug: SessionDescriptionHandler.onicecandidate;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onicecandidate

 SIP.js debug: SessionDescriptionHandler.onconnectionstatechange connected;  sip.SessionDescriptionHandler  SessionDescriptionHandler.onconnectionstatechange connected

 SIP.js log: No ACK for 2xx response received, attempting retransmission;  sip.invite-dialog  No ACK for 2xx response received, attempting retransmission

 SIP.js log: Connecting  sip.Transport  Connecting

 SIP.js log: No ACK for 2xx response received, attempting retransmission;  sip.invite-dialog  No ACK for 2xx response received, attempting retransmission

 SIP.js debug: Timer L expired for INVITE server transaction z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Timer L expired for INVITE server transaction z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js debug: Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js debug: State change to "Terminated" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 State change to "Terminated" on INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js debug: Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.;  sip.transaction.ist z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1 Destroyed INVITE server transaction with id z9hG4bK7067.6666761a7b8cd79e144c23563f08e27a.1.

 SIP.js log: Invitation.onAckTimeout;  sip.Invitation  Invitation.onAckTimeout

 SIP.js log: No ACK received for an extended period of time, terminating session;  sip.Invitation  No ACK received for an extended period of time, terminating session

 SIP.js log: INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 sending BYE request;  sip.invite-dialog  INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 sending BYE request

 SIP.js debug: Constructing non-INVITE client transaction with id z9hG4bK1142919.;  sip.transaction.nict z9hG4bK1142919 Constructing non-INVITE client transaction with id z9hG4bK1142919.

 SIP.js log: INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 destroyed;  sip.invite-dialog  INVITE dialog 0c9727d0-5947-4b8f-89c1-dc72d20ce738pjiklk0jit6f50db65-dd9d-42df-913c-a6117a9e5a46 destroyed

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Terminated;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 transitioned to state Terminated

 SIP.js log: Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 in state Terminated is being disposed;  sip.Invitation  Session 0c9727d0-5947-4b8f-89c1-dc72d20ce7386f50db65-dd9d-42df-913c-a6117a9e5a46 in state Terminated is being disposed

 SIP.js debug: SessionDescriptionHandler.close;  sip.SessionDescriptionHandler  SessionDescriptionHandler.close

**Comment by james-criscuolo** [comment]
Is there a reason your server is ignoring the 200 OK? I think the far side should be able to ACK and BYE, but I'd have to check the RFC. I am unsure if we are out of spec here or not.

**Comment by iHateYourGlasses** [comment]
> Is there a reason your server is ignoring the 200 OK?

Server does not ignore it -  the very reason of CANCEL response to 200 OK is another user(s) accepting this invite at the same time - it causes ACK response to this user and CANCEL response to all others.

**Comment by james-criscuolo** [comment]
https://tools.ietf.org/html/rfc3261#section-9.2

Specifically:
>   If the transaction  for the original request still exists, the behavior of the UAS on
   receiving a CANCEL request depends on whether it has already sent a
   final response for the original request.  If it has, the CANCEL
   request has no effect on the processing of the original request, no
   effect on any session state, and no effect on the responses generated
   for the original request.  If the UAS has not issued a final response
   for the original request, its behavior depends on the method of the
   original request.  If the original request was an INVITE, the UAS
   SHOULD immediately respond to the INVITE with a 487 (Request
   Terminated).  A CANCEL request has no impact on the processing of
   transactions with any other method defined in this specification.

So it appears your server should be doing something else, we are correctly ignoring the CANCEL.
