### ISSUE TITLE
Double Subscribe Request at the same message Request

### ISSUE THREAD

**Issue by MarwaAbuEssa** [onsip/SIP.js#920]
Hi,

I'm using SIPJS 20 and implementing contact presence as at the following link

https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.subscriber.md

everything worked perfect except that some times , the asterisk server response with error causing unregister of agent , when i used wireshark to follow the error i found out double subscribe request at the same sip request . as found at the following image

![image](https://user-images.githubusercontent.com/7272394/113034059-fa445600-9191-11eb-8e72-b142ce786310.png)

I don't know why and how this occurs all what the code doing is a simple loop for my contacts extensions to subscribe to their presence and it is working although that suddenly my  user agent getting registered due to the above error . i tried to set 100 millisecond timeout between every subscribe request for each extension but still got the error randomly . any help Please about the error ?

**Comment by james-criscuolo** [comment]
They are likely just getting auth'ed, but. a full sip trace would confirm.

**Comment by MarwaAbuEssa** [comment]
Hi @james-criscuolo  thanks for your reply. what do you means by auth'ed ? unfortunately when this case happens the asterisk server responds with an error and stop the user agent connection and registration that's why I don't have a sip trace and traced it with Wireshark but I can try to send you the details of sip corrupted SUBSCRBE message

**Comment by james-criscuolo** [comment]
If you could post the pcap from the wireshark, that's a full sip trace.

**Comment by MarwaAbuEssa** [comment]
Hi James ,

I sent you a full sip trace from Wireshark to your email , your help is appreciated 

Thanks

**Comment by MarwaAbuEssa** [comment]
hi @james-criscuolo ,

I sent you the full sip trace on email , i hope you have time to see it.
 
I made a small modification at my code . the subscriptions of extension's presence will start at onConnect event of user agent 

`onConnect(){
	if(this.userAgent.state === UserAgentState.Started){
	this.subscribeAllPresence();  
}` 

instead of registrar state change to registered  (this is the old code 👎 )

`this.registerer.stateChange.addListener((registerState) => {
           switch (registerState) {
                  case RegistererState.Registered: 
                    this.subscribeAllPresence(); 
                  break;
               }  
         });`


and unsubscribe  at the onDiconnect event

`onDisconnect(error:Error){
	 this.unSubscribeAllPresence();
}`

also I set the following values for useragent to reconnect upon connection drops

 connectionTimeout: 10, 
 maxReconnectionAttempts:240 ,
 reconnectionTimeout: 15


the double SUBSCRIBE requests is much less after these changes but it still happens sometimes . 

I confirm I'm still use  the subscriber as at the following link : https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.subscriber.md 

the only difference that onNotify function I'm adding  ` notification.accept();` then processing the request data to get the presence notification which is working successfully if the double SUBSRIBE request didn't happened .

any help about the double SUBSCRIBE request ?any recommendations about best practices to start the subscription or end it ?

Thanks in advance,
Marwa

**Comment by slachtar** [comment]
Hello,
@MarwaAbuEssa: Have you fixed this issue?
I'm facing the same problem using sipjs latest 0.20.0. 
The subscription goes correctly, but after few times another subscription is issued automatically but with empty content.
Thanks

**Comment by MarwaAbuEssa** [comment]
Hi @slachtar ,

sorry for the late reply, you need to ensure that you have only one instance of user agent during your app running and ensure on websocket disconnect and reconnect again to re-send your subscriptions again if it is terminated. 

I hope this help ,
Thanks

**Comment by md-riaz** [comment]
`async function subscribeContactExt(contact, account) {
    try {

        // get userAgent from sipAccounts
        const sessionManager = sipAccounts[account.id].sessionManager;

        const userAgent = sessionManager.userAgent;

        // Create a new subscriber.
        const targetURI = new URI("sip", contact.number, account.domain);
        const eventType = "presence";
        const subscriber = new Subscriber(userAgent, targetURI, eventType);

        // Add delegate to handle event notifications.
        subscriber.delegate = {
            onNotify: (notification) => {
                // send a response
                notification.accept();
                // handle notification here
                console.log('Notification received:', notification);
                
                updateContactPresence(contact, notification.request.body);
            },
            onSubscribe: (subscription) => {
                console.log('Subscribed to contact:', contact);
                updateContactPresence(contact, 'subscribed');
            },
            onRefresh: (subscription) => {
                console.log('Refreshed subscription:', contact);
            }
        };

        // Monitor subscription state changes.
        subscriber.stateChange.addListener((newState) => {
            switch (newState) {
                case SubscriptionState.Terminated:
                    console.log('Subscription terminated');
                    updateContactPresence(contact, 'terminated');
                    break;
                case SubscriptionState.Subscribed:
                    console.log('Subscription subscribed');
                    updateContactPresence(contact, 'subscribed');
                    break;
                case SubscriptionState.NotifyWait:
                    console.log('Subscription notify wait');
                    updateContactPresence(contact, 'notify wait');
                    break;
                default:
                    console.log('Subscription state changed:', newState);
                    break;
            }
        });

        // Attempt to establish the subscription
        await subscriber.subscribe();

        // add subscriber to subscription
        sipAccounts[account.id].subscribers[contact.number] = subscriber;

        console.log('Subscription established:', contact.number);
    

    } catch (error) {
        console.error('Error subscribing to contact:', error);
    }
}`

after running this code i only get,
console.log('Subscription notify wait');

console.log('Subscription established:', contact.number);

and after sometime, 
console.log('Subscription terminated');

does this work with userAgent of sessionManager?
