### ISSUE TITLE
Provide Documentation for Subscribing to SIP.JS messages

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [onsip/SIP.js#922]
**Is your feature request related to a problem? Please describe.**

My problem is I'm trying to write a SIP.JS test harness to understand the library before I use it in my job. My job will require me to implement SIP.JS with basic messaging functionality. 

**Describe the solution you'd like**
For the record, here is my post in the Google Group: https://groups.google.com/g/sip_js/c/6ldpU1uu1E8 . No updates or comments. I am looking for a way to subscribe to SIP.JS messages. There are guides on how to send messages: https://sipjs.com/guides/send-message/ . However, there is no guide on how to receive messages. Previously, there was documentation on this: https://sipjs.com/api/0.15.0/message/. However, this has been removed of the Github documentation. The Github documentation does not seem to have any guide for subscribing to messages. I would like there to be a guide on receiving messages. 

**Describe alternatives you've considered**

There is ample documentation on the Subscriber class: https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.subscriber.md . This is going to be helpful in other aspects of the application, but there doesn't seem to be a `message` event type.

**Additional context**

If you could also comment the solution on this ticket that would be great. I know this isn't exactly the place for a request like this. However, I have looked through the documentation and asked the google group with no real success. I also found this link: https://github.com/onsip/SIP.js/blob/0.16.0/docs/migration-0.15-0.16.md which references subscribing to messages via the session but still doesn't really tell you how. I'm out of options that doesn't involve putting in a ticket.

**Comment by james-criscuolo** [comment]
Messages are not event based, so it makes sense that the subscriber wouldn't have it. You are looking for onMessage of the UserAgentDelegate: https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.useragentdelegate.onmessage.md

**Comment by JustAnotherSoftwareDeveloper** [comment]
Thanks!
