### ISSUE TITLE
Echo Test Not Working For Both Audio and Video

### ISSUE THREAD

**Issue by ihartzell** [onsip/SIP.js#923]
Hello,

I have been following the SimpleUser guide, and I'm trying to issue an echo test. I have an options object which is of type SimpleUserOptions, and I have the constraints property under the media property, and when I set the audio: true, and the video: false I will hear the whole "You are about to enter an echo test..." voice prompt.

The issue is when I set both of those properties to true, I won't hear the voice prompt. A local video will appear, and then after about 15 seconds the remote video will appear and I can see myself testing echoing voice and video. It's almost like for some reason when video and audio are both set to true for some reason the voice prompt doesn't happen, and I need that to happen for a proper echo test.

**Comment by ihartzell** [comment]
Why was this invalid?

**Comment by egreenmachine** [comment]
You did not follow the template for a bug report. And did not provide any useful information for a bug report.

However, I believe this is a question that should be directed at our [google group](https://groups.google.com/g/sip_js).
