### ISSUE TITLE
Compile issue using npm on windows

### ISSUE THREAD

**Issue by gbfarah** [onsip/SIP.js#925]
When running npm run build-and-test. Error below is encountered... Appears to assume linux flavoured build machine

cp dist/sip.js dist/sip-$npm_package_version.js && cp dist/sip.min.js dist/sip-$npm_package_version.min.js

> sip.js@0.20.0 copy-dist-files C:\temp\SIPJS_latest\SIP.js
> cp dist/sip.js dist/sip-$npm_package_version.js && cp dist/sip.min.js dist/sip-$npm_package_version.min.js

'cp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sip.js@0.20.0 copy-dist-files: `cp dist/sip.js dist/sip-$npm_package_version.js && cp dist/sip.min.js dist/sip-$npm_package_version.min.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sip.js@0.20.0 copy-dist-files script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by james-criscuolo** [comment]
Yes, our build is currently *nix. If you are just using this as a dependency, you can install via npm.

**Comment by seanbright** [comment]
https://github.com/onsip/SIP.js/pull/516

**Comment by john-e-riordan** [comment]
Hi,

We are doing dev in *nix environment currently. #516 is likely perhaps helpful if you must. Not sure what it would take to support Windows as development environment, but it's a very low priority at the moment as given the resources we have we don't want to add maintaining an alternative windows dev environment to the list. So gonna close this.

Thanks and regards,

John
