### ISSUE TITLE
Allow deterministic termination of ICE gathering process

### ISSUE THREAD

**Issue by dixoncb** [onsip/SIP.js#929]
I want to move on from ICE gathering as soon as I have a viable srflx or relay candidate. My PC has multiple IP addresses and a connection to a Kamailio proxy takes around 8 seconds before ICE gathering is complete. 

I'd like to be able to inspect the latest ICE candidate and, if it meets my needs, to move on to SDP generation immediately. 

Setting timeout seems a little arbitrary. I'd like to know the moment I have a suitable route. I've prepared a PR which implements this feature, and my connection time is reduced to around 2 seconds. I think it would be helpful in most similar use cases. 

This would be my first PR, so please let me know if it's suitable for the project.

**Comment by ffdixon** [comment]
Would you be willing to share the PR with others -- we're using sip.js in the [BigBlueButton](https://github.com/bigbluebutton/bigbluebutton) project and would like to speed up connectivity as well.

**Comment by etamme** [comment]
Im guessing this is his branch https://github.com/dixoncb/SIP.js/tree/feature/fasterICE

**Comment by clshortfuse** [comment]
This works fine:

````js
  call.delegate = {
    onSessionDescriptionHandler: (sdh) => {
      sdh.peerConnectionDelegate = {
        onicecandidate: (event) => {
          if (event.candidate?.type === 'srflx') {
            sdh.iceGatheringComplete();
          }
        },
      };
    },
  };
````

But I'd be concerned about breaking changes. `peerConnectionDelegate` isn't stable in the API, nor is `iceGatheringComplete()`

https://github.com/onsip/SIP.js/blob/5555a9811f33df1f1461c9094a59b82307b25405/docs/session-description-handler/sip.js.sessiondescriptionhandler.peerconnectiondelegate.md

**Comment by john-e-riordan** [comment]
@dixoncb - yes setting a timeout is arbitrary
@clshortfuse - yes your approach is a valid

`iceGatherComplete()` is currently `protected` which is an issue
perhaps `iceGatherComplete()` should be `public`?
perhaps another alternative to timeout?

**Comment by clshortfuse** [comment]
I meant this:

https://github.com/onsip/SIP.js/blob/b26885ce24a5788dd3f3db45f726c93e6b7b3763/src/platform/web/session-description-handler/session-description-handler.ts#L127-L138

I read it as that we (users) are not supposed to directly interface with `peerConnectionDelegate`. But I could be misreading the remarks. The remarks might be comment explaining/justifying why the getter exists to implementers, not for us users. Warnings about directly interfacing with a class should appear the class, not at the properly used delegate. You don't see the warning until you actually use the delegate, making it possibly confusing.

If that is the case, then `iceGatherComplete()` being public would probably be enough. Users can code their own timeout.

**Comment by john-e-riordan** [comment]
I see the confusion... the remarks are intended to be read as "By all means please use this delegate to get access to the peer connection events instead of adding your own handlers to the peer connection." But I can see how they appear to be a warning and scare people away from using the delegate which exactly the opposite of what is intended.

I've fixed the remarks so make it clear that delegate is what we want users to use.
And I've made`iceGatheringComplete()` public, which I agree should then allow users to code their own strategy.

**Comment by clshortfuse** [comment]
Looks good! 

Perhaps, "ICE gathering completion strategy" instead of "ICE gathering "timeout" strategy" because users can signal complete based on a received candidate as well.

**Comment by john-e-riordan** [comment]
Will update the comment (thanks for wording suggestion) and get it up on main branch.

Will go out with next release.

Thank you!
