### ISSUE TITLE
Where are the options on the doc page?

### ISSUE THREAD

**Issue by evandrocoan** [onsip/SIP.js#931]
Going at the GitHub index I can find them:

![image](https://user-images.githubusercontent.com/5332158/119370912-3c6aaf00-bc8c-11eb-8848-aac2445208c8.png)

But why they are not on the page itself?

https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.registererregisteroptions.md

![image](https://user-images.githubusercontent.com/5332158/119370872-2f4dc000-bc8c-11eb-8e19-f64e34121d67.png)

Why split the documentation over so many small pages which does not link everything? This documentation is quite bad. I am not criticizing the contents, but the organization. So many quite small pages make things really hard to find.

But out of topic, it would be nice to have small usage examples as this other documentation does: https://www.doubango.org/sipml5/docgen/symbols/SIPml.Stack.html#newSession

![image](https://user-images.githubusercontent.com/5332158/119371417-c9156d00-bc8c-11eb-8534-b714801d30ac.png)

That other documentation also has a problem which splitting things into several pages making things harder to find, but it has much less pages than this documentation. It has about 10 pages, which is tangible to open all in the browser and search for what I am looking for.

**Comment by evandrocoan** [comment]
I think I just found a page with the options: https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.registereroptions.md
![image](https://user-images.githubusercontent.com/5332158/119373682-0ed33500-bc8f-11eb-8347-448795a9e7b1.png)

But again, that page links to several small pages with only few lines each. This make really harder to search for something.

Instead of opening each option on its own page, you can create an anchor on the own options page.

**Comment by evandrocoan** [comment]
This would significantly reduce the number of pages and would be quite an improvement for what it is today.

My in opinion, everything should be in a single page with anchors (and summary).

But beginning by putting things like the RegistererOptions options on the same page with anchors to each item, would be great first improvement.

**Comment by evandrocoan** [comment]
It is hard to find stuff when there are quite large number of pages to open because I do not know nothing about this project. Then, I have to read everything. And most important, re-read the same thing several times. So, if everything is scattered into countless pages, I have to open countless browser tabs, to keep track of each thing, but with so many small pages, it is not possible to open that many browser tabs because I would not know which one is what. 

On the contrary, if there are a handset of pages to open and read, I can keep track of them and keep they open on the browser.

If you wonder, in case I need to read two different places in the same page, I can open two browser tabs into the same page.

**Comment by egreenmachine** [comment]
The docs are generated automatically using https://www.npmjs.com/package/@microsoft/api-documenter. If you want to improve them we would happily take a PR.

**Comment by john-e-riordan** [comment]
Better documentation is always good to have. The docs are autogenerated at the moment. If you want to improve them we would happily take a PR.
