### ISSUE TITLE
Why add Date to the log prefix?

### ISSUE THREAD

**Issue by evandrocoan** [onsip/SIP.js#933]
```diff
 static/js/sip.js | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/static/js/sip.js b/static/js/sip.js
index b1d9dbe..302d33a 100644
--- a/static/js/sip.js
+++ b/static/js/sip.js
@@ -9428,7 +9428,8 @@ class LoggerFactory {
     print(levelToLog, category, label, content) {
         if (typeof content === "string") {
             // eslint-disable-next-line @typescript-eslint/no-explicit-any
-            const prefix = [new Date(), category];
+            const prefix = [category];
             if (label) {
                 prefix.push(label);
             }
-- 
2.25.1
```

Both chrome and firefox have an option to enable timespant on the logs. 

1. ![image](https://user-images.githubusercontent.com/5332158/119750619-1aca1d00-be70-11eb-88ed-aa82a446b71c.png)

1. ![image](https://user-images.githubusercontent.com/5332158/119750658-26b5df00-be70-11eb-8427-48df00db1a03.png)

This date prefix is quite big, and it does not help by creating much longer log lines.
```js
Wed May 26 2021 22:21:27 GMT-0300 (Brasilia Standard Time) | sip.Transport | Received WebSocket text message:

// vs builtin chrome/firefox timestamp which shows milliseconds

22:21:56.841 sip.Transport | Received WebSocket text message:
```

**Comment by egreenmachine** [comment]
Logger can be overridden https://github.com/onsip/SIP.js/blob/master/docs/api/sip.js.useragent.getloggerfactory.md

To answer the question we have found it helpful in our case for capturing log files from clients. Additionally, it is difficult enough to get people to provide logs as is. The times can be helpful when debugging issues and getting people to enable timestamps is just another step they wont do. I think we are going to leave this on by default for the time being.
