### ISSUE TITLE
UserAgent EarlyMedia Issue

### ISSUE THREAD

**Issue by 7i77an** [onsip/SIP.js#937]
**Describe the bug**
In outgoing calls I need to listen to the early media audio.
After configuring early media using the UserAgent api, it always returns a 403.

**Logs**
https://gist.github.com/7i77an/d83d145a8658d7866f61e9542c90f532

**To Reproduce (if possible)**
The InviterInviteOptions  is:

		var InviterInviteOptions = {
		  requestDelegate: {
		    onAccept: (response) => {
		      console.log("Positive response = " + response);
		    },
		    onReject: (response) => {
		      console.log("Negative response = " + response);
		    }
		  },
		  earlyMedia : true,
		  sessionDescriptionHandlerOptions: {
		    constraints: {
		      audio: true,
		      video: false
		    }
		  }
		};

**Comment by 7i77an** [comment]
I'm test https://github.com/InnovateAsterisk/Browser-Phone and hear ok early media (use old version sipjs => 0.11.6)

In the onprogress event have a hack:

    session.on('progress', function (response) {
        // Provisional 1xx
        if(response.status_code == 100){
            $(MessageObjId).html(lang.trying);
        }
        else if(response.status_code == 180){
            $(MessageObjId).html(lang.ringing);
            
            var soundFile = audioBlobs.EarlyMedia_European;
            if(UserLocale().indexOf("us") > -1) soundFile = audioBlobs.EarlyMedia_US;
            if(UserLocale().indexOf("gb") > -1) soundFile = audioBlobs.EarlyMedia_UK;
            if(UserLocale().indexOf("au") > -1) soundFile = audioBlobs.EarlyMedia_Australia;
            if(UserLocale().indexOf("jp") > -1) soundFile = audioBlobs.EarlyMedia_Japan;

            // Play Early Media
            console.log("Audio:", soundFile.url);
            var earlyMedia = new Audio(soundFile.blob);
            earlyMedia.preload = "auto";
            earlyMedia.loop = true;
            earlyMedia.oncanplaythrough = function(e) {
                if (typeof earlyMedia.sinkId !== 'undefined' && getAudioOutputID() != "default") {
                    earlyMedia.setSinkId(getAudioOutputID()).then(function() {
                        console.log("Set sinkId to:", getAudioOutputID());
                    }).catch(function(e){
                        console.warn("Failed not apply setSinkId.", e);
                    });
                }
                earlyMedia.play().then(function(){
                    // Audio Is Playing
                }).catch(function(e){
                    console.warn("Unable to play audio file.", e);
                }); 
            }
            this.data.earlyMedia = earlyMedia;
        }
        else if(response.status_code === 183){
            $(MessageObjId).html(response.reason_phrase + "...");

            // Special Early Media Handling
            if(response.body != "" && this.hasOffer && !this.dialog){
                // Confirm the dialog, eventhough it's a provisional answer
                if (!this.createDialog(response, 'UAC')) {
                    console.warn("Could not create Dialog ");
                    return;
                }

                // this ensures that 200 will not try to set description
                this.hasAnswer = true;

                // Force the session status
                this.status = SIP.Session.C.STATUS_EARLY_MEDIA;

                // Set the SDP from the response, so the media can connect
                // (Assuming that the response is a vlid SDP)
                this.sessionDescriptionHandler.setDescription(response.body).catch(function(reason){
                    console.warn("Failed to set SDP in 183 response: ", reason);
                });
            }
        }
        else {
            // 181 = Call is Being Forwarded
            // 182 = Call is queued (Busy server!)
            // 199 = Call is Terminated (Early Dialog)

            $(MessageObjId).html(response.reason_phrase + "...");
        }

        // Custom Web hook
        if(typeof web_hook_on_modify !== 'undefined') web_hook_on_modify("progress", response);
    });

On the server I have an asterisk with this dialplan:

exten => 500,1,Progress()
exten => 500,n,Wait(1)
exten => 500,n,Playback(demo-congrats,noanswer)
exten => 500,n,Hangup()

https://wiki.asterisk.org/wiki/display/AST/Early+Media+and+the+Progress+Application.

I have read that earlyMedia works correctly with the latest version (0.20), however I have not been able to make it work.

**Comment by 7i77an** [comment]
I found the problem, a configuration error.
Anyway it would be nice if they add earlyMedia support to the SimpleUser class.

I need to change all my integration just to have this feature.

I consider that there is a trade off to determine whether or not it is within SimpleUSer.
I believe that an outgoing call with earlyMedia support is a basic functionality.

**Comment by m-yunus** [comment]
Can u share the code if the early media Supported in SimpleUSer
