### ISSUE TITLE
simple-user listener is never execute

### ISSUE THREAD

**Issue by fsjun** [onsip/SIP.js#939]
![image](https://user-images.githubusercontent.com/9162928/124535840-701f2400-de49-11eb-863b-5a379f229a62.png)
this.session is a Proxy object, session is Inviter object, so "this.session !== session" is always true.

**Comment by egreenmachine** [comment]
@john-e-riordan any idea why this check is even in there?

**Comment by john-e-riordan** [comment]
Guessing it may have been in there for a reason prior to `c1a86a7c4` and could/should have been cleaned up then? Anyway, I don't see any harm in removing the guard - looks like it is not currently guarding anything.

**Comment by john-e-riordan** [comment]
Done in 258c5036beb31ae2f9d2d1ce5157955814e45f39
