### ISSUE TITLE
Module '"sip.js"' has no exported member 'Session'.

### ISSUE THREAD

**Issue by sadewole** [onsip/SIP.js#942]
Prior to now, I've been able to use these properties:
  { Session, SessionInviteOptions, SessionState, UserAgent, UserAgentOptions, UserAgentState }

But installing `sip.js` today and there's an error showing **no export member** for those.

And another thing I observed is that the version for this is still the same as my old project.  *"sip.js": "^0.20.0"*

**Comment by james-criscuolo** [comment]
This is almost certainly a project configuration issue, particularly given that you have the same version for both (please note how you have the version declared does not guarantee they will be the same, but that happens to be the latest version). I'd compare your build configurations, this may be an ES6 or ES module issue.
