### ISSUE TITLE
Simple Guide has a broken link to Simple User

### ISSUE THREAD

**Issue by kelfink** [onsip/SIP.js#943]
**Describe the bug**
https://sipjs.com/guides/simple/ has a link in "You should consider upgrading to the Simple User on the latest SIP.js Version." but the link 404's.  It is currently https://sipjs.com/simple-user

**Logs**
Please include a [gist](https://gist.github.com/) or attached file with full logs. If this is not included, the first response will likely be requesting them.

**To Reproduce (if possible)**
1. Go to 'https://sipjs.com/guides/simple/'
2. Click on 'Simple User' within the Disclaimer section
3. See 404 error

**Expected behavior**
the correct (unknown so far) Simple User guide

**Observed behavior**
404 error.

**Environment Information**

**Additional context**

**Comment by kelfink** [comment]
I expect the correct link is:  https://sipjs.com/guides/simple-user/

**Comment by john-e-riordan** [comment]
Yup. However that project is here: https://github.com/onsip/sipjs.com which is understandably a bit confusing.

I'm not able to transfer the issue, so I just cut and pasted it to: https://github.com/onsip/sipjs.com/issues/65
