### ISSUE TITLE
How to catch CANCEL event for incoming call

### ISSUE THREAD

**Issue by slavikbialik** [onsip/SIP.js#944]
Hi,
It's probably a feature request then just a question as I am sure it's not implemented today in API, but I was wondering if there's a workaround anyway so thought it worth asking here.

What I am trying to do is catch a **SIP CANCEL** on an **Invitation**.
The use case is very simple... I want to be able to return some indication when I'm answering the call.
Until today I was just waiting for **SessionState** to be **ESTABLISHED**, but it's not good enough and it is open to race conditions. I have a call center with agents, and I'm broadcasting the call to all agents. So when there's a case that 2 agents are trying to answer the call in the same time, one of them will succeed and then 2nd should get a CANCEL.
Problem is that in both cases, they'll switch to **SessionState = ESTABLISHED**, and it's not correct in my case because the call itself is not really established, that's why I'm looking for a way to catch the CANCEL and act according to it.

I asked something similar around 10 months ago, but no response:
https://groups.google.com/g/sip_js/c/hW9XUohVnDU/m/9TeE8WpqAQAJ

Any ideas?

**Comment by iomariani** [comment]
Hey @slavikbialik, lurking around there's a delegate for `onCancel` on [IncomingRequestDelegate](https://github.com/onsip/SIP.js/blob/5cf805632e48ec2d882f4b1e0eab2ae7c78beda5/docs/core/sip.js.incomingrequestdelegate.oncancel.md).

https://github.com/onsip/SIP.js/blob/5cf805632e48ec2d882f4b1e0eab2ae7c78beda5/src/api/invitation.ts#L420-L436

However it seems to be used for internal use only, I'm not sure how to listen to it when receiving it.

Although looking at the code, you can definitely catch it when sessionState transition to Terminated and `session.isCanceled` is true.

**Comment by slavikbialik** [comment]
> Hey @slavikbialik, lurking around there's a delegate for `onCancel` on [IncomingRequestDelegate](https://github.com/onsip/SIP.js/blob/5cf805632e48ec2d882f4b1e0eab2ae7c78beda5/docs/core/sip.js.incomingrequestdelegate.oncancel.md).
> 
> https://github.com/onsip/SIP.js/blob/5cf805632e48ec2d882f4b1e0eab2ae7c78beda5/src/api/invitation.ts#L420-L436
> 
> However it seems to be used for internal use only, I'm not sure how to listen to it when receiving it.
> 
> Although looking at the code, you can definitely catch it when sessionState transition to Terminated and `session.isCanceled` is true.

Thanks!
Shame I cannot use it in SessionDelegate.. it would be awesome, now I'll have to find a way to add this in the code, and I fear it won't be an easy task for me. 
Also I see that `isCanceled` flag is private, and I cannot access it using the API.
And I cannot understand why the `_onCancel` function is visible to use in the API commands, although I cannot really use it to do something.
If you have any ideas (regarding the code), it would be very much appreciated :)

**Comment by slavikbialik** [comment]
@iomariani Well... after further investigation I realize that it is 100% race condition, and it's not so easy to reproduce, but still I will have to fix it for my platform at least.
What happens is that SIP.js sends 200OK on the INVITE, but before this 200OK reaches my FreeSWITCH, FreeSWITCH sees that the call is answered elsewhere and it generates a CANCEL towards the SIP.js client.
So from SIP.js perspective, it tried to answer the call by sending a final response (200 OK) but then got a CANCEL.
According to the RFC, CANCEL should not be received after final response, and if so it should ignore it and SIP.js implements exactly that. 
But in my case, I cannot allow cases like that and I will probably need to change the source code (which I already did - not 100% tested yet) that will allow getting CANCEL after final response so when it gets it, it will terminate the session before fully answered (before the ACK). Hopefully it will work for me.

**Comment by egreenmachine** [comment]
Yeah. This looks like a pretty standard race condition that we are handling to RFC standard. What FS should do is "Accept and Terminate". It should detect that the 200 OK arrived for a session that it already cancelled and since this is a known SIP race condition it should take the 200 OK and then send a BYE for the call. From your agents perspective this would be that the call was answered then immediately hung up on. There may be a special in the reason of the BYE that you can use to provide better feedback to the agent, but this is all really a question of how FS handles this race condition.

**Comment by slavikbialik** [comment]
> Yeah. This looks like a pretty standard race condition that we are handling to RFC standard. What FS should do is "Accept and Terminate". It should detect that the 200 OK arrived for a session that it already cancelled and since this is a known SIP race condition it should take the 200 OK and then send a BYE for the call. From your agents perspective this would be that the call was answered then immediately hung up on. There may be a special in the reason of the BYE that you can use to provide better feedback to the agent, but this is all really a question of how FS handles this race condition.

Hi Eric, thanks for the reply!
I investigated it from FreeSWITCH perspective and I saw that it receives the CANCEL after it already generates the CANCEL towards the SIP.js client. But then it gets the 200OK and it ignores it as it already sent a CANCEL.
Of course FreeSWITCH detects this race condition (as it seems) and after the ACK (on the 200OK - which couldn't answer the call of course) the FreeSWITCH sends a BYE, but BYE is lacking the Reason with the "answered elsewhere".

I thought about doing something simple on the SIP.js side:
Add some new variable in `invitation.ts` class, like `isReceivedCancelOutOfOrder` which will be a boolean and PUBLIC so it can be accessible by the API.
Then in the following IF condition:
https://github.com/onsip/SIP.js/blob/5cf805632e48ec2d882f4b1e0eab2ae7c78beda5/src/api/invitation.ts#L424
I will set this flag to TRUE.

In my client code I will be able to delegate with the `onAck` (what I previously contributed) and check if when I get an ACK if the flag `isReceivedCancelOutOfOrder` is TRUE, if it's TRUE I know something wrong happened, means the race condition happened. ELSE, everything is OK.

What do you think?

Previously I started to break the RFC in the SIP.js code by NOT ignoring CANCEL when SessionState is ESTABLISHED and I were able to delegate `onCancel` through the API, but then it got very complicated and there's lot of things to consider when doing it.
So the idea above is more simple then breaking the RFC.

**Comment by egreenmachine** [comment]
As you found out, breaking the RFC can lead to some very nasty scenarios. I would highly recommend sticking to the standard here. 

IMO the best way to handle this is either a reason from FS in the bye message, or an extra header on the bye to indicate that this scenario has happened. A hack in SIP.js here is really specific to your use case here and I do not see much use adding it to the library. I believe that Freeswitch is supposed to send a reason "Call Completed Elsewhere" on the BYE message. This code lives in `mod_sofia.c`. I would try and track down why that is not getting added.

If you still wanted to add your code to SIP.js, I think that it should work. You could take it a step further and add some sort of `onOutOfOrderCancel` listener, that way you don't need to wait for the ACK as there could be processing/network delays. But again, I do not see us accepting any of this into the library.

**Comment by slavikbialik** [comment]
> As you found out, breaking the RFC can lead to some very nasty scenarios. I would highly recommend sticking to the standard here.
> 
> IMO the best way to handle this is either a reason from FS in the bye message, or an extra header on the bye to indicate that this scenario has happened. A hack in SIP.js here is really specific to your use case here and I do not see much use adding it to the library. I believe that Freeswitch is supposed to send a reason "Call Completed Elsewhere" on the BYE message. This code lives in `mod_sofia.c`. I would try and track down why that is not getting added.
> 
> If you still wanted to add your code to SIP.js, I think that it should work. You could take it a step further and add some sort of `onOutOfOrderCancel` listener, that way you don't need to wait for the ACK as there could be processing/network delays. But again, I do not see us accepting any of this into the library.

Thanks!
What about pushing `onCancel` in session delegation? I found a suitable solution for that out of order CANCEL in my very specific case without breaking RFC and changing any code in SIP.js, but still had to delegate `onCancel` to the API (which is working for me). Because I still had a case where I press on the ANSWER button, and while 200OK is still being generated I got an immediate CANCEL while SessionState.ESTABLISHING already, so had to be able to catch that CANCEL and do something in my code.
Let me know if you'll accept a PR of delegating `onCancel` to the API. I'd prefer to have it inside the community package and not to manage a repository of my own just for this.
Thanks!

**Comment by egreenmachine** [comment]
I think I would be ok with adding an `onCancel` to the API with some caveats. It should not change the underlying behavior of the UAS core. The cancel is a special case handled by the core, and should remain that way. And on the API level, I think that it should only fire if the session was actually cancelled. So if the cancel is received in the wrong state (ESTABLISHED), I would expect that delegate to not be called. I think that is consistent with other delegate methods.

**Comment by slavikbialik** [comment]
Closing this post. Hopefully we'll see it soon in next release after PR is merged.
Thanks! :)
