### ISSUE TITLE
is it possible ice gathering before answer/invite?

### ISSUE THREAD

**Issue by mberatsanli** [onsip/SIP.js#949]
I'm working on a project, I hear the sound too late after answer the call, when I checked the logs I realized it was because of ice gathering.

My goal is to complete the ice gathering before the loading app and send this ice information to sipjs (sessionDescriptionHandler)

**Comment by egreenmachine** [comment]
You can do early media or set the iceCheckingTimeout. But this must happen for every call. If you want more granular control over the ice process you can override the default Session Description Handler.

**Comment by mberatsanli** [comment]
Thank you for answer, but earlyMedia options is not working for me also I set iceCheckingTimeout as 0 and I face this delay everytime

![image](https://user-images.githubusercontent.com/15654470/131832974-940fb766-500a-437e-bb0f-c8bf536914d2.png)

Can you help me a bit on how to override SessionDescriptionHandler for solve this delay?
