### ISSUE TITLE
RFC8599 support 

### ISSUE THREAD

**Issue by ahmedfayoub** [onsip/SIP.js#956]
Hi,

I'm just wondering if we have support for RFC8599 support or having it on the development road map ?
I'd like to be able to add these new variables in the contact sip header.

Contact: <sip:alice@alicemobile.example.com;
       **pn-provider=acme;
       pn-param=acme-param;
       pn-prid=ZTY4ZDJlMzODE1NmUgKi0K**>

**Comment by firestation** [comment]
Hi, we have the same problem, i want to use PUSH but Sip.js does not include params into uri part of Contact header.(or i am little bit blind to find this way) 
is it possible to have fix for 0.20 version or have some new feature like contactParams but contactUriParams for example? 
Thanks.

**Comment by MarwaAbuEssa** [comment]
Hi,

adding contactparams for useragent options should solve this issue like :

  `this.userAgent = new UserAgent({
 contactParams:{
       ws_address: environment.sip.url,
         ws_port:"9568"
       }  
})`

and the result is 

`Contact: <sip:oopgbpt6@4h99rplc4g16.invalid;ws_address=127.0.0.1;ws_port=9568>;expires=600`

Thanks

**Comment by firestation** [comment]
> adding contactparams for useragent
Hi, thanks for advice will check it out and inform if it works.

**Comment by john-e-riordan** [comment]
[As noted, ](https://github.com/onsip/SIP.js/issues/956#issuecomment-1097755941) setting `contactParams` should work.
