### ISSUE TITLE
Force VP8 codec usage. 

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [onsip/SIP.js#962]
**Is your feature request related to a problem? Please describe.**

Safari is the problem child of WebRTC implementation. They recently introduced a bug that straight up breaks our implementation if we use the H.264 codec. https://bugs.webkit.org/show_bug.cgi?id=232006 . I have no faith in Apple fixing this in a timely manner. I also have no faith in a further regression. The solution is to force the usage of VP8 by safari. 

**Describe the solution you'd like**

I would like a field in the `userAgentOptions` where you can select what the video codec is set to. 

**Describe alternatives you've considered**

So there's this post: https://stackoverflow.com/questions/51788193/webrtc-and-peerjs-how-to-choose-h264-instead-of-vp8 . The method they describe is only available in safari so you'd basically be forced to manually alter the SDP. I feel that is asking for trouble. 

**Additional context**

I don't think this is possible with the current implementation, but there's a lot about the `sessionDescriptionHandlerFactory` I don't understand.

**Comment by iomariani** [comment]
> So there's this post: https://stackoverflow.com/questions/51788193/webrtc-and-peerjs-how-to-choose-h264-instead-of-vp8 . The method they describe is only available in safari so you'd basically be **forced to manually alter the SDP**. I feel that is asking for trouble.

Currently, there's no method to _enforce_ a codec...
As noted on the topic, [setCodecProferences](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences) is only available on Safari atm.

So yeah, there's no _easy way_, you need to mangle the SDP offer manually.
You can do that using a [SessionDescriptionHandlerModifier](https://github.com/onsip/SIP.js/blob/5cf805632e48ec2d882f4b1e0eab2ae7c78beda5/src/api/session-description-handler.ts#L65):

```ts
import { SessionDescriptionHandlerModifier, Inviter } from 'sip.js'

const modifier: SessionDescriptionHandlerModifier = (description) => {
  let { sdp = '' } = description

  // modify the sdp

  description.sdp = sdp

  return Promise.resolve(description)
}

// use your modifier on your INVITE
const inviter = new Inviter(userAgent, target, {
  sessionDescriptionHandlerModifiers: [modifier]
})
```

Perhaps you can use the[ modifiers exposed on the library](https://github.com/onsip/SIP.js/blob/master/src/platform/web/modifiers/modifiers.ts) as a reference...

**Comment by JustAnotherSoftwareDeveloper** [comment]
Thanks. If Safari doesn't fix this that gives me a start on how to change the SDP manually.

**Comment by john-e-riordan** [comment]
Is this still an issue with current Safari?
