### ISSUE TITLE
Demo applications don't work in Safari 15.1

### ISSUE THREAD

**Issue by danvirsen** [onsip/SIP.js#963]
**Describe the bug**
The demo applications don't work in Safari 15.1.
Connecting to wss://edge.sip.onsip.com works fine, but the connection closes when trying to register.
Everything works fine in Chrome.

I know this isn't really a sip.js issue but since I don't know where to report issues with the test server, I created an issue here.

**To Reproduce (if possible)**
1. Clone the repository.
2. Build the demo applications.
3. Go to the demo-2 application in Safari 15.1.
4. Click "Connect" for the user "Alice".
5. Click "Register User".

**Expected behavior**
The user should be registered, the "Register User" button should be disabled, and the "Initiate Video Session" should be enabled.

**Observed behavior**
An error is shown:
```
[Alice] Server disconnected.
WebSocket closed wss://edge.sip.onsip.com (code: 1006)
```

**Environment Information**
 - edge.sip.onsip.com
 - Safari 15.1

**Additional context**
The demo at https://sipjs.com/ doesn't work either.

FreeSWITCH recently solved what I'm guessing is the same issue with Safari 15.1. It's probably not helpful, but a PR for it can be seen here: https://github.com/freeswitch/sofia-sip/pull/94

**Comment by john-e-riordan** [comment]
I was not able to reproduce the issue in Safari 15.6.

**Comment by apaul0210** [comment]
this also happens in iOS 16.4 too, is there any update on this at all?

> I was not able to reproduce the issue in Safari 15.6.

**Comment by apaul0210** [comment]
can i ask, why was this issue closed?
