### ISSUE TITLE
Mute crashes Safari (SimpleUser)

### ISSUE THREAD

**Issue by danvirsen** [onsip/SIP.js#964]
**Describe the bug**
Muting outgoing media crashes the page in the latest version of Safari.

**Logs**
traceSip is enabled, but no error is logged. The last log is:
```
[Log] Fri Nov 26 2021 12:31:40 GMT+0100 (CET) | sip.SimpleUser | [user15@{server}] disabling media tracks... (demo-2.js, line 7697)
```

**To Reproduce (if possible)**
1. Clone the repository.
2. Build the demo applications.
3. Go to the demo-2 application in Safari 15.1.
4. Connect and register users and start a call.
5. Check the "Mute" checkbox in Safari.

**Expected behavior**
The outgoing media stream should be disabled, and the "Mute" checkbox should be checked.

**Observed behavior**
The page reloads and Safari shows the following error:
```
This web page was reloaded because a problem occurred.
```

**Environment Information**
 - FreeSWITCH 1.10.7
 - Safari 15.1

**Additional context**
The websocket server in the demo doesn't currently work with Safari 15.1 so I used a FreeSWITCH to do the testing. Everything works fine in Chrome.

**Comment by john-e-riordan** [comment]
Could not reproduce in Safari 15.6
