### ISSUE TITLE
Question: Does transport options no longer support wsServers as an array?

### ISSUE THREAD

**Issue by nerdchacha** [onsip/SIP.js#969]
I was going through the code for WebTransport. 
From what I could see in the code, a lot of changes have been made and SIP.js seems to not support things like multiple `wsServers`, `weight` etc.
I also see functions like `getNextWsServer` removed
Can someone confirm if with 0.20.0, SIP.js does not support wsServers as an array?

**Comment by seanbright** [comment]
This is not a support forum - try https://groups.google.com/g/sip_js instead
