### ISSUE TITLE
registration time is long

### ISSUE THREAD

**Issue by MarwaAbuEssa** [onsip/SIP.js#985]
These are typically directed to the [google group](https://groups.google.com/forum/#!forum/sip_js).
HI ,

I'm using latest version of SIPjs and I developed a function to start useragent then register the registerar. registration is working and i can perform IN/OUT calls successfully .  my only issue is it takes long time about 3 - 5 seconds to register which is not a good practice for mobile apps .I'm setting iceGatheringtimeout to 500 . 

Any help ?

**Comment by slavikbialik** [comment]
`iceGatheringtimeout` will only affect on establishing a call. It will not affect the registration process.
I would look at the PBX itself to see if it gets the REGISTER on time. Maybe you have a SIP proxy before the PBX that is not handling the routing of the REGISTER correctly to the proper place.

**Comment by MarwaAbuEssa** [comment]
HI slavikbialik ,

Thanks for your reply . I found out the useragent start request before register is the one which take long time not the register itself . actually opening was is exactly the one which causes the issue .so it's not related to anything in sipJS . thanks again for your support
