### ISSUE TITLE
UserAgent: Cannot listen sound audio from phone

### ISSUE THREAD

**Issue by thanhndbkhn** [onsip/SIP.js#987]
**Describe the bug**
When I make a call from Browser to Phone number.
Only one way sound response from browser,
```
 const userAgentOptions: UserAgentOptions = {
    authorizationUsername: "*****",
    authorizationPassword: "******",
    transportOptions,
    allowLegacyNotifications: true,
    logConfiguration: true,
    uri,
  };

  const userAgent = new UserAgent(userAgentOptions);

  const target = `sip:0967211692@homer.siptrunk.vn`;
  const targetURI = UserAgent.makeURI(target);
  let inviter: any;
  userAgent.start().then(() => {
    inviter =
      targetURI &&
      new Inviter(userAgent, targetURI, {
        earlyMedia: true,
        sessionDescriptionHandlerOptions: {
          constraints: {
            audio: true,
            video: false,
          },
        },
      });
    inviter && inviter.invite();
  });
```

**Logs**
`Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | Configuration:
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · allowLegacyNotifications: true
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · authorizationHa1: ""
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · authorizationPassword: NOT SHOWN
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · authorizationUsername: "1000"
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · autoStart: false
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · autoStop: true
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · delegate: {}
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · contactName: ""
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · contactParams: {"transport":"ws"}
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · displayName: ""
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · forceRport: false
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · hackAllowUnregisteredOptionTags: false
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · hackIpInContact: false
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · hackViaTcp: false
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · logBuiltinEnabled: true
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · logConfiguration: true
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · logConnector: undefined
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · logLevel: "log"
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · noAnswerTimeout: 60
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · preloadedRouteSet: []
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · reconnectionAttempts: 0
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · reconnectionDelay: 4
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · sendInitialProvisionalResponse: true
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · sessionDescriptionHandlerFactory: (session, options) => {
    // provide a default media stream factory if need be
    if (mediaStreamFactory === undefined) {
      mediaStreamFactory = Object(_media_stream_factory_default__WEBPACK_IMPORTED_MODULE_0__["defaultMediaStreamFactory"])();
    } // make sure we allow `0` to be passed in so timeout can be disabled

    const iceGatheringTimeout = (options === null || options === void 0 ? void 0 : options.iceGatheringTimeout) !== undefined ? options === null || options === void 0 ? void 0 : options.iceGatheringTimeout : 5000; // merge passed factory options into default session description configuration

    const sessionDescriptionHandlerConfiguration = {
      iceGatheringTimeout,
      peerConnectionConfiguration: Object.assign(Object.assign({}, Object(_peer_connection_configuration_default__WEBPACK_IMPORTED_MODULE_1__["defaultPeerConnectionConfiguration"])()), options === null || options === void 0 ? void 0 : options.peerConnectionConfiguration)
    };
    const logger = session.userAgent.getLogger("sip.SessionDescriptionHandler");
    return new _session_description_handler__WEBPACK_IMPORTED_MODULE_2__["SessionDescriptionHandler"](logger, mediaStreamFactory, sessionDescriptionHandlerConfiguration);
  }
logger-factory.js:93 Wed Apr 13 2022 00:48:58 GMT+0700 (Indochina Time) | sip.UserAgent | · sessionDescriptionHandlerFactoryOptions: {}`

**Comment by john-e-riordan** [comment]
This is not a support forum - try https://groups.google.com/g/sip_js instead
