### ISSUE TITLE
no ACK request received 

### ISSUE THREAD

**Issue by MarwaAbuEssa** [onsip/SIP.js#990]
Hi ,

I'm using your latest sipjs lib . all registration , ringing , answering call with voice transmitted is working correctly .the issue is that **sometimes** sipjs in my app don't receive an ack request and keeps sending 200 ok although I'm pretty sure asterisk send the ack as I saw in it's logs .

I added console log at onACK event in invitation delegate and found out  that sometimes it receives onack event and sometimes not although the asterisk server send it all time  . also in case not getting the onack event I can't terminate the call from app and sipjs ends the call onacktimeout event 

`No ACK for 2xx response received, attempting retransmission
sip.Invitation | Invitation.onAckTimeout
 No ACK received for an extended period of time, terminating session`

I can't guess the reason of this behavior or from where to start debugging 

any help is appreciated

Thanks

**Logs**
Please include a [gist](https://gist.github.com/) or attached file with full logs. If this is not included, the first response will likely be requesting them.

**To Reproduce (if possible)**

**Expected behavior**
expecting sipjs to receive ack request all time 

**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**

**Comment by MarwaAbuEssa** [comment]
I can see ack from server side sent but the app keep re-transmit as if it doesn't get it . sometime it keeps re-transmitting till the call ends and sometime it accept the ack after 2 or 3 times
![ack](https://user-images.githubusercontent.com/7272394/168882409-cf41efbf-f5c5-4d1b-a5dd-0b59863f2433.png)

**Comment by webstackdev** [comment]
@MarwaAbuEssa what software is in your screenshot showing networking messages?

**Comment by Aayushi-Mashru** [comment]
Hello, @MarwaAbuEssa Were you able to come up with a solution for this? I am also facing the same behavior for some of our users.

Also, When this scenario comes up, I am not able to send the BYE from my application. The the call ends only when sip.js sends BYE after around 30 seconds of retransmissions. Any suggestions on how can I handle this?

**Comment by MarwaAbuEssa** [comment]
@Aayushi-Mashru I found out I had an issue with registration. some times double registration at the same time can cause this issue and sometimes a missing extra contact param.
