### ISSUE TITLE
Wrong Contact header when GRUU enabled on registrar

### ISSUE THREAD

**Issue by zusrut** [onsip/SIP.js#991]
#989 pull request was created to solve this issue.

**Describe the bug**
SIP.js UA puts GRUU contact value into REGISTER contact header.

**To Reproduce (if possible)**
Set up regId or instanceId or both parameters in registerer options. 
Then if GRUU enabled on a registrar and it response with GRUU contact on second re-REGISTER SIP.js will use it as contact header.

**Expected behavior**
GRUU  contact can be used everywhere except REGISTER messages.

**Environment Information**
 - SIP.js version 0.20.0

According [rfc5627](https://datatracker.ietf.org/doc/html/rfc5627)
>  [3.3](https://datatracker.ietf.org/doc/html/rfc5627#section-3.3). Using a GRUU
> 
>Once a user agent obtains GRUUs from the registrar, it uses them in
>several ways. First, it uses them as the contents of the Contact
>     header field in non-REGISTER requests and responses that it emits
>     (for example, an INVITE request and 200 OK response). According to
>     [RFC 3261](https://datatracker.ietf.org/doc/html/rfc3261) [[1](https://datatracker.ietf.org/doc/html/rfc5627#ref-1)], the Contact header field is supposed to contain a URI
>     that routes to that user agent. Prior to this specification, there
>     hasn't been a way to really meet that requirement. The user agent
>     would use one of its temporary GRUUs for anonymous calls, and use its
>     public GRUU otherwise.
> 
>Second, the UA can use the GRUU in any other place it needs to use a
>URI that resolves to itself, such as a webpage.

BTW I do not see recent activity at the project - is it still actively supported? @jscheid @nud @ibc @pedrokiefer @etamme

**Comment by john-e-riordan** [comment]
#989 has been picked onto the main branch.

Thank you.
