### ISSUE TITLE
Conference with 3 or more sessions.

### ISSUE THREAD

**Issue by joselaurosouza** [onsip/SIP.js#995]
**How to create a conference method by joining 3 or more sessions?**
I would like to be able to do a conference process where 3 or more sessions share the same audio, being able to talk to each other, I can normally transfer a call and taking into account that the conference process followed the same pattern, I understand that it can a preference or new call must be made after that to retrieve the session from the new transfer or call and make the original session share the audio with the new one, as the new one also shares with the previous sessions.

Has anyone ever done this process?
I'm not making progress at this point.

I believe this method will make SIPjs more robust.

Grateful!

**Comment by john-e-riordan** [comment]
Yes this can and has been done using SIP.js. 
But this is not a support forum - try https://groups.google.com/g/sip_js instead
You are welcome open a feature request, but please utilize the associated template.
Thanks.
