### ISSUE TITLE
Not able to send BYE or CANCEL in case of 2xx retransmission loop in SIP.js

### ISSUE THREAD

**Issue by Aayushi-Mashru** [onsip/SIP.js#998]
**Describe the bug**
For some of our users we are facing the following issue when the 200 OK for answering the call is sent but ACK is not received for the same:
_sip.invite-dialog | No ACK for 2xx response received, attempting retransmission_

After this the 200 OK keeps getting retransmitted, in such case I am not able to send BYE or CANCEL from the application side on pressing the hangup.

The call only terminates when SIP.js sends BYE after retransmissions.

**Logs**
Have attached app logs file which contains the SIP packets logs from SIP.js 

**Expected behavior**
I should be able to send BYE / CANCEL in this case.

**Observed behavior**
BYE / CANCEL not being sent until the retransmission loop is completed.

**Environment Information**
 - Backend server: opensips
 - Version - 3.0.1 
 - "react-native": "^0.62.2"
 - "react-native-webrtc": "^1.94.1"
 - "sip.js20": "npm:sip.js@^0.20.0"
 
[Callee_log.pdf](https://github.com/onsip/SIP.js/files/9131040/Callee_log.pdf)

**Comment by MarwaAbuEssa** [comment]
Hi ,

I faced the same issue you have and discovered that creating multiple user agents causes this problem. you should initiate a user agent only once during your app running and then you can send register request as many times as you need but with only one user agent initiated  .

I hope this help 
Thanks

**Comment by john-e-riordan** [comment]
Hi - this is not a bug. SIP.js is retransmitting the 200 Ok because it did not receive an ACK, which is what it is supposed to do. You might find some help in the [google group](https://groups.google.com/forum/#!forum/sip_js) if you are still having an  issue. Thanks.
